// CBET Academy question bank, units 7 to 9. All questions are original.
window.FRA = window.FRA || {};
FRA.questions = FRA.questions || [];
FRA.questions.push(
// u7l1
{id:"u7l1-1",t:"u7l1",q:"A nurse reports that a monitor 'never works right' and asks for a replacement. What should the technician do first?",a:["Replace the monitor immediately","Gather details and verify the complaint by observing the fault","Open the case and inspect the boards","Order a new patient cable"],c:1,e:"The troubleshooting method begins with gathering information and reproducing the complaint. Replacing a device before verifying the fault often fixes nothing and hides a use error or an environmental cause."},
{id:"u7l1-2",t:"u7l1",q:"A device fault that appears only when the patient cable is flexed and disappears when it is held still most likely indicates which type of problem?",a:["A power supply failure","A software defect","An intermittent connection such as a broken conductor at a strain relief","A calibration drift"],c:2,e:"Intermittent faults that correlate with movement point to cable breaks, loose connectors, or cold solder joints. Sudden total failures suggest power; gradual drift suggests aging components."},
{id:"u7l1-3",t:"u7l1",q:"Investigation of a pump overdose shows the log recorded a concentration of 10 mg/mL entered for a 1 mg/mL bag, and the pump delivers accurately on the analyzer. How should this be classified and addressed?",a:["A device failure; replace the pump","A battery problem; replace the battery","A network fault; contact IT","A use error; address through training, a second-person check, and drug library limits"],c:3,e:"The device performed as programmed, so this is a use error. The remedy is education, workflow safeguards, and drug library hard limits, plus a report if the interface contributed to the mistake."},
{id:"u7l1-4",t:"u7l1",q:"After replacing a failed board in a patient monitor, what must be done before the monitor returns to service?",a:["Perform a full performance verification and an electrical safety test, then document","Only test the parameter the board handled","Return it immediately to reduce downtime","Ask the nurse to test it on the next patient"],c:0,e:"Any repair that opens the case requires a complete performance verification and electrical safety test, not just a check of the repaired function, followed by documentation."},
{id:"u7l1-5",t:"u7l1",q:"A device is involved in a patient injury. What should the technician do with the device before repairing it?",a:["Repair it quickly so it can return to use","Remove it from service, tag it, preserve its logs and accessories, and notify risk management before any repair","Clear its logs to reset it","Return it to the manufacturer immediately"],c:1,e:"Evidence must be preserved for the investigation. The device, its settings, logs, and accessories are sequestered as found; repair waits until the investigation permits it."},

// u7l2
{id:"u7l2-1",t:"u7l2",q:"A technician replaces a blown inlet fuse on a device and it blows again immediately when powered on. What does this indicate?",a:["The replacement fuse was defective","The outlet voltage is too low","A short circuit downstream, such as a failed power supply or shorted load","The fuse rating should be increased"],c:2,e:"A fuse that fails again after replacement indicates a fault it is protecting against. Installing a larger fuse is dangerous; the short must be located and repaired."},
{id:"u7l2-2",t:"u7l2",q:"A monitor resets every time its NIBP pump starts inflating a cuff. What is the most likely cause?",a:["A defective NIBP cuff","A broken ECG cable","A software bug in the NIBP module","A power supply that sags under load, often from aged capacitors"],c:3,e:"A reset coinciding with a heavy load such as a pump or heater means the supply cannot maintain its rails under current demand, commonly from aging electrolytic capacitors."},
{id:"u7l2-3",t:"u7l2",q:"Which battery chemistry is light and energy dense but requires a protection circuit and must be removed from service if the pack swells or overheats?",a:["Lithium-ion","Nickel-cadmium","Nickel-metal hydride","Sealed lead-acid"],c:0,e:"Lithium-ion batteries offer high energy density but need protection circuits and careful handling; swelling, heat, or damage indicates a hazard requiring removal and proper disposal."},
{id:"u7l2-4",t:"u7l2",q:"An SpO2 module in one bedside monitor shows a module fault. When moved to another monitor the fault follows it. What has been isolated?",a:["The first monitor's module slot","The module itself","The central station","The SpO2 sensor"],c:1,e:"Substitution isolates the fault: if the problem moves with the module, the module is defective; if it stays with the monitor, the slot, connector, or host is at fault."},
{id:"u7l2-5",t:"u7l2",q:"How should the battery of a transport monitor be evaluated during preventive maintenance?",a:["By reading the charge indicator","By measuring the open-circuit voltage only","By running the device under a realistic load until the low-battery alarm and comparing runtime to specification","By weighing the battery"],c:2,e:"Runtime under load to the low-battery alarm is the meaningful test. Voltage alone does not reveal capacity loss. Life-support device batteries are also replaced by date regardless."},

// u7l3
{id:"u7l3-1",t:"u7l3",q:"An ECG lead wire that looks undamaged produces lead-off alarms whenever the patient moves. Where is the break most likely located?",a:["In the monitor's input circuit","In the central station software","In the electrode gel","Inside the jacket at the strain relief near the snap or plug"],c:3,e:"Conductors fatigue and break at strain reliefs where cables flex most, while the outer jacket remains intact. A continuity test while flexing confirms it."},
{id:"u7l3-2",t:"u7l3",q:"A pulse oximeter gives no reading on a patient. The technician places the sensor on their own finger and still gets no reading, then tries a known-good sensor and it reads normally. What has been shown?",a:["The original sensor is defective","The patient has poor perfusion","The monitor's SpO2 module is defective","The ambient light is too bright"],c:0,e:"Testing on the technician removed the patient as a variable, and substituting a known-good sensor restored function, isolating the fault to the original sensor."},
{id:"u7l3-3",t:"u7l3",q:"ECG noise on a monitor appears only when a sequential compression device in the same room cycles, and stops when the SCD is moved to a different outlet. What is the most likely cause?",a:["A defective ECG module","Electromagnetic interference associated with the original outlet or its grounding","Dried electrodes","The monitor's notch filter is disabled"],c:1,e:"Correlating the noise with a specific source and outlet points to electromagnetic interference and grounding. The outlet should be tested and reported to facilities."},
{id:"u7l3-4",t:"u7l3",q:"Why should a damaged patient cable be replaced rather than spliced?",a:["Splicing is too time-consuming","Manufacturers prohibit all cable repairs for warranty reasons only","A splice alters impedance and shielding, lacks strain relief, cannot be cleaned, and may create a leakage path","Spliced cables cannot carry digital signals"],c:2,e:"Patient cables are safety-critical assemblies. A splice compromises shielding, reliability, cleanability, and electrical isolation, so cables are replaced."},
{id:"u7l3-5",t:"u7l3",q:"A monitor otherwise operates normally but its screen is completely dark. Which components should be suspected first?",a:["The ECG input circuit","The network interface","The battery charger","The backlight or its inverter and the display cable"],c:3,e:"A device that runs normally without a visible image usually has a failed backlight, inverter, or display cable rather than a processing fault."},

// u7l4
{id:"u7l4-1",t:"u7l4",q:"Four service requests arrive at once: a cosmetic crack on a TENS unit, an ICU ventilator that failed its pre-use check with no spare available, a pump involved in an overdose last night, and a clinic's only ultrasound showing an image artifact. What is the correct order to act?",a:["Sequester the incident pump, then the ventilator, then the ultrasound, then the TENS","Ultrasound, ventilator, pump, TENS","Ventilator, TENS, ultrasound, pump","TENS, ultrasound, pump, ventilator"],c:0,e:"Patient incidents come first so evidence is preserved, then life support without backup, then devices blocking care, and cosmetic issues last."},
{id:"u7l4-2",t:"u7l4",q:"A nine-year-old infusion pump needs a mechanism repair costing 60 percent of a new pump, lacks a drug library, and the manufacturer is ending support next year. What is the most appropriate recommendation?",a:["Repair it because it has been reliable","Recommend replacement, supported by cost, age, support, and safety data","Keep it in service without repair","Splice in a mechanism from another model"],c:1,e:"Repair cost above roughly half of replacement, end of support, and missing modern safety features all favor replacement. The technician supplies the data; capital planning decides."},
{id:"u7l4-3",t:"u7l4",q:"A device still under the manufacturer's warranty fails. What should the technician do?",a:["Repair it in house to save time","Discard it and order a new one","Contact the vendor, because self-repair may void the warranty, and document the call","Ignore the warranty since the hospital owns the device"],c:2,e:"Warranty and service contract terms usually require vendor service. Performing an unauthorized repair can void coverage and shift costs to the hospital."},
{id:"u7l4-4",t:"u7l4",q:"What is the fastest way to restore clinical capability when a critical device fails and a repair will take several days?",a:["Expedite parts shipping","Keep the failed device in service with a warning label","Ask the unit to borrow from another department informally","Issue a PM-current loaner from the spare pool and log it in the CMMS"],c:3,e:"A managed spare pool lets care continue while the repair proceeds. Loaners must be tracked so they return and the failed unit does not disappear."},
{id:"u7l4-5",t:"u7l4",q:"A Class I recall notice arrives for a model of infusion pump in the inventory. What does the classification require?",a:["Immediate action across every affected unit, matched by serial number and documented","Action can wait until the next PM","Only notification of the purchasing department","Disposal of all pumps of that brand"],c:0,e:"Class I recalls involve a reasonable probability of serious harm and require immediate action on every affected device, with records of serial numbers, actions, dates, and technicians."},

// u7l5
{id:"u7l5-1",t:"u7l5",q:"Which opening question is most effective when a nurse calls to report a malfunctioning device?",a:["Did you check whether it was plugged in?","Tell me what happened, and what did the screen say exactly?","Who was using it when it broke?","Why didn't you call sooner?"],c:1,e:"Open questions and the exact error text gather facts without implying blame. Questions that sound accusatory discourage staff from reporting future problems."},
{id:"u7l5-2",t:"u7l5",q:"A pump under-delivered because its administration set had been used for three days past its 24-hour rating. Which explanation to the nursing unit is most appropriate?",a:["You left the set on too long; the package says 24 hours.","The peristaltic segment lost compliance beyond its validated duty cycle.","The tubing wears out after a day in the pump and delivers less; sets need changing every 24 hours, and I'll ask the educator to add it to the checklist.","The pump is defective and will be replaced."],c:2,e:"The best explanation states the cause plainly, the action, and a system-level fix without blaming the individual and without jargon."},
{id:"u7l5-3",t:"u7l5",q:"What characterizes effective user training on medical equipment?",a:["A long classroom lecture covering every feature","Training only when a device is purchased","An email with the manual attached","Short, hands-on, task-specific sessions at the device that are documented"],c:3,e:"Brief hands-on practice on the tasks that generate problems, delivered at the device and documented, changes behavior; training is repeated for new staff and after changes."},
{id:"u7l5-4",t:"u7l5",q:"A nurse reports that a pump almost ran free when the door was opened, but no harm occurred. How should this be treated?",a:["Reported as a near miss so the door clamp can be checked across the fleet","Ignored, since no one was hurt","Blamed on the nurse's technique","Recorded only if it happens again"],c:0,e:"Near misses reveal fleet-wide hazards before they injure someone. A reporting culture depends on thanking reporters and closing the loop with findings."},
{id:"u7l5-5",t:"u7l5",q:"During troubleshooting, a technician discovers that an outlet sparks when a bed is plugged in. Which department should be notified?",a:["Information technology","Facilities, after tagging the outlet out of use","Infection prevention","Purchasing"],c:1,e:"Electrical outlets and building power belong to facilities. The technician tags the hazard immediately and reports it so it is repaired."},

// u8l1
{id:"u8l1-1",t:"u8l1",q:"Two adjacent ICU rooms at the end of a hallway have no waveforms at the central station while their bedside monitors work normally. What is the most likely cause?",a:["Electrodes on both patients","The ECG modules in both monitors","A shared network switch or its ports serving that area","The central station's software license"],c:2,e:"Several beds in one area with all parameters missing points to the shared infrastructure for that area, such as a switch or its ports, not to individual accessories."},
{id:"u8l1-2",t:"u8l1",q:"A monitor displays a heart rate of 150 on a patient whose palpated pulse is 75. What is the most likely explanation?",a:["The patient has an arrhythmia the nurse cannot feel","The monitor's battery is low","The NIBP cuff is too small","Tall T waves or pacemaker spikes are being counted as beats; adjust the lead, gain, or pacer setting"],c:3,e:"A displayed rate exactly double the true rate results from the monitor counting an extra deflection per cycle, typically a tall T wave or a pacer spike. Lead selection and gain correct it."},
{id:"u8l1-3",t:"u8l1",q:"A monitor's ECG shows a flat line while the patient is sitting up talking. What should be checked first?",a:["The ECG cable connection to the patient and monitor","Begin CPR","The central station server","The SpO2 probe"],c:0,e:"A conscious, talking patient is not in asystole. A flat trace means the cable is disconnected or a lead is selected that is not connected. Some monitors flag this differently from asystole."},
{id:"u8l1-4",t:"u8l1",q:"Vital signs from a monitor are appearing in the wrong patient's electronic record. Where does the problem most likely lie?",a:["A faulty network cable","The admission and discharge workflow at the central station, leaving a stale bed association","The monitor's ECG module","The hospital's firewall"],c:1,e:"Data in the wrong chart is a patient association problem: the previous patient was not discharged from the bed or the new patient was not admitted. The network delivered the data as addressed."},
{id:"u8l1-5",t:"u8l1",q:"A single telemetry patient's signal drops out repeatedly while other patients on the same unit are fine. What should be checked first?",a:["The central station server","The telemetry antenna system","The transmitter's battery, leads, and whether the patient is leaving the coverage area","The unit's network switch"],c:2,e:"One patient dropping points to that patient's transmitter, battery, electrodes, or location. Several patients in one zone point to antennas; everyone points to the receiver or central station."},

// u8l2
{id:"u8l2-1",t:"u8l2",q:"An ultrasound image shows vertical dark bands that persist regardless of the patient or preset. What is the most likely cause?",a:["The system's main board","A network problem with PACS","Insufficient gel","Damaged elements in the transducer"],c:3,e:"Dropout bands correspond to failed transducer elements. Swapping transducers or imaging a phantom confirms it. A whole-image fault would suggest the system."},
{id:"u8l2-2",t:"u8l2",q:"An infusion pump programmed at 2 mL/hr alarms for downstream occlusion nearly an hour after the line was kinked. What does this indicate?",a:["Expected behavior, because time to alarm is long at low rates as pressure builds slowly","The pump's occlusion sensor has failed","The drug library is outdated","The air-in-line detector is dirty"],c:0,e:"At low flow rates, pressure rises slowly against an occlusion, so the time to alarm is longer. Analyzers test both occlusion pressure and time to alarm to confirm this behavior is within specification."},
{id:"u8l2-3",t:"u8l2",q:"Which infusion pump failure does NOT produce an alarm and therefore must be tested at every preventive maintenance?",a:["Downstream occlusion","Free-flow when the set is removed","Air in the line","Low battery"],c:1,e:"Free-flow protection failure is silent and can deliver an entire bag by gravity. Occlusion, air, and battery conditions alarm, but free-flow and delivery accuracy must be verified by testing."},
{id:"u8l2-4",t:"u8l2",q:"A pump is suspected in a medication overdose. Which action is correct?",a:["Clear the pump and return it to the pool","Power off the pump and reprogram it to test","Sequester the pump with its set and bag as found, photograph the display, and download the event log","Wash the pump and send it to the vendor"],c:2,e:"Evidence preservation is essential. The event log records every keystroke, alarm, and delivery, which usually establishes what happened. Clearing or reprogramming destroys that evidence."},
{id:"u8l2-5",t:"u8l2",q:"A drug is ordered at 2 mg/min from a bag containing 400 mg in 250 mL. What pump rate delivers the order?",a:["7.5 mL/hr","750 mL/hr","125 mL/hr","75 mL/hr"],c:3,e:"Concentration is 400 / 250 = 1.6 mg/mL. Rate = 2 mg/min divided by 1.6 mg/mL = 1.25 mL/min, times 60 = 75 mL/hr. A tenfold difference in a programmed rate signals a decimal or unit error."},

// u8l3
{id:"u8l3-1",t:"u8l3",q:"During a PM, a technician disconnects a radiant warmer's skin probe and the heater continues at full output with no alarm. What should be done?",a:["Remove the warmer from service, because a failed probe-off alarm can cause burns","Note it as a minor finding","Increase the alarm volume","Replace the skin probe only"],c:0,e:"A radiant warmer without a functioning probe-off alarm runs open-loop and can severely burn an infant. It is an immediate removal until repaired and retested."},
{id:"u8l3-2",t:"u8l3",q:"An electrosurgical unit alarms and refuses to activate during a procedure. The return pad is found to be partially peeled from the patient. How should this be interpreted?",a:["The ESU has failed and must be replaced","Return electrode monitoring is working correctly by preventing a burn from poor pad contact","The active electrode is defective","The ESU's fuse has blown"],c:1,e:"Return electrode monitoring measures contact quality through a split pad and inhibits output when contact degrades. The alarm is the safety feature performing as designed."},
{id:"u8l3-3",t:"u8l3",q:"A defibrillator's charge time to maximum energy has increased from 6 seconds to 25 seconds. Which components are most likely responsible?",a:["The ECG cable or pads","The paper printer","The battery or the energy storage capacitor","The synchronization circuit"],c:2,e:"Charge time depends on the battery's ability to deliver current and the capacitor's condition. A large increase indicates battery aging first, then capacitor deterioration."},
{id:"u8l3-4",t:"u8l3",q:"An anesthesia machine fails its low-pressure leak test. Which items should be checked systematically?",a:["The ECG electrodes and cable","The pipeline oxygen supply pressure","The scavenging exhaust fan only","Vaporizer seating and fill caps, gaskets, absorber canister seal, circuit connections, and bellows"],c:3,e:"Low-pressure leaks come from the vaporizer manifold, absorber, circuit, and bellows. A methodical search of each seal and connection locates the leak."},
{id:"u8l3-5",t:"u8l3",q:"A gas flow analyzer shows a ventilator delivering 400 mL when set to 500 mL, and the exhalation valve is suspected. What else should be checked before condemning the valve?",a:["Flow sensor calibration and the circuit compliance setting","The patient's height","The room temperature","The ventilator's network address"],c:0,e:"Delivered volume errors arise from flow sensor calibration, exhalation valve leaks, or incorrect circuit compliance compensation. Calibrate and verify each before replacing parts."},

// u8l4
{id:"u8l4-1",t:"u8l4",q:"A laboratory centrifuge will not start when the start button is pressed, although it has power. What should be checked first?",a:["The rotor balance","The lid interlock and latch sensor","The refrigeration compressor","The tachometer calibration"],c:1,e:"Centrifuges will not start unless the lid interlock confirms the lid is closed and latched. It is the most common no-start cause, followed by the timer, belt or brushes, and fuse."},
{id:"u8l4-2",t:"u8l4",q:"A blood bank refrigerator's chart shows a slow temperature rise over two hours beginning right after the night shift fully restocked the shelves, then a fall after the load was redistributed. What was the cause?",a:["Compressor failure","A failed door alarm","Blocked airflow from overloaded shelves","A power outage"],c:2,e:"Overloading blocks internal airflow and causes gradual warming that resolves when the load is redistributed. The log makes the cause and the excursion's extent clear."},
{id:"u8l4-3",t:"u8l4",q:"Several unrelated devices in one laboratory room reset at about the same time each morning. What is the most likely cause?",a:["Each device has a separate fault","The room's network switch","A software virus","Power quality problems such as sags from a large load starting on the same circuit"],c:3,e:"Multiple different devices failing together in one location point to the environment, typically power sags or surges from elevators, imaging equipment, or HVAC. A UPS or a conditioned circuit resolves it."},
{id:"u8l4-4",t:"u8l4",q:"Quality control results on a chemistry analyzer are out of range. Which items should be examined first?",a:["Reagent lots and expiration, calibration, and probe clogging","The network cable","The room's lighting","The laboratory information system"],c:0,e:"QC failures most often trace to reagents, calibration, or fluidic problems such as clogged probes and worn tubing. The analyzer's diagnostics guide the sequence; vendors service under contract."},
{id:"u8l4-5",t:"u8l4",q:"A refrigerator alarm does not sound when the technician simulates a high temperature during PM. Which items should be checked?",a:["The compressor and condenser","Probe placement, alarm setpoints, the alarm's backup battery, and remote notification configuration","The door hinge","The shelf spacing"],c:1,e:"Alarm failures during testing usually involve the probe, setpoints, a dead alarm backup battery, or notification configuration rather than the refrigeration system itself."},

// u8l5
{id:"u8l5-1",t:"u8l5",q:"Which entry in a defibrillator PM record provides usable evidence that the device met specification?",a:["Energy OK","Tested per procedure","Delivered 194 J at a 200 J setting and 351 J at a 360 J setting, within tolerance","No problems found"],c:2,e:"Records must contain measured values against specification so a reader can verify the device was within tolerance on that date. Adjectives are not evidence."},
{id:"u8l5-2",t:"u8l5",q:"What is required of an alternative, risk-based equipment maintenance program?",a:["It may cover every device including life support at any interval","It applies only to laboratory equipment","It eliminates the need for PM records","It must be documented and data-driven, and life-support, imaging, and manufacturer-mandated devices must stay on the manufacturer's schedule"],c:3,e:"Accreditors and CMS allow risk-based intervals when documented and supported by data, but life-support, imaging, and devices with manufacturer-mandated schedules remain on the manufacturer's intervals."},
{id:"u8l5-3",t:"u8l5",q:"What PM completion rate is expected for life-support equipment?",a:["100 percent","90 percent","95 percent","80 percent"],c:0,e:"Life-support and other high-risk devices must reach 100 percent on-time PM completion. Surveyors examine completion percentages and expect any missed devices to be located and resolved."},
{id:"u8l5-4",t:"u8l5",q:"A new infusion pump arrives on a nursing unit directly from the vendor. What must occur before it is used on a patient?",a:["Nothing, because it is new","An incoming inspection including safety testing, performance verification, configuration, inventory entry, and user training","Only a visual inspection","A vendor demonstration"],c:1,e:"Every new, loaned, or demo device receives an acceptance inspection and is entered into inventory and configured to hospital standards before first patient use."},
{id:"u8l5-5",t:"u8l5",q:"During a PM an infusion pump delivers 12 percent low against a manufacturer tolerance of 5 percent. What is the correct action?",a:["Return it to service with a note","Adjust the tolerance in the procedure","Fail the PM, repair, retest, and only then return it to service","Return it and schedule a recheck next quarter"],c:2,e:"A reading outside the manufacturer's tolerance is a failed PM. The device is repaired and retested to specification before it returns to patient use."},

// u9l1
{id:"u9l1-1",t:"u9l1",q:"Two devices have addresses 10.20.5.11 and 10.20.6.7 with a subnet mask of 255.255.255.0. How do they communicate?",a:["Directly, because they share the first two octets","Only over Wi-Fi","They cannot communicate","Through a router at the default gateway, because they are on different subnets"],c:3,e:"With a /24 mask the first three octets identify the network: 10.20.5 and 10.20.6 differ, so traffic passes through the gateway router."},
{id:"u9l1-2",t:"u9l1",q:"A monitor shows an address of 169.254.10.22 and cannot reach the central station. What does this address indicate?",a:["The device requested a DHCP address and received no response","A static address assigned by IT","A valid public internet address","The address of the default gateway"],c:0,e:"169.254.x.x is an automatic private address assigned when DHCP fails. The link, the DHCP server, or the VLAN configuration should be checked."},
{id:"u9l1-3",t:"u9l1",q:"Why are bedside monitors and central stations usually assigned static IP addresses?",a:["Static addresses are faster","The central station must always find each monitor at the same address","DHCP is not compatible with Ethernet","Static addresses do not require a subnet mask"],c:1,e:"Devices that other systems must locate reliably use fixed addresses or DHCP reservations. A changing address would break communication with the central station and interfaces."},
{id:"u9l1-4",t:"u9l1",q:"At which layer and by which device are MAC addresses used to forward frames?",a:["Network layer, by routers","Transport layer, by firewalls","Data link layer, by switches","Application layer, by servers"],c:2,e:"MAC addresses are hardware addresses used at the data link layer; switches learn which MAC is on which port. IP addresses operate at the network layer through routers."},
{id:"u9l1-5",t:"u9l1",q:"What is the maximum recommended length of a copper twisted-pair Ethernet run?",a:["10 meters","55 meters","500 meters","100 meters"],c:3,e:"Twisted-pair Ethernet is specified to 100 meters including patch cables. Beyond that, links show errors and speed problems; fiber is used for longer runs."},

// u9l2
{id:"u9l2-1",t:"u9l2",q:"Which Wi-Fi band offers longer range and better wall penetration but has only three non-overlapping channels and more interference?",a:["2.4 GHz","5 GHz","6 GHz","608 MHz"],c:0,e:"2.4 GHz propagates farther but is crowded and has few channels. 5 GHz offers more channels and speed with shorter range. 608 MHz is a medical telemetry band, not Wi-Fi."},
{id:"u9l2-2",t:"u9l2",q:"A wireless infusion pump connects in the patient room but drops its connection in the hallway and reconnects only after a restart. What is the most likely cause?",a:["The pump's drug library","A coverage gap or roaming problem between access points","The central station license","The pump's battery"],c:1,e:"Devices that fail when moving between areas suffer from coverage gaps or roaming handoff problems, identified by a site survey and controller client history."},
{id:"u9l2-3",t:"u9l2",q:"An entire fleet of wireless pumps stops connecting on the same day with no hardware changes. What is a likely cause?",a:["All the pump radios failed at once","A single access point failure","An expired authentication certificate or an authentication server change","Low batteries in every pump"],c:2,e:"Simultaneous fleet-wide connection failure points to a shared dependency such as an expired certificate, an authentication server, or a controller configuration change."},
{id:"u9l2-4",t:"u9l2",q:"What is a virtual server?",a:["A server located in another building","A server accessible only by wireless","A backup copy of a server","A server running as a virtual machine on a hypervisor that shares one physical host with other virtual machines"],c:3,e:"Virtualization runs multiple independent servers on one physical machine under a hypervisor, providing consolidation and easy snapshots, but a host failure affects every VM on it."},
{id:"u9l2-5",t:"u9l2",q:"A hospital considers a cloud-hosted maintenance management system that will store patient-identifiable device histories. What agreement must be in place with the provider?",a:["A business associate agreement covering protected health information","A software license only","A wireless spectrum license","A DICOM conformance statement"],c:0,e:"When a vendor stores or accesses PHI, HIPAA requires a business associate agreement along with encryption, access controls, and audit logging."},

// u9l3
{id:"u9l3-1",t:"u9l3",q:"A monitor has no link light at its network port, but a laptop plugged into the same wall jack shows link. What should be tried next?",a:["Reconfigure the monitor's IP address","Swap the monitor's patch cable, then suspect the monitor's network interface","Restart the central station","Call the vendor for a software update"],c:1,e:"Link at the jack with a laptop proves the building wiring and switch port; no link at the monitor points to its patch cable or its own network interface."},
{id:"u9l3-2",t:"u9l3",q:"A ping to a server returns 'Destination host unreachable.' What does this most likely indicate?",a:["The server is powered off","A firewall blocked the ping","The sending device has no route, typically a wrong gateway or subnet mask on its own configuration","The DNS server is down"],c:2,e:"'Unreachable' comes from the sender's own stack or gateway having no path. 'Request timed out' indicates the packet was sent but no reply returned."},
{id:"u9l3-3",t:"u9l3",q:"Which command displays a device's IP address, subnet mask, default gateway, and DHCP lease on a Windows computer?",a:["ping","tracert","nslookup","ipconfig /all"],c:3,e:"ipconfig /all shows the complete network configuration. ping tests reachability, tracert shows the router path, and nslookup tests name resolution."},
{id:"u9l3-4",t:"u9l3",q:"A cable passes a simple continuity test but the link fails at gigabit speed and works only at 100 Mb/s. What is the likely cable problem?",a:["A split pair or excessive length that continuity testing does not reveal","A completely open conductor","The wrong connector color","A shorted pair"],c:0,e:"Split pairs pass pin-to-pin continuity but ruin the twisted-pair signaling needed at higher speeds; a wiring-map or certification tester detects them."},
{id:"u9l3-5",t:"u9l3",q:"When reporting a monitoring network problem to IT, what should the technician include?",a:["A request to replace the switch","The device's address and MAC, the symptom timeline, the tests performed with results, and a specific question about recent changes","A guess about the cause","Only the room number"],c:1,e:"Measured facts and a specific question shorten resolution dramatically. IT can check a port, VLAN, or change window when given the address, MAC, and timeline."},

// u9l4
{id:"u9l4-1",t:"u9l4",q:"Which HL7 message type informs connected systems that a patient has been admitted, transferred, or discharged?",a:["ORU","ORM","ADT","ACK"],c:2,e:"ADT messages maintain the census across systems. ORU carries results and observations, ORM carries orders, and ACK acknowledges receipt."},
{id:"u9l4-2",t:"u9l4",q:"In an HL7 results message, which segment carries an individual observation value such as a heart rate?",a:["MSH","PID","OBR","OBX"],c:3,e:"OBX segments hold each observation with its identifier, value, and units. MSH is the header, PID identifies the patient, and OBR describes the observation request."},
{id:"u9l4-3",t:"u9l4",q:"Which three parameters must match on both a CT scanner and the PACS for DICOM communication to succeed?",a:["AE title, IP address, and port","Username, password, and domain","MAC address, VLAN, and gateway","Patient name, MRN, and date"],c:0,e:"Each DICOM node is configured with the other's application entity title, IP address, and port. A mismatch in any one prevents the association."},
{id:"u9l4-4",t:"u9l4",q:"What is the purpose of DICOM verification (C-ECHO)?",a:["To send an image to PACS","To confirm two DICOM nodes are configured to communicate, similar to a network ping at the application level","To retrieve a patient's prior studies","To print a film"],c:1,e:"C-ECHO tests the DICOM association between two nodes without transferring images, verifying titles, addresses, and ports at the application layer."},
{id:"u9l4-5",t:"u9l4",q:"Why should a technologist select a patient from the modality worklist rather than typing demographics at the imaging device?",a:["Typing is slower","Typing is not permitted by DICOM","Worklist populates the study with correct demographics from the RIS and prevents mismatched studies in PACS","Worklist compresses the images"],c:2,e:"Manual entry creates spelling and identifier errors that produce orphaned or mismatched studies requiring PACS administrator merges. Worklist pulls verified data from the scheduling system."},

// u9l5
{id:"u9l5-1",t:"u9l5",q:"A patient monitor is being returned to the vendor for a trade-in. What must be done first?",a:["Nothing, because monitors do not store patient data","Cover the screen with tape","Remove the battery only","Sanitize or remove stored patient data from the device and document it"],c:3,e:"Monitors store trends, waveforms, and patient identifiers, all of which are PHI. Storage must be sanitized with a documented method before the device leaves the organization."},
{id:"u9l5-2",t:"u9l5",q:"Which practice best describes the principle of least privilege?",a:["Each account has only the access its role requires, and default vendor passwords are changed","Everyone shares one administrator account for convenience","Passwords are written on the device for quick access","All users have full access to simplify support"],c:0,e:"Least privilege limits each account to what the job needs and removes default credentials, containing the damage from any compromised account."},
{id:"u9l5-3",t:"u9l5",q:"What is the most common way malware enters a healthcare network?",a:["Through the medical telemetry antennas","Phishing emails and messages that trick users into clicking links or opening attachments","Through the hospital's paging system","Through calibrated test equipment"],c:1,e:"Phishing is the leading initial entry point for malware and credential theft, which is why training and reporting suspicious messages are core defenses."},
{id:"u9l5-4",t:"u9l5",q:"Why are medical devices placed on their own VLANs with firewall rules?",a:["To make them faster","Because DICOM requires a separate VLAN","To segment them so an infection on the general network cannot reach devices that may run unpatched operating systems","To reduce cabling costs"],c:2,e:"Segmentation limits the traffic that can reach medical devices, protecting those that cannot be patched promptly and containing outbreaks like ransomware."},
{id:"u9l5-5",t:"u9l5",q:"A central station displays a ransomware message. What should the technician do first?",a:["Power it off and reinstall the software","Ignore it and continue monitoring","Pay the ransom to restore monitoring","Disconnect it from the network, keep it powered for forensics, switch the unit to downtime procedures, and notify IT security and risk management"],c:3,e:"Isolating the machine stops spread, preserving it supports investigation, and downtime procedures maintain patient safety. Recovery uses clean rebuilds and tested backups."},

// u9l6
{id:"u9l6-1",t:"u9l6",q:"A computer's clock resets to a default date every time it is powered on and its firmware settings are lost. What is the most likely cause?",a:["A dead CMOS battery on the motherboard","A failing hard drive","A virus","A bad network cable"],c:0,e:"The CMOS battery maintains firmware settings and the real-time clock when power is off. When it dies, the date resets and settings revert at each boot."},
{id:"u9l6-2",t:"u9l6",q:"A lab analyzer console displays 'no bootable device' at startup. Which are the most likely causes?",a:["A failed graphics card","A failed storage drive, a wrong boot order, or a USB device left in a port","A dead power supply","A missing network connection"],c:1,e:"The firmware runs but cannot find an operating system, which points to the drive, the boot order, or removable media interfering with the boot."},
{id:"u9l6-3",t:"u9l6",q:"What is the difference between RAM and storage in a computer?",a:["RAM is permanent; storage is temporary","They are the same component","RAM is volatile working memory cleared at power off; storage persists data on a drive","RAM holds the operating system permanently"],c:2,e:"RAM holds data the processor is actively using and empties when power is removed. Storage such as an HDD or SSD retains the operating system, applications, and data."},
{id:"u9l6-4",t:"u9l6",q:"A RAID array on a central station server reports a degraded state but the system is still running. What should be done?",a:["Nothing, because the system still works","Turn off the server until the vendor visits","Reformat the array","Replace the failed drive promptly, because a second failure could cause total data loss"],c:3,e:"Degraded means one drive has failed and redundancy is gone. Replacing it promptly restores protection before another failure destroys the array."},
{id:"u9l6-5",t:"u9l6",q:"A serial (RS-232) connection between a legacy device and a computer shows only garbled characters. What must be matched on both ends?",a:["Baud rate, data bits, parity, stop bits, and the correct cable type","IP address and subnet mask","AE title and port","MAC address and VLAN"],c:0,e:"Serial links require identical communication parameters at both ends and the right cable (straight or null modem). A mismatch produces garbage or nothing."}
);
