// CBET Academy question bank, units 4 to 6. All questions are original.
window.FRA = window.FRA || {};
FRA.questions = FRA.questions || [];
FRA.questions.push(
// u4l1
{id:"u4l1-1",t:"u4l1",q:"On an ECG strip recorded at 25 mm/s, consecutive R waves are four large boxes apart. What is the heart rate?",a:["60 bpm","75 bpm","100 bpm","150 bpm"],c:1,e:"At 25 mm/s each large box is 0.20 s, so heart rate = 300 divided by the number of large boxes between R waves: 300 / 4 = 75 bpm. Using small boxes, 1500 / 20 also gives 75."},
{id:"u4l1-2",t:"u4l1",q:"Which ECG lead is defined as the voltage of the left leg electrode minus the right arm electrode?",a:["Lead I","Lead III","Lead II","aVR"],c:2,e:"Lead II = LL minus RA and is the standard monitoring lead. Lead I is LA minus RA and Lead III is LL minus LA; Einthoven's law states II = I + III."},
{id:"u4l1-3",t:"u4l1",q:"A cardiologist needs to evaluate ST-segment changes accurately. Which ECG bandwidth should be used?",a:["Monitoring mode, 0.5 to 40 Hz","Telemetry mode, 1 to 20 Hz","A 60 Hz notch filter only","Diagnostic mode, 0.05 to 150 Hz"],c:3,e:"Diagnostic bandwidth extends down to 0.05 Hz, low enough to reproduce the slow ST segment faithfully, and up to 150 Hz for sharp features. Monitoring mode's 0.5 Hz high-pass distorts ST segments."},
{id:"u4l1-4",t:"u4l1",q:"In the AHA electrode color code, which color is the right arm electrode?",a:["White","Red","Green","Black"],c:0,e:"RA is white, LA is black, RL is green (the reference), LL is red, and the chest lead is brown. The memory aid is white on the right, smoke over fire on the left."},
{id:"u4l1-5",t:"u4l1",q:"An ECG shows a slowly rolling baseline that rises and falls with the patient's breathing. What is the most likely cause?",a:["60 Hz interference from a nearby device","Wandering baseline from respiration and electrode movement","A pacemaker","Ventricular fibrillation"],c:1,e:"Slow baseline drift synchronized with breathing is wandering baseline caused by chest movement and drying electrodes. 60 Hz interference appears as a thick fuzzy trace, not a slow drift."},

// u4l2
{id:"u4l2-1",t:"u4l2",q:"Which blood pressure value does an oscillometric NIBP monitor measure directly, with the other values derived from it?",a:["Systolic pressure","Diastolic pressure","Mean arterial pressure","Pulse pressure"],c:2,e:"The cuff oscillations are largest at mean arterial pressure, which the monitor measures directly. Systolic and diastolic are derived from where the oscillation amplitude rises and falls past set fractions of the maximum."},
{id:"u4l2-2",t:"u4l2",q:"An adult patient with a large arm is measured with a standard adult cuff that is clearly too small. How will the readings be affected?",a:["The monitor will refuse to measure","They will read falsely low","They will be accurate but slow","They will read falsely high"],c:3,e:"A cuff that is too small or too loose must be inflated harder to occlude the artery and reads falsely high. Bladder width should be about 40 percent of the arm circumference."},
{id:"u4l2-3",t:"u4l2",q:"An arterial line transducer is mounted 13.6 cm below the patient's phlebostatic axis. How will the displayed pressure be affected?",a:["About 10 mmHg too high","About 10 mmHg too low","About 1 mmHg too high","Unaffected"],c:0,e:"Fluid columns add pressure: 13.6 cm of water equals 10 mmHg. A transducer below the reference level reads high by that amount; above the level it reads low. Re-level and re-zero."},
{id:"u4l2-4",t:"u4l2",q:"After a fast-flush test, an arterial waveform appears rounded with no dicrotic notch and no oscillations. Which condition is present, and how are the readings affected?",a:["Underdamping; systolic reads high","Overdamping; systolic reads low and diastolic high","Optimal damping; readings are accurate","Transducer failure; no reading"],c:1,e:"Overdamping from air bubbles, clots, kinks, or loose connections rounds the waveform, eliminates the notch, and causes systolic to read low and diastolic high. Underdamping causes ringing and a high systolic."},
{id:"u4l2-5",t:"u4l2",q:"What is the standard sensitivity of a disposable invasive pressure transducer that allows it to be used with any compliant monitor?",a:["50 microvolts per volt per mmHg","5 millivolts per mmHg","5 microvolts per volt per mmHg","1 volt per mmHg"],c:2,e:"The industry standard is 5 microvolts of output per volt of excitation per mmHg, so transducers and monitors from different vendors interchange."},

// u4l3
{id:"u4l3-1",t:"u4l3",q:"A patient rescued from a house fire has an SpO2 reading of 99 percent but is confused and cyanotic. What is the most likely explanation?",a:["The oximeter probe is on the wrong finger","Ambient light is lowering the reading","The patient has excellent oxygenation","Carboxyhemoglobin from carbon monoxide is causing a falsely high reading"],c:3,e:"Carboxyhemoglobin absorbs light like oxyhemoglobin, so a pulse oximeter reads falsely high in carbon monoxide poisoning. A blood gas with co-oximetry is needed."},
{id:"u4l3-2",t:"u4l3",q:"Which two wavelengths does a pulse oximeter use?",a:["About 660 nm red and 940 nm infrared","About 400 nm and 500 nm","About 1,000 nm and 2,000 nm","About 4.26 micrometers and 10 micrometers"],c:0,e:"Red light near 660 nm and infrared near 940 nm are absorbed differently by oxygenated and deoxygenated hemoglobin; the ratio of the pulsatile absorbances gives SpO2. Capnography uses 4.26 micrometer infrared."},
{id:"u4l3-3",t:"u4l3",q:"During transport, a ventilated patient's EtCO2 waveform suddenly disappears while the ventilator continues to show delivered volumes. What should be checked first?",a:["The capnograph's calibration","The patient and the airway connection, because loss of the waveform indicates disconnection, apnea, or loss of circulation","The monitor's battery","The ventilator's oxygen supply"],c:1,e:"CO2 appears in exhaled gas only when air moves and blood flows. A sudden flat capnogram means a disconnected or dislodged airway or lost circulation and is a clinical emergency, checked before any equipment troubleshooting."},
{id:"u4l3-4",t:"u4l3",q:"A capnography system draws a sample of exhaled gas through thin tubing to a sensor inside the monitor. Which type is this, and what is its known drawback?",a:["Mainstream; adds dead space at the airway","Transcutaneous; requires skin heating","Sidestream; introduces a delay and requires a water trap and clean tubing","Impedance; is fooled by motion"],c:2,e:"Sidestream capnography samples gas through tubing, allowing use on non-intubated patients but adding delay and clogging risk. Mainstream places the sensor at the airway."},
{id:"u4l3-5",t:"u4l3",q:"A new temperature probe reads 3 degrees lower than a reference on the same patient. What is the most likely cause?",a:["The patient's temperature changed","The probe needs a longer warm-up","The monitor's ECG cable is loose","The probe is from a different YSI series than the monitor expects"],c:3,e:"Thermistor probes follow either the YSI 400 or YSI 700 resistance curve, and the two are not interchangeable. A mismatched probe reads several degrees off without an error message."},

// u4l4
{id:"u4l4-1",t:"u4l4",q:"Under IEC 60601-1-8, how is a high-priority alarm such as asystole indicated visually?",a:["A flashing red light","A flashing yellow light","A steady cyan light","A steady green light"],c:0,e:"High-priority alarms are red and flashing with an urgent tone; medium-priority alarms are yellow and flashing; low-priority alarms are cyan or yellow and steady."},
{id:"u4l4-2",t:"u4l4",q:"Every monitor on a nursing unit simultaneously stops displaying at the central station, although each bedside monitor still works locally. Where should troubleshooting begin?",a:["Each bedside monitor's ECG cable","The network switch or central station server, because the problem is system-wide","The patient electrodes","The telemetry transmitter batteries"],c:1,e:"When all beds fail at once the common element is the network or the central station. A single bed offline points to that bed's cable, port, or configuration."},
{id:"u4l4-3",t:"u4l4",q:"Which frequency bands are reserved in the United States for wireless medical telemetry?",a:["2.4 GHz and 5 GHz","88 to 108 MHz","608 to 614 MHz, 1395 to 1400 MHz, and 1427 to 1432 MHz","900 MHz only"],c:2,e:"The Wireless Medical Telemetry Service bands are protected from interference: 608 to 614 MHz, 1395 to 1400 MHz, and 1427 to 1432 MHz. Some systems use Wi-Fi at 2.4 and 5 GHz, which is shared."},
{id:"u4l4-4",t:"u4l4",q:"A unit reports many false lead-off alarms from telemetry patients every shift. What is the most likely cause and the best corrective action?",a:["Failed transmitters; replace them all","Antenna failure; add antennas","Central station software; reinstall it","Poor electrode contact and skin preparation; change electrodes daily and prep skin properly"],c:3,e:"False lead-off alarms come from high electrode impedance: dried gel, poor skin prep, and old electrodes. Daily electrode changes and proper preparation are standard alarm management measures."},
{id:"u4l4-5",t:"u4l4",q:"Staff on a busy unit have begun silencing monitor alarms without checking the patient because so many are false. What is this phenomenon called?",a:["Alarm fatigue","Alarm escalation","Signal saturation","Telemetry drift"],c:0,e:"Alarm fatigue occurs when excessive low-value alarms desensitize staff, so real alarms are missed. Alarm management programs adjust limits, delays, and electrode practices to reduce it."},

// u4l5
{id:"u4l5-1",t:"u4l5",q:"How does a fetal monitor measure fetal heart rate non-invasively?",a:["Impedance pneumography","Ultrasound Doppler detecting the moving fetal heart","ECG electrodes on the mother's abdomen","Infrared absorption"],c:1,e:"The ultrasound transducer detects the frequency shift from the moving fetal heart and derives a rate. A fetal scalp electrode is the direct, invasive alternative."},
{id:"u4l5-2",t:"u4l5",q:"A fetal heart rate trace shows 78 bpm that exactly matches the maternal pulse displayed on the monitor. What has most likely happened?",a:["The fetus is in distress","The tocodynamometer belt is too tight","The Doppler transducer has locked onto the maternal pulse and must be repositioned","The paper speed is wrong"],c:2,e:"When the FHR trace matches the maternal pulse, the ultrasound is detecting the mother's vessels rather than the fetal heart. Reposition the transducer and confirm; monitors display maternal pulse for this comparison."},
{id:"u4l5-3",t:"u4l5",q:"What does a tocodynamometer measure?",a:["Intrauterine pressure in mmHg","Fetal heart rate","Fetal oxygen saturation","The timing and duration of uterine contractions by sensing abdominal firmness"],c:3,e:"The TOCO is a pressure-sensing button strapped over the fundus. It shows when contractions occur and how long they last but not true intrauterine pressure; an intrauterine pressure catheter provides that."},
{id:"u4l5-4",t:"u4l5",q:"What is the 10-20 system used in EEG?",a:["A standardized method of placing scalp electrodes at proportional intervals of head measurements","A gain and filter setting","A sampling rate specification","A classification of seizure types"],c:0,e:"The 10-20 system places electrodes at 10 and 20 percent intervals of measured head dimensions so placements are consistent and reproducible between laboratories."},
{id:"u4l5-5",t:"u4l5",q:"Which EEG frequency band is below 4 Hz and associated with deep sleep?",a:["Alpha","Delta","Theta","Beta"],c:1,e:"Delta rhythms are below 4 Hz and dominate deep sleep. Theta is 4 to 8 Hz, alpha 8 to 13 Hz in relaxed wakefulness, and beta above 13 Hz in alert states."},

// u4l6
{id:"u4l6-1",t:"u4l6",q:"Which test instrument measures the energy a defibrillator actually delivers?",a:["An electrical safety analyzer","A patient simulator","A defibrillator analyzer with a 50-ohm load","An oscilloscope"],c:2,e:"A defibrillator analyzer presents a 50-ohm load that mimics the patient and measures delivered energy, charge time, synchronization, and pacing output."},
{id:"u4l6-2",t:"u4l6",q:"A ventilator displays a PEEP of 10 cm H2O. Approximately how much is this in mmHg?",a:["13.6 mmHg","1.36 mmHg","10 mmHg","7.4 mmHg"],c:3,e:"1 mmHg equals 1.36 cm H2O, so 10 cm H2O divided by 1.36 is about 7.4 mmHg."},
{id:"u4l6-3",t:"u4l6",q:"A patient's temperature is recorded as 102.2 F. What is this in Celsius?",a:["39.0 C","38.0 C","37.0 C","40.0 C"],c:0,e:"C = (F minus 32) / 1.8 = (102.2 minus 32) / 1.8 = 70.2 / 1.8 = 39.0 C."},
{id:"u4l6-4",t:"u4l6",q:"What is the difference between lumens and lux when evaluating a surgical light?",a:["Lumens measure color temperature; lux measures brightness","Lumens are the lamp's total light output; lux is the illumination arriving at a surface, rated at one meter","Lux is the total output; lumens are at the surface","They are the same unit"],c:1,e:"Lumens describe how much light a source emits in total. Lux is lumens per square meter at the illuminated surface, which is why surgical lights are specified in lux at one meter."},
{id:"u4l6-5",t:"u4l6",q:"Before using a safety analyzer to test a patient monitor, what should the technician confirm about the analyzer itself?",a:["That it is the same brand as the monitor","That it has been reset to factory defaults","That its calibration is current and traceable, shown by the calibration label","That it is plugged into a red outlet"],c:2,e:"Test equipment has its own calibration schedule traceable to national standards. An out-of-calibration analyzer produces readings that cannot be trusted or defended in an audit."},

// u5l1
{id:"u5l1-1",t:"u5l1",q:"How is a spirometer's volume accuracy verified?",a:["With a sound level meter","With a patient simulator","With certified test weights","With a 3-liter calibration syringe delivered at several speeds"],c:3,e:"A 3-liter syringe pushed at different speeds checks that the spirometer reads the known volume within a few percent across flow rates. Filters and mouthpieces are replaced for infection control."},
{id:"u5l1-2",t:"u5l1",q:"An ultrasound examination of a superficial vessel in the neck requires the best possible resolution. Which transducer frequency is most appropriate?",a:["10 MHz or higher","3.5 MHz","5 MHz","2 MHz"],c:0,e:"Higher ultrasound frequencies give better resolution but less penetration, so superficial structures use high-frequency transducers. Deep abdominal imaging uses 2 to 5 MHz."},
{id:"u5l1-3",t:"u5l1",q:"What instrument is used to calibrate an audiometer?",a:["A tachometer","A sound level meter with an artificial ear coupler","A light meter","A 3-liter syringe"],c:1,e:"Audiometer output is verified with a sound level meter attached to a coupler that simulates the ear, typically annually, plus daily listening checks. Testing must occur in a quiet booth."},
{id:"u5l1-4",t:"u5l1",q:"Which two safety items must be present in a room where cardiac stress testing is performed?",a:["A GFCI outlet and a light meter","A fire extinguisher and a UPS","A crash cart with a defibrillator and an emergency stop on the treadmill","An isolation transformer and a tachometer"],c:2,e:"Stress testing provokes cardiac events, so a defibrillator and emergency equipment must be immediately available, and the treadmill must have an emergency stop the patient can reach."},
{id:"u5l1-5",t:"u5l1",q:"How should a patient scale be verified during preventive maintenance?",a:["By weighing a technician and comparing to a bathroom scale","By measuring the load cell resistance only","By checking the display brightness","By applying certified test weights at several points of the range and confirming return to zero"],c:3,e:"Certified test weights verify accuracy across the range, and the scale should return to zero when unloaded. Level placement and nothing touching the platform are also confirmed."},

// u5l2
{id:"u5l2-1",t:"u5l2",q:"A nurse opens the door of a large-volume pump to change the administration set and the bag begins running rapidly into the patient by gravity. Which safety feature has failed or been bypassed?",a:["Free-flow protection","Downstream occlusion alarm","Air-in-line detection","The drug library"],c:0,e:"Free-flow protection uses a clamp in the set or the pump's door mechanism to stop gravity flow whenever the set is removed. Its failure can deliver an entire bag in minutes."},
{id:"u5l2-2",t:"u5l2",q:"An order calls for 1,000 mL of fluid to be infused over 8 hours. What rate should be programmed on the pump?",a:["80 mL/hr","125 mL/hr","100 mL/hr","250 mL/hr"],c:1,e:"Rate in mL/hr equals total volume divided by hours: 1,000 / 8 = 125 mL/hr."},
{id:"u5l2-3",t:"u5l2",q:"A 70 kg patient is ordered a drug at 0.1 mg/kg/hr from a bag containing 1 mg/mL. What pump rate delivers this dose?",a:["0.7 mL/hr","70 mL/hr","7 mL/hr","10 mL/hr"],c:2,e:"Dose per hour = 0.1 mg/kg/hr x 70 kg = 7 mg/hr. At 1 mg/mL, that is 7 mL/hr. Always convert dose to mass per hour, then divide by concentration."},
{id:"u5l2-4",t:"u5l2",q:"Which infusion device feature limits how often a patient can self-administer a dose of pain medication?",a:["Keep-vein-open rate","The air-in-line sensor","Upstream occlusion detection","The lockout interval on a PCA pump"],c:3,e:"Patient-controlled analgesia pumps enforce a lockout interval between boluses and an hourly or four-hour maximum, and log every request and delivery in a locked case."},
{id:"u5l2-5",t:"u5l2",q:"A syringe pump is programmed at 0.5 mL/hr, yet no drug reaches the patient for several minutes after starting. What is the most likely explanation?",a:["Start-up delay from mechanical slack at very low rates, or an unseated syringe","The pump's battery is low","The drug library blocked the infusion","The air-in-line sensor is dirty"],c:0,e:"At very low rates, the lead screw must take up mechanical slack before the plunger moves, causing a start-up delay. A syringe not fully seated and clamped produces the same result."},

// u5l3
{id:"u5l3-1",t:"u5l3",q:"In an infant incubator's servo mode, what does the controller use as its target?",a:["The set air temperature","The temperature measured by a probe on the infant's skin","The room temperature","The humidity level"],c:1,e:"Skin (servo) mode adjusts the heater to hold the infant's skin probe at the set temperature. Air mode holds the air temperature instead. Probe-off alarms are essential in servo mode."},
{id:"u5l3-2",t:"u5l3",q:"A radiant warmer's skin probe falls off the infant and the heater continues at full output. Which safety function has failed?",a:["The humidity alarm","The phototherapy timer","The probe-off or probe-failure alarm that should stop uncontrolled heating","The fan interlock"],c:2,e:"Radiant warmers depend on the skin probe for servo control; a probe-off alarm must sound and limit heating, or the warmer runs open-loop and can burn the infant."},
{id:"u5l3-3",t:"u5l3",q:"What wavelength range is used for neonatal phototherapy, and how is its output verified?",a:["Infrared, 940 nm; verified with a thermometer","Red light, 660 nm; verified with an SpO2 simulator","Ultraviolet, 254 nm; verified with a light meter","Blue light around 425 to 475 nm; verified with a radiometer"],c:3,e:"Blue light in the 425 to 475 nm range breaks down bilirubin. Output is measured with a radiometer in microwatts per square centimeter per nanometer, and lamps are replaced by hours of use."},
{id:"u5l3-4",t:"u5l3",q:"A patient is burned under a forced-air warming blanket. Investigation finds the hose was used without the blanket attached. What is this practice called, and why does it cause injury?",a:["Hosing; the concentrated outlet air is hot enough to burn skin","Servo failure; the water temperature exceeded 42 C","Alternate pathing; ESU current returned through the hose","Siphoning; fluid drained into the blanket"],c:0,e:"Using the warmer hose without its diffusing blanket, called hosing, directs hot air onto a small area of skin and causes burns. The blanket must always be attached."},
{id:"u5l3-5",t:"u5l3",q:"Which vacuum setting is typical for adult airway suctioning?",a:["10 to 20 mmHg","80 to 120 mmHg","300 to 400 mmHg","760 mmHg"],c:1,e:"Adult airway suction is typically regulated to about 80 to 120 mmHg; children and infants use lower settings. Regulators are verified against a vacuum gauge."},

// u5l4
{id:"u5l4-1",t:"u5l4",q:"A laboratory centrifuge vibrates violently and moves across the bench when started. What should be checked first?",a:["The lid interlock switch","The timer accuracy","Whether the tubes are balanced by weight in opposing positions","The room temperature"],c:2,e:"An unbalanced rotor is the most common cause of centrifuge vibration and a safety hazard. Loads must be balanced by weight opposite each other; persistent vibration then points to the rotor or a bearing."},
{id:"u5l4-2",t:"u5l4",q:"What is the required storage temperature range for blood products and most vaccines, and what must the storage unit provide?",a:["Minus 20 to minus 10 C; a lockable door","0 to 4 C; a glass door","10 to 15 C; humidity control","2 to 8 C; continuous temperature logging with high and low alarms"],c:3,e:"Blood and vaccines are stored at 2 to 8 C. Refrigerators must log temperature continuously, alarm on excursions with remote notification, and be on emergency power; an excursion can destroy the inventory."},
{id:"u5l4-3",t:"u5l4",q:"How is centrifuge speed verified during preventive maintenance?",a:["With a tachometer, often optical or strobe, compared against the set RPM","By listening to the motor","By timing a full cycle","By measuring the rotor diameter"],c:0,e:"A tachometer measures actual rotor speed against the setting. Because relative centrifugal force depends on speed squared and rotor radius, speed errors change separation results."},
{id:"u5l4-4",t:"u5l4",q:"A pathology department asks the biomed shop to add a cryostat to the inventory. What kind of device is a cryostat?",a:["A refrigerated centrifuge","A microtome inside a refrigerated chamber for cutting frozen tissue sections","A freezer alarm system","A cooled incubator for cell culture"],c:1,e:"A cryostat houses a microtome in a chamber at about minus 20 C so frozen tissue sections can be cut for rapid diagnosis during surgery. Blade sharpness and biohazard handling are the key safety concerns."},
{id:"u5l4-5",t:"u5l4",q:"How do laboratory analyzers prove that their measurements remain accurate between calibrations?",a:["By replacing reagents weekly","By restarting daily","By running quality control samples with known values","By running distilled water"],c:2,e:"Calibrators set the analyzer's scale and quality control samples with known values are run regularly to prove the calibration holds. Out-of-range QC halts patient testing until corrected."},

// u6l1
{id:"u6l1-1",t:"u6l1",q:"Why can an electrosurgical unit pass hundreds of milliamps through a patient without causing muscle contraction?",a:["Because the current is direct current","Because the patient is anesthetized","Because the return electrode absorbs the stimulation","Because its frequency of about 300 kHz to 3 MHz is above the range that stimulates nerves and muscle"],c:3,e:"Nerve and muscle membranes cannot respond to reversals faster than roughly 100 kHz, so ESU current at hundreds of kilohertz heats tissue without stimulation."},
{id:"u6l1-2",t:"u6l1",q:"A patient suffers a burn under the return electrode pad during a long procedure. Which ESU feature is designed to prevent this, and how does it work?",a:["Return electrode monitoring; a split pad's contact impedance is measured and the generator disables output if contact degrades","Bipolar mode; it eliminates the pad","The coagulation waveform; it lowers voltage","A footswitch interlock; it limits activation time"],c:0,e:"Return electrode (contact quality) monitoring measures impedance between the halves of a split pad and inhibits the ESU when the contact area shrinks or the pad disconnects, preventing current concentration burns."},
{id:"u6l1-3",t:"u6l1",q:"Which electrosurgical waveform is a continuous sine wave used to vaporize tissue for a clean incision?",a:["Coagulation","Cut","Blend","Fulguration"],c:1,e:"Cut mode uses a continuous, lower-voltage sine wave that boils cells and creates a clean cut with little hemostasis. Coagulation uses interrupted, higher-voltage bursts that dry and seal tissue."},
{id:"u6l1-4",t:"u6l1",q:"Which instrument verifies an electrosurgical unit's output power and the function of its return electrode monitoring?",a:["A defibrillator analyzer","A gas flow analyzer","An electrosurgical analyzer with selectable loads and a split-pad simulator","A patient simulator"],c:2,e:"An ESU analyzer measures output power into tissue-like loads, high-frequency leakage, and tests return electrode monitoring by simulating a balanced, unbalanced, and disconnected split pad."},
{id:"u6l1-5",t:"u6l1",q:"The laparoscopic video image in an OR has become dim and yellowish over several months. What is the most likely cause?",a:["The camera control unit software","The insufflator","The video routing switcher","Broken fibers in the light cable or an aged lamp in the light source"],c:3,e:"Light cables lose fibers with repeated flexing and lamps darken with age, dimming and discoloring the image. Holding the cable to a light shows dark spots where fibers are broken."},

// u6l2
{id:"u6l2-1",t:"u6l2",q:"During a PM, a pneumatic tourniquet displays 250 mmHg while a reference gauge on the same cuff reads 205 mmHg. What is the significance?",a:["The controller's gauge is out of calibration and could cause under- or over-pressurization; recalibrate before use","Normal variation; no action needed","The cuff is the wrong size","The reference gauge must be wrong"],c:0,e:"Tourniquet pressure accuracy directly affects patient safety: too low lets blood into the field, too high injures nerves and tissue. A 45 mmHg discrepancy requires calibration before return to service."},
{id:"u6l2-2",t:"u6l2",q:"What are the standard parameters of a gravity steam sterilization cycle, and what confirms the cycle was effective?",a:["100 C for 5 minutes; a chemical indicator","121 C at about 15 psi for 15 to 30 minutes; a biological indicator","132 C for 60 minutes; the printout alone","80 C for 30 minutes; a temperature log"],c:1,e:"Gravity steam cycles run at 121 C and about 15 psi for 15 to 30 minutes. Biological indicators containing spores prove lethality; chemical indicators only show exposure to the cycle."},
{id:"u6l2-3",t:"u6l2",q:"A blood warmer's outlet temperature measures 44 C during testing. What action is required?",a:["Note it and return to service","Increase flow to cool the outlet","Remove it from service because the over-temperature cutoff should prevent exceeding about 42 C, above which red cells are damaged","Replace the disposable cassette only"],c:2,e:"Blood must not be warmed above about 42 C. An outlet reading of 44 C means the over-temperature cutoff and alarm have failed; the device is unsafe until repaired and retested."},
{id:"u6l2-4",t:"u6l2",q:"In what unit is a surgical light's illumination specified?",a:["Lumens at the lamp","Candela per bulb","Watts of lamp power","Lux at one meter"],c:3,e:"Surgical lights are rated in lux, the illumination arriving at the surgical field, measured at one meter, along with color temperature and shadow control."},
{id:"u6l2-5",t:"u6l2",q:"A surgical microscope's head slowly drops toward the patient when released. What should be inspected?",a:["The stand's counterbalance and brakes","The eyepiece diopters","The fiber-optic light cable","The video camera port"],c:0,e:"A microscope head that drifts indicates the stand is out of balance or its brakes are failing, a serious injury risk. Balance and brake function are tested with the head fully loaded."},

// u6l3
{id:"u6l3-1",t:"u6l3",q:"A defibrillator set to 200 J delivers 150 J into the analyzer's 50-ohm load. What should the technician conclude?",a:["The reading is within tolerance","The delivered energy is out of tolerance, suggesting capacitor or relay problems, and the unit must be removed from service","The analyzer needs a higher load","The battery is fully charged"],c:1,e:"Delivered energy must fall within the manufacturer's tolerance, often about 15 percent. A 25 percent shortfall indicates aging capacitors or relay problems and the defibrillator cannot remain in service."},
{id:"u6l3-2",t:"u6l3",q:"For which rhythm must a defibrillator's synchronized mode be used, and why?",a:["Ventricular fibrillation, to speed delivery","Asystole, to restart the heart","Atrial fibrillation with a pulse, so the shock is timed to the R wave and avoids the T wave, which could trigger VF","Pulseless ventricular tachycardia, to reduce energy"],c:2,e:"Cardioversion of organized rhythms is synchronized to the R wave because a shock landing on the T wave can cause ventricular fibrillation. VF and pulseless VT have no organized R wave and are shocked unsynchronized."},
{id:"u6l3-3",t:"u6l3",q:"What is the recommended first shock energy for defibrillating a child?",a:["1 J/kg","10 J/kg","4 J/kg","2 J/kg"],c:3,e:"Pediatric defibrillation begins at 2 J/kg and increases to 4 J/kg for subsequent shocks. Adult biphasic doses are typically 120 to 200 J."},
{id:"u6l3-4",t:"u6l3",q:"An external pacemaker in demand mode is set to 70 bpm. How does it behave when the patient's own heart rate is 85 bpm?",a:["It inhibits pacing because the intrinsic rate exceeds the set rate","It paces at 70 bpm regardless","It increases its rate to 85","It alarms for loss of capture"],c:0,e:"Demand mode senses intrinsic beats and paces only when the patient's rate falls below the set rate. Fixed (asynchronous) mode would pace regardless and risk competing with the heart."},
{id:"u6l3-5",t:"u6l3",q:"How does an intra-aortic balloon pump assist a failing heart?",a:["It inflates during systole to push blood forward","It inflates during diastole to increase coronary perfusion and deflates just before systole to reduce afterload","It replaces the heart's pumping entirely","It paces the heart electrically"],c:1,e:"The balloon, filled with helium, inflates in diastole to push blood back toward the coronary arteries and deflates just before systole so the ventricle ejects against less resistance, improving oxygen supply and reducing demand."},

// u6l4
{id:"u6l4-1",t:"u6l4",q:"A ventilator sounds its high-pressure alarm. Which condition is most consistent with this alarm?",a:["A circuit disconnection","A leaking cuff","A kinked endotracheal tube or secretions obstructing the airway","An empty oxygen cylinder"],c:2,e:"High-pressure alarms indicate the ventilator cannot deliver gas: obstruction from kinks, secretions, coughing, biting, or bronchospasm. Disconnections and leaks trigger low-pressure alarms."},
{id:"u6l4-2",t:"u6l4",q:"What tidal volume should a ventilator deliver to a 70 kg adult at 7 mL per kg of ideal body weight, and what minute volume results at 14 breaths per minute?",a:["350 mL and 4.9 L/min","980 mL and 13.7 L/min","700 mL and 9.8 L/min","490 mL and 6.9 L/min"],c:3,e:"7 mL/kg x 70 kg = 490 mL tidal volume. Minute volume = tidal volume x rate = 490 mL x 14 = 6,860 mL, about 6.9 L/min."},
{id:"u6l4-3",t:"u6l4",q:"How is an oxygen analyzer calibrated before it is used to verify a ventilator's FiO2?",a:["At 21 percent (room air) and 100 percent oxygen","At 0 percent and 50 percent","At 50 percent only","It requires no calibration"],c:0,e:"Oxygen analyzers are calibrated at two points, room air (21 percent) and pure oxygen (100 percent). Galvanic sensors deplete over time and must be replaced."},
{id:"u6l4-4",t:"u6l4",q:"An anesthesia machine will not deliver nitrous oxide when the oxygen flow is turned off. What does this indicate?",a:["A flowmeter failure requiring repair","The hypoxic guard is functioning correctly by preventing a hypoxic gas mixture","An empty nitrous oxide cylinder","A scavenging system fault"],c:1,e:"The hypoxic guard links the oxygen and nitrous oxide controls so the delivered mixture never falls below about 21 to 25 percent oxygen. Refusing nitrous without oxygen is the safety feature working."},
{id:"u6l4-5",t:"u6l4",q:"Which vaporizer color code identifies sevoflurane?",a:["Purple","Blue","Yellow","Orange"],c:2,e:"Vaporizers are agent-specific and color coded: sevoflurane yellow, isoflurane purple, desflurane blue. Keyed fillers prevent charging a vaporizer with the wrong agent."}
);
