// CBET Academy question bank, units 1 to 3. All questions are original.
// Fields: id, t (lesson id), q (stem), a (four options), c (index of correct option), e (explanation).
window.FRA = window.FRA || {};
FRA.questions = FRA.questions || [];
FRA.questions.push(
// u1l1
{id:"u1l1-1",t:"u1l1",q:"A nurse asks a technician to move an SpO2 probe from the patient's wrist to a site more distal on the same arm. Where should the probe go?",a:["The elbow","A finger","The shoulder","The upper arm"],c:1,e:"Distal means farther from the trunk. On an arm, the fingers are distal to the wrist; the elbow, upper arm, and shoulder are all proximal to it."},
{id:"u1l1-2",t:"u1l1",q:"A monitor alarm log shows repeated entries labeled 'bradycardia.' What does this term indicate?",a:["A fast heart rate above 100 bpm","Difficulty breathing","A slow heart rate below 60 bpm","High blood pressure"],c:2,e:"Brady- means slow and cardia refers to the heart, so bradycardia is a heart rate below 60 beats per minute. Tachycardia is a rate above 100."},
{id:"u1l1-3",t:"u1l1",q:"An OR schedule lists a patient positioned prone for a spinal procedure. In which position will the patient be?",a:["Lying face up","Lying on the left side","Sitting upright","Lying face down"],c:3,e:"Prone is lying face down; supine is lying face up. Positioning terms matter for OR tables, pressure injury prevention, and equipment placement."},
{id:"u1l1-4",t:"u1l1",q:"Which layer of the skin provides most of the electrical resistance that limits shock current and that ECG skin preparation is meant to reduce?",a:["The epidermis","The subcutaneous fat","The dermis","The capillary bed"],c:0,e:"The dry outer epidermis is a good insulator. Skin prep and conductive gel lower its impedance for electrodes, and wet or broken skin removes that protection, which is why shock currents rise."},
{id:"u1l1-5",t:"u1l1",q:"A technician reading an incident report sees the word 'hypoxemia.' Decoding the word parts, what does it mean?",a:["Too much oxygen in the blood","Too little oxygen in the blood","Inflammation of the lungs","Removal of a lung"],c:1,e:"Hypo- means too little, ox refers to oxygen, and -emia means a blood condition, so hypoxemia is too little oxygen in the blood. Hyper- would mean too much."},

// u1l2
{id:"u1l2-1",t:"u1l2",q:"On an ECG tracing, which waveform represents depolarization of the ventricles?",a:["The P wave","The T wave","The QRS complex","The PR segment"],c:2,e:"The QRS complex is ventricular depolarization, which precedes ventricular contraction. The P wave is atrial depolarization and the T wave is ventricular repolarization."},
{id:"u1l2-2",t:"u1l2",q:"During a manual blood pressure measurement, the first tapping sound heard through the stethoscope as the cuff deflates corresponds to which pressure?",a:["Mean arterial pressure","Diastolic pressure","Pulse pressure","Systolic pressure"],c:3,e:"The first Korotkoff sound occurs when cuff pressure drops just below systolic and blood begins to pulse through; the point where sounds disappear marks diastolic."},
{id:"u1l2-3",t:"u1l2",q:"A nurse reports that the arterial line waveform no longer shows a dicrotic notch and reads a low systolic value. Which event does the dicrotic notch normally represent, and what does its absence suggest?",a:["Aortic valve closure; an overdamped line","Mitral valve opening; a clot in the catheter tip","SA node firing; a loose ECG electrode","Ventricular filling; a cuff that is too small"],c:0,e:"The dicrotic notch marks aortic valve closure on the arterial waveform. A rounded waveform without a notch and a falsely low systolic reading indicate overdamping from air, clot, kinks, or loose connections."},
{id:"u1l2-4",t:"u1l2",q:"A patient's blood pressure is 120/90 mmHg. What is the approximate mean arterial pressure?",a:["105 mmHg","100 mmHg","95 mmHg","110 mmHg"],c:1,e:"MAP = diastolic + (systolic minus diastolic) / 3 = 90 + 30/3 = 100 mmHg. Diastole lasts longer than systole, so the mean sits closer to the diastolic value."},
{id:"u1l2-5",t:"u1l2",q:"Which structure is the heart's natural pacemaker, initiating each normal heartbeat?",a:["The AV node","The bundle of His","The SA node","The Purkinje fibers"],c:2,e:"The sinoatrial node in the right atrium fires first, producing the P wave. The AV node delays the impulse, and the bundle of His and Purkinje fibers conduct it to the ventricles."},

// u1l3
{id:"u1l3-1",t:"u1l3",q:"Which monitored parameter most directly reflects how well a patient is ventilating (moving air) rather than how well the blood is oxygenated?",a:["SpO2","Temperature","Blood pressure","End-tidal CO2"],c:3,e:"End-tidal CO2 reflects ventilation and circulation, because CO2 reaches the lungs only if air is moving and blood is flowing. SpO2 reflects oxygenation, which can be maintained by supplemental oxygen even with poor ventilation."},
{id:"u1l3-2",t:"u1l3",q:"A ventilator is set to a tidal volume of 500 mL and a rate of 14 breaths per minute. What is the minute volume?",a:["7.0 L/min","5.0 L/min","3.5 L/min","14 L/min"],c:0,e:"Minute volume = tidal volume x rate = 500 mL x 14 = 7,000 mL, or 7.0 liters per minute."},
{id:"u1l3-3",t:"u1l3",q:"How does mechanical ventilation differ fundamentally from normal breathing?",a:["It uses negative pressure, whereas normal breathing uses positive pressure","It delivers gas under positive pressure, whereas normal breathing draws air in with negative pressure","It bypasses the alveoli","It removes CO2 chemically instead of by exhalation"],c:1,e:"Normal breathing lowers pressure in the chest so air flows in; a ventilator pushes gas in under positive pressure, which is why airway pressure limits and alarms are essential."},
{id:"u1l3-4",t:"u1l3",q:"A spirometry report shows an FEV1/FVC ratio of 0.55. What does this suggest?",a:["Normal lung function","A defective spirometer","Airway obstruction such as asthma or COPD","Excellent athletic conditioning"],c:2,e:"A normal FEV1/FVC ratio is roughly 0.7 to 0.8. A lower ratio means the patient cannot exhale quickly, the pattern of obstructive disease."},
{id:"u1l3-5",t:"u1l3",q:"In what order does inhaled air pass through the airway?",a:["Trachea, alveoli, bronchi, bronchioles","Bronchi, trachea, bronchioles, alveoli","Alveoli, bronchioles, bronchi, trachea","Trachea, bronchi, bronchioles, alveoli"],c:3,e:"Air travels from the trachea into the right and left bronchi, then progressively smaller bronchioles, ending in the alveoli where gas exchange occurs."},

// u1l4
{id:"u1l4-1",t:"u1l4",q:"Electrosurgical units deliver hundreds of milliamps through tissue without causing muscle contraction. Why?",a:["The frequency is far too high for nerves and muscles to respond","The current is DC","The return electrode absorbs all stimulation","The patient is grounded"],c:0,e:"Nerves and muscles respond to low-frequency current such as 60 Hz. ESU output at roughly 300 kHz to 3 MHz reverses too fast for membranes to follow, so it heats tissue without stimulating it."},
{id:"u1l4-2",t:"u1l4",q:"A frightened patient's heart rate and blood pressure rise on the monitor. Which part of the nervous system is responsible?",a:["The parasympathetic branch","The sympathetic branch","The cerebellum","The peripheral sensory nerves"],c:1,e:"The sympathetic branch of the autonomic nervous system produces the fight-or-flight response, raising heart rate and blood pressure. The parasympathetic branch slows the heart."},
{id:"u1l4-3",t:"u1l4",q:"Which EEG frequency band is typically seen in a relaxed adult with eyes closed?",a:["Delta, below 4 Hz","Theta, 4 to 8 Hz","Alpha, 8 to 13 Hz","Beta, above 13 Hz"],c:2,e:"Alpha rhythm at 8 to 13 Hz characterizes a relaxed, awake state with eyes closed. Delta is deep sleep, theta is drowsiness, and beta is active alertness."},
{id:"u1l4-4",t:"u1l4",q:"Which part of the brain controls breathing and heart rate, so that injury to it is immediately life-threatening?",a:["The cerebrum","The cerebellum","The spinal cord","The brainstem"],c:3,e:"The brainstem regulates breathing, heart rate, blood pressure, and consciousness. The cerebrum handles thought and voluntary movement, and the cerebellum coordinates balance."},
{id:"u1l4-5",t:"u1l4",q:"Which type of muscle is under voluntary control and is the tissue most often recorded by surface EMG?",a:["Skeletal muscle","Cardiac muscle","Smooth muscle","Visceral muscle"],c:0,e:"Skeletal muscle is voluntary and attached to bones; EMG records its electrical activity. Smooth muscle in vessels and the gut and cardiac muscle in the heart are involuntary."},

// u1l5
{id:"u1l5-1",t:"u1l5",q:"Why are enteral feeding pump connectors designed so they cannot attach to an intravenous line?",a:["To reduce manufacturing cost","To prevent feeding formula from being infused into a vein, which is fatal","To make cleaning easier","To allow higher flow rates"],c:1,e:"Enteral-only connectors are a deliberate design incompatibility. Formula belongs in the GI tract; infusing it into the bloodstream causes death, so the connectors physically prevent the error."},
{id:"u1l5-2",t:"u1l5",q:"By what process does waste move from the patient's blood into the dialysate across the dialyzer membrane?",a:["Active pumping by the machine","Chemical neutralization","Diffusion across a semipermeable membrane","Centrifugal separation"],c:2,e:"Hemodialysis relies on diffusion: waste molecules move from higher concentration in the blood to lower concentration in the dialysate across the semipermeable fibers, with pressure removing excess water."},
{id:"u1l5-3",t:"u1l5",q:"Which organ produces insulin, the hormone that lowers blood glucose?",a:["The liver","The thyroid","The adrenal gland","The pancreas"],c:3,e:"The pancreas releases insulin, which lowers blood glucose, and glucagon, which raises it. Diabetes results from too little insulin or resistance to it."},
{id:"u1l5-4",t:"u1l5",q:"A blood bank refrigerator alarm is set to trigger outside which normal storage range for blood products?",a:["2 to 8 C","0 to 2 C","Minus 20 to minus 10 C","10 to 15 C"],c:0,e:"Blood products and many vaccines are stored at 2 to 8 C with continuous temperature logging and alarms. Blood warmers must not exceed about 42 C when warming for transfusion."},
{id:"u1l5-5",t:"u1l5",q:"Which blood component carries oxygen and is the reason pulse oximetry works?",a:["Plasma","Hemoglobin in red blood cells","Platelets","White blood cells"],c:1,e:"Hemoglobin in red cells binds oxygen, and oxygenated and deoxygenated hemoglobin absorb red and infrared light differently, which is the principle behind pulse oximetry."},

// u2l1
{id:"u2l1-1",t:"u2l1",q:"A 24 V supply drives 3 A through a load. What is the load resistance?",a:["72 ohms","0.125 ohm","8 ohms","27 ohms"],c:2,e:"Ohm's law rearranged for resistance is R = V / I, so 24 volts divided by 3 amps gives 8 ohms. Multiplying instead (72) or dividing the other way (0.125) are the common mistakes."},
{id:"u2l1-2",t:"u2l1",q:"Two 100-ohm resistors are connected in parallel. What is the total resistance?",a:["200 ohms","100 ohms","25 ohms","50 ohms"],c:3,e:"For two equal resistors in parallel, total resistance is half of one: (100 x 100) / (100 + 100) = 50 ohms. Parallel resistance is always less than the smallest branch."},
{id:"u2l1-3",t:"u2l1",q:"In a series circuit, which electrical quantity is the same through every component?",a:["Current","Voltage","Power","Resistance"],c:0,e:"A series circuit has one path, so the same current flows through each component. Voltages across the components add up to the source voltage."},
{id:"u2l1-4",t:"u2l1",q:"The current through a resistor doubles. What happens to the power it dissipates?",a:["It doubles","It quadruples","It stays the same","It halves"],c:1,e:"P = I squared x R, so doubling the current multiplies power by four. This is why slightly overloaded components overheat and fail."},
{id:"u2l1-5",t:"u2l1",q:"Why is a 120 V shock through wet skin far more dangerous than through dry skin?",a:["Wet skin raises the voltage","Water changes the frequency of the current","Wet skin lowers body resistance, so Ohm's law gives a much larger current","Dry skin conducts better than wet skin"],c:2,e:"Current equals voltage divided by resistance. Dry skin may be 100,000 ohms (about 1 mA), while wet skin may be 1,000 ohms, allowing about 120 mA, which is in the fibrillation range."},

// u2l2
{id:"u2l2-1",t:"u2l2",q:"What is the approximate peak voltage of a 120 V RMS supply?",a:["85 V","120 V","240 V","170 V"],c:3,e:"Peak = 1.414 x RMS = 1.414 x 120 = about 170 V. RMS is the effective heating value that meters display."},
{id:"u2l2-2",t:"u2l2",q:"A line isolation monitor in an operating room alarms. What does this indicate?",a:["A first fault has raised the total hazard current to about 5 mA and should be located","The GFCI has tripped","The isolation transformer has failed open","The generator has started"],c:0,e:"The LIM continuously measures the isolated system's insulation and alarms at 5 mA of total hazard current, indicating a first fault. Staff unplug devices one at a time to find the faulty one before a second fault makes the system dangerous."},
{id:"u2l2-3",t:"u2l2",q:"Within how many seconds must a hospital's essential electrical system restore power after a utility failure?",a:["1 second","10 seconds","60 seconds","5 minutes"],c:1,e:"NFPA 99 and NFPA 70 require the alternate power source to restore power within 10 seconds. Life-support devices on red critical-branch outlets usually also have batteries to cover the gap."},
{id:"u2l2-4",t:"u2l2",q:"In a US power cord, which conductor color is the ground?",a:["Black","White","Green","Red"],c:2,e:"Black (or red) is hot, white is neutral, and green or bare is ground, which carries current only during a fault and provides the safety path."},
{id:"u2l2-5",t:"u2l2",q:"A GFCI outlet is installed near a sink in a patient room. Which statement about its protection is correct?",a:["It protects against microshock to a patient with a cardiac catheter","It trips at 10 microamps","It replaces the need for an equipment ground","It trips at about 5 mA of imbalance to protect people from macroshock but does not protect against microshock"],c:3,e:"A GFCI detects about 5 mA of current leaving on the hot conductor and not returning on the neutral, protecting people from macroshock. That threshold is far above the 10 microamp microshock level, so it offers no microshock protection."},

// u2l3
{id:"u2l3-1",t:"u2l3",q:"A monitor resets intermittently, and the power supply output shows excessive ripple. Which component is the most likely cause?",a:["A dried-out electrolytic filter capacitor","The transformer primary winding","A shorted zener diode","The line fuse"],c:0,e:"The filter capacitor smooths the rectified DC. As electrolytics age they dry out and lose capacitance, producing ripple, hum, low output under load, and random resets; a bulged top is the visual clue."},
{id:"u2l3-2",t:"u2l3",q:"A 10 kilohm resistor charges a 100 microfarad capacitor. Approximately what percentage of the final voltage is reached after 1 second?",a:["37%","63%","50%","99%"],c:1,e:"The time constant is R x C = 10,000 x 0.0001 = 1 second. After one time constant the capacitor reaches about 63% of its final voltage; after five it is about 99%."},
{id:"u2l3-3",t:"u2l3",q:"Which filter type removes 60 Hz mains interference from a physiological signal while passing the frequencies above and below it?",a:["Low-pass","High-pass","Notch","Band-pass"],c:2,e:"A notch filter removes a single narrow frequency band, and 60 Hz hum is its classic use. Low-pass and high-pass remove everything above or below a cutoff."},
{id:"u2l3-4",t:"u2l3",q:"A resistor is marked red, violet, orange, gold. What is its value?",a:["2.7 kilohms, 5%","27 ohms, 5%","270 kilohms, 10%","27 kilohms, 5%"],c:3,e:"Red 2, violet 7, orange multiplier of three zeros gives 27,000 ohms; gold is 5% tolerance."},
{id:"u2l3-5",t:"u2l3",q:"A technician troubleshooting a long signal path with a schematic measures the test point in the middle of the chain and finds it correct. Where is the fault?",a:["After the midpoint","Before the midpoint","At the power supply","In the first stage"],c:0,e:"Half-splitting: if the signal is correct at the midpoint, every stage before it is working, so the fault lies downstream. Testing the middle of the remaining section halves the search again."},

// u2l4
{id:"u2l4-1",t:"u2l4",q:"Place the stages of a linear power supply in the correct order from the mains input to the DC output.",a:["Rectifier, transformer, regulator, filter","Transformer, rectifier, filter capacitor, regulator","Filter capacitor, rectifier, transformer, regulator","Regulator, filter, transformer, rectifier"],c:1,e:"The transformer steps the voltage down, the rectifier converts AC to pulsing DC, the filter capacitor smooths it, and the regulator holds the output steady."},
{id:"u2l4-2",t:"u2l4",q:"Which amplifier characteristic allows an ECG front end to display a 1 mV heart signal despite volts of 60 Hz interference present on both electrodes?",a:["High input impedance alone","Low gain","High common-mode rejection ratio of a differential (instrumentation) amplifier","A large output capacitor"],c:2,e:"An instrumentation amplifier amplifies the difference between the two electrodes and rejects what they share. Interference appears on both electrodes equally and cancels; the heart signal appears as a difference and survives."},
{id:"u2l4-3",t:"u2l4",q:"Which component provides electrical isolation between a patient-connected input and the mains-powered circuitry?",a:["A zener diode","A filter capacitor","A bridge rectifier","An optocoupler or isolation amplifier"],c:3,e:"Optocouplers pass signals as light across a gap, and isolation amplifiers and transformers perform the same function for analog signals and power, keeping patient circuits floating so leakage cannot reach the patient."},
{id:"u2l4-4",t:"u2l4",q:"A device's fuse blows repeatedly when replaced. What does this most likely indicate?",a:["A shorted component downstream, which must be found before replacing the fuse","The fuse rating is too high","Normal aging of the fuse","A weak battery"],c:0,e:"A blown fuse is usually a symptom, not the fault. Repeated failures point to a shorted component such as a rectifier diode or output transistor; replacing the fuse without finding the short just blows another."},
{id:"u2l4-5",t:"u2l4",q:"An ECG in diagnostic mode must reproduce frequencies up to 150 Hz. What is the minimum sampling rate required by the Nyquist rule?",a:["75 samples per second","More than 300 samples per second","150 samples per second","1,500 samples per second"],c:1,e:"The Nyquist rule requires sampling at more than twice the highest frequency of interest, so more than 300 samples per second; practical designs sample at 500 to 1,000."},

// u2l5
{id:"u2l5-1",t:"u2l5",q:"An infusion pump runs normally on AC power but shuts down within seconds when unplugged. What are the most likely causes?",a:["A blown line fuse or a bad power cord","A failed display","A depleted or aged battery, a failed charger circuit, or a poor battery connection","A software fault"],c:2,e:"Normal operation on AC proves the supply and main circuitry work. Immediate shutdown on battery points to the battery itself, the charging circuit, or the connector between them."},
{id:"u2l5-2",t:"u2l5",q:"Which battery chemistry is prone to the memory effect that shrinks usable capacity after repeated partial discharges?",a:["Lithium-ion","Sealed lead-acid","Alkaline","Nickel-cadmium"],c:3,e:"Nickel-cadmium cells develop the memory effect and benefit from periodic full discharge and charge conditioning. Lithium-ion has no memory effect; lead-acid suffers from sulfation instead."},
{id:"u2l5-3",t:"u2l5",q:"A laboratory analyzer must never experience a power interruption, even for milliseconds, during a run. Which UPS type is appropriate?",a:["Online double-conversion","Line-interactive","Standby","A surge protector"],c:0,e:"An online double-conversion UPS continuously rectifies and re-inverts power, so the load never sees the utility and there is no transfer gap. Standby and line-interactive units have brief switching delays."},
{id:"u2l5-4",t:"u2l5",q:"What is the nominal voltage of a single lithium-ion cell?",a:["1.2 V","3.6 to 3.7 V","2.0 V","1.5 V"],c:1,e:"Lithium-ion cells are nominally 3.6 to 3.7 V. Nickel-cadmium and nickel-metal hydride are 1.2 V, lead-acid 2.0 V, and alkaline primary cells 1.5 V."},
{id:"u2l5-5",t:"u2l5",q:"During a PM, which battery test best verifies that a device's battery can still support clinical use?",a:["Measuring the open-circuit voltage","Checking that the charge indicator lights","Running the device on battery until the low-battery alarm and comparing the runtime to specification","Weighing the battery"],c:2,e:"Voltage says little about capacity. A runtime test under real load reveals aged batteries that still show full voltage but cannot deliver the specified minutes."},

// u3l1
{id:"u3l1-1",t:"u3l1",q:"At approximately what 60 Hz current level does a person lose the ability to release an energized conductor?",a:["1 mA","1 A","100 mA","10 to 20 mA"],c:3,e:"The let-go threshold is about 10 to 20 mA, where forearm muscles contract involuntarily. Perception is about 1 mA, and 100 to 300 mA is the fibrillation range."},
{id:"u3l1-2",t:"u3l1",q:"A patient has a fluid-filled catheter in the heart. Approximately how much current delivered through that catheter could cause ventricular fibrillation?",a:["10 microamps","5 mA","50 mA","1 A"],c:0,e:"Microshock bypasses the skin's resistance and delivers current directly to the heart, where as little as 10 microamps can trigger fibrillation. This is why cardiac-connected equipment has microamp leakage limits."},
{id:"u3l1-3",t:"u3l1",q:"A device with a broken ground pin continues to operate normally. Why is it still a hazard?",a:["It draws more current","Its normal leakage current has no safe path and may flow through a patient touching the chassis","It will overheat","Its fuse will blow"],c:1,e:"Every device leaks a small current to its chassis. The ground wire normally returns it safely. Without a ground, the chassis floats and the leakage can pass through anyone who touches the chassis and something grounded."},
{id:"u3l1-4",t:"u3l1",q:"Under NFPA 99, what is the maximum acceptable resistance between the chassis of patient-care equipment and the ground pin of its plug?",a:["0.1 ohm","5 ohms","0.5 ohm","50 ohms"],c:2,e:"Ground resistance must not exceed 0.5 ohm, ensuring fault and leakage current has a low-resistance path. Worn plugs, damaged cords, and loose internal ground straps raise it."},
{id:"u3l1-5",t:"u3l1",q:"During a PM, a technician finds a patient monitor's power cord with the ground pin missing and the strain relief pulled out. What is the correct action?",a:["Tape the strain relief and return the device to service","Use a two-prong adapter until a new cord arrives","Continue using it because the device still powers on","Replace the cord, retest electrical safety, and document the repair"],c:3,e:"Damaged cords are replaced, never taped, and adapters that defeat the ground are prohibited. After replacement the device is safety tested and the work is documented."},

// u3l2
{id:"u3l2-1",t:"u3l2",q:"Under IEC 60601-1, what is the normal-condition AC patient leakage limit for a type CF applied part?",a:["10 microamps","50 microamps","100 microamps","500 microamps"],c:0,e:"Type CF (cardiac floating) applied parts are limited to 10 microamps in normal condition and 50 microamps under single fault, because they may connect directly to the heart. Types B and BF allow 100 and 500 microamps."},
{id:"u3l2-2",t:"u3l2",q:"Which symbol identifies an applied part that is safe for direct cardiac connection?",a:["A stick figure","A heart inside a box","A stick figure inside a box","A square inside a square"],c:1,e:"The heart in a box marks a type CF applied part. A plain figure is type B, a figure in a box is type BF, and the square within a square denotes Class II double insulation."},
{id:"u3l2-3",t:"u3l2",q:"Why does a safety analyzer measure chassis leakage with the ground open and the polarity reversed as well as in normal condition?",a:["To warm up the device","To test the outlet rather than the device","Because those single-fault conditions raise leakage, and the device must remain safe under any single fault","Because normal-condition readings are unreliable"],c:2,e:"IEC 60601-1 requires safety under a single fault. Open ground and reversed polarity are the faults that most increase chassis leakage, so the analyzer simulates them and compares readings to the single-fault limits."},
{id:"u3l2-4",t:"u3l2",q:"Which document is the design and test standard for medical electrical equipment, as opposed to the code governing the health care facility?",a:["NFPA 99","NFPA 70","OSHA 29 CFR 1910","IEC 60601-1"],c:3,e:"IEC 60601-1 defines how medical electrical equipment is designed and tested, including classes, applied-part types, and leakage limits. NFPA 99 governs the facility's systems and testing practices, and NFPA 70 is the electrical code for building wiring."},
{id:"u3l2-5",t:"u3l2",q:"When must electrical safety testing be performed on a patient monitor?",a:["At incoming inspection, after any repair that could affect safety, and at scheduled preventive maintenance","Only when it is purchased","Only when a user reports a tingle","Once every five years"],c:0,e:"Testing at incoming inspection catches shipping damage and defects, testing after repair catches disturbed grounds and insulation, and scheduled PM catches aging. All three are documented."},

// u3l3
{id:"u3l3-1",t:"u3l3",q:"A technician must service a ventilator in the room of a patient with active tuberculosis. Which PPE is required?",a:["Gloves only","A fit-tested N95 respirator, in a negative-pressure room","A surgical mask","A face shield without a mask"],c:1,e:"Tuberculosis requires airborne precautions: a fit-tested N95 respirator and a negative-pressure isolation room. A surgical mask does not filter airborne particles adequately."},
{id:"u3l3-2",t:"u3l3",q:"When removing PPE after working in an isolation room, which item should be removed first?",a:["The gown","The mask","The gloves","Eye protection"],c:2,e:"Gloves are the most contaminated item and come off first, followed by eye protection, gown, and finally the mask, with hand hygiene between steps."},
{id:"u3l3-3",t:"u3l3",q:"A flexible endoscope contacts mucous membranes but does not enter sterile tissue. Under the Spaulding classification, what is the minimum reprocessing required?",a:["Low-level disinfection","No reprocessing between patients","Cleaning only","High-level disinfection"],c:3,e:"Semi-critical items that touch mucous membranes require at least high-level disinfection after thorough cleaning. Critical items entering sterile tissue must be sterilized; non-critical items touching intact skin need low-level disinfection."},
{id:"u3l3-4",t:"u3l3",q:"Why must a device be cleaned before it is disinfected?",a:["Dried soil and blood shield organisms from the disinfectant","Disinfectants are only effective on wet surfaces","Cleaning sterilizes the device","Disinfection damages dirty surfaces"],c:0,e:"Disinfectants cannot penetrate dried organic material. Cleaning with detergent and friction removes soil so the disinfectant can contact the organisms for the required time."},
{id:"u3l3-5",t:"u3l3",q:"What are the standard parameters for a gravity steam sterilization cycle?",a:["100 C at atmospheric pressure for 5 minutes","121 C at 15 psi for 15 to 30 minutes","150 C at 5 psi for 60 minutes","80 C at 30 psi for 10 minutes"],c:1,e:"Standard steam sterilization runs at 121 C (250 F) and about 15 psi for 15 to 30 minutes; flash cycles use 132 to 135 C for a few minutes. Biological indicators confirm the cycle killed spores."},

// u3l4
{id:"u3l4-1",t:"u3l4",q:"In the United States, a medical gas cylinder painted green contains which gas?",a:["Nitrous oxide","Carbon dioxide","Oxygen","Nitrogen"],c:2,e:"US cylinder colors: oxygen green, nitrous oxide blue, carbon dioxide gray, nitrogen black, medical air yellow, helium brown. Pin index and DISS fittings prevent wrong connections regardless of color."},
{id:"u3l4-2",t:"u3l4",q:"A technician is asked to bring a steel tool cart into an MRI suite to work on a monitor in the magnet room. What is the correct response?",a:["Proceed, because the scanner is not running","Proceed if the cart is unplugged","Proceed after turning off the room lights","Refuse, because the magnet is always on and ferromagnetic objects become projectiles in zone IV"],c:3,e:"The MRI magnet is always energized. Ferromagnetic objects are pulled into it with dangerous force. Only MR Safe or MR Conditional equipment enters zone IV, after screening."},
{id:"u3l4-3",t:"u3l4",q:"A small fire starts in an equipment closet. Using the RACE procedure, what is the first action?",a:["Rescue anyone in immediate danger","Pull the alarm","Extinguish the fire","Confine the fire by closing doors"],c:0,e:"RACE stands for Rescue, Alarm, Confine, Extinguish (or Evacuate), in that order. People in immediate danger are moved first, then the alarm is activated."},
{id:"u3l4-4",t:"u3l4",q:"A technician working near a fluoroscopy unit doubles their distance from the X-ray source. By roughly how much does their radiation exposure change?",a:["It halves","It drops to one quarter","It stays the same","It doubles"],c:1,e:"Radiation intensity follows the inverse square law: doubling the distance reduces exposure to one quarter. Time, distance, and shielding are the three protective principles under ALARA."},
{id:"u3l4-5",t:"u3l4",q:"Which section of a safety data sheet describes the first-aid measures to take after exposure?",a:["Section 2","Section 8","Section 4","Section 13"],c:2,e:"The 16-section SDS format places first-aid measures in Section 4. Section 2 is hazard identification, Section 8 covers exposure controls and PPE, and Section 13 covers disposal."},

// u3l5
{id:"u3l5-1",t:"u3l5",q:"Which federal agency establishes the Conditions of Participation that hospitals must meet, including requirements for maintaining equipment in safe operating condition?",a:["The FDA","OSHA","AAMI","CMS"],c:3,e:"The Centers for Medicare and Medicaid Services sets the Conditions of Participation. Accrediting organizations with deemed status survey hospitals on CMS's behalf."},
{id:"u3l5-2",t:"u3l5",q:"A hospital wants to move a category of infusion pumps to a maintenance interval longer than the manufacturer recommends. What must be in place for this to be acceptable under CMS rules?",a:["A documented risk assessment by a qualified individual supporting an alternative equipment maintenance program, with device history to justify the change","Approval from the pump manufacturer only","A memo from the nursing director","Nothing, because infusion pumps are exempt from maintenance requirements"],c:0,e:"CMS permits AEM programs when a qualified person documents a risk-based justification supported by the device's history. Imaging equipment, lasers, and devices with manufacturer or legal requirements are excluded from AEM."},
{id:"u3l5-3",t:"u3l5",q:"Which ANSI/AAMI standard provides guidance specifically for alternative equipment maintenance programs?",a:["EQ56","EQ103","EQ93","EQ89"],c:1,e:"EQ103 covers AEM programs. EQ56 is the recommended practice for a medical equipment management program, EQ89 addresses scheduled maintenance and performance verification, and EQ93 defines vocabulary."},
{id:"u3l5-4",t:"u3l5",q:"A patient dies and the event may be related to a malfunctioning infusion pump. Within what time must the hospital, as a user facility, report the death to the FDA and the manufacturer?",a:["24 hours","30 calendar days","10 work days","One year, in the annual report"],c:2,e:"Under FDA medical device reporting rules, user facilities report device-related deaths to both the FDA and the manufacturer within 10 work days. Serious injuries are reported to the manufacturer within 10 work days."},
{id:"u3l5-5",t:"u3l5",q:"During a survey, an accreditor asks for evidence that scheduled maintenance on life-support equipment was completed on time. Which source provides this?",a:["The manufacturer's brochure","The purchase order","The technician's memory","A PM completion report generated from the CMMS"],c:3,e:"The CMMS holds the PM schedule, completion records, and test results, and its reports demonstrate compliance. Work that is not documented in the CMMS cannot be shown to a surveyor."}
);
