// CBET Academy question bank for the supplementary lessons in curriculum-4.js. All questions are original.
// Fields: id, t (lesson id), q (stem), a (four options), c (index of correct option), e (explanation).
window.FRA = window.FRA || {};
FRA.questions = FRA.questions || [];
FRA.questions.push(
// u1l6
{id:"u1l6-1",t:"u1l6",q:"Which layer of the integumentary system lies deepest?",a:["Epidermis","Hypodermis","Dermis","Stratum basale"],c:1,e:"The hypodermis (subcutaneous layer) lies beneath the dermis. The stratum basale is only the deepest part of the epidermis, which is the outermost layer."},
{id:"u1l6-2",t:"u1l6",q:"A pathology report describes muscle tissue with filaments arranged without visible stripes. Which muscle type is this?",a:["Skeletal","Cardiac","Smooth","Striated"],c:2,e:"Smooth muscle is non-striated and involuntary, found in the walls of hollow organs and vessels. Skeletal and cardiac muscle are both striated."},
{id:"u1l6-3",t:"u1l6",q:"How many bones make up the adult appendicular skeleton?",a:["80","33","206","126"],c:3,e:"The appendicular skeleton (girdles and limbs) has 126 bones; the axial skeleton has 80; together they total 206. There are 33 vertebrae."},
{id:"u1l6-4",t:"u1l6",q:"In which part of the brain is sensory information interpreted?",a:["The cerebrum, in the parietal lobe","The cerebellum","The medulla oblongata","The pons"],c:0,e:"The parietal lobe of the cerebrum interprets sensory input and body position. The cerebellum coordinates movement, and the medulla and pons in the brain stem run autonomic functions."},
{id:"u1l6-5",t:"u1l6",q:"Which division of the nervous system controls voluntary movement such as walking?",a:["Autonomic","Somatic","Parasympathetic","Sympathetic"],c:1,e:"The somatic nervous system controls voluntary skeletal muscle. The autonomic system, with its sympathetic and parasympathetic branches, handles involuntary functions."},

// u1l7
{id:"u1l7-1",t:"u1l7",q:"Which statement correctly matches a digestive organ to its function?",a:["The jejunum is the first section of the small intestine","The gallbladder produces insulin","The large intestine reabsorbs water to form solid waste","The duodenum is the middle section where sugars are absorbed"],c:2,e:"The large intestine's main job is reabsorbing water. The duodenum is the first section of the small intestine, the jejunum the second, and insulin comes from the pancreas."},
{id:"u1l7-2",t:"u1l7",q:"Where are the parathyroid glands located?",a:["On the anterior surface of the thyroid's lateral lobes","Below the liver in the biliary tract","Behind the stomach near the duodenum","On the posterior aspect of the thyroid's lateral lobes"],c:3,e:"The four parathyroid glands sit on the posterior aspect of the thyroid's lateral lobes and regulate blood calcium."},
{id:"u1l7-3",t:"u1l7",q:"After a meal, insulin rises and lowers blood glucose, and as glucose falls the pancreas reduces insulin release. Which mechanism is this?",a:["Negative feedback","Positive feedback","Parasympathetic regulation","Stress response"],c:0,e:"Negative feedback reverses or minimizes a change to keep a system stable. Positive feedback amplifies a change, as in labor contractions."},
{id:"u1l7-4",t:"u1l7",q:"Which force primarily drives filtration of blood in the kidney's glomerulus?",a:["Osmosis","Blood pressure","Smooth muscle contraction","Peristalsis"],c:1,e:"Blood pressure forces filtrate out of the glomerular capillaries into Bowman's capsule. Peristalsis moves food through the gut, not blood through the kidney."},
{id:"u1l7-5",t:"u1l7",q:"Which statement about hemoglobin is incorrect?",a:["It is a protein found in red blood cells","It contains iron to which oxygen binds","It is the ratio of red blood cells to total blood volume","It transports oxygen from the lungs to the body"],c:2,e:"The ratio of red cells to blood volume is the hematocrit. Hemoglobin is the iron-containing protein inside red cells that carries oxygen."},

// u2l6
{id:"u2l6-1",t:"u2l6",q:"A lamp draws 500 mA from a 120 V source for 8 hours. How much energy does it use?",a:["60 kWh","480 kWh","4.8 kWh","0.48 kWh"],c:3,e:"Power is 0.5 A x 120 V = 60 W. Energy is power times time: 60 W x 8 h = 480 Wh = 0.48 kWh."},
{id:"u2l6-2",t:"u2l6",q:"A 120 V source feeds a 60 ohm resistor in series with a 100 ohm resistor. What is the voltage across the 60 ohm resistor?",a:["45 V","60 V","75 V","38 V"],c:0,e:"Voltage divides in proportion to resistance: 120 V x 60 / (60 + 100) = 120 x 0.375 = 45 V."},
{id:"u2l6-3",t:"u2l6",q:"At a circuit node, 9 A flows in while 5 A and 2 A leave on two branches. What current flows in the third branch?",a:["16 A","2 A","7 A","4 A"],c:1,e:"Kirchhoff's current law: current in equals current out. 9 A = 5 A + 2 A + I, so I = 2 A."},
{id:"u2l6-4",t:"u2l6",q:"A battery reads 1.58 V open circuit and drops to 1.46 V when an 80 ohm resistor is connected. What is its internal resistance?",a:["0.12 ohm","8.25 ohms","6.58 ohms","1.46 ohms"],c:2,e:"Load current is 1.46 / 80 = 0.01825 A. The 0.12 V lost inside the battery divided by that current gives 0.12 / 0.01825 = 6.58 ohms."},
{id:"u2l6-5",t:"u2l6",q:"An ideal inverting op-amp circuit uses a 5 kilohm input resistor and must have a gain of 9. What feedback resistance is required?",a:["556 ohms","180 kilohms","90 kilohms","45 kilohms"],c:3,e:"Inverting gain equals the feedback resistance divided by the input resistance, so R feedback = 9 x 5 kilohms = 45 kilohms."},

// u2l7
{id:"u2l7-1",t:"u2l7",q:"A circuit supplies 180 W of true power and 240 VAR of reactive power. What is the magnitude of the apparent power?",a:["300 VA","420 VA","60 VA","360 VA"],c:0,e:"Apparent power is the hypotenuse: S = square root of (180 squared + 240 squared) = square root of 90,000 = 300 VA."},
{id:"u2l7-2",t:"u2l7",q:"What is the approximate reactance of a 40 millihenry inductor at 60 Hz?",a:["24 ohms","15 ohms","2.4 ohms","150 ohms"],c:1,e:"XL = 2 x pi x f x L = 2 x 3.1416 x 60 x 0.040 = 15.1 ohms."},
{id:"u2l7-3",t:"u2l7",q:"Which of the following is an active circuit component?",a:["A capacitor","A thermistor","A transistor","An inductor"],c:2,e:"Active components need a power source and provide gain or control; a transistor amplifies. Capacitors, inductors, and thermistors are passive."},
{id:"u2l7-4",t:"u2l7",q:"Which battery characteristic most directly determines the weight of a battery needed for a given application?",a:["Voltage per cell","Internal resistance","Voltage discharge curve","Energy density"],c:3,e:"Energy density is energy per unit mass, so for a required amount of energy it sets how heavy the battery must be."},
{id:"u2l7-5",t:"u2l7",q:"A switching power supply delivers only its full input voltage to the output. What has most likely happened?",a:["The switching element has shorted","The switching element is stuck open","The output filter capacitor has opened","The battery is undercharged"],c:0,e:"A shorted switching element passes the full input through instead of a chopped fraction. An element stuck open would give zero output."},

// u3l6
{id:"u3l6-1",t:"u3l6",q:"Which of the following does NOT comply with NFPA 99 requirements for medical gas cylinder storage?",a:["Cylinders stored between minus 7 and 52 C","Wrapped cylinders placed in secure storage","A warning on the door of a room holding positive-pressure gases other than oxygen","Cylinders kept out of tightly enclosed spaces"],c:1,e:"Cylinders must be unwrapped before storage. Temperature limits, door warnings for other positive-pressure gases, and avoiding tight enclosures are all required."},
{id:"u3l6-2",t:"u3l6",q:"Which statement matches NFPA 99 electrical requirements for a general patient room?",a:["A minimum of two receptacles in the bathroom","A maximum of four tamper-resistant outlets","A minimum of eight non-locking receptacles","At least one isolated-ground receptacle in the patient care vicinity"],c:2,e:"Patient bed locations require at least eight non-locking receptacles, tamper-resistant in patient care spaces. Isolated-ground receptacles are prohibited in the vicinity, and bathrooms have no minimum."},
{id:"u3l6-3",t:"u3l6",q:"Which scenario violates NFPA 99?",a:["A detachable power cord with a locking mechanism on a portable monitor","A device in the patient care vicinity with 0.1 ohm between chassis and ground","A relocatable power tap loaded to 60 percent of its rating","Tinned loose ends of a stranded cable under a screw terminal"],c:3,e:"Tinned stranded ends under screw terminals are prohibited because the solder cold-flows and loosens. The other items are within the code's limits."},
{id:"u3l6-4",t:"u3l6",q:"An oxygen storage area is protected by compliant automatic sprinklers. What is the minimum separation required between the oxygen cylinders and stored flammable liquids?",a:["5 feet","20 feet","50 feet","No separation is required"],c:0,e:"Oxidizing gases must be at least 20 feet from flammables, reduced to 5 feet when the space has compliant sprinklers, or no separation inside a compliant gas cabinet."},
{id:"u3l6-5",t:"u3l6",q:"Under NFPA 99, how far may a data outlet be from its telecommunications room, and how many rooms must a floor have at minimum?",a:["100 meters; one per building","90 meters; one per floor","50 meters; two per floor","300 meters; one per floor"],c:1,e:"No data outlet may be more than 90 meters of cable from its telecommunications room, and each floor needs at least one room, each serving no more than 20,000 square feet."},

// u3l7
{id:"u3l7-1",t:"u3l7",q:"Which statement about workplace exposure limits is most accurate?",a:["Short-term exposure limits are averaged over a full shift","The CDC publishes the recommended exposure limits","Permissible exposure limits are the maximum legal exposure limits","Recommended exposure levels are the doses that kill half of test subjects"],c:2,e:"PELs are OSHA's legal maximums averaged over a shift. STELs are 15-minute ceilings, NIOSH publishes RELs, and LD50 is the lethal dose for half of subjects."},
{id:"u3l7-2",t:"u3l7",q:"Which is NOT a recognized GHS physical or health hazard pictogram?",a:["Flammable","Irritant","Corrosive","Reducer"],c:3,e:"GHS pictograms include flame, flame over circle (oxidizer), corrosion, exclamation mark (irritant), and others. There is no reducer pictogram; oxidizers are the hazard because they feed combustion."},
{id:"u3l7-3",t:"u3l7",q:"Which statement about blood-borne pathogen waste is FALSE?",a:["Waste with dried blood may be placed directly in regular trash without sealing","Contaminated broken glass may not be picked up by hand","Waste with liquid blood must be sealed and disposed of separately","The standard defines blood-borne pathogens as disease-causing microorganisms in human blood"],c:0,e:"Items with dried blood may go with regular trash only after being sealed in a plastic bag. Free-flowing blood is regulated waste for a licensed hauler."},
{id:"u3l7-4",t:"u3l7",q:"Which organization is the nonprofit accrediting body for clinical laboratories, inspecting every two years under CMS authority?",a:["The Joint Commission","College of American Pathologists","DNV","OSHA"],c:1,e:"CAP accredits medical and hospital laboratories with regular and unannounced inspections. The Joint Commission and DNV accredit healthcare organizations; OSHA protects workers."},
{id:"u3l7-5",t:"u3l7",q:"Which legislative act requires reporting of adverse events involving medical equipment?",a:["HITECH Act","HIPAA","Safe Medical Devices Act","DMCA"],c:2,e:"The SMDA extends FDA medical device reporting to user facilities: deaths to the FDA and manufacturer, serious injuries to the manufacturer, with annual summaries."},

// u4l7
{id:"u4l7-1",t:"u4l7",q:"A sphygmomanometer is reported to always read too high. What is the MOST appropriate way to check the device?",a:["Visually inspect the cuff and patch any leak","Ask staff to test it on another patient","Recalibrate the manometer and return it to service","Test it on a noninvasive blood pressure simulator"],c:3,e:"A simulator gives a controlled diagnosis without a patient. A leak would lower readings, not raise them, so patching is the wrong direction, and recalibrating before diagnosing skips the cause."},
{id:"u4l7-2",t:"u4l7",q:"Which ECG appearance indicates ventricular tachycardia?",a:["Wide QRS complexes at a rapid rate","Rapid irregular P waves","Rapid, consistent narrow waves","Extreme chaotic waves with no complexes"],c:0,e:"Ventricular tachycardia produces rapid, wide QRS complexes. Rapid consistent narrow waves are atrial tachycardia, quivering irregular atrial activity is atrial fibrillation, and chaos with no complexes is ventricular fibrillation."},
{id:"u4l7-3",t:"u4l7",q:"Which standard ECG lead provides a view of the inferior wall of the heart?",a:["V1","aVF","Lead I","aVR"],c:1,e:"aVF's positive pole is the left leg, below the heart, so it views the inferior wall. V1 views horizontally, aVR from the right arm, and lead I across the shoulders."},
{id:"u4l7-4",t:"u4l7",q:"Which set of parameters is measured by a ventilator analyzer?",a:["Carbon dioxide concentration, oxygen concentration, gas pressure, inspiratory time","Gas flow, carbon dioxide concentration, gas pressure, breath detection threshold","Gas flow, oxygen concentration, gas pressure, breath detection threshold","Gas flow, carbon dioxide concentration, oxygen concentration, inspiratory time"],c:2,e:"Ventilator analyzers measure flow, pressure, volumes, oxygen concentration, and breath detection thresholds. They do not measure carbon dioxide concentration; that is capnography."},
{id:"u4l7-5",t:"u4l7",q:"What does the continuity mode of a digital multimeter measure?",a:["Peak voltage across a component","The frequency of a signal","Total current between two points","Total resistance between two points in an unpowered circuit"],c:3,e:"Continuity mode passes a small current through an unpowered circuit and measures resistance, sounding a tone when it is low enough to indicate a connection."},

// u5l5
{id:"u5l5-1",t:"u5l5",q:"Which phenomenon allows an ultrasound transducer to convert mechanical pressure into an electrical charge?",a:["Piezoelectricity","The Doppler effect","Photoluminescence","The pyroelectric effect"],c:0,e:"Piezoelectric crystals produce charge when deformed and deform when charged, so one element both sends and receives. Doppler describes frequency shifts from motion, not the conversion."},
{id:"u5l5-2",t:"u5l5",q:"Blood moving toward a Doppler ultrasound transducer will produce which change in the reflected sound?",a:["A lower pitch","A higher pitch","No change in pitch","An increase in volume only"],c:1,e:"Motion toward the transducer compresses the reflected waves, raising their frequency, which is heard as a higher pitch."},
{id:"u5l5-3",t:"u5l5",q:"Which imaging technique produces live moving images of internal tissues using continuous X-rays and an image intensifier?",a:["Radiography","Computed tomography","Fluoroscopy","Magnetic resonance imaging"],c:2,e:"Fluoroscopy uses a continuous or pulsed X-ray beam and an image intensifier or flat panel to show real-time motion, such as contrast flowing through vessels."},
{id:"u5l5-4",t:"u5l5",q:"By which method does an MRI scanner form an image?",a:["Rotating X-ray slices reconstructed by computer","Injecting a positron-emitting tracer","Occlusion of electromagnetic fields by dense tissue","Detecting the release of energy as magnetically aligned atoms realign"],c:3,e:"MRI aligns atomic spins in a strong magnet, disturbs them with radio pulses, and detects the signals emitted as they realign. Rotating X-rays describe CT and tracers describe PET."},
{id:"u5l5-5",t:"u5l5",q:"Which type of radiation is detected in positron emission tomography?",a:["Gamma","Beta","Alpha","Delta"],c:0,e:"When a positron from the tracer meets an electron, both annihilate into two gamma photons traveling in opposite directions, which the detector ring times and locates."},

// u5l6
{id:"u5l6-1",t:"u5l6",q:"What structure is examined with an ophthalmoscope?",a:["The tympanic membrane","The fundus of the eye","The palatine tonsils","The nasal sinuses"],c:1,e:"An ophthalmoscope views the interior of the eye, the fundus, including the retina and optic disc. The tympanic membrane is viewed with an otoscope."},
{id:"u5l6-2",t:"u5l6",q:"Which of the following is NOT measured by an audiometer?",a:["Sensorineural hearing","Hearing threshold","Sound frequencies","Conductive hearing"],c:2,e:"An audiometer generates tones at set frequencies and measures the threshold at which they are heard, distinguishing sensorineural from conductive loss. It does not measure frequencies."},
{id:"u5l6-3",t:"u5l6",q:"A handheld tympanic thermometer consistently gives low readings across several attempts with fresh probe covers. What is the MOST probable cause?",a:["Low battery power","A disconnected infrared sensor","A torn probe cover","A cracked lens"],c:3,e:"A cracked lens focuses less infrared onto the thermopile, lowering readings. A disconnected sensor or dead battery would give no reading, and fresh covers rule out a torn cover."},
{id:"u5l6-4",t:"u5l6",q:"Which electrode system measures the partial pressure of carbon dioxide in a blood gas analyzer?",a:["Severinghaus electrode","Glass pH electrode alone","Clark electrode","Mercury electrode"],c:0,e:"The Severinghaus electrode places a glass pH electrode behind a CO2-permeable membrane in bicarbonate; CO2 changes the pH, which is read as voltage. The Clark electrode measures oxygen."},
{id:"u5l6-5",t:"u5l6",q:"A laboratory spectrophotometer works intermittently at every wavelength. What is the MOST likely cause?",a:["A disconnected photosensor","A faulty power cable","An aging deuterium lamp","A failed wavelength motor"],c:1,e:"Intermittent failure across all wavelengths points to the power cable. A disconnected sensor would read nothing, an old deuterium lamp would fail only in the ultraviolet, and a dead motor could not change wavelengths."},

// u5l7
{id:"u5l7-1",t:"u5l7",q:"An enteral feeding pump gives a constant low-flow error. Which of the following would NOT cause this alert?",a:["Kinked tubing upstream of the pump","Feeding solution coating the drip chamber walls","Excessive ambient light at the feeding set detector","A dislodged drip chamber"],c:2,e:"Bright light on the detector causes a 'no set detected' error, not low flow. A coated or dislodged drip chamber and kinked tubing all trigger low-flow alarms."},
{id:"u5l7-2",t:"u5l7",q:"Which infusion device most commonly uses a peristaltic mechanism?",a:["Syringe pump","Pressure infuser","PCA pump","Enteral feeding pump"],c:3,e:"Enteral pumps use rotary peristaltic heads to push viscous formula through wide tubing. Syringe and PCA pumps depress plungers, and pressure infusers squeeze a bag."},
{id:"u5l7-3",t:"u5l7",q:"A PCA pump delivers its baseline infusion but does not provide doses when the patient presses the pendant. What should be checked FIRST?",a:["The pump settings","The patient pendant","The motor","The power cable"],c:0,e:"If the lockout interval or the maximum dose has been reached, requests are correctly refused. Settings are checked before the pendant or motor; a motor fault would also affect the basal rate."},
{id:"u5l7-4",t:"u5l7",q:"Which describes normal operation of a sequential compression device?",a:["All cuffs inflate and deflate simultaneously, then rest","Cuffs inflate in series from the distal to the proximal end, then deflate for a rest period","Cuffs inflate in series from the proximal to the distal end, then deflate for a rest period","Each cuff inflates and deflates alone in turn without a rest period"],c:1,e:"Inflating from the ankle toward the thigh pushes venous blood back toward the heart, imitating walking. Reversed order would push blood toward the foot."},
{id:"u5l7-5",t:"u5l7",q:"Which action would NOT increase the effectiveness of bilirubin phototherapy?",a:["Replacing a dim bulb with a brighter one","Moving the light source closer to the skin","Replacing an old bulb with one emitting 630 to 720 nm","Exposing more skin directly to the light"],c:2,e:"Bilirubin absorbs light from roughly 360 to 520 nm, most effectively in the blue-green region. A red or infrared bulb at 630 to 720 nm does nothing; brighter, closer, and more exposure all help."},

// u6l5
{id:"u6l5-1",t:"u6l5",q:"Which component of a hemodialysis circuit is located after the dialyzer, just before blood returns to the patient?",a:["Blood pump","Heparin pump","Dialyzer pressure monitor","Air trap and detector"],c:3,e:"The air trap and detector are the last components before the return, stopping the pump if bubbles are found. The blood pump comes first and the heparin pump precedes the dialyzer."},
{id:"u6l5-2",t:"u6l5",q:"Which of the following is NOT a component of external epicardial pacing?",a:["Subclavian leads","Output and rate adjustment","An AC power supply option","Electrodes with conductive gel"],c:0,e:"Epicardial pacing uses wires on the heart's surface brought out through the chest. Subclavian venous leads belong to transvenous pacing."},
{id:"u6l5-3",t:"u6l5",q:"In an anesthesia machine, which section is the first one downstream of the flow control for the anesthetic agent?",a:["Common gas outlet","Vaporizer","Ventilator","Gas supply"],c:1,e:"Gas passes the flow controls and then the vaporizer, which adds agent, before the streams rejoin at the common gas outlet and continue to the circuit and ventilator."},
{id:"u6l5-4",t:"u6l5",q:"Which laser type produces a wavelength appropriate for skin surface procedures because it is strongly absorbed by water?",a:["Excimer","Nd:YAG","Carbon dioxide","Argon"],c:2,e:"CO2 lasers emit far-infrared light absorbed by water, giving shallow penetration ideal for soft tissue and skin. Nd:YAG penetrates deeper, argon targets pigment, and excimer emits ultraviolet."},
{id:"u6l5-5",t:"u6l5",q:"A tabletop autoclave is reported to produce no steam. Which set of problems is most likely responsible?",a:["Defective water pump, low water pressure, leaky steam valve, burnt-out heater","Low water pressure, leaky steam valve, tripped breaker, burnt-out heater","Defective water pump, leaky steam valve, tripped breaker, burnt-out heater","Defective water pump, low water pressure, tripped breaker, burnt-out heater"],c:3,e:"Steam production fails when water cannot reach the heater or the heater cannot run: a bad pump, low pressure, a tripped breaker, or a burned-out element. A leaky steam valve affects pressure control, not production."},

// u7l6
{id:"u7l6-1",t:"u7l6",q:"An infusion pump switched to backup battery power while plugged in and no longer runs on AC. What should be checked FIRST?",a:["The power cable and outlet","The voltage regulator output","The internal power board","The battery charging circuit"],c:0,e:"Power cables are abused and fail often. Check the cable's continuity and the outlet before opening the pump to examine its internal power circuit."},
{id:"u7l6-2",t:"u7l6",q:"Which of the following is NOT a factor in the criticality of a medical device?",a:["The risk of harm if the device fails","The time required to perform maintenance","The frequency of preventive maintenance","The device's necessity to the organization"],c:1,e:"Criticality combines importance to the mission, likelihood of failure or maintenance demand, and potential harm. Repair or maintenance time is not part of the score."},
{id:"u7l6-3",t:"u7l6",q:"Which phrase best describes root cause analysis?",a:["A method of finding the most cost-efficient solution to a problem","A set of methods to improve quality and reduce error rates","A series of iterative questions to determine the underlying cause of failure and develop a solution from it","An interrogative process to find where in the task chain a failure occurred"],c:2,e:"Root cause analysis keeps asking why until it reaches the underlying cause, then directs the solution at that cause to prevent recurrence. It is not a cost exercise."},
{id:"u7l6-4",t:"u7l6",q:"Which situation is most likely a device or system error rather than a use error?",a:["A medication overdose from a misconfigured infusion pump","Noisy ECG readings near high-powered electrical equipment","Blurry images from a newly inspected handheld ultrasound","A nurse station not receiving data from vital signs monitors"],c:3,e:"Missing data across the network is a network or hardware failure. Misconfiguration is use error, blurry images from a good unit usually mean too little gel, and ECG noise near heavy equipment is an environmental use issue."},
{id:"u7l6-5",t:"u7l6",q:"Which tool would NOT help differentiate a local connectivity problem from a network-wide one for patient monitors?",a:["An electrical safety analyzer","A cable tester or tracer","The ping utility","A digital multimeter"],c:0,e:"Safety analyzers measure leakage and ground resistance, which are electrical safety matters, not connectivity. Ping, cable testers, and a multimeter's continuity check all test the connection."},

// u8l6
{id:"u8l6-1",t:"u8l6",q:"A capnography monitor powers on but displays no EtCO2 value; the filter and moisture trap are new. Which fault and test correspond?",a:["A clogged filter; check the nasal cannula and tubing","An internal leak; occlude the port upstream of the moisture trap","An air leak; occlude the port downstream of the filter","An absent filter; remove and reconnect the moisture trap"],c:1,e:"With new consumables, an internal leak is the remaining fault, tested by occluding the port upstream of the filter and moisture trap to see whether the device holds."},
{id:"u8l6-2",t:"u8l6",q:"A vital signs monitor shows no respiration rate, but ECG, SpO2, and other functions work normally. What is the likely cause?",a:["A faulty SpO2 probe","A disconnected monitor","A faulty input printed circuit board","Bad electrode leads"],c:2,e:"Bad leads or a disconnected monitor would also disrupt the ECG, and the SpO2 probe is unrelated to respiration. A fault on the input board's respiration channel leaves the other functions intact."},
{id:"u8l6-3",t:"u8l6",q:"A histology cryostat consistently produces squashed sections despite a new blade and correct set temperatures. Which is NOT a probable cause?",a:["There are cracks in the sectioning chamber","The thermistor is faulty","The refrigeration works intermittently","The cutting speed is too slow"],c:3,e:"Slow cutting does not compress sections. A faulty thermistor, intermittent refrigeration, or chamber cracks all let the block warm, which squashes sections."},
{id:"u8l6-4",t:"u8l6",q:"An electrosurgical generator turns on and appears to work but delivers no output. What is the MOST likely cause?",a:["A blown high-voltage power supply fuse","A loose display connector","A blown low-voltage power supply fuse","A faulty power switch"],c:0,e:"The high-voltage supply drives the RF output. A blown low-voltage fuse or bad power switch would keep the unit from turning on, and a display connector fault would only blank the display."},
{id:"u8l6-5",t:"u8l6",q:"An aspirator's suction has weakened gradually over time. Which of the following is NOT a probable cause?",a:["Loose tubing","A blown fuse","A cracked collection chamber","A clogged hydrophobic filter"],c:1,e:"A blown fuse stops the pump entirely rather than weakening suction gradually. Leaks and a progressively clogging filter reduce vacuum over time."},

// u9l7
{id:"u9l7-1",t:"u9l7",q:"Which statement about the HITECH Act is FALSE?",a:["It penalizes providers who do not implement electronic health records","It incentivizes adoption of certified electronic health records","It sets guidelines for hospital spending on electronic health records","It defines requirements for meaningful use of electronic health records"],c:2,e:"HITECH pays incentives, imposes penalties, and defines meaningful use, but it does not set spending guidelines beyond its adoption requirements."},
{id:"u9l7-2",t:"u9l7",q:"Which title of HIPAA contains the privacy and security rules and determines fines for violations?",a:["Title I","Title V","Title III","Title II"],c:3,e:"Title II's Administrative Simplification provisions hold the privacy and security rules and the fraud and abuse controls. Title I covers insurance portability."},
{id:"u9l7-3",t:"u9l7",q:"Which of the following is included in the FDA definition of a Medical Device Data System?",a:["A vital signs monitor in a patient room","A television showing news in a clinic lobby","A power cable to the nurses' station computers","A tracking board in a surgical waiting room"],c:0,e:"An MDDS stores, transfers, reformats, or displays medical device data. Only the vital signs monitor handles medical data; the others do not."},
{id:"u9l7-4",t:"u9l7",q:"Which statement about IEC 80001 is true?",a:["It was published by the FDA","It applies to any medical organization that connects medical devices across its network","It sets acceptable risk levels for IT networks with medical devices","It defines medical devices to include drugs and implants used in patient care"],c:1,e:"IEC 80001-1 was published by IEC and ISO, excludes drugs from its device definition, and leaves acceptable risk levels to each jurisdiction, but applies to any network incorporating medical devices."},
{id:"u9l7-5",t:"u9l7",q:"Which item is NOT a consideration in the Manufacturer Disclosure Statement for Medical Device Security (MDS2)?",a:["User authorization and authentication","The presence of an emergency access (break-glass) feature","Structural integrity of the device","Plans for third-party components"],c:2,e:"The MDS2 catalogs security features such as emergency access, authentication, updates, backups, and third-party component plans. Physical structural integrity is not a security item."},

// u9l8
{id:"u9l8-1",t:"u9l8",q:"Which of the following is NOT a layer of the OSI network model?",a:["Physical layer","Session layer","Application layer","Conversion layer"],c:3,e:"The seven layers are physical, data link, network, transport, session, presentation, and application. Data conversion is a function of the presentation layer."},
{id:"u9l8-2",t:"u9l8",q:"Which binary subnet mask corresponds to 255.255.255.240?",a:["11111111.11111111.11111111.11110000","11111111.11111111.11111111.00110101","11111111.11111111.11111111.11111100","11111111.11111111.11111111.11111000"],c:0,e:"240 in binary is 11110000. A mask must be contiguous ones followed by zeros, so 00110101 is invalid; 11111100 is 252 and 11111000 is 248."},
{id:"u9l8-3",t:"u9l8",q:"Which statement describes the function of the ping utility?",a:["It tests the current and resistance of a physical connection","It sends data to check the time to send and receive a message","It echoes back all information received from another device","It is the function ultrasound transducers use to send and receive signals"],c:1,e:"Ping sends ICMP echo requests and reports whether replies return, the round-trip time, and packet loss. It does not test cable electrical properties or echo everything received."},
{id:"u9l8-4",t:"u9l8",q:"Which action would NOT effectively test the connection between two computers on a wired network?",a:["Pinging one computer's local address from the other","Using an Ethernet cable tester","Power cycling one device at a time","Checking end-to-end cable resistance with a multimeter"],c:2,e:"Power cycling may clear a fault but does not identify whether a working connection exists. Ping, a cable tester, and a resistance check each verify the link."},
{id:"u9l8-5",t:"u9l8",q:"Which statement about a picture archiving and communication system (PACS) is true?",a:["PACS generates medical data from test equipment","PACS primarily transfers patient health insurance information","PACS tracks and manages laboratory sample data","PACS stores and transports imaging data on medical networks"],c:3,e:"PACS stores, transports, and displays medical images with patient data attached, interfacing with RIS and LIS. Sample tracking is the laboratory information system's job."}
);
