// APlus Academy Core 2 question bank, units 1 to 3. All questions are original.
// Fields: id, t (lesson id), q (stem), a (four options), c (index of correct option), e (explanation).
window.FRA = window.FRA || {};
FRA.questions = FRA.questions || [];
FRA.questions.push(
// u1l1
{id:"u1l1-1",t:"u1l1",q:"A technician must format a 128 GB flash drive to carry 9 GB video files between a Windows PC and a Mac. Which filesystem should be used?",a:["NTFS","exFAT","FAT32","ext4"],c:1,e:"exFAT has no 4 GB file limit and is read and written by Windows, macOS, and Linux. FAT32 caps files at 4 GB, NTFS is read-only on macOS without extra software, and ext4 is Linux-only."},
{id:"u1l1-2",t:"u1l1",q:"Which filesystem is the default for the Windows system drive and supports per-file permissions and encryption?",a:["exFAT","ReFS","NTFS","APFS"],c:2,e:"NTFS provides permissions, EFS encryption, compression, and journaling. ReFS is for resilience on servers and workstations, APFS is Apple's filesystem, and exFAT has no permissions."},
{id:"u1l1-3",t:"u1l1",q:"A school wants inexpensive laptops that run web applications, store data in the cloud, and are managed from a central console. Which operating system fits?",a:["iPadOS","macOS","Windows Pro","Chrome OS"],c:3,e:"Chrome OS on Chromebooks is browser-centered, cloud-first, and managed through the Google Admin console, which suits schools. The others are heavier or tied to specific hardware."},
{id:"u1l1-4",t:"u1l1",q:"A company still runs an operating system version that no longer receives security updates from its vendor. What is this condition called?",a:["End-of-life","An update limitation","A feature update","A compatibility concern"],c:0,e:"End-of-life means the vendor has stopped supporting the version with patches. It is listed as a vulnerability in the security domain and the answer is upgrade, replace, or isolate."},
{id:"u1l1-5",t:"u1l1",q:"A user cannot install a 64-bit application on an older PC. What is the MOST likely reason?",a:["The PC uses the FAT32 filesystem","The PC runs a 32-bit operating system","The application requires Chrome OS","The PC has a TPM 2.0 chip"],c:1,e:"A 64-bit application requires a 64-bit operating system. A 64-bit OS can run 32-bit applications, but a 32-bit OS cannot run 64-bit ones."},

// u1l2
{id:"u1l2-1",t:"u1l2",q:"A new laptop shipped with Windows 11 Home cannot be joined to the company's Active Directory domain. What is the BEST solution?",a:["Reinstall Windows 11 Home","Enable the TPM in firmware","Upgrade the edition to Windows 11 Pro","Switch the PC to a workgroup"],c:2,e:"Home editions cannot join a domain. An edition upgrade to Pro (by entering a Pro key) is done in place and adds domain join, BitLocker, Remote Desktop hosting, and Group Policy Editor."},
{id:"u1l2-2",t:"u1l2",q:"Which Windows 10 edition supports the ReFS filesystem and up to four physical processors?",a:["Home","Pro","N version","Pro for Workstations"],c:3,e:"Pro for Workstations adds ReFS, persistent memory, up to four CPUs, and a 6 TB RAM limit for high-end workstations."},
{id:"u1l2-3",t:"u1l2",q:"A user wants coworkers to connect to their Windows PC with Remote Desktop, but the option to enable it is missing. What explains this?",a:["The PC runs Windows Home, which cannot host Remote Desktop","Remote Desktop requires a 64-bit processor","Remote Desktop is only available in N editions","The PC is joined to a domain"],c:0,e:"All editions include the Remote Desktop client, but only Pro and higher can act as a Remote Desktop host. Home users need an edition upgrade or a third-party remote tool."},
{id:"u1l2-4",t:"u1l2",q:"A technician needs to move a workstation from 32-bit Windows 10 to 64-bit Windows 11. Which installation type is required?",a:["In-place upgrade","Clean install","Repair installation","Edition upgrade by product key"],c:1,e:"There is no in-place path from a 32-bit to a 64-bit installation. The technician must back up data and perform a clean install of the 64-bit version."},
{id:"u1l2-5",t:"u1l2",q:"A PC fails the Windows 11 upgrade check even though it has a recent processor and 8 GB of RAM. Which two firmware-related requirements should the technician check?",a:["BitLocker and Group Policy","A 720p display and a Microsoft account","TPM 2.0 and UEFI with Secure Boot","ReFS and a second processor"],c:2,e:"Windows 11 requires TPM 2.0 and UEFI firmware capable of Secure Boot. On many machines these exist but are disabled in firmware settings."},

// u1l3
{id:"u1l3-1",t:"u1l3",q:"A technician must install Windows on 40 identical desktops in a new office as efficiently as possible. Which method is BEST?",a:["A clean install from a USB drive on each PC","Restoring each PC's recovery partition","A repair installation on each PC","Image deployment"],c:3,e:"Image deployment prepares one reference machine, captures its image, and copies it to many PCs, often over the network, producing identical systems quickly."},
{id:"u1l3-2",t:"u1l3",q:"A new laptop is shipped directly to a remote employee, who signs in on first boot and the device enrolls in management and configures itself without IT touching it. What is this called?",a:["Zero-touch deployment","Multiboot","Remote network installation","Recovery partition restore"],c:0,e:"Zero-touch deployment (for example, an Autopilot-style program) lets a device provision itself from the vendor's service on first boot with no technician involvement."},
{id:"u1l3-3",t:"u1l3",q:"During Windows setup on a new PC, no drives appear in the disk selection screen. What should the technician do?",a:["Convert the disk from GPT to MBR","Load third-party storage drivers from a USB drive","Switch the boot method to PXE","Run a repair installation"],c:1,e:"When setup cannot see the disk, the storage or RAID controller needs a driver the installer lacks. The Load driver option reads it from removable media."},
{id:"u1l3-4",t:"u1l3",q:"Which partition style is required to boot Windows on a UEFI system and supports disks larger than 2 TB?",a:["MBR","Dynamic","GPT","Extended"],c:2,e:"GPT (GUID partition table) is required for UEFI boot, allows up to 128 partitions, and has no 2 TB limit. MBR is the legacy BIOS scheme limited to four primary partitions and 2 TB."},
{id:"u1l3-5",t:"u1l3",q:"Before performing an in-place upgrade from Windows 10 to Windows 11 on an office PC, what should the technician do FIRST?",a:["Convert the disk to MBR","Format the drive","Disable Secure Boot","Back up the user's files and settings and verify application and hardware compatibility"],c:3,e:"Upgrade considerations begin with a backup of files and preferences and a check of application, driver, and hardware compatibility, so a failed or incompatible upgrade does not cost data or productivity."},

// u1l4
{id:"u1l4-1",t:"u1l4",q:"A video editing application lists a dedicated graphics card with 6 GB of VRAM as a requirement. The office PCs use integrated graphics. What is the correct conclusion?",a:["The PCs need a dedicated graphics card or replacement workstations","Updating the graphics driver will meet the requirement","Adding system RAM will satisfy the VRAM requirement","The application will run in compatibility mode"],c:0,e:"Integrated graphics borrows system RAM and does not provide dedicated VRAM. Meeting the requirement means installing a graphics card or using a workstation that has one."},
{id:"u1l4-2",t:"u1l4",q:"A vendor provides software as an ISO file. What is the first step to install it on a Windows PC?",a:["Burn the ISO to a DVD","Mount the ISO as a virtual drive and run the installer","Rename the ISO to .exe","Extract the ISO with a compression tool"],c:1,e:"Windows mounts an ISO as a virtual drive with a right-click; the installer inside then runs normally. Burning media is unnecessary."},
{id:"u1l4-3",t:"u1l4",q:"Before deploying a new application company-wide, a technician documents required training, expected downtime, and changes to daily workflows. Which impact category is this?",a:["Device","Network","Operation","Business"],c:2,e:"Operational impact covers how people work: training, downtime, workflows, and support. Device impact is machine resources, network impact is bandwidth and ports, and business impact is cost and compliance."},
{id:"u1l4-4",t:"u1l4",q:"A new employee's account exists in the cloud office suite, but the desktop applications report they are unlicensed. What should be checked FIRST?",a:["Whether the PC has a 64-bit OS","Whether the PC is on a metered connection","Whether the ISO was mounted correctly","Whether a license has been assigned to the user"],c:3,e:"Cloud suites assign licenses per user from a pool. Without an assigned or valid license, the apps and mailbox refuse to work even though the account exists."},
{id:"u1l4-5",t:"u1l4",q:"Users want to sign in to the cloud productivity suite with the same username and password they use on the office domain. Which feature provides this?",a:["Identity synchronization","Licensing assignment","Sync and folder settings","Image deployment"],c:0,e:"Identity synchronization copies directory accounts to the cloud tenant so one identity works both on-premises and in the cloud."},

// u2l1
{id:"u2l1-1",t:"u2l1",q:"A service failed to start overnight and a technician wants to know why. Which tool shows the error?",a:["Disk Management (diskmgmt.msc)","Event Viewer (eventvwr.msc)","Certificate Manager (certmgr.msc)","Task Scheduler (taskschd.msc)"],c:1,e:"Event Viewer's System log records service failures with the reason. Application errors are in the Application log and logon audits in the Security log."},
{id:"u2l1-2",t:"u2l1",q:"A technician installs a second hard drive, but it does not appear in File Explorer. Which tool should be used to make it usable?",a:["Device Manager","Performance Monitor","Disk Management","Task Manager"],c:2,e:"Disk Management initializes a new disk (MBR or GPT), creates a partition, formats it, and assigns a drive letter."},
{id:"u2l1-3",t:"u2l1",q:"After a driver update, a network adapter stopped working. Which tool lets the technician roll back to the previous driver?",a:["Group Policy Editor","Local Users and Groups","Resource Monitor","Device Manager"],c:3,e:"Device Manager (devmgmt.msc) shows the adapter, flags problems with a yellow triangle, and offers Roll Back Driver when a previous driver exists."},
{id:"u2l1-4",t:"u2l1",q:"A workstation boots slowly because many programs launch at sign-in. Which Task Manager tab is used to disable them?",a:["Startup","Performance","Processes","Services"],c:0,e:"The Startup tab lists programs that run at sign-in with their startup impact and allows each to be disabled. This function moved to Task Manager from msconfig."},
{id:"u2l1-5",t:"u2l1",q:"A technician needs to enforce a minimum password length on a standalone Windows Pro workstation that is not on a domain. Which tool is used?",a:["Certificate Manager (certmgr.msc)","Group Policy Editor (gpedit.msc)","Task Scheduler (taskschd.msc)","Disk Management (diskmgmt.msc)"],c:1,e:"The Local Group Policy Editor sets account policies such as password length and lockout on a single machine; in a domain, the same settings come from domain Group Policy Objects."},

// u2l2
{id:"u2l2-1",t:"u2l2",q:"A vendor requires proof that a PC boots in UEFI mode with Secure Boot enabled. Which utility shows this without rebooting?",a:["Disk Cleanup (cleanmgr)","System Configuration (msconfig)","System Information (msinfo32)","Registry Editor (regedit)"],c:2,e:"System Information's summary lists BIOS Mode (Legacy or UEFI) and Secure Boot State, along with hardware, drivers, and software inventory."},
{id:"u2l2-2",t:"u2l2",q:"A file cannot be deleted because Windows reports it is in use. Which tool identifies the process holding the file open?",a:["Disk Defragmenter (dfrgui)","Disk Cleanup (cleanmgr)","System Information (msinfo32)","Resource Monitor (resmon)"],c:3,e:"Resource Monitor's CPU tab can search associated handles for a file name and show which process has it open, so the process can be ended."},
{id:"u2l2-3",t:"u2l2",q:"A technician wants a PC to boot into safe mode on its next restart without pressing keys during startup. Which tool provides this option?",a:["System Configuration (msconfig)","Resource Monitor (resmon)","Registry Editor (regedit)","Disk Defragmenter (dfrgui)"],c:0,e:"System Configuration's Boot tab has a Safe boot option (Minimal, Alternate shell, or Network). Uncheck it afterward or the PC keeps booting to safe mode."},
{id:"u2l2-4",t:"u2l2",q:"After an upgrade to Windows 11, a laptop's small SSD is nearly full. Which action frees the most space?",a:["Run Disk Defragmenter on the SSD","Run Disk Cleanup and remove the previous Windows installation","Export the registry","Disable the paging file"],c:1,e:"Disk Cleanup's Clean up system files option removes the previous Windows installation (Windows.old), often 20 GB or more, along with update leftovers. Defragmenting an SSD frees nothing and adds wear."},
{id:"u2l2-5",t:"u2l2",q:"A support article instructs the technician to change a value under HKEY_LOCAL_MACHINE. What should be done before making the change?",a:["Defragment the drive","Disable all Microsoft services","Export the registry key or create a restore point","Run Disk Cleanup"],c:2,e:"A wrong registry edit can prevent Windows from booting. Exporting the key (or creating a restore point) provides a way back."},

// u2l3
{id:"u2l3-1",t:"u2l3",q:"Which command displays a Windows PC's MAC address and DNS servers?",a:["ping -a","hostname","netstat -n","ipconfig /all"],c:3,e:"ipconfig /all extends the basic output with the physical (MAC) address, DHCP server, lease times, and DNS servers for each adapter."},
{id:"u2l3-2",t:"u2l3",q:"A user reports an intermittent connection to a remote server. Which command shows packet loss at each hop over time?",a:["pathping","tracert","nslookup","net use"],c:0,e:"pathping performs a trace and then sends packets to every hop for several minutes, reporting loss per hop, which pinpoints a flaky link."},
{id:"u2l3-3",t:"u2l3",q:"A hard drive reports read errors. Which command scans for bad sectors and recovers readable information?",a:["format /q","chkdsk /r","diskpart clean","sfc /scannow"],c:1,e:"chkdsk /r locates bad sectors and recovers readable data, implying /f to fix filesystem errors. diskpart clean erases the partition table and format destroys data."},
{id:"u2l3-4",t:"u2l3",q:"A Group Policy change is not taking effect on a workstation. Which command applies policy immediately?",a:["gpresult /r","whoami /groups","gpupdate /force","net user"],c:2,e:"gpupdate /force refreshes and reapplies all Group Policy settings now. gpresult /r reports which policies have been applied."},
{id:"u2l3-5",t:"u2l3",q:"Windows reports that system files may be corrupted. Which command verifies and repairs protected system files?",a:["chkdsk /f","robocopy /mir","winver","sfc /scannow"],c:3,e:"The System File Checker (sfc /scannow) verifies protected system files and replaces corrupted copies. If it cannot repair them, DISM /online /cleanup-image /restorehealth repairs the source first."},

// u2l4
{id:"u2l4-1",t:"u2l4",q:"A legacy application cannot reach the internet because it uses the system proxy, which changed. Which Control Panel applet holds the proxy configuration?",a:["Internet Options","Network and Sharing Center","Programs and Features","Devices and Printers"],c:0,e:"Internet Options, Connections tab, LAN settings holds the system proxy used by many applications. Settings, Network and Internet, Proxy changes the same values."},
{id:"u2l4-2",t:"u2l4",q:"A scanner's software crashes after a recent Windows update. Where can the technician uninstall that specific update?",a:["System, Advanced system settings","Programs and Features, View installed updates","File Explorer Options","Indexing Options"],c:1,e:"Programs and Features lists installed updates and allows a problem update to be uninstalled; Settings, Windows Update, View update history offers the same."},
{id:"u2l4-3",t:"u2l4",q:"A user receives a file named invoice.pdf that is actually an executable, but the .exe extension was not visible. Which setting should be changed?",a:["Show hidden files, folders, and drives","Hide protected operating system files","Hide extensions for known file types (turn it off)","Launch folder windows in a separate process"],c:2,e:"With extensions hidden, invoice.pdf.exe displays as invoice.pdf. Turning off Hide extensions for known file types in File Explorer Options exposes the real extension."},
{id:"u2l4-4",t:"u2l4",q:"Which power state writes the contents of memory to disk and powers the computer off completely, so no work is lost if the battery dies?",a:["Sleep","Standby","Fast startup","Hibernate"],c:3,e:"Hibernate saves RAM to hiberfil.sys and powers off. Sleep and standby keep RAM powered and drain the battery; fast startup only hibernates the kernel session at shutdown."},
{id:"u2l4-5",t:"u2l4",q:"A USB audio interface disconnects whenever the PC has been idle for a while. Which power setting should be disabled?",a:["USB selective suspend","Fast startup","Hibernate","Choose what closing the lid does"],c:0,e:"USB selective suspend lets Windows power down idle USB devices. Disabling it in the advanced power settings keeps the device connected."},

// u2l5
{id:"u2l5-1",t:"u2l5",q:"A technician wants to stop programs from running automatically when a USB drive is inserted. Which Settings category contains this option?",a:["Apps","Devices","Privacy","Personalization"],c:1,e:"AutoPlay is under Settings, Devices. Turning it off prevents media from launching content automatically, which is also a security best practice."},
{id:"u2l5-2",t:"u2l5",q:"A user's laptop is tethered to a phone hotspot with a limited data plan. Which Settings option limits background downloads and updates on that connection?",a:["Airplane mode","Proxy","Metered connection","Data usage reset"],c:2,e:"Marking the connection as metered under Network and Internet tells Windows to limit background data, defer non-critical updates, and pause syncing."},
{id:"u2l5-3",t:"u2l5",q:"A user wants to sign in with a fingerprint instead of a password. Which Settings category is used?",a:["System, About","Ease of Access","Privacy","Accounts, Sign-in options"],c:3,e:"Sign-in options under Accounts configure PIN, Windows Hello face and fingerprint, security keys, and dynamic lock."},
{id:"u2l5-4",t:"u2l5",q:"A videoconferencing app cannot access the webcam, although the camera works in other apps. Where should the technician look?",a:["Settings, Privacy, Camera","Settings, Devices, Printers and scanners","Settings, Gaming","Settings, Time and Language"],c:0,e:"App permissions for the camera, microphone, and location are under Privacy. The specific app's toggle is likely off."},
{id:"u2l5-5",t:"u2l5",q:"Which Settings category contains Windows Update, Windows Security, Backup, and Recovery (Reset this PC)?",a:["System","Update and Security","Apps","Accounts"],c:1,e:"Update and Security groups Windows Update, Delivery Optimization, Windows Security, Backup, Troubleshoot, Recovery, and Activation. Windows 11 splits some into their own categories with the same contents."},

// u2l6
{id:"u2l6-1",t:"u2l6",q:"A workstation can reach every device on the local subnet but nothing on the internet. Which client setting is MOST likely wrong?",a:["The DNS server","The DHCP scope","The default gateway","The proxy exceptions"],c:2,e:"The default gateway is the router for all non-local traffic. If it is missing or on the wrong subnet, local devices work but everything beyond the router fails."},
{id:"u2l6-2",t:"u2l6",q:"Which command maps drive letter S to the share named data on server FS01 and reconnects it at every sign-in?",a:["net user S: \\\\FS01\\data /add","nslookup FS01 data","robocopy \\\\FS01\\data S: /mir","net use S: \\\\FS01\\data /persistent:yes"],c:3,e:"net use maps a drive letter to a UNC path; /persistent:yes makes the mapping survive reboots. The GUI equivalent is Map network drive with Reconnect at sign-in."},
{id:"u2l6-3",t:"u2l6",q:"Other computers on the office LAN cannot see or connect to a new PC, although the PC can browse the internet. What should be checked FIRST?",a:["Whether the PC's network profile is set to Public","Whether the PC has a static IP address","Whether IPv6 is disabled","Whether the proxy is set to automatic"],c:0,e:"The Public profile turns off network discovery and file sharing and applies the strictest firewall rules. Switching the network to Private allows the PC to be seen and reached on a trusted LAN."},
{id:"u2l6-4",t:"u2l6",q:"A small business PC needs to become a member of the company's Active Directory domain. Which two conditions must be met?",a:["The PC uses a static IP address and a public network profile","The PC runs Windows Pro or higher and its DNS points to a domain controller","The PC runs Windows Home and has BitLocker enabled","The PC has a metered connection and a mapped drive"],c:1,e:"Domain join requires an edition of Pro or above, and the PC must locate a domain controller through DNS. Addressing method and firewall profile do not decide eligibility."},
{id:"u2l6-5",t:"u2l6",q:"A remote employee's laptop connects to the company VPN, but internal servers can be reached only by IP address, not by name. What is the MOST likely cause?",a:["The firewall profile is set to Private","The laptop is using DHCP","The VPN connection is not using the internal DNS servers","The proxy is set to manual"],c:2,e:"Names resolving only outside the company indicate the VPN adapter is not handing out or using the internal DNS servers. Reaching servers by IP proves the tunnel itself works."},

// u3l1
{id:"u3l1-1",t:"u3l1",q:"A Mac user downloaded an application and, after opening the file, sees a window containing the application icon and a folder shortcut but nothing seems installed. Which file type is this and what should the user do?",a:["A .pkg; run the installer wizard","A .zip; extract it with Disk Utility","An .app; move it to the Trash","A .dmg; drag the application into the Applications folder and eject the image"],c:3,e:"A .dmg mounts as a virtual disk showing the app and an Applications shortcut. Dragging the app into Applications installs it; the image is then ejected."},
{id:"u3l1-2",t:"u3l1",q:"Where are a macOS user's personal preferences and application support files stored?",a:["/Users/name/Library","/Library","/System","/Applications"],c:0,e:"The user Library (~/Library, hidden by default) holds that user's preferences, caches, and application support. /Library is system-wide and /System is the protected OS."},
{id:"u3l1-3",t:"u3l1",q:"Which macOS feature provides full-disk encryption?",a:["Keychain","FileVault","Time Machine","Spotlight"],c:1,e:"FileVault encrypts the entire startup disk. Keychain stores passwords, Time Machine backs up, and Spotlight searches."},
{id:"u3l1-4",t:"u3l1",q:"An application on a Mac has stopped responding. Which key combination opens the tool to end it?",a:["Command-Space","Ctrl-Alt-Delete","Command-Option-Esc","Command-Tab"],c:2,e:"Command-Option-Esc opens Force Quit Applications. Command-Space opens Spotlight and Command-Tab switches apps."},
{id:"u3l1-5",t:"u3l1",q:"Which Apple mechanism delivers small urgent security fixes to macOS between full operating system updates?",a:["Time Machine","Continuity","Mission Control","Rapid Security Response"],c:3,e:"Rapid Security Response patches are lightweight security updates applied quickly without waiting for a full macOS release."},

// u3l2
{id:"u3l2-1",t:"u3l2",q:"A Linux script reports 'Permission denied' when run. Which command makes it executable?",a:["chmod +x script.sh","chown +x script.sh","mount script.sh","sudo grep script.sh"],c:0,e:"chmod changes permissions; +x adds execute for the owner (or all classes). chown changes ownership, not permissions."},
{id:"u3l2-2",t:"u3l2",q:"A technician needs to install a package on an Ubuntu workstation. Which command sequence is correct?",a:["sudo dnf install package","sudo apt update && sudo apt install package","su apt get package","fsck install package"],c:1,e:"Ubuntu and Debian use apt; updating the package index and then installing with sudo is the standard sequence. dnf is for Fedora and Red Hat."},
{id:"u3l2-3",t:"u3l2",q:"Which Linux file stores hashed user passwords and is readable only by root?",a:["/etc/passwd","/etc/hosts","/etc/shadow","/etc/fstab"],c:2,e:"/etc/shadow holds password hashes and aging information with root-only permissions; /etc/passwd lists accounts and is world-readable."},
{id:"u3l2-4",t:"u3l2",q:"A Linux server reports that a filesystem is full. Which command shows free space on each mounted filesystem?",a:["du -sh","top","ls -la","df -h"],c:3,e:"df -h reports free and used space per mounted filesystem. du -sh shows the space consumed by a specific directory, which is the next step to find the culprit."},
{id:"u3l2-5",t:"u3l2",q:"Which command shows the IP addresses assigned to a modern Linux system's interfaces?",a:["ip addr","ipconfig /all","dig","curl"],c:0,e:"The ip command replaced ifconfig; ip addr (or ip a) lists interfaces and addresses, and ip route shows the gateway. ipconfig is the Windows command."}
);
