// APlus Academy Core 2 question bank, units 6 to 9. All questions are original.
// Fields: id, t (lesson id), q (stem), a (four options), c (index of correct option), e (explanation).
window.FRA = window.FRA || {};
FRA.questions = FRA.questions || [];
FRA.questions.push(
// u6l1
{id:"u6l1-1",t:"u6l1",q:"A workstation began showing a blue screen with the same stop code right after a new graphics driver was installed. What should the technician do FIRST?",a:["Replace the RAM","Boot to safe mode and roll back the driver","Reinstall Windows","Run a full antivirus scan"],c:1,e:"A crash that follows a specific change points at that change. Safe mode loads minimal drivers so the machine starts, and rolling back the driver undoes the change. Reinstalling is far down the ladder."},
{id:"u6l1-2",t:"u6l1",q:"Every HTTPS site shows certificate errors on one PC, domain logins fail, and the clock shows a date from several years ago. What is the MOST likely cause?",a:["An expired root certificate at the domain controller","A rootkit","A failed CMOS battery causing time drift","A bad network cable"],c:2,e:"Time drift from a dead CMOS battery makes certificates appear not yet valid and breaks Kerberos, which tolerates only about five minutes of clock skew. Replace the battery, set the zone, and resync."},
{id:"u6l1-3",t:"u6l1",q:"A user's sign-in takes eight minutes, but other users on the same computer sign in within seconds. Which symptom and cause does this describe?",a:["Boot issue caused by a corrupted boot record","Time drift caused by a wrong time zone","No OS found caused by the boot order","Slow profile load caused by an oversized or corrupted user profile"],c:3,e:"Because other users are fine, the machine and network are eliminated and the problem is that user's profile: too large, roaming over a slow link, or corrupted. Trim it or rebuild it."},
{id:"u6l1-4",t:"u6l1",q:"After a docking station with several devices was attached, Windows reports that the controller does not have enough resources. What is the appropriate fix?",a:["Move some devices to a different USB controller or use a powered hub","Increase the page file size","Run chkdsk /r","Disable Secure Boot"],c:0,e:"USB controller resource warnings mean too many device endpoints share one controller. Spreading devices across controllers, using a powered hub, or updating chipset drivers resolves it."},
{id:"u6l1-5",t:"u6l1",q:"A desktop powers off by itself under heavy load, and the case is hot to the touch. Which cause should be investigated FIRST?",a:["A corrupted user profile","Overheating from a clogged heatsink or failed fan","Malware blocking Windows Update","An expired software license"],c:1,e:"Frequent shutdowns under load with a hot case indicate thermal protection shutting the system down. Clean the heatsink, check the fans, and replace the thermal paste."},

// u6l2
{id:"u6l2-1",t:"u6l2",q:"The command sfc /scannow reports that it found corrupt files but was unable to fix some of them. What should the technician run NEXT?",a:["chkdsk /f","Reset this PC","DISM /Online /Cleanup-Image /RestoreHealth, then sfc again","format C:"],c:2,e:"When sfc cannot repair, the component store it draws from is damaged. DISM with RestoreHealth repairs that store, after which sfc can complete."},
{id:"u6l2-2",t:"u6l2",q:"Which recovery option returns system files, drivers, and registry settings to an earlier point without removing the user's documents?",a:["Reset this PC with remove everything","Clean install","Low-level format","System Restore"],c:3,e:"System Restore rolls back system state to a restore point while leaving personal files in place. Reset and clean install are more destructive."},
{id:"u6l2-3",t:"u6l2",q:"A PC will not boot into Windows. How can the technician reach the Windows Recovery Environment without installation media?",a:["Interrupt the boot three times so Automatic Repair opens the advanced options","Press F8 during POST","Hold the Windows key at power-on","Remove the CMOS battery"],c:0,e:"After three consecutive failed boots, Windows opens Automatic Repair with the advanced options, which include Startup Repair, System Restore, Uninstall Updates, and Command Prompt. Installation media is the alternative."},
{id:"u6l2-4",t:"u6l2",q:"A single user's Start menu and taskbar are broken, but a test account on the same PC works normally. Which repair is MOST appropriate?",a:["Reimage the computer","Rebuild the user's profile","Replace the hard drive","Roll back the BIOS"],c:1,e:"A problem confined to one user on a working machine is a profile problem. Create a fresh profile and migrate the user's data rather than rebuilding the whole system."},
{id:"u6l2-5",t:"u6l2",q:"Windows starts normally in safe mode but freezes during a normal boot. What does this indicate?",a:["The hard drive has failed","The RAM is faulty","A third-party driver, service, or startup program is the cause","The processor is overheating"],c:2,e:"Safe mode loads only core drivers and services. Stability in safe mode with instability in normal mode points at third-party software; a clean boot narrows it down."},

// u6l3
{id:"u6l3-1",t:"u6l3",q:"A window appears stating that the PC has 37 infections and provides a phone number for immediate support. The organization does not use that product. What is this?",a:["A legitimate Windows Defender alert","A Windows Update prompt","A firewall notification","A rogue antivirus showing false alerts"],c:3,e:"False alerts from a product that was never installed are scareware. Do not call or pay; run the real, updated antimalware from a clean boot and remove the program and extensions."},
{id:"u6l3-2",t:"u6l3",q:"A user's documents now end in an unfamiliar extension, and a text file demanding payment appears in each folder. What should the technician do FIRST?",a:["Disconnect the system from the network","Restore the files from backup immediately","Pay the ransom to recover the files","Run Disk Cleanup"],c:0,e:"This is ransomware. Quarantine the machine first so it cannot encrypt shares or spread, then follow the malware removal procedure and restore from clean backups. Never pay."},
{id:"u6l3-3",t:"u6l3",q:"Searches typed into the browser land on an unrelated shopping site, and the proxy settings contain an address nobody configured. Which symptom is this?",a:["Certificate warning","Redirection caused by a hijacked proxy or extension","Low memory warning","Time drift"],c:1,e:"Redirection comes from a changed search engine, a malicious extension, a rogue proxy, altered DNS, or a poisoned hosts file. Clear the proxy, remove the extension, reset the browser, and scan."},
{id:"u6l3-4",t:"u6l3",q:"Certificate warnings appear on every HTTPS site on one workstation, and the warning shows an issuer nobody recognizes. What is the MOST likely explanation after ruling out the clock?",a:["Every website's certificate expired at once","The browser cache is full","Something on the PC or in the path is intercepting HTTPS with its own root certificate","The user has a slow connection"],c:2,e:"Warnings on all sites indicate a local cause. With the clock correct, an unfamiliar issuer means interception: a filtering proxy whose root is not trusted, or malware that installed its own root certificate."},
{id:"u6l3-5",t:"u6l3",q:"Several PCs cannot install Windows updates, and on each the antivirus has been disabled by an unknown process. How should this be treated?",a:["As an isolated Windows Update bug","As a hardware failure","As a licensing problem","As a security incident requiring the malware removal procedure"],c:3,e:"OS update failures combined with disabled protection are a security symptom; malware often blocks updates to keep its entry point open. Isolate and remediate the machines rather than just fixing updates."},

// u6l4
{id:"u6l4-1",t:"u6l4",q:"A phone's operating system update fails repeatedly. The phone is at 25 percent battery on cellular data with almost no free storage. What should the user do?",a:["Charge the phone, connect to Wi-Fi, and free up storage","Factory reset the phone","Enable developer mode","Replace the SIM card"],c:0,e:"OS updates need sufficient storage, a charged battery (usually 50 percent or a charger), and typically Wi-Fi. Meeting those prerequisites resolves most update failures."},
{id:"u6l4-2",t:"u6l4",q:"A mobile application freezes and will not close. What is the FIRST step?",a:["Reinstall the operating system","Force-close the application and reopen it","Reset network settings","Remove the battery"],c:1,e:"The mobile fix ladder starts with force-closing and reopening the app, then restarting the device, then updating, clearing cache, reinstalling, and only later resetting."},
{id:"u6l4-3",t:"u6l4",q:"A user reports the screen no longer rotates when the phone is turned sideways. What should be checked FIRST?",a:["The Bluetooth pairing list","The battery health","The rotation lock setting in quick settings","The data-usage limit"],c:2,e:"Rotation lock is the most common cause and takes seconds to check. Next, confirm the app supports rotation; a sensor failure is the last theory."},
{id:"u6l4-4",t:"u6l4",q:"A phone's battery drains by early afternoon. Where should the technician look FIRST to identify the cause?",a:["The store account settings","The Wi-Fi network list","The list of paired Bluetooth devices","The battery usage screen showing consumption per app"],c:3,e:"Battery settings show which apps and features consumed the most since the last charge. The top consumer, whether the screen, background refresh, location, or an unknown app, directs the fix."},
{id:"u6l4-5",t:"u6l4",q:"A phone will not connect to a car's hands-free system that worked last week. What is the recommended fix?",a:["Forget the pairing on both devices and pair again","Enable NFC","Factory reset the phone","Disable Wi-Fi"],c:0,e:"Stale or mismatched Bluetooth pairings are resolved by forgetting the device on both sides and re-pairing, after toggling Bluetooth and checking for updates."},

// u6l5
{id:"u6l5-1",t:"u6l5",q:"After installing a game from a website link, a user's phone consumes gigabytes of data daily and runs slowly. What is the MOST likely cause?",a:["A failing battery","A malicious application from an unofficial source","An OS update in progress","Rotation lock"],c:1,e:"Sideloaded apps skip store review and are the main source of mobile malware. High network traffic and degraded response after such an install indicate exfiltration, mining, or ad fraud."},
{id:"u6l5-2",t:"u6l5",q:"A corporate phone is flagged as non-compliant and can no longer receive company email. Which of the following is a likely reason?",a:["The phone has too many photos","The screen brightness is too high","The device has been rooted or jailbroken","The user changed the wallpaper"],c:2,e:"Root access and jailbreaking break the OS security model and block updates, so MDM compliance rules detect them and cut off corporate resources until the device is reset and re-enrolled."},
{id:"u6l5-3",t:"u6l5",q:"Full-screen ads appear on a phone even when no browser is open. Which app permission most likely enables this?",a:["Location","Camera","Contacts","Draw over other apps (overlay)"],c:3,e:"Overlay permission lets an app draw on top of everything, which adware uses for ads and malware uses for fake login screens. Find the recently installed app that holds it and remove it."},
{id:"u6l5-4",t:"u6l5",q:"A user tapped a text message link and installed what looked like their bank's app, which then asked for their PIN twice and their account was drained. What happened?",a:["Application spoofing delivered by smishing","A Bluetooth pairing attack","A screen autorotation failure","A data-usage limit notification"],c:0,e:"A look-alike app imitating a real one to steal credentials is application spoofing; the text message was the smishing delivery. Uninstall, contact the bank, change credentials, and report."},
{id:"u6l5-5",t:"u6l5",q:"Malware on an Android phone resists uninstallation. What must the technician do before the app can be removed?",a:["Enable developer mode","Revoke the app's device administrator permission","Turn off Wi-Fi","Clear the browser cache"],c:1,e:"Apps with device administrator rights cannot be uninstalled until that permission is revoked in security settings. If it still resists, safe mode or a factory reset is next."},

// u6l6
{id:"u6l6-1",t:"u6l6",q:"A user reports an application crashes every afternoon. According to the troubleshooting method, what should the technician do FIRST?",a:["Reinstall the application","Replace the workstation","Question the user, note what changed, and gather information","Escalate to tier 3"],c:2,e:"Identifying the problem comes first: symptoms, timeline, changes, and a backup. The afternoon pattern is itself a clue that points toward heat or load."},
{id:"u6l6-2",t:"u6l6",q:"A scenario states that other users on the same PC are unaffected by a problem one user reports. What does this detail allow the technician to conclude?",a:["The hardware must be replaced","The domain controller is down","The network switch is faulty","Shared components such as the machine and network are unlikely causes; the user's profile or settings are"],c:3,e:"When others on the same machine are fine, the machine, network, and domain are eliminated in one step, and the theory shifts to that user's profile, permissions, or settings."},
{id:"u6l6-3",t:"u6l6",q:"The technician has confirmed a theory of probable cause. What is the NEXT step in the troubleshooting method?",a:["Establish a plan of action and implement the solution","Document findings","Question the user again","Verify full system functionality"],c:0,e:"After the theory is confirmed, the technician plans the fix, including risks and rollback, and implements it or escalates. Verification and documentation follow."},
{id:"u6l6-4",t:"u6l6",q:"During a ransomware incident on a shared drive, which action comes BEFORE restoring files from backup?",a:["Paying the ransom","Containing the incident by disconnecting the encrypting machine and following the incident response policy","Wiping the source machine","Emailing all users a warning"],c:1,e:"Restoring while the encrypting machine is still connected re-encrypts the restored files. Containment, evidence preservation, and notification come first, then recovery from clean backups."},
{id:"u6l6-5",t:"u6l6",q:"After applying a fix, what completes the troubleshooting process?",a:["Closing the ticket immediately","Reinstalling the operating system as a precaution","Verifying full functionality with the user, implementing preventive measures, and documenting the outcome","Escalating to a vendor"],c:2,e:"The method ends with verification, prevention, and documentation, including a knowledge base article and, for security incidents, an incident report."},

// u7l1
{id:"u7l1-1",t:"u7l1",q:"A ticket reads only 'computer broken.' Which ticketing best practice is missing?",a:["An escalation level","A service-level agreement","An asset tag","A clear, concise issue description with facts"],c:3,e:"The issue description should state what happened, when, error text, what changed, and who is affected. Without facts, nobody can begin troubleshooting."},
{id:"u7l1-2",t:"u7l1",q:"Two technicians tried the same failed fix an hour apart on one ticket. Which part of the ticket was neglected?",a:["Progress notes","Device information","Category","User information"],c:0,e:"Progress notes record what was tried, the result, and the time, so the next person does not repeat work. They are one of the three places clear written communication is required."},
{id:"u7l1-3",t:"u7l1",q:"Which system records assets and how they relate to users, software, network devices, and support contracts, so the impact of a change can be assessed?",a:["Knowledge base","Configuration management database (CMDB)","Ticketing system","Service-level agreement"],c:1,e:"The CMDB holds configuration items and their relationships. It answers which systems depend on a switch being replaced or which user has which laptop."},
{id:"u7l1-4",t:"u7l1",q:"A former contractor's VPN account still works two months after leaving. Which document would have prevented this?",a:["Software package custom installation procedure","Network topology diagram","User off-boarding checklist","Incident report"],c:2,e:"The off-boarding checklist ensures accounts are disabled, access and tokens revoked, devices collected, and data transferred on the departure date."},
{id:"u7l1-5",t:"u7l1",q:"An internet provider promised a four-hour response for outages but took two days. Which document defines that obligation?",a:["An acceptable use policy","A new-user setup checklist","A standard operating procedure","An external service-level agreement"],c:3,e:"SLAs define response and resolution targets. An external or third-party SLA governs vendors and providers; an internal SLA governs IT's commitments to the business."},

// u7l2
{id:"u7l2-1",t:"u7l2",q:"A change to a core switch failed at 3 a.m. and the team had no way to return to the previous state. Which change management element was missing?",a:["A rollback plan and backup plan","End-user acceptance","A change freeze","Peer review"],c:0,e:"The rollback plan describes how to undo the change, and the backup plan provides the saved configuration or data to restore. Both are required before implementation."},
{id:"u7l2-2",t:"u7l2",q:"Which change type is pre-approved, low risk, and follows a standard operating procedure without individual change board review?",a:["Normal change","Standard change","Emergency change","Rollback change"],c:1,e:"Standard changes such as password resets and routine installs are pre-approved and logged. Normal changes go to the change board; emergency changes use an expedited approval and are documented afterward."},
{id:"u7l2-3",t:"u7l2",q:"A vulnerability is being actively exploited and a patch is available, but the next change board meeting is a week away. What should be done?",a:["Wait for the change board","Skip change management entirely","Submit an emergency change through the expedited approval process and document it afterward","Schedule it for the next change freeze"],c:2,e:"Emergency changes exist for situations that cannot wait. They still get approval, from an emergency approver, and full documentation after implementation."},
{id:"u7l2-4",t:"u7l2",q:"What is the purpose of a change freeze?",a:["To require all changes be made at once","To assign responsible staff","To test changes in a sandbox","To prohibit non-emergency changes during a sensitive period such as financial close"],c:3,e:"A change freeze blocks normal changes during periods when disruption is unacceptable. Maintenance windows are the opposite: the agreed times when changes are made."},
{id:"u7l2-5",t:"u7l2",q:"After a change is implemented, which step confirms that the people who use the system agree it works before the change is closed?",a:["End-user acceptance","Sandbox testing","Risk analysis","Request form submission"],c:0,e:"End-user acceptance is the final confirmation from users. Risk analysis and sandbox testing happen before implementation."},

// u7l3
{id:"u7l3-1",t:"u7l3",q:"A full backup runs Sunday and incremental backups run Monday through Thursday. A failure occurs Friday morning. Which backup sets are needed to restore?",a:["Sunday and Thursday only","Sunday, Monday, Tuesday, Wednesday, and Thursday","Thursday only","Sunday only"],c:1,e:"Each incremental contains only changes since the previous backup, so a restore needs the last full plus every incremental since it, in order."},
{id:"u7l3-2",t:"u7l3",q:"A full backup runs Sunday and differential backups run Monday through Thursday. Which sets restore the system after a Friday failure?",a:["Thursday only","All five sets","Sunday and Thursday","Sunday and Monday"],c:2,e:"A differential contains all changes since the last full, so the last full plus the most recent differential is a complete restore."},
{id:"u7l3-3",t:"u7l3",q:"Which backup type is assembled on the backup server from the last full backup and subsequent incrementals, without re-reading all the data from the source?",a:["Differential","Mirror","Snapshot","Synthetic full"],c:3,e:"A synthetic full combines an existing full with later incrementals to produce a new full, giving simple restores without the load of a real full backup."},
{id:"u7l3-4",t:"u7l3",q:"What does the 3-2-1 backup rule require?",a:["Three copies of the data, on two different media or systems, with one copy off-site","Three backups per day, two per week, one per month","Three technicians, two locations, one vendor","Three full backups, two differentials, one incremental"],c:0,e:"The rule protects against device failure, media failure, and site loss. Many organizations add an offline or immutable copy to defeat ransomware."},
{id:"u7l3-5",t:"u7l3",q:"A user needs last Tuesday's version of a spreadsheet without losing the edits made since. Which recovery approach should be used?",a:["In-place overwrite restore","Restore to an alternative location and copy what is needed","Reimage the workstation","Restore the entire drive"],c:1,e:"Restoring to an alternative location keeps the current file intact and lets the user compare and pick. An in-place restore would overwrite the newer work."},

// u8l1
{id:"u8l1-1",t:"u8l1",q:"A technician is about to install memory in a desktop at a carpeted workstation in winter. Which precaution is MOST important?",a:["Wear rubber gloves","Keep the computer plugged in for grounding","Wear a grounded ESD wrist strap and work on an ESD mat","Increase the room temperature"],c:2,e:"Dry air and carpet build static that can destroy components below the level a person can feel. A grounded strap and mat keep the technician and the equipment at the same potential. The PC should be unplugged."},
{id:"u8l1-2",t:"u8l1",q:"A power supply fan has failed. What should the technician do?",a:["Open the power supply and replace the fan","Discharge the capacitors with a screwdriver and repair it","Run the PC without a power supply fan","Replace the power supply as a unit"],c:3,e:"Power supplies hold dangerous voltages in their capacitors and are not user-serviceable. They are replaced as complete units."},
{id:"u8l1-3",t:"u8l1",q:"Which extinguisher class is appropriate for an electrical fire involving a smoking UPS?",a:["Class C (CO2 or dry chemical)","Class A water extinguisher","A garden hose","Class K"],c:0,e:"Electrical fires require a Class C extinguisher in the United States. Water conducts electricity and must never be used on energized equipment."},
{id:"u8l1-4",t:"u8l1",q:"A technician must move a 40-kilogram server from a cart into a rack. What is the proper approach?",a:["Lift with the back and twist into position","Get help or use a lift, bend the knees, and keep the load close","Slide it up the rack rails alone","Carry it above shoulder height"],c:1,e:"Loads over roughly 23 kilograms (50 pounds) need two people or equipment. Lift with the legs, keep the back straight, hold the load close, and turn with the feet."},
{id:"u8l1-5",t:"u8l1",q:"Before opening a desktop computer to replace a component, what should be done FIRST?",a:["Turn off the monitor","Put on safety goggles","Disconnect the power cord and drain residual charge by pressing the power button","Remove the CMOS battery"],c:2,e:"The power switch and standby leave the board energized. Unplugging and then holding the power button drains the capacitors before hands go inside."},

// u8l2
{id:"u8l2-1",t:"u8l2",q:"A technician is unsure whether a cleaning solvent is safe to use near equipment and how to dispose of it. Which document should be consulted?",a:["The acceptable use policy","The change request form","The service-level agreement","The safety data sheet (SDS or MSDS)"],c:3,e:"The SDS lists hazards, handling, first aid, spill response, protective equipment, and disposal for any chemical product."},
{id:"u8l2-2",t:"u8l2",q:"How should used lithium-ion laptop batteries be disposed of?",a:["Through a battery recycling program with the terminals taped","In the regular trash","Burned in an incinerator on site","Buried with other office waste"],c:0,e:"Lithium-ion batteries can catch fire if damaged or shorted and contain regulated materials. They go to battery recycling with terminals taped, never to the trash."},
{id:"u8l2-3",t:"u8l2",q:"Lights dim and a server reboots whenever a large air compressor in the building starts. Which device addresses this problem?",a:["A surge suppressor alone","A line-interactive uninterruptible power supply","A longer extension cord","A second power strip"],c:1,e:"The compressor causes brownouts (voltage sags). A UPS with voltage regulation carries the load through sags and outages; a surge suppressor only clamps spikes."},
{id:"u8l2-4",t:"u8l2",q:"What are the generally recommended temperature and humidity ranges for an equipment room?",a:["10 to 15 C and 10 to 20 percent humidity","30 to 35 C and 70 to 80 percent humidity","18 to 27 C and 40 to 60 percent humidity","Any temperature as long as humidity is 0 percent"],c:2,e:"Roughly 18 to 27 degrees Celsius with 40 to 60 percent relative humidity balances component life against static (too dry) and corrosion or condensation (too humid)."},
{id:"u8l2-5",t:"u8l2",q:"Which tool should be used to remove dust from inside a computer?",a:["A household vacuum cleaner","A hair dryer on high heat","A damp cloth on the motherboard","Compressed air with ventilation, or a vacuum rated for electronics"],c:3,e:"Compressed air used with ventilation while holding fans still, or an antistatic electronics vacuum, removes dust safely. Household vacuums generate static and can dislodge components."},

// u8l3
{id:"u8l3-1",t:"u8l3",q:"While replacing a drive, a technician sees files that appear to be illegal content. What should the technician do?",a:["Stop, preserve the system, and report to management per the incident response policy","Copy the files to a USB drive as proof","Delete the files to protect the company","Confront the user"],c:0,e:"The technician's role is to recognize, preserve, and report. Exploring or deleting alters evidence; management decides on involving law enforcement."},
{id:"u8l3-2",t:"u8l3",q:"An investigator asks that memory contents be captured before the suspect PC is imaged and powered off. Which principle is being applied?",a:["Chain of custody","Order of volatility","Data retention","Acceptable use"],c:1,e:"Order of volatility means collecting the most perishable evidence first: registers and memory before disk, disk before remote logs and backups. Powering off destroys memory evidence."},
{id:"u8l3-3",t:"u8l3",q:"Evidence from an incident was passed between several people with no record of who handled it or when. What has been compromised?",a:["The end-user license agreement","The change freeze","The chain of custody","The backup rotation"],c:2,e:"Chain of custody is the unbroken documented record of everyone who collected, handled, transported, or stored evidence. Gaps allow the evidence to be challenged."},
{id:"u8l3-4",t:"u8l3",q:"An office has installed a utility that is licensed as free for personal use on 200 company computers. What is the issue?",a:["Nothing; free software may be used anywhere","The software is open-source","The software needs a perpetual license","The software violates the personal-use versus corporate-use license terms"],c:3,e:"Personal-use licenses do not cover business use. The organization must purchase corporate licensing or remove the software."},
{id:"u8l3-5",t:"u8l3",q:"Which login banner states that a system is for authorized use only and that activity is monitored, supporting policy enforcement?",a:["A splash screen","A knowledge base article","A configuration profile","A rollback plan"],c:0,e:"Splash screens or login banners give notice of authorized use and monitoring, so continuing implies consent. They support the acceptable use policy and any later action."},

// u8l4
{id:"u8l4-1",t:"u8l4",q:"A customer angrily blames the technician for a slow network. What is the BEST response?",a:["Explain firmly that the technician is not at fault","Listen without interrupting, avoid arguing, restate the issue, and explain the next steps","Leave and reschedule","Tell the customer the problem is minor"],c:1,e:"Professionalism means not arguing or becoming defensive, not dismissing the issue, listening actively, and clarifying, then setting expectations for the fix."},
{id:"u8l4-2",t:"u8l4",q:"A technician realizes they will arrive 20 minutes late to a customer appointment. What should they do?",a:["Arrive late without comment","Cancel the appointment","Contact the customer before the appointment time with a new estimate","Send a text after arriving"],c:2,e:"Being on time is expected; when running late, the technician contacts the customer ahead of the appointment and sets a new expectation."},
{id:"u8l4-3",t:"u8l4",q:"A user describes a problem vaguely. Which technique BEST narrows the scope?",a:["Ask yes-or-no questions only","Ask the user to submit a ticket later","Guess the cause and start fixing","Ask open-ended questions and restate the issue to verify understanding"],c:3,e:"Open-ended questions draw out details, and restating confirms the technician understood. Both are listed clarification techniques."},
{id:"u8l4-4",t:"u8l4",q:"While working on a computer, the technician notices payroll spreadsheets open on the screen. What is the appropriate action?",a:["Minimize them, mention it to the user, and avoid viewing the contents","Read them to understand the business","Take a photo for the ticket","Email the files to the user for safekeeping"],c:0,e:"Customers' confidential and private materials on computers, desks, or printers must be handled appropriately: not read, not copied, and not discussed."},
{id:"u8l4-5",t:"u8l4",q:"A technician is asked by a coworker about a well-known customer's laptop repair. How should the technician respond?",a:["Share the details since it is a coworker","Decline to share details, using discretion about customer encounters","Post about it on social media after work","Describe the customer's files"],c:1,e:"Professionalism requires discretion when discussing experiences and encounters. Customer details are not shared with coworkers who have no need to know, nor on social media."},

// u9l1
{id:"u9l1-1",t:"u9l1",q:"A user received an email attachment named invoice.vbs and opened it. What kind of file is this and what is the concern?",a:["A Python script; it is safe to run","A batch file; it only maps drives","A VBScript file run by the Windows Script Host; a common malware carrier","A shell script; it cannot run on Windows"],c:2,e:"The .vbs extension is VBScript, executed by the Windows Script Host with the user's rights. Script attachments are a classic way malware is delivered."},
{id:"u9l1-2",t:"u9l1",q:"Which script file type is native to modern Windows automation and uses cmdlets such as Get-Service?",a:[".bat",".sh",".py",".ps1"],c:3,e:"PowerShell scripts use the .ps1 extension and cmdlets with Verb-Noun names. Batch files use .bat, shell scripts .sh, and Python .py."},
{id:"u9l1-3",t:"u9l1",q:"A script that was meant to clean temporary folders deleted user documents on several PCs because of a wrong path. Which scripting consideration does this illustrate?",a:["Inadvertently changing system settings or data","Unintentionally introducing malware","Browser crashes from resource mishandling","Improper file extension"],c:0,e:"Scripts run with the launching user's rights and repeat mistakes at scale. Testing on one machine and a pilot group before wide deployment prevents this."},
{id:"u9l1-4",t:"u9l1",q:"Which of the following is a listed use case for scripting?",a:["Replacing a motherboard","Remapping network drives at sign-in","Degaussing hard drives","Choosing business casual attire"],c:1,e:"Scripting use cases include basic automation, restarting machines, remapping network drives, installing applications, automated backups, gathering information, and initiating updates."},
{id:"u9l1-5",t:"u9l1",q:"A script opens browser tabs in a loop with no exit condition, and the system becomes unresponsive. What does this demonstrate?",a:["A licensing violation","Proper automation","Resource mishandling causing browser or system crashes","A rootkit"],c:2,e:"Loops without limits and processes that are never closed exhaust memory and CPU. Scripts need exit conditions, limits, and logging."},

// u9l2
{id:"u9l2-1",t:"u9l2",q:"A firewall report shows repeated login attempts from the internet against TCP port 3389 on a server. What should be done?",a:["Change the RDP password only","Ignore it because RDP is encrypted","Switch to VNC on the same port","Close the port to the internet and provide RDP access through a VPN or gateway with MFA"],c:3,e:"Internet-exposed RDP is constantly brute-forced and is a leading ransomware entry point. RDP should be reachable only through a VPN or Remote Desktop Gateway with multifactor authentication."},
{id:"u9l2-2",t:"u9l2",q:"An administrator needs encrypted command-line access to a Linux server. Which tool should be used?",a:["SSH","VNC","RDP","SPICE"],c:0,e:"SSH provides encrypted shell access on TCP 22 and is the standard for Linux, macOS, and network devices; key-based authentication is preferred."},
{id:"u9l2-3",t:"u9l2",q:"A managed service provider must monitor the health of 400 customer endpoints, push patches, and open remote control sessions from one console. Which technology fits?",a:["Videoconferencing software","Remote monitoring and management (RMM)","Microsoft Remote Assistance","A file transfer client"],c:1,e:"RMM platforms use agents on each endpoint to monitor, patch, script, and remote-control at scale. Because the console can push anything anywhere, it needs MFA and least privilege."},
{id:"u9l2-4",t:"u9l2",q:"Which remote access method allows PowerShell commands to run on remote Windows machines over ports 5985 and 5986?",a:["VNC","RDP","WinRM","SPICE"],c:2,e:"Windows Remote Management implements WS-Management and powers PowerShell remoting over HTTP 5985 or HTTPS 5986. SPICE is a VM console protocol and VNC shares a screen."},
{id:"u9l2-5",t:"u9l2",q:"Which is the MAIN security concern with using native VNC across an untrusted network?",a:["It only works on Windows","It requires a smart card","It uses port 3389","Its native encryption is weak or absent, so it should be tunneled through SSH or a VPN"],c:3,e:"Many VNC implementations send traffic with little or no encryption. Tunneling through SSH or a VPN and using a strong password addresses the risk."},

// u9l3
{id:"u9l3-1",t:"u9l3",q:"A technician pastes a customer's error log, including account numbers, into a public AI chatbot to get help. Which concern does this raise?",a:["Data security and data privacy: regulated data has left the organization","Plagiarism","Application integration","Screen autorotation"],c:0,e:"Anything entered into a public AI service leaves the organization and may be retained. Regulated data must be redacted and only approved private tools used."},
{id:"u9l3-2",t:"u9l3",q:"An AI assistant confidently suggests a PowerShell cmdlet that does not exist. What is this called?",a:["Bias","A hallucination","Plagiarism","Integration"],c:1,e:"Hallucinations are fluent, confident, false outputs such as invented commands, settings, or citations. Every fact and command must be verified before use."},
{id:"u9l3-3",t:"u9l3",q:"A student submits an essay generated entirely by an AI tool as their own original work. Which concept applies?",a:["Appropriate use","Data source","Plagiarism","Accuracy"],c:2,e:"Presenting AI-generated content as one's own original work where originality is required is plagiarism; policies require disclosure and review."},
{id:"u9l3-4",t:"u9l3",q:"An AI-based screening tool consistently ranks applicants from one background higher regardless of qualifications. Which limitation is this?",a:["Hallucination","Data retention","Application integration","Bias"],c:3,e:"Models learn from data containing human biases and reproduce them. Decisions affecting people require human review and are usually restricted by policy."},
{id:"u9l3-5",t:"u9l3",q:"What is the recommended practice when an AI tool proposes a command to fix a production server?",a:["Verify it against documentation and test it in a sandbox before using it","Run it immediately since AI is accurate","Post it on social media for review","Disable the antivirus before running it"],c:0,e:"Appropriate use treats AI output as a draft. Accuracy limitations and hallucinations mean commands must be verified and tested before touching production."}
);
