// APlus Academy Core 2 question bank, units 4 and 5. All questions are original.
// Fields: id, t (lesson id), q (stem), a (four options), c (index of correct option), e (explanation).
window.FRA = window.FRA || {};
FRA.questions = FRA.questions || [];
FRA.questions.push(
// u4l1
{id:"u4l1-1",t:"u4l1",q:"A company wants to stop unauthorized people from slipping into the building behind badge-carrying employees. Which physical control BEST addresses this?",a:["Bollards at the entrance","An access control vestibule","A magnetometer","Additional exterior lighting"],c:1,e:"An access control vestibule is a two-door space where the second door opens only after the first closes and the person is verified, one person at a time. It defeats tailgating. Bollards stop vehicles, magnetometers find metal, and lighting deters."},
{id:"u4l1-2",t:"u4l1",q:"Which physical security measure is designed to prevent a vehicle from being driven into a building entrance?",a:["Badge readers","Motion sensors","Bollards","Equipment locks"],c:2,e:"Bollards are short heavy posts placed in front of entrances and walkways to stop vehicles. The other options control people, not cars."},
{id:"u4l1-3",t:"u4l1",q:"Management wants a record of exactly who entered the server room and at what time. Which control provides this?",a:["A keyed door lock","A fence around the property","Cable locks on the servers","A badge reader on the server room door"],c:3,e:"Badge readers log each entry by identity and time. A keyed lock records nothing, a fence is perimeter security, and cable locks protect equipment from removal."},
{id:"u4l1-4",t:"u4l1",q:"Which of the following authentication methods is an example of something you are?",a:["A palm print scanner","A smart card with a PIN","A mobile digital key","A key fob"],c:0,e:"Biometrics such as palm print, fingerprint, retina, face, and voice are something you are. Key fobs, smart cards, and mobile digital keys are something you have; the PIN is something you know."},
{id:"u4l1-5",t:"u4l1",q:"Laptops keep disappearing from an open-plan office during the day even though the building has badge access. Which control is the MOST direct fix?",a:["A retina scanner at the front door","Cable locks and locked cabinets","Bollards in the parking lot","Disabling SSID broadcast"],c:1,e:"When the building layer is already controlled, the next ring inward is the device. Equipment locks such as cable locks and locked cabinets stop the laptops themselves from being carried off."},

// u4l2
{id:"u4l2-1",t:"u4l2",q:"A receptionist's account was found to be a member of the local Administrators group on every PC. Which security principle does this violate?",a:["Zero Trust","Single sign-on","Principle of least privilege","Just-in-time access"],c:2,e:"Least privilege gives each account only the rights its job requires. A receptionist does not need administrator rights, and granting them lets any malware running as that user take over the machine."},
{id:"u4l2-2",t:"u4l2",q:"Which authentication method generates a six-digit code that changes every 30 seconds based on a shared secret and the current time?",a:["SMS","Email OTP","SAML","TOTP"],c:3,e:"A time-based one-time password (TOTP) is computed from a shared secret and the clock, so authenticator apps and hardware tokens produce the same code without a network. SMS and email deliver codes; SAML is an SSO standard."},
{id:"u4l2-3",t:"u4l2",q:"Employees log in once with their corporate credentials and gain access to a dozen cloud applications without signing in again. Which standard most commonly makes this web single sign-on possible?",a:["SAML","LDAP","TACACS+","WPA3"],c:0,e:"SAML lets an identity provider assert to web applications that a user is authenticated, enabling single sign-on across services. LDAP queries a directory, TACACS+ authenticates device administrators, and WPA3 is wireless encryption."},
{id:"u4l2-4",t:"u4l2",q:"A company wants administrators to receive elevated rights only when they request them for a specific task, for a limited time, with the session recorded. Which solution provides this?",a:["Mobile device management","Privileged access management with just-in-time access","Data loss prevention","An access control list"],c:1,e:"PAM vaults privileged credentials and grants just-in-time access for a bounded period while recording the session, removing standing administrator rights. MDM manages devices and DLP watches data leaving."},
{id:"u4l2-5",t:"u4l2",q:"A spreadsheet containing customer credit card numbers was emailed to a personal address without being blocked. Which control was missing?",a:["Multifactor authentication","Zero Trust network access","Data loss prevention","A directory service"],c:2,e:"DLP inspects data leaving by email, upload, USB, or print, recognizes sensitive content such as card numbers, and blocks or logs it. MFA protects logins, not outbound data."},

// u4l3
{id:"u4l3-1",t:"u4l3",q:"A technician is configuring a new access point and all client devices support the latest standards. Which wireless security setting should be selected?",a:["WPA2 with TKIP","WEP with a 128-bit key","WPA with TKIP","WPA3"],c:3,e:"WPA3 is the current standard, using SAE for the handshake, forward secrecy, and protected management frames. TKIP and WEP are deprecated and insecure."},
{id:"u4l3-2",t:"u4l3",q:"Which protocol does an access point use to forward a user's credentials to a central authentication server for enterprise Wi-Fi, typically over UDP ports 1812 and 1813?",a:["RADIUS","TACACS+","LDAP","Kerberos"],c:0,e:"RADIUS is the central authentication service for 802.1X wireless, VPNs, and network access, using UDP 1812 for authentication and 1813 for accounting. TACACS+ uses TCP 49 for device administration; Kerberos issues tickets in a domain."},
{id:"u4l3-3",t:"u4l3",q:"Network engineers want every command run on the switches to be authorized and logged per administrator, with the whole authentication packet encrypted. Which protocol fits?",a:["RADIUS","TACACS+","WPA2-Enterprise","SAE"],c:1,e:"TACACS+ separates authentication, authorization, and accounting, encrypts the entire packet, and supports per-command authorization for network device administration over TCP 49. RADIUS encrypts only the password field."},
{id:"u4l3-4",t:"u4l3",q:"Domain users on one workstation cannot authenticate, and the technician notices the PC's clock is 20 minutes off. Which authentication protocol is most likely failing?",a:["TACACS+","RADIUS","Kerberos","WPA2-Personal"],c:2,e:"Kerberos tickets carry timestamps, and Active Directory rejects clients whose clocks differ from the domain controller by more than about five minutes. Synchronizing time restores logins."},
{id:"u4l3-5",t:"u4l3",q:"What is the main difference between WPA2-Personal and WPA2-Enterprise?",a:["Enterprise uses TKIP while Personal uses AES","Personal requires certificates on every client","Enterprise does not encrypt traffic","Personal uses a shared passphrase; Enterprise authenticates each user through 802.1X and a RADIUS server"],c:3,e:"Personal mode uses one pre-shared key for all devices. Enterprise mode uses 802.1X with per-user credentials checked by RADIUS, giving each session a unique key and letting one user be revoked without changing everyone's passphrase."},

// u4l4
{id:"u4l4-1",t:"u4l4",q:"A user installed what appeared to be a free video codec, and the machine later began accepting remote commands from an attacker. What type of malware was the codec?",a:["A trojan","A boot sector virus","A virus","Adware"],c:0,e:"A trojan disguises itself as useful software and, once run, installs a backdoor or drops other malware. It does not spread by itself; the user installs it."},
{id:"u4l4-2",t:"u4l4",q:"A workstation is hot, its fans run constantly, and Task Manager shows an unfamiliar process using nearly 100 percent of the CPU. Which malware type is MOST likely?",a:["A keylogger","A cryptominer","Stalkerware","Spyware"],c:1,e:"Cryptominers hijack CPU and GPU cycles to mine cryptocurrency, producing heat, fan noise, slowness, and a process consuming all resources. Keyloggers and spyware are designed to stay quiet."},
{id:"u4l4-3",t:"u4l4",q:"A machine continues to behave abnormally and hide processes even though several antivirus scans report it clean. What is the MOST reliable remediation?",a:["Run the scans again in the morning","Clear the browser cache","Reinstall the operating system from known-good media","Disable the firewall and rescan"],c:2,e:"A rootkit hides from the operating system's own tools, so scanners running on the infected OS cannot see it. Reimaging or reinstalling the OS is the reliable cure, after backing up and scanning the data."},
{id:"u4l4-4",t:"u4l4",q:"An attack runs PowerShell commands launched from a document macro and never writes an executable to disk. Which security tool is BEST suited to detect it?",a:["Signature-based antivirus","A pop-up blocker","A degausser","Endpoint detection and response"],c:3,e:"Fileless malware lives in memory and uses legitimate tools, so file signature scanning misses it. EDR watches process behavior on the endpoint and can detect and isolate such activity."},
{id:"u4l4-5",t:"u4l4",q:"What is the difference between EDR and MDR?",a:["MDR is EDR operated and monitored by an outside security provider","EDR works only on mobile devices","MDR is a hardware appliance while EDR is software","EDR filters email while MDR filters web traffic"],c:0,e:"Managed detection and response is endpoint detection and response run by a third-party team that watches the alerts around the clock. XDR extends detection across email, network, cloud, and servers."},

// u4l5
{id:"u4l5-1",t:"u4l5",q:"A user receives a text message claiming a package is on hold and asking them to tap a link and confirm payment details. What kind of attack is this?",a:["Vishing","Smishing","Whaling","Shoulder surfing"],c:1,e:"Smishing is phishing delivered by SMS text message. Vishing is by voice call, whaling targets executives, and shoulder surfing is watching a screen or keyboard."},
{id:"u4l5-2",t:"u4l5",q:"A crafted email is sent specifically to the company's chief financial officer, referencing a real acquisition and asking for an urgent wire transfer. Which term BEST describes this?",a:["Smishing","Dumpster diving","Whaling","An evil twin attack"],c:2,e:"Whaling is spear phishing aimed at executives, usually about money or legal matters. If the sender's mailbox is genuinely compromised, it is also business email compromise."},
{id:"u4l5-3",t:"u4l5",q:"At a coffee shop, a laptop sees two networks with the shop's name, one with a much stronger signal, and after connecting a certificate warning appears for the mail server. What is happening?",a:["A zero-day attack","A brute-force attack","A SQL injection attack","An evil twin providing an on-path position"],c:3,e:"An evil twin is a rogue access point using the legitimate SSID so victims connect through the attacker, who then sits on-path and intercepts traffic. The certificate warning is the interception being noticed."},
{id:"u4l5-4",t:"u4l5",q:"An exploit is used against a vulnerability the vendor has not yet released a patch for. What is this called?",a:["A zero-day attack","A dictionary attack","Spoofing","An insider threat"],c:0,e:"A zero-day exploits a flaw with no available patch, and often no signature, so behavior-based defenses and least privilege are the main protections until a fix ships."},
{id:"u4l5-5",t:"u4l5",q:"Which of the following is listed as a vulnerability rather than an attack?",a:["Cross-site scripting","An end-of-life operating system","A distributed denial of service","Business email compromise"],c:1,e:"Vulnerabilities are weaknesses: non-compliant, unpatched, and unprotected systems, end-of-life software, and BYOD. Cross-site scripting, DDoS, and BEC are attacks that exploit weaknesses."},

// u5l1
{id:"u5l1-1",t:"u5l1",q:"A folder is shared with the share permission Full Control for Everyone, and the NTFS permission for the Sales group is Read. What can a Sales user do when accessing the folder over the network?",a:["Full Control","Modify files","Read only","Nothing; access is denied"],c:2,e:"Over the network the effective permission is the most restrictive combination of share and NTFS permissions. Full Control at the share layer and Read at the NTFS layer results in Read."},
{id:"u5l1-2",t:"u5l1",q:"A user belongs to a group that is allowed Modify on a folder and to another group that is denied Write on the same folder. What is the result?",a:["The user can write because Allow was set first","The user can write because Modify includes Write","The user loses all access to the folder","The user cannot write because an explicit Deny overrides Allow"],c:3,e:"Allow permissions accumulate across groups, but an explicit Deny always overrides Allow. The user keeps read access from Modify but cannot write."},
{id:"u5l1-3",t:"u5l1",q:"A technician moves a file from the Finance folder to the Public folder on the same NTFS volume, and the file still has Finance permissions. Why?",a:["Moving within the same volume retains the file's existing permissions","NTFS permissions cannot be changed after a file is created","The Public folder has inheritance disabled","The file has the read-only attribute set"],c:0,e:"A move within one NTFS volume keeps the file's permissions. A copy, or a move to a different volume, inherits the destination folder's permissions. Copy the file instead or reset inheritance."},
{id:"u5l1-4",t:"u5l1",q:"Which account type should ordinary employees use for daily work on a Windows PC?",a:["Administrator","Standard user","Guest","Power user"],c:1,e:"Standard accounts cannot install most software or change system settings without an administrator's credentials, which limits what malware running as the user can do. Guest should stay disabled; Power Users is a legacy group."},
{id:"u5l1-5",t:"u5l1",q:"A user right-clicks a program and chooses Run as administrator, and a consent dialog appears before the program starts. Which Windows feature displays this prompt?",a:["BitLocker","Windows Defender Firewall","User Account Control","Encrypting File System"],c:2,e:"User Account Control prompts for consent or administrator credentials whenever a task needs elevated rights, so nothing changes the system silently. It should never be turned off."},

// u5l2
{id:"u5l2-1",t:"u5l2",q:"A company wants the entire drive of each laptop encrypted so a stolen laptop's data cannot be read in another computer. Which feature should be used?",a:["EFS","NTFS permissions","Folder redirection","BitLocker"],c:3,e:"BitLocker encrypts the whole volume, normally keyed to the TPM, so the disk is unreadable outside the original boot chain. EFS encrypts individual files for one user and NTFS permissions do not protect a drive moved to another machine."},
{id:"u5l2-2",t:"u5l2",q:"After a motherboard replacement, a laptop boots to a screen asking for a 48-digit key. What is being requested?",a:["The BitLocker recovery key","The Windows product key","The Active Directory password","The TPM owner password"],c:0,e:"The TPM on the new board cannot release the BitLocker key because the boot measurements changed, so BitLocker asks for the recovery key that should have been saved to Active Directory, a Microsoft account, a file, or paper."},
{id:"u5l2-3",t:"u5l2",q:"Two managers share one workstation, and each needs files that the other cannot open even with local administrator rights. Which feature meets this need?",a:["BitLocker To Go","EFS","Share permissions","A guest account"],c:1,e:"EFS encrypts files or folders with a key tied to the user's certificate, so other users, including administrators, cannot read them. BitLocker To Go protects removable drives, and permissions can be overridden by an administrator."},
{id:"u5l2-4",t:"u5l2",q:"A user transferred from Sales to Marketing still receives the Sales department's desktop restrictions after logging in. Which Active Directory action fixes this?",a:["Assign the user a home folder","Enable BitLocker on the user's PC","Move the user object to the Marketing organizational unit","Rename the user account"],c:2,e:"Group Policy is linked to organizational units, so a user object in the Sales OU keeps receiving Sales policies. Moving the object to the Marketing OU applies Marketing's policies; group memberships should be updated as well."},
{id:"u5l2-5",t:"u5l2",q:"Users lose their Documents folder contents whenever their PC is reimaged. Which Active Directory feature stores those folders on a server while they still appear local to the user?",a:["Domain join","A login script","A security group","Folder redirection"],c:3,e:"Folder redirection is a Group Policy setting that points Documents, Desktop, and other folders to a server share, so files follow the user to any PC and are backed up centrally."},

// u5l3
{id:"u5l3-1",t:"u5l3",q:"Which characteristic contributes MOST to the strength of a password?",a:["Its length","Changing it every 30 days","Including the user's initials","Using the same password on every site so it is remembered"],c:0,e:"Length is the dominant factor because each added character multiplies the search space. Complexity and uniqueness help; reuse is a weakness."},
{id:"u5l3-2",t:"u5l3",q:"A PC became infected the moment a found USB drive was inserted. Which hardening setting would have prevented the program from launching?",a:["Enabling the guest account","Disabling AutoRun","Setting a screensaver lock","Applying an account expiration date"],c:1,e:"AutoRun and AutoPlay let inserted media launch programs automatically. Disabling them is a standard hardening step against malware on removable media."},
{id:"u5l3-3",t:"u5l3",q:"A contractor's account was still active and used months after the contract ended. Which account management setting addresses this?",a:["Failed-attempts lockout","Restricting login times","Account expiration dates","Disabling unused services"],c:2,e:"Applying an expiration date to temporary and contractor accounts makes them stop working automatically on the scheduled day, without relying on someone remembering to disable them."},
{id:"u5l3-4",t:"u5l3",q:"Logs show thousands of failed password attempts against one user account over a single night. Which control BEST mitigates this attack?",a:["Disabling SSID broadcast","Enabling AutoPlay","Renaming the administrator account","A failed-attempts lockout policy"],c:3,e:"A lockout after a small number of failed attempts stops online brute-force and dictionary attacks by freezing the account for a period. The other options do not address repeated guesses."},
{id:"u5l3-5",t:"u5l3",q:"A thief booted a stolen desktop from a USB drive and copied its files. Which pair of controls would have prevented this?",a:["A BIOS/UEFI supervisor password with a locked boot order, and data-at-rest encryption","A screensaver lock and a strong Windows password","Disabling the guest account and restricting login times","A password manager and a content filter"],c:0,e:"A firmware supervisor password prevents changing the boot order to bypass Windows, and full-disk encryption makes the data unreadable even if the drive is removed. Windows passwords alone do not protect data from an alternate boot."},

// u5l4
{id:"u5l4-1",t:"u5l4",q:"Which mobile screen lock method provides no real security?",a:["Fingerprint","Swipe","A six-digit PIN","Facial recognition"],c:1,e:"A swipe unlock performs no authentication at all. A pattern is weak, a PIN is acceptable when long enough, and biometrics are strong with a PIN fallback."},
{id:"u5l4-2",t:"u5l4",q:"An employee reports that a corporate phone containing company email was left in a taxi and cannot be recovered. What should the technician do to protect the data?",a:["Change the Wi-Fi passphrase","Install antivirus on the user's replacement phone","Issue a remote wipe through the MDM console","Disable SSID broadcast in the office"],c:2,e:"After locating and locking fail to recover the device, a remote wipe erases it so the data is unreadable. MDM or the platform's locator service performs it; the replacement is restored from remote backup."},
{id:"u5l4-3",t:"u5l4",q:"A company allows personal phones to access work email but wants to be able to erase only the company data if an employee leaves. Which approach provides this?",a:["Corporate-owned devices with full wipe","Blocking application updates","Disabling device encryption","BYOD with an MDM work profile and selective wipe"],c:3,e:"Under a BYOD policy, MDM installs a managed work profile or container. A selective wipe removes the company's data and apps while leaving personal photos and messages untouched."},
{id:"u5l4-4",t:"u5l4",q:"Which mobile security feature erases or locks the device after a set number of incorrect passcode entries?",a:["Failed log-in attempts restrictions","Content filtering","A configuration profile","Remote backup"],c:0,e:"Failed-attempt restrictions lock the device for increasing periods or wipe it after repeated wrong passcodes, giving a lost device time to be located and wiped before its passcode can be guessed."},
{id:"u5l4-5",t:"u5l4",q:"Before a phone may receive the company's mail profile it must run a current OS version, have encryption and a passcode enabled, and must not be jailbroken. What are these conditions called?",a:["Locator application settings","Profile security requirements","Patch management","Antimalware definitions"],c:1,e:"Profile security requirements are the minimum standards a device must meet to be enrolled and receive the work profile. Non-compliant devices are blocked until they meet the bar."},

// u5l5
{id:"u5l5-1",t:"u5l5",q:"Which router setting should be disabled because it lets any device on the LAN open inbound ports automatically?",a:["DHCP","WPA3","UPnP","Content filtering"],c:2,e:"Universal Plug and Play allows programs and devices to open router ports without the administrator's involvement, which malware exploits. It should be turned off and any needed ports forwarded manually."},
{id:"u5l5-2",t:"u5l5",q:"A small office wants visitors to have internet access without being able to reach the office file server or printers. Which router feature provides this?",a:["Port forwarding","MAC filtering","Disabling SSID broadcast","An isolated guest network"],c:3,e:"A guest SSID with client isolation gives visitors internet access on a segment separated from the LAN, so they cannot reach internal devices."},
{id:"u5l5-3",t:"u5l5",q:"What is the FIRST configuration change a technician should make on a newly installed SOHO router?",a:["Change the default administrator password","Enable the DMZ host","Set the channel to 6","Turn on remote management"],c:0,e:"Default credentials are printed on the device and published online, so changing the administrator password comes first, followed by a firmware update and wireless encryption settings."},
{id:"u5l5-4",t:"u5l5",q:"A security camera recorder inside the office must accept connections from the internet on one specific port. Which router feature accomplishes this with the least exposure?",a:["Enabling UPnP","Port forwarding of that single port to the recorder","Placing the recorder as the DMZ host","Disabling the firewall"],c:1,e:"Port forwarding maps one public port to one internal device and port, exposing only that service. A DMZ host forwards every port to the device, and UPnP hands control to the devices themselves."},
{id:"u5l5-5",t:"u5l5",q:"Which two wireless settings are considered weak security measures because they are easily bypassed?",a:["WPA3 and a long passphrase","Guest isolation and firmware updates","Disabling SSID broadcast and MAC address filtering","HTTPS management and disabling remote management"],c:2,e:"The SSID is still visible in wireless traffic when broadcast is off, and MAC addresses are visible and easily cloned. Neither replaces strong encryption and a strong passphrase."},

// u5l6
{id:"u5l6-1",t:"u5l6",q:"A technician downloads a browser installer and wants to confirm it has not been altered since the vendor published it. What should be done?",a:["Run the installer and check for errors","Install it in private browsing mode","Scan the file with a pop-up blocker","Compare the file's computed hash with the hash published by the vendor"],c:3,e:"Hashing produces a fingerprint of the file. If the computed SHA-256 matches the vendor's published value, the bytes are identical; a mismatch means corruption or tampering."},
{id:"u5l6-2",t:"u5l6",q:"Which browser mode prevents history, cookies, and cached pages from being saved on the local computer after the window closes?",a:["Private browsing mode","Browser data synchronization","Secure DNS","Ad blocking"],c:0,e:"Private browsing keeps no local traces once the session ends. It does not hide activity from the network, the employer, or the website."},
{id:"u5l6-3",t:"u5l6",q:"A user's browser shows a warning that a shopping site's certificate is not valid. What should the user do?",a:["Click through the warning and continue shopping","Not proceed, and investigate the cause before entering any information","Disable the pop-up blocker","Clear the cache and click through"],c:1,e:"A certificate warning means the certificate is expired, mismatched, untrusted, or the connection is being intercepted. Proceeding on a site that takes payments risks an on-path attack."},
{id:"u5l6-4",t:"u5l6",q:"Which browser setting encrypts name lookups so they cannot be read or altered on the local network, but may bypass the organization's DNS-based content filtering?",a:["A proxy server","Pop-up blocking","Secure DNS","Password manager"],c:2,e:"Secure DNS (DNS over HTTPS) encrypts DNS queries to a resolver. Because it sidesteps the company's DNS filter, some organizations disable it by policy."},
{id:"u5l6-5",t:"u5l6",q:"After installing a free utility, a user's browser opens to an unfamiliar search page and searches are redirected. What is the MOST likely cause?",a:["An expired certificate","A disabled ad blocker","Browser data synchronization","An untrusted extension or potentially unwanted program"],c:3,e:"Bundled installers add untrusted extensions and PUPs that change the home page, search engine, and proxy. Remove the extension, check the proxy setting, reset the browser, and scan."},

// u5l7
{id:"u5l7-1",t:"u5l7",q:"Which data destruction method is ineffective on solid-state drives?",a:["Degaussing","Incineration","Shredding","Drilling"],c:0,e:"Degaussing destroys data on magnetic media by scrambling the magnetic field. Solid-state drives store charge in flash cells, so a degausser does nothing to them."},
{id:"u5l7-2",t:"u5l7",q:"Fifty laptops are being donated to a school. Which method makes the drives safe to reuse?",a:["A quick format","An erase or wipe using overwrite or the drive's secure erase","Drilling the platters","Removing the drive labels"],c:1,e:"Wiping by overwrite or the drive's secure erase command sanitizes the drive while leaving it usable. A quick format only rewrites the file table and leaves data recoverable."},
{id:"u5l7-3",t:"u5l7",q:"An auditor asks for proof that retired drives containing patient data were destroyed. Which document should the technician produce?",a:["The router configuration backup","A screenshot of the quick format","The certificate of destruction from the third-party vendor","The software license agreement"],c:2,e:"A certificate of destruction or recycling lists each serial number, the method, and the date, signed by the vendor. It is the accepted proof for regulatory audits."},
{id:"u5l7-4",t:"u5l7",q:"A user performed a quick format on a drive before selling the PC. What is the risk?",a:["The drive will no longer boot Windows","The partition table becomes GPT","The drive's firmware is erased","The data remains recoverable with common tools"],c:3,e:"A quick format rewrites only the filesystem structures; the data blocks are untouched and easily recovered. A verified wipe or secure erase is required before disposal or resale."},
{id:"u5l7-5",t:"u5l7",q:"A failed hard drive that held payroll records cannot be powered on or wiped. What should be done with it?",a:["Physically destroy it through shredding or drilling and record the serial number","Place it in the regular trash","Reformat it on another PC","Store it indefinitely in an unlocked drawer"],c:0,e:"A drive that cannot be sanitized must be physically destroyed. Shredding through a certified vendor, or drilling in-house per policy, followed by documentation, meets both data and e-waste requirements."},

// u5l8
{id:"u5l8-1",t:"u5l8",q:"A user reports constant pop-ups and a disabled antivirus. According to the malware removal procedure, what should the technician do FIRST?",a:["Quarantine the system","Investigate and verify the malware symptoms","Disable System Restore","Educate the user"],c:1,e:"Step one is to investigate and verify the symptoms so the problem is confirmed as malware rather than a hardware or configuration fault. Quarantine is step two."},
{id:"u5l8-2",t:"u5l8",q:"The technician has confirmed that a workstation is infected. What is the NEXT step in the malware removal procedure?",a:["Run a full antivirus scan immediately","Create a restore point","Quarantine the system by disconnecting it from the network","Reinstall the operating system"],c:2,e:"Once malware is confirmed, the system is quarantined, typically by unplugging the network cable and disabling Wi-Fi, so it cannot spread or reach its command server."},
{id:"u5l8-3",t:"u5l8",q:"Why does the malware removal procedure call for disabling System Restore on a Windows Home machine before remediation?",a:["To free disk space for the scan","To speed up the boot process","Because antivirus cannot run while System Restore is enabled","So infected restore points are deleted and cannot reinfect the machine"],c:3,e:"Restore points can contain infected files that scanners cannot clean. Disabling System Restore deletes them, preventing a later restore from bringing the malware back."},
{id:"u5l8-4",t:"u5l8",q:"Malware has been removed and Windows and application updates have been applied. What should the technician do NEXT?",a:["Enable System Restore and create a restore point","Disable System Restore","Quarantine the system","Investigate and verify symptoms"],c:0,e:"After remediation and updates, System Restore is re-enabled and a clean restore point is created, capturing the machine in its known-good state. Educating the user follows."},
{id:"u5l8-5",t:"u5l8",q:"Which step is the LAST in the seven-step malware removal procedure?",a:["Schedule scans and run updates","Educate the end user","Remediate the infected system","Disable System Restore"],c:1,e:"User education is the final step: explaining what happened and how to avoid it. Without it the same click brings the same malware back."}
);
