// NetPlus Academy question bank: network services (unit 5 lessons 3-5) and operations (unit 8 lessons 1-6).
window.FRA = window.FRA || {};
FRA.questions = FRA.questions || [];
FRA.questions.push(
// u5l3
{id:"u5l3-1",t:"u5l3",q:"Clients on a remote subnet with no local DHCP server fail to obtain addresses. What should be configured on the router interface for that subnet?",a:["A DHCP reservation","A DHCP relay, also called an IP helper address","A DHCP exclusion","A DNS forwarder"],c:1,e:"DHCP Discover is a broadcast that routers do not forward. A relay converts it to a unicast to the central server."},
{id:"u5l3-2",t:"u5l3",q:"A network printer must always receive the same IP address but the administrator wants to keep managing addresses centrally. What should be configured?",a:["A static address on the printer only","A shorter lease time","A DHCP reservation for the printer's MAC address","A second scope"],c:2,e:"A reservation ties an address to a MAC so the device always gets the same lease while DHCP still manages it."},
{id:"u5l3-3",t:"u5l3",q:"Which is the correct order of the DHCP lease process?",a:["Discover, Request, Offer, Acknowledge","Request, Offer, Discover, Acknowledge","Offer, Discover, Acknowledge, Request","Discover, Offer, Request, Acknowledge"],c:3,e:"DORA: the client Discovers, the server Offers, the client Requests, the server Acknowledges."},
{id:"u5l3-4",t:"u5l3",q:"A server was manually assigned 192.168.1.150, which is inside the DHCP scope. Later a laptop receives the same address and both devices have intermittent connectivity. How should this be prevented?",a:["Add an exclusion for 192.168.1.150 in the scope","Shorten the lease time","Enable DHCP snooping","Add a DNS PTR record"],c:0,e:"An exclusion tells the server never to lease that address, preventing the duplicate."},
{id:"u5l3-5",t:"u5l3",q:"Which DHCP option delivers the default gateway to clients?",a:["Option 6","Option 3","Option 15","Option 66"],c:1,e:"Option 3 is the router (default gateway). Option 6 is DNS servers, 15 is domain name, and 66 is the TFTP server used for phone provisioning."},
{id:"u5l3-6",t:"u5l3",q:"At what point in the lease does a DHCP client normally try to renew?",a:["At 25 percent of the lease","Only when the lease expires","At 50 percent of the lease","Every 60 seconds"],c:2,e:"Clients attempt renewal with the original server at half the lease time, then broadcast for any server at 87.5 percent."},
{id:"u5l3-7",t:"u5l3",q:"Users on a floor receive addresses with a gateway that does not exist and lose connectivity. The DHCP server's log shows no leases for them. What is the MOST likely cause?",a:["Scope exhaustion","An STP loop","A missing DNS record","A rogue DHCP server on the segment"],c:3,e:"An unauthorized DHCP server answering first hands out incorrect settings. DHCP snooping on switches blocks it."},

// u5l4
{id:"u5l4-1",t:"u5l4",q:"Which DNS record type resolves an IP address back to a hostname?",a:["A","MX","PTR","TXT"],c:2,e:"PTR records live in the reverse zone and map addresses to names."},
{id:"u5l4-2",t:"u5l4",q:"A company changes its email provider. Which DNS record must be updated so mail is delivered to the new servers?",a:["A","CNAME","NS","MX"],c:3,e:"MX records specify the mail exchangers for a domain."},
{id:"u5l4-3",t:"u5l4",q:"Users can reach servers by IP address but not by hostname. What is the MOST likely cause?",a:["DNS misconfiguration","Incorrect default gateway","Duplicate MAC address","Spanning tree loop"],c:0,e:"If IP connectivity works but names do not resolve, name resolution is the failing service."},
{id:"u5l4-4",t:"u5l4",q:"Which record type makes www.example.com an alias for webserver01.example.com?",a:["A","CNAME","AAAA","SRV"],c:1,e:"A CNAME points one name to another name. A and AAAA point names to addresses."},
{id:"u5l4-5",t:"u5l4",q:"Which technology digitally signs DNS records so resolvers can verify they were not forged?",a:["DNS over HTTPS","DNS over TLS","DNSSEC","Dynamic DNS"],c:2,e:"DNSSEC provides integrity and authenticity through signatures. DoH and DoT encrypt the transport for privacy."},
{id:"u5l4-6",t:"u5l4",q:"A record type stores SPF and domain-verification strings. Which is it?",a:["PTR","SOA","NS","TXT"],c:3,e:"TXT records hold arbitrary text and are used for SPF, DKIM, DMARC, and ownership verification."},
{id:"u5l4-7",t:"u5l4",q:"A DNS server returns an answer from its cache rather than from the zone it hosts. How is that answer described?",a:["Non-authoritative","Authoritative","Recursive","Iterative"],c:0,e:"Only servers hosting the zone give authoritative answers. Cached answers from a resolver are non-authoritative."},
{id:"u5l4-8",t:"u5l4",q:"Which protocol encrypts DNS queries between a client and its resolver using TCP port 853?",a:["DNSSEC","DNS over TLS","DNS over HTTPS","LDAPS"],c:1,e:"DoT uses TCP 853. DoH uses HTTPS on 443. DNSSEC signs but does not encrypt."},
{id:"u5l4-9",t:"u5l4",q:"Which record type does an IPv6 host need to resolve a name to an IPv6 address?",a:["A","PTR","AAAA","MX"],c:2,e:"AAAA records map names to 128-bit IPv6 addresses."},

// u5l5
{id:"u5l5-1",t:"u5l5",q:"Users cannot log in to the domain after a switch's clock drifted 20 minutes from the domain controllers. Which service should be fixed?",a:["DNS","SNMP","DHCP","NTP"],c:3,e:"Kerberos authentication fails when clocks differ by more than about five minutes. NTP keeps them synchronized."},
{id:"u5l5-2",t:"u5l5",q:"A trading firm requires clock synchronization accurate to less than a microsecond. Which protocol is designed for this?",a:["PTP","NTP","NTS","SNTP"],c:0,e:"Precision Time Protocol uses hardware timestamps for sub-microsecond accuracy; NTP is millisecond-class."},
{id:"u5l5-3",t:"u5l5",q:"What does an NTP stratum 1 server synchronize to?",a:["Another stratum 1 server","A stratum 0 reference clock such as GPS or an atomic clock","The nearest stratum 2 server","A DHCP server"],c:1,e:"Stratum 0 is the reference clock itself. Stratum 1 servers are directly attached to one and stratum numbers increase with distance."},
{id:"u5l5-4",t:"u5l5",q:"Which protocol adds authentication and encryption to time synchronization so an attacker cannot feed false time to clients?",a:["PTP","DNSSEC","NTS","IPsec AH"],c:2,e:"Network Time Security protects NTP with authenticated, encrypted key exchange."},
{id:"u5l5-5",t:"u5l5",q:"Security analysts cannot correlate events across firewalls, switches, and servers because timestamps disagree. What is the underlying problem?",a:["Syslog is using the wrong port","SNMPv3 is not enabled","The SIEM has too little storage","Devices are not synchronized to a common NTP source"],c:3,e:"Log correlation depends on consistent time. All devices should sync to the same internal NTP hierarchy."},

// u8l1
{id:"u8l1-1",t:"u8l1",q:"Which document shows how traffic flows between networks, including IP addressing, VLANs, and routing, rather than where devices physically sit?",a:["Logical network diagram","Physical network diagram","Rack diagram","Cable map"],c:0,e:"Logical diagrams depict addressing and data flow. Physical diagrams, rack diagrams, and cable maps show location and wiring."},
{id:"u8l1-2",t:"u8l1",q:"A technician must find which patch panel port connects to wall jack 3B-14 without tracing cables. Which document should exist for this?",a:["Logical diagram","Cable map","SLA","Heat map"],c:1,e:"A cable map or wiring diagram records jack-to-panel-to-switch-port connections."},
{id:"u8l1-3",t:"u8l1",q:"Which record is the authoritative source for every subnet and assigned address, preventing duplicates and overlaps?",a:["Asset inventory","Rack diagram","IPAM","Change log"],c:2,e:"IP address management tracks subnets, addresses, and assignments."},
{id:"u8l1-4",t:"u8l1",q:"An ISP contract promises 99.9 percent uptime and four-hour response to outages. What is this document called?",a:["MOU","NDA","AUP","SLA"],c:3,e:"A service level agreement defines guaranteed performance and the remedies if it is missed."},
{id:"u8l1-5",t:"u8l1",q:"Which diagram shows the front of each equipment cabinet with the rack unit position of every device?",a:["Rack diagram","Layer 3 diagram","Floor plan","Logical diagram"],c:0,e:"Rack diagrams document device placement by rack unit within each rack."},
{id:"u8l1-6",t:"u8l1",q:"Which inventory item helps a team decide when a switch must be replaced because the vendor will stop providing support?",a:["Its MAC address","Its warranty and support status","Its VLAN assignments","Its patch panel port"],c:1,e:"Asset inventories track warranty and support dates so end-of-support devices are refreshed before they become a risk."},
{id:"u8l1-7",t:"u8l1",q:"Which type of diagram would show switches, trunks, VLANs, and the spanning tree root?",a:["Layer 1 diagram","Layer 3 diagram","Layer 2 diagram","Rack diagram"],c:2,e:"Layer 2 diagrams cover switching topology. Layer 1 covers cabling and Layer 3 covers routing and subnets."},

// u8l2
{id:"u8l2-1",t:"u8l2",q:"A technician plans to upgrade firmware on a core switch. According to change management, what should happen FIRST?",a:["Perform the upgrade immediately to reduce risk exposure","Submit a change request with an impact assessment and rollback plan, then obtain approval","Notify users after the upgrade is complete","Disable logging so the change is not recorded"],c:1,e:"Change management requires a request, impact analysis, rollback plan, and approval before work begins in a scheduled window."},
{id:"u8l2-2",t:"u8l2",q:"A vendor announces that a firewall model will receive no further security patches. Which milestone has it reached?",a:["End of sale","End of life","End of support","Decommissioning"],c:2,e:"End of support means no more fixes or help. The device becomes a security liability and should be replaced."},
{id:"u8l2-3",t:"u8l2",q:"Which configuration is the approved standard build against which running configurations are compared to detect unauthorized changes?",a:["Production configuration","Backup configuration","Startup configuration","Baseline or golden configuration"],c:3,e:"The golden configuration is the reference standard. Deviations from it indicate drift or unauthorized changes."},
{id:"u8l2-4",t:"u8l2",q:"What should be done to a router immediately before applying an approved change?",a:["Save a backup of the current configuration","Erase its configuration","Disable its interfaces","Remove it from monitoring permanently"],c:0,e:"A backup taken before the change makes the rollback plan possible."},
{id:"u8l2-5",t:"u8l2",q:"A user requests a routine, pre-approved password reset for a network device account. Which process handles this?",a:["A full change advisory board review","A service request","An emergency change","A decommissioning procedure"],c:1,e:"Service requests cover low-risk, standard tasks that do not require the full change management review."},
{id:"u8l2-6",t:"u8l2",q:"When decommissioning a switch, which step protects the organization's information?",a:["Leave the configuration in place for the buyer","Remove only the power cord","Wipe the configuration and any stored data, then update inventory","Change its VLAN to 1"],c:2,e:"Decommissioning includes securely erasing configuration and data, updating documentation, and recovering licenses."},

// u8l3
{id:"u8l3-1",t:"u8l3",q:"An administrator wants to poll switches with SNMP and requires the traffic to be authenticated and encrypted. Which version must be used?",a:["SNMPv1","SNMPv2c","SNMPv3","SNMP over syslog"],c:2,e:"Versions 1 and 2c use plaintext community strings. Version 3 adds authentication and privacy."},
{id:"u8l3-2",t:"u8l3",q:"An administrator needs to see which hosts and applications consume the most WAN bandwidth without capturing every packet. Which method provides this?",a:["Syslog","SNMP traps","Full packet capture","Flow data such as NetFlow"],c:3,e:"Flow data summarizes conversations by source, destination, port, and volume. Packet capture records everything and syslog records events."},
{id:"u8l3-3",t:"u8l3",q:"In SNMP, what is an OID?",a:["The unique identifier of a variable in the MIB","The community string","The trap destination address","The polling interval"],c:0,e:"Object identifiers address individual variables in the management information base."},
{id:"u8l3-4",t:"u8l3",q:"A switch interface goes down and the switch immediately notifies the management station without being polled. What kind of message is this?",a:["SNMP Get","SNMP trap","SNMP Set","Syslog query"],c:1,e:"Traps are unsolicited notifications sent by the agent to the manager on UDP 162."},
{id:"u8l3-5",t:"u8l3",q:"A security team wants to collect logs from firewalls, servers, and switches in one place and receive alerts when patterns across them indicate an attack. Which system provides this?",a:["Protocol analyzer","IPAM","SIEM","NetFlow collector"],c:2,e:"A security information and event management system aggregates and correlates logs from many sources."},
{id:"u8l3-6",t:"u8l3",q:"Monitoring should alert when a link's utilization is unusual compared with its normal pattern for that time of day, not just when it crosses a fixed number. What must be established first?",a:["A default route","A VLAN","A trap destination","A baseline"],c:3,e:"A baseline captures normal behavior over time so deviations, or anomalies, can be detected."},
{id:"u8l3-7",t:"u8l3",q:"A technician needs to inspect the full contents of packets between a client and a server to debug an application. Which tool is appropriate?",a:["Protocol analyzer with a mirror port or tap","Flow analyzer","SNMP polling","Syslog server"],c:0,e:"Only a packet capture shows full payloads. Feed the analyzer from a SPAN port or a tap."},
{id:"u8l3-8",t:"u8l3",q:"Which syslog severity level indicates the most serious condition?",a:["7 Debug","0 Emergency","4 Warning","6 Informational"],c:1,e:"Syslog severities run from 0 (emergency) to 7 (debug); lower numbers are more severe."},

// u8l4
{id:"u8l4-1",t:"u8l4",q:"A VoIP call has choppy, garbled audio. Monitoring shows packets arriving with widely varying delay between them. Which condition is this?",a:["Latency","Bandwidth saturation","Packet loss","Jitter"],c:3,e:"Jitter is variation in delay. Steady latency is tolerable for voice; variable delay is not."},
{id:"u8l4-2",t:"u8l4",q:"Which monitoring solution reports whether services are reachable and calculates uptime against the SLA?",a:["Availability monitoring","Configuration monitoring","Traffic analysis","Network discovery"],c:0,e:"Availability monitoring checks reachability and tracks uptime percentages."},
{id:"u8l4-3",t:"u8l4",q:"A link rated at 1 Gbps consistently carries 850 Mbps during business hours. Which metric describes this, and what does it indicate?",a:["Latency; the link is slow","Utilization; the link is approaching congestion","Jitter; the link is unstable","MTBF; the link will fail soon"],c:1,e:"Utilization is throughput divided by capacity. Sustained utilization above roughly 70 to 80 percent signals imminent congestion."},
{id:"u8l4-4",t:"u8l4",q:"Which tool automatically finds devices on the network and how they interconnect, using SNMP, LLDP, and ping sweeps?",a:["Log aggregation","Availability monitoring","Network discovery","IPAM"],c:2,e:"Network discovery maps the devices and topology, either ad hoc or on a schedule."},
{id:"u8l4-5",t:"u8l4",q:"A file transfer to a remote site is slow even though the link has plenty of free bandwidth. Round-trip time is 300 ms. Which metric is limiting performance?",a:["Utilization","Packet loss","Jitter","Latency"],c:3,e:"High latency limits TCP throughput regardless of available bandwidth because acknowledgments take longer to return."},
{id:"u8l4-6",t:"u8l4",q:"Which monitoring type alerts when a device's running configuration differs from its approved baseline?",a:["Configuration monitoring","Performance monitoring","Traffic analysis","Availability monitoring"],c:0,e:"Configuration monitoring watches for changes and compliance against the golden configuration."},

// u8l5
{id:"u8l5-1",t:"u8l5",q:"A company decides it can afford to lose at most one hour of data if a disaster strikes. Which metric does this define?",a:["RPO","RTO","MTTR","MTBF"],c:0,e:"Recovery point objective is the maximum acceptable data loss measured in time. RTO is the time to restore service."},
{id:"u8l5-2",t:"u8l5",q:"Which type of recovery site has power, cooling, and networking equipment in place, but data must be restored and systems started before it can take over?",a:["Hot site","Warm site","Cold site","Cloud site"],c:1,e:"A warm site has infrastructure but not current data. A hot site runs continuously; a cold site is empty space."},
{id:"u8l5-3",t:"u8l5",q:"Which recovery site is the cheapest to maintain and the slowest to bring online?",a:["Hot site","Warm site","Cold site","Active-active site"],c:2,e:"A cold site provides only space, power, and cooling with no equipment or data, so recovery takes days or weeks."},
{id:"u8l5-4",t:"u8l5",q:"A pair of firewalls both pass traffic simultaneously and share the load; if one fails, the other carries everything. Which configuration is this?",a:["Active-passive","Warm site","Cold standby","Active-active"],c:3,e:"Active-active means all nodes serve traffic at once. Active-passive keeps a standby idle until failover."},
{id:"u8l5-5",t:"u8l5",q:"The disaster recovery team meets in a conference room and talks through how they would respond to a data center fire, without touching any systems. What is this exercise called?",a:["Tabletop exercise","Validation test","Failover test","Penetration test"],c:0,e:"A tabletop exercise walks through the plan verbally to find gaps. A validation test actually performs the recovery."},
{id:"u8l5-6",t:"u8l5",q:"A business requires that its ordering system be back online within two hours of any failure. Which metric is this?",a:["RPO","RTO","MTBF","SLA"],c:1,e:"Recovery time objective is the maximum time a service may be down."},
{id:"u8l5-7",t:"u8l5",q:"Which metric would a planner use to estimate how often a component is expected to fail and how many spares to stock?",a:["MTTR","RPO","MTBF","RTO"],c:2,e:"Mean time between failures is the expected operating time between failures of a component."},
{id:"u8l5-8",t:"u8l5",q:"Which server feature combines two network adapters so that if one link fails the server stays connected?",a:["Multipathing","Port mirroring","Load balancing","NIC teaming"],c:3,e:"NIC teaming bonds adapters for redundancy and sometimes bandwidth. Multipathing does the equivalent for storage paths."},

// u8l6
{id:"u8l6-1",t:"u8l6",q:"A company requires administrators to reach network devices even if the production network is completely down. Which management approach provides this?",a:["In-band management over SSH","Out-of-band management using console servers or a dedicated management network","A client-to-site VPN","A web GUI over HTTPS"],c:1,e:"Out-of-band management uses a separate path that does not depend on the production network."},
{id:"u8l6-2",t:"u8l6",q:"Remote employees connect to the corporate network using VPN software on their laptops. Which VPN type is this?",a:["Site-to-site","Clientless","Client-to-site","Full mesh"],c:2,e:"Client-to-site, or remote access VPN, connects individual users through client software."},
{id:"u8l6-3",t:"u8l6",q:"With a particular VPN configuration, only traffic destined for corporate subnets goes through the tunnel while web browsing goes directly to the internet. What is this called?",a:["Full tunnel","Site-to-site","Clientless VPN","Split tunnel"],c:3,e:"Split tunneling sends only corporate traffic through the VPN. It saves bandwidth but bypasses corporate inspection for other traffic."},
{id:"u8l6-4",t:"u8l6",q:"Administrators must first connect to a single hardened server and from there open sessions to internal devices. What is this server called?",a:["Jump box","Proxy server","Load balancer","Root bridge"],c:0,e:"A jump box or bastion host funnels administrative access through one monitored, hardened point."},
{id:"u8l6-5",t:"u8l6",q:"Which remote access method allows users to reach internal web applications through a browser over TLS without installing software?",a:["IPsec client","Clientless VPN","Console connection","SSH tunnel"],c:1,e:"Clientless VPNs work in the browser using TLS, typically limited to web-based resources."},
{id:"u8l6-6",t:"u8l6",q:"Which management method should replace Telnet for command-line access to network devices?",a:["HTTP","SNMPv1","SSH","TFTP"],c:2,e:"SSH provides encrypted command-line access on TCP 22. Telnet sends everything in plaintext."},
{id:"u8l6-7",t:"u8l6",q:"Two offices need their networks permanently joined so users can reach resources at either site without doing anything special. Which VPN type is appropriate?",a:["Client-to-site","Clientless","Split tunnel","Site-to-site"],c:3,e:"Site-to-site VPNs connect two gateways with an always-on tunnel, making the sites behave as one network."}
);
