// NetPlus Academy question bank: unit 7 (routing, appliances, cloud, modern networking, physical installations).
window.FRA = window.FRA || {};
FRA.questions = FRA.questions || [];
FRA.questions.push(
// u7l1 Routing fundamentals
{id:"u7l1-1",t:"u7l1",q:"A user can communicate with devices on the local subnet but cannot reach any remote networks or the internet. Which setting is MOST likely wrong?",a:["DNS server address","Default gateway","NTP server","DHCP lease time"],c:1,e:"Local traffic never touches the gateway, so a wrong gateway breaks only remote destinations."},
{id:"u7l1-2",t:"u7l1",q:"As a packet travels from a workstation through two routers to a server, which of the following remains unchanged?",a:["The source and destination MAC addresses","The source and destination IP addresses","The frame check sequence","The TTL value"],c:1,e:"Routers rewrite the frame at each hop and decrement the TTL, but the IP addresses in the packet stay the same unless NAT is applied."},
{id:"u7l1-3",t:"u7l1",q:"A branch router has routes only to its local subnets. Users cannot reach the internet. Which route should be added?",a:["A route to 127.0.0.0/8","A default route 0.0.0.0/0 pointing to the ISP","A route to 169.254.0.0/16","A host route to the DNS server"],c:1,e:"The default route matches any destination not otherwise in the table and sends it toward the internet."},
{id:"u7l1-4",t:"u7l1",q:"Which routing method requires an administrator to manually enter every route and does not adapt when a link fails?",a:["Dynamic routing","Static routing","Link-state routing","Policy routing"],c:1,e:"Static routes are typed in by hand. They are predictable and low overhead but do not change automatically."},
{id:"u7l1-5",t:"u7l1",q:"A host wants to send a packet to a destination on a different subnet. Which MAC address does it place in the frame's destination field?",a:["The destination host's MAC","The default gateway's MAC","The broadcast MAC","Its own MAC"],c:1,e:"For remote destinations the host frames the packet to its default gateway, learned through ARP, and the router takes it from there."},
{id:"u7l1-6",t:"u7l1",q:"A packet reaches the remote server but the reply never arrives back at the client. What is a likely cause?",a:["The client's DNS is wrong","The remote network lacks a return route to the client's subnet","The client's MAC address is invalid","The TTL is too high"],c:1,e:"Routing must work in both directions. A missing or incorrect route back to the source drops replies."},

// u7l2 Routing protocols and selection
{id:"u7l2-1",t:"u7l2",q:"A router learns a route to the same destination prefix from OSPF, from EIGRP, and from a manually configured static route. Which route is placed in the routing table?",a:["The OSPF route, because it is link-state","The EIGRP route, because it has the best metric","The static route, because it has the lowest administrative distance","All three are load-balanced"],c:2,e:"For identical prefixes, administrative distance decides. Static is 1, EIGRP is 90, OSPF is 110. Lower wins."},
{id:"u7l2-2",t:"u7l2",q:"A routing table contains 10.1.0.0/16, 10.1.1.0/24, and a default route. A packet arrives for 10.1.1.50. Which route is used?",a:["10.1.0.0/16","10.1.1.0/24","The default route","The route with the lowest metric"],c:1,e:"Longest prefix match is evaluated first. The /24 is the most specific match, so it wins before administrative distance or metric are considered."},
{id:"u7l2-3",t:"u7l2",q:"Which routing protocol is used between autonomous systems on the internet?",a:["OSPF","EIGRP","RIP","BGP"],c:3,e:"Border Gateway Protocol is the exterior gateway protocol that exchanges routes between autonomous systems."},
{id:"u7l2-4",t:"u7l2",q:"Which routing protocol uses hop count as its metric and is limited to 15 hops?",a:["OSPF","RIP","BGP","IS-IS"],c:1,e:"RIP counts hops with a maximum of 15. OSPF uses cost, EIGRP a composite metric, and BGP path attributes."},
{id:"u7l2-5",t:"u7l2",q:"Which statement describes a link-state routing protocol?",a:["Each router knows only what its neighbors advertise","Each router builds a complete map of the area and computes shortest paths","It sends its full routing table every 30 seconds","It is used only between autonomous systems"],c:1,e:"Link-state protocols such as OSPF flood link information so every router has the full topology and runs a shortest-path algorithm."},
{id:"u7l2-6",t:"u7l2",q:"Which is the default administrative distance of OSPF?",a:["1","90","110","120"],c:2,e:"OSPF is 110. EIGRP is 90, RIP is 120, static is 1, connected is 0."},
{id:"u7l2-7",t:"u7l2",q:"An organization with two internet providers wants to influence which provider is used for inbound and outbound traffic based on policy. Which protocol is designed for this?",a:["RIP","OSPF","BGP","VRRP"],c:2,e:"BGP is path-vector and policy based, which is why multihomed organizations use it to control traffic across providers."},
{id:"u7l2-8",t:"u7l2",q:"Two routes to the same prefix are learned from the same OSPF process. How does the router choose between them?",a:["Lowest administrative distance","Lowest metric (cost)","Longest prefix","Highest router ID"],c:1,e:"When prefix and administrative distance are equal, the metric decides. For OSPF that is cost."},

// u7l3 NAT and FHRP
{id:"u7l3-1",t:"u7l3",q:"A small office with 50 internal hosts reaches the internet through a single public IP address. Which technology makes this possible?",a:["Static NAT","PAT, also called NAT overload","VLSM","DHCP relay"],c:1,e:"Port address translation maps many private addresses to one public address by tracking source port numbers."},
{id:"u7l3-2",t:"u7l3",q:"Which protocol allows two routers to share one virtual gateway IP address so hosts keep connectivity if the primary router fails, and is an open standard?",a:["HSRP","VRRP","BGP","LACP"],c:1,e:"VRRP is the open-standard first hop redundancy protocol. HSRP is Cisco proprietary."},
{id:"u7l3-3",t:"u7l3",q:"An internal web server at 10.0.0.25 must be reachable from the internet at a fixed public address. Which NAT type is appropriate?",a:["Static NAT","Dynamic NAT","PAT","NAT64"],c:0,e:"Static NAT provides a permanent one-to-one mapping between a private and a public address, suitable for publishing a server."},
{id:"u7l3-4",t:"u7l3",q:"In NAT terminology, what is the inside global address?",a:["The private address of an internal host","The public address that represents an internal host to the outside","The address of the ISP router","The address of an external web server"],c:1,e:"Inside local is the private address before translation; inside global is its public translation."},
{id:"u7l3-5",t:"u7l3",q:"Hosts use 192.168.1.1 as their gateway. Two routers participate in an FHRP with that address as the virtual IP. What happens when the active router fails?",a:["Hosts must be reconfigured with the standby router's address","The standby router takes over the virtual IP and MAC, and hosts continue without change","All hosts lose connectivity until the router is replaced","DHCP issues new gateway addresses"],c:1,e:"FHRPs make failover transparent. The standby assumes the virtual address and hosts keep using the same gateway."},
{id:"u7l3-6",t:"u7l3",q:"A router's single WAN interface must carry three provider circuits, each on its own VLAN tag with its own IP address. What is configured?",a:["Three physical interfaces","Three subinterfaces","Three SVIs","Three loopbacks"],c:1,e:"Subinterfaces split one physical interface into tagged logical interfaces, each with its own addressing."},

// u7l4 Appliances
{id:"u7l4-1",t:"u7l4",q:"A security team wants a device placed inline that can automatically drop malicious packets rather than only generating alerts. Which device meets this requirement?",a:["IDS","IPS","Proxy server","Load balancer"],c:1,e:"An IPS sits in the traffic path and blocks in real time. An IDS is passive and only alerts."},
{id:"u7l4-2",t:"u7l4",q:"A company's web application runs on six identical servers. Which device distributes incoming client connections across them and removes a failed server from rotation?",a:["Proxy server","Load balancer","IDS","VPN concentrator"],c:1,e:"A load balancer spreads connections across a server pool using health checks to route around failures."},
{id:"u7l4-3",t:"u7l4",q:"Servers need block-level access to shared storage that appears to each server as a local disk. Which solution fits?",a:["NAS","SAN","CDN","Proxy"],c:1,e:"A storage area network provides block-level storage over iSCSI or Fibre Channel. NAS provides file-level shares."},
{id:"u7l4-4",t:"u7l4",q:"A global company wants users in every region to download its videos from a nearby cache instead of the origin data center. Which solution provides this?",a:["Load balancer","Content delivery network","Reverse proxy in the data center","NAS"],c:1,e:"A CDN caches content on distributed edge servers so users fetch it from the closest node."},
{id:"u7l4-5",t:"u7l4",q:"Which device caches web content, filters URLs, and hides internal client addresses when users browse the internet?",a:["Forward proxy","Load balancer","IPS","Router"],c:0,e:"A forward proxy makes requests on behalf of internal clients, providing caching, filtering, and address hiding."},
{id:"u7l4-6",t:"u7l4",q:"Voice traffic must be prioritized over file downloads when a WAN link is congested. Which function is required?",a:["NAT","QoS","STP","DHCP"],c:1,e:"Quality of service classifies and prioritizes traffic so latency-sensitive applications get through during congestion."},
{id:"u7l4-7",t:"u7l4",q:"Which device terminates many encrypted tunnels from remote workers at the network edge?",a:["VPN concentrator","Wireless LAN controller","Load balancer","Media converter"],c:0,e:"A VPN concentrator is purpose-built to terminate large numbers of VPN connections."},
{id:"u7l4-8",t:"u7l4",q:"A device monitors a copy of network traffic from a mirror port and sends an alert when it detects an attack signature but cannot stop the traffic. What is it?",a:["IPS","IDS","Firewall","Proxy"],c:1,e:"An intrusion detection system is passive and out of band. It detects and alerts but does not block."},

// u7l5 Cloud
{id:"u7l5-1",t:"u7l5",q:"A company rents virtual machines from a cloud provider and installs and manages its own operating systems and applications while the provider manages the hardware and hypervisors. Which service model is this?",a:["SaaS","PaaS","IaaS","DaaS"],c:2,e:"Infrastructure as a service provides compute, storage, and network; the customer manages everything from the OS up."},
{id:"u7l5-2",t:"u7l5",q:"Developers deploy code to a cloud platform that manages the operating system, runtime, and scaling for them. Which service model is this?",a:["IaaS","PaaS","SaaS","Private cloud"],c:1,e:"Platform as a service provides the runtime environment; developers supply only the application code."},
{id:"u7l5-3",t:"u7l5",q:"Which cloud construct applies stateful firewall rules to the network interface of an individual virtual machine?",a:["Network security list","Network security group","Internet gateway","VPC"],c:1,e:"Security groups attach to instances or their interfaces. Network security lists or network ACLs apply to whole subnets and are stateless."},
{id:"u7l5-4",t:"u7l5",q:"Virtual machines in a private cloud subnet must download updates from the internet but must not be reachable from the internet. Which component provides this?",a:["Internet gateway","NAT gateway","Direct connect","VPN concentrator"],c:1,e:"A NAT gateway allows outbound connections from private subnets while blocking unsolicited inbound traffic."},
{id:"u7l5-5",t:"u7l5",q:"An application automatically adds servers during peak hours and removes them at night, and the company pays only for what runs. Which cloud characteristic is this?",a:["Multitenancy","Elasticity","Data locality","Redundancy"],c:1,e:"Elasticity is automatic scaling up and down with demand. Scalability is the ability to grow; elasticity adds the automatic shrink."},
{id:"u7l5-6",t:"u7l5",q:"A company keeps its database on premises but runs its web front end in a public cloud, connected by a VPN. Which deployment model is this?",a:["Public","Private","Hybrid","Community"],c:2,e:"Hybrid cloud combines on-premises or private resources with public cloud services."},
{id:"u7l5-7",t:"u7l5",q:"Which term describes running routers, firewalls, and load balancers as software instances instead of dedicated hardware appliances?",a:["NFV","VPC","SDN","IaC"],c:0,e:"Network functions virtualization delivers network functions as virtual machines or containers."},
{id:"u7l5-8",t:"u7l5",q:"A company needs predictable bandwidth and latency to its cloud provider and is willing to pay for a dedicated circuit. Which connectivity option fits?",a:["Site-to-site VPN over the internet","Direct connect private link","Clientless VPN","Satellite"],c:1,e:"A direct connection is a dedicated private circuit to the provider with guaranteed performance, unlike a VPN over the public internet."},

// u7l6 Modern networking
{id:"u7l6-1",t:"u7l6",q:"Which security model assumes no user or device is trusted by default, even inside the network perimeter, and verifies every access request?",a:["Defense in depth","Zero trust","Screened subnet","Implicit trust"],c:1,e:"Zero trust means never trust, always verify, with policy-based authentication and least privilege for every request."},
{id:"u7l6-2",t:"u7l6",q:"In software-defined networking, which plane makes forwarding decisions and is centralized in a controller?",a:["Data plane","Control plane","Management plane","Physical plane"],c:1,e:"SDN separates the control plane, now in a controller, from the data plane that forwards packets on each device."},
{id:"u7l6-3",t:"u7l6",q:"A branch office uses a broadband connection and an LTE connection, and a central controller steers each application over the best path in real time. Which technology is this?",a:["MPLS","SD-WAN","VXLAN","BGP"],c:1,e:"SD-WAN is application aware and transport agnostic, using policy from a central controller to choose paths."},
{id:"u7l6-4",t:"u7l6",q:"Which technology encapsulates Layer 2 frames in UDP so a VLAN can extend across a routed network between data centers?",a:["802.1Q","VXLAN","GRE","LACP"],c:1,e:"VXLAN stretches Layer 2 over Layer 3 with a 24-bit identifier supporting about 16 million segments."},
{id:"u7l6-5",t:"u7l6",q:"A network team stores device configurations as templates in a version control system and uses automation to detect and correct devices whose running configuration has diverged. What is this practice?",a:["Infrastructure as code","Port mirroring","Change advisory board","Out-of-band management"],c:0,e:"Infrastructure as code manages configuration in files under source control, deploying automatically and correcting configuration drift."},
{id:"u7l6-6",t:"u7l6",q:"A new SD-WAN appliance shipped to a branch downloads its complete configuration automatically when connected, with no on-site technician. Which feature is this?",a:["Zero-touch provisioning","Split tunneling","Port security","Route summarization"],c:0,e:"Zero-touch provisioning lets devices self-configure from a central controller when first powered on."},
{id:"u7l6-7",t:"u7l6",q:"Which cloud-delivered service combines SD-WAN networking with security functions such as secure web gateway, firewall, and zero trust access for remote users and branches?",a:["SASE","VPC","NFV","IaC"],c:0,e:"Secure access service edge merges networking and security into one cloud service. SSE is the security portion without SD-WAN."},
{id:"u7l6-8",t:"u7l6",q:"In an SDN architecture, which interface do applications use to request services from the controller?",a:["Southbound API","Northbound API","Console port","Trunk port"],c:1,e:"Northbound APIs connect applications to the controller. Southbound APIs connect the controller to the network devices."},

// u7l7 Physical installations
{id:"u7l7-1",t:"u7l7",q:"Which location in a building houses the provider's demarcation point and the core network equipment, and connects to the smaller wiring closets on each floor?",a:["IDF","MDF","PDU","Patch panel"],c:1,e:"The main distribution frame is the primary wiring room with the demarc. IDFs are the per-floor closets that connect back to it."},
{id:"u7l7-2",t:"u7l7",q:"How tall is one rack unit?",a:["1 inch","1.75 inches","2.5 inches","4 inches"],c:1,e:"A rack unit, 1U, is 1.75 inches (44.45 mm). Equipment height is described in multiples of U."},
{id:"u7l7-3",t:"u7l7",q:"A server room's racks are arranged with all equipment fronts facing one aisle. What is the purpose of this layout?",a:["To simplify cable labeling","To create hot and cold aisles so intake and exhaust air do not mix","To reduce the number of PDUs required","To comply with plenum cable rules"],c:1,e:"Equipment draws cool air from the front and exhausts hot air to the rear. Hot and cold aisle containment keeps the two separate and improves cooling."},
{id:"u7l7-4",t:"u7l7",q:"Which device provides battery power to keep equipment running through a short outage and gives time for a clean shutdown or generator start?",a:["PDU","UPS","Surge protector","Inverter"],c:1,e:"An uninterruptible power supply bridges outages with battery power and conditions the incoming power."},
{id:"u7l7-5",t:"u7l7",q:"What is the recommended relative humidity range for a network equipment room?",a:["10 to 20 percent","40 to 60 percent","70 to 80 percent","90 to 100 percent"],c:1,e:"Around 40 to 60 percent balances the static discharge risk of dry air against the condensation risk of humid air."},
{id:"u7l7-6",t:"u7l7",q:"Horizontal cabling from wall jacks terminates in the wiring closet on which component, so that permanent cables are never re-terminated when connections change?",a:["PDU","Patch panel","UPS","Media converter"],c:1,e:"Patch panels terminate the permanent runs; short patch cords connect panel ports to switch ports and can be moved freely."},
{id:"u7l7-7",t:"u7l7",q:"A switch is installed in a rack where air flows from the cold aisle at the rear to the hot aisle at the front. Which switch airflow option should be selected?",a:["Port-side exhaust","Port-side intake","Side-to-side","Any; airflow does not matter for switches"],c:0,e:"If the switch ports face the hot aisle at the front, air must exit on the port side, so a port-side exhaust model matches the room's airflow."},
{id:"u7l7-8",t:"u7l7",q:"Which fire suppression approach is appropriate for a room full of network equipment?",a:["Water sprinklers only","A clean agent or inert gas system","Foam","No suppression is needed"],c:1,e:"Clean agent and gas systems extinguish fires without destroying electronics. Water is a last resort in equipment rooms."}
);
