// NetPlus Academy question bank: unit 9 (troubleshooting).
window.FRA = window.FRA || {};
FRA.questions = FRA.questions || [];
FRA.questions.push(
// u9l1
{id:"u9l1-1",t:"u9l1",q:"A technician has tested a theory and confirmed the actual cause of a network problem. According to the troubleshooting methodology, what is the NEXT step?",a:["Implement the solution","Establish a plan of action and identify potential effects","Verify full system functionality","Document findings"],c:1,e:"After confirming the cause, plan the fix and consider its side effects before implementing."},
{id:"u9l1-2",t:"u9l1",q:"Which is the FIRST step of the troubleshooting methodology?",a:["Establish a theory of probable cause","Test the theory","Identify the problem","Document findings"],c:2,e:"Identifying the problem, including gathering information and determining what changed, comes first."},
{id:"u9l1-3",t:"u9l1",q:"A technician has implemented a fix for a routing issue. What should be done NEXT?",a:["Document the outcome","Escalate to the vendor","Establish a new theory","Verify full system functionality and implement preventive measures"],c:3,e:"After implementation comes verification and prevention. Documentation is the final step."},
{id:"u9l1-4",t:"u9l1",q:"While identifying a problem, a technician learns that a firewall rule was changed the previous evening. Which methodology action does this represent?",a:["Determining if anything has changed","Testing the theory","Implementing the solution","Escalating"],c:0,e:"Asking what changed is part of identifying the problem and often points directly at the cause."},
{id:"u9l1-5",t:"u9l1",q:"A technician's theory is that a failing cable causes a user's disconnects. The technician's next action should be to:",a:["Replace every cable on the floor","Test the theory, for example by swapping the cable or testing it","Document the cable failure","Order new switches"],c:1,e:"Step three is testing the theory to determine the cause before planning or implementing changes."},
{id:"u9l1-6",t:"u9l1",q:"A help desk technician determines that fixing a problem requires changes to the core router, which only senior engineers may modify. What should the technician do?",a:["Make the change anyway","Document that the problem cannot be fixed","Escalate the issue","Reboot the core router"],c:2,e:"When a fix is beyond your authority or ability, the methodology calls for escalation."},
{id:"u9l1-7",t:"u9l1",q:"A technician begins troubleshooting by checking whether the host can ping its gateway, then moves up or down the OSI layers depending on the result. Which approach is this?",a:["Top-to-bottom","Bottom-to-top","Trial and error","Divide and conquer"],c:3,e:"Divide and conquer starts in the middle of the stack, typically Layer 3, and narrows the search from there."},
{id:"u9l1-8",t:"u9l1",q:"Several users report three unrelated symptoms at once. How should the technician handle them according to the methodology?",a:["Approach multiple problems individually","Assume one root cause and fix it","Ignore the least severe symptom","Escalate all three immediately"],c:0,e:"Part of identifying the problem is treating separate problems separately rather than assuming a single cause."},

// u9l2
{id:"u9l2-1",t:"u9l2",q:"A switch interface connected to another switch shows a rapidly increasing CRC error counter. What is the MOST likely cause?",a:["An exhausted DHCP scope","An incorrect VLAN assignment","A damaged cable, interference, or a duplex mismatch","A misconfigured default gateway"],c:2,e:"CRC errors mean frames arrived corrupted, which points to Layer 1 or 2 issues such as cabling, EMI, or duplex mismatch."},
{id:"u9l2-2",t:"u9l2",q:"A new fiber link between two switches shows no light received at either end. Both transceivers and the fiber test good. What is the MOST likely cause?",a:["Attenuation","MTU mismatch","Wrong VLAN","Transmit and receive strands are reversed"],c:3,e:"If TX at one end is connected to TX at the other, neither receiver sees light. Swap the strands at one end."},
{id:"u9l2-3",t:"u9l2",q:"A switch port shows err-disabled. What must happen before the port carries traffic again?",a:["The underlying violation must be fixed and the port cleared by an administrator","Nothing; it recovers automatically after 60 seconds","The switch must be rebooted","The cable category must be upgraded"],c:0,e:"Error-disabled is a protective shutdown for violations such as port security or BPDU guard. Fix the cause, then re-enable the port."},
{id:"u9l2-4",t:"u9l2",q:"An IP camera powers on, then reboots repeatedly when it starts recording. The switch port is 802.3af. What is the MOST likely problem?",a:["Wrong VLAN","The camera needs more power than the port's PoE standard provides","DNS failure","STP blocking"],c:1,e:"A device that needs PoE+ on a PoE port gets enough power to boot but not to run under load. This is an incorrect PoE standard."},
{id:"u9l2-5",t:"u9l2",q:"A workstation cable was run alongside fluorescent light ballasts and the user experiences intermittent errors. What is the cause?",a:["Crosstalk","Attenuation","Electromagnetic interference","Improper termination"],c:2,e:"EMI from ballasts, motors, and power lines induces noise. Reroute or use shielded cable."},
{id:"u9l2-6",t:"u9l2",q:"A cable tester reports a split pair on a newly terminated run. What does this indicate?",a:["The cable exceeds 100 meters","The fiber polish is mismatched","The connector is the wrong type","Wires from different pairs were placed in positions that should hold one twisted pair"],c:3,e:"A split pair passes continuity tests but breaks the twisting that cancels noise, causing crosstalk and errors."},
{id:"u9l2-7",t:"u9l2",q:"An interface shows many giant frames. What is the likely cause?",a:["A jumbo frame or MTU configuration mismatch","Collisions","Wrong wiring standard","A rogue DHCP server"],c:0,e:"Giants are frames larger than the interface's MTU, typically from a device sending jumbo frames to a port that does not accept them."},
{id:"u9l2-8",t:"u9l2",q:"The far end of a link accepts only vendor-branded optics and refuses the module a technician installed. What kind of problem is this?",a:["Attenuation","Transceiver mismatch","Duplex mismatch","Crosstalk"],c:1,e:"Transceiver mismatches include incompatible speeds, wavelengths, and vendor-locked modules that the switch rejects."},
{id:"u9l2-9",t:"u9l2",q:"A port shows status administratively down. What is the fix?",a:["Replace the cable","Clear the err-disabled state","Issue the command to bring the interface up; it was shut down by configuration","Change the transceiver"],c:2,e:"Administratively down means an administrator disabled the port with a shutdown command. Re-enable it in configuration."},

// u9l3
{id:"u9l3-1",t:"u9l3",q:"After a technician connects two switches with an extra cable, all users on the floor lose connectivity, switch CPUs spike, and MAC addresses flap between ports. What is happening?",a:["DHCP scope exhaustion","An ACL is blocking traffic","A DNS outage","A Layer 2 loop and broadcast storm"],c:3,e:"A redundant link without functioning spanning tree creates a loop. Broadcasts multiply until the switches are overwhelmed."},
{id:"u9l3-2",t:"u9l3",q:"Two workstations on a subnet report intermittent connectivity, and one shows an address conflict warning. What is the MOST likely cause?",a:["Duplicate IP address","Wrong default gateway","Bad transceiver","MTU mismatch"],c:0,e:"Address conflict warnings and alternating connectivity between two hosts indicate a duplicate IP, often a static address inside a DHCP scope."},
{id:"u9l3-3",t:"u9l3",q:"A host at 192.168.1.50 with mask 255.255.255.0 can reach some hosts on its subnet but not others in the 192.168.1.128 to .254 range. The rest of the subnet uses 255.255.255.128. What is wrong?",a:["The switch port is in the wrong VLAN","The host has an incorrect subnet mask","DNS is misconfigured","The default gateway is down"],c:1,e:"A mask mismatch makes the host believe addresses are local when they are not, or vice versa, so it fails to route correctly to part of the range."},
{id:"u9l3-4",t:"u9l3",q:"Users can ping a server and reach it by web browser, but a new application on TCP port 8443 fails from the user subnet only. What is the MOST likely cause?",a:["DNS failure","STP blocking","An ACL or firewall rule blocking that port","Duplicate IP address"],c:2,e:"When general connectivity works but one specific port fails from one location, a filtering rule is blocking it."},
{id:"u9l3-5",t:"u9l3",q:"Traffic to a remote network takes an unexpected slow path even though a faster route exists. Which route selection factor should the technician check FIRST?",a:["The PoE budget","The MAC address table","The DHCP lease time","Whether a more specific prefix or lower administrative distance route exists for that destination"],c:3,e:"Routers prefer the longest prefix, then lowest administrative distance, then metric. An unexpected path usually means a more preferred route entry exists."},
{id:"u9l3-6",t:"u9l3",q:"Users in one building lose connectivity every morning, and their PCs show 169.254 addresses while afternoon arrivals are fine after some leave. What is the cause?",a:["DHCP address pool exhaustion","Rogue DHCP server","STP loop","Wrong native VLAN"],c:0,e:"The scope runs out during peak occupancy. Widen the pool or shorten the lease."},
{id:"u9l3-7",t:"u9l3",q:"The core switch should be the spanning tree root but an access switch has taken the role, and traffic between buildings crosses a slow link. What is the fix?",a:["Disable STP","Lower the bridge priority on the core switch","Enable jumbo frames","Add a default route"],c:1,e:"The lowest bridge ID wins the root election. Set a lower priority on the intended root."},
{id:"u9l3-8",t:"u9l3",q:"A host receives a valid address from DHCP but gets a default gateway that does not exist. The authorized DHCP server's configuration is correct. What should be checked?",a:["The cable length","The host's MAC address","For a rogue DHCP server on the segment","The spanning tree root"],c:2,e:"Correct server configuration plus wrong client settings means another server is answering. Enable DHCP snooping."},
{id:"u9l3-9",t:"u9l3",q:"A technician verifies that a host's IP, mask, and gateway are correct and that it can ping the gateway and internet addresses, yet websites do not load by name. What should be checked?",a:["The cable category","The switch's spanning tree state","The PoE budget","The DNS server configuration on the host"],c:3,e:"Connectivity by IP with no name resolution isolates the problem to DNS."},

// u9l4
{id:"u9l4-1",t:"u9l4",q:"Users in one area report slow Wi-Fi despite full signal strength. A survey shows three nearby access points all operating on channel 6. What is the MOST likely cause?",a:["Channel overlap causing co-channel interference","Attenuation from walls","Weak encryption","Roaming misconfiguration"],c:0,e:"Strong signal rules out coverage. APs sharing a channel must share airtime, collapsing throughput. Spread them across 1, 6, and 11."},
{id:"u9l4-2",t:"u9l4",q:"A 10 Gbps server farm connects to users through a single 1 Gbps uplink that stays at 100 percent utilization. Which term describes the uplink?",a:["Jitter","Bottleneck","Latency","Attenuation"],c:1,e:"A bottleneck is the slowest element in a path that limits everything behind it."},
{id:"u9l4-3",t:"u9l4",q:"Voice calls have gaps and robotic audio, but file transfers and web browsing perform normally. Which two conditions are the MOST likely culprits?",a:["DNS and DHCP failures","Attenuation and crosstalk","Jitter and packet loss","VLAN and STP misconfiguration"],c:2,e:"Real-time voice is sensitive to variable delay and lost packets, which TCP-based transfers hide through retransmission."},
{id:"u9l4-4",t:"u9l4",q:"Laptops stay connected to a distant access point with a weak signal even when they are next to another AP. What is the MOST likely cause?",a:["An STP loop","DHCP scope exhaustion","Wrong PoE standard","Roaming misconfiguration such as excessive AP transmit power or too little cell overlap"],c:3,e:"Clients decide when to roam. Too-high power or poor overlap makes them cling to the original AP. Tune power and overlap."},
{id:"u9l4-5",t:"u9l4",q:"A microwave oven in a break room causes wireless clients nearby to disconnect several times an hour. Which fix is BEST?",a:["Move the clients to the 5 GHz band or a different 2.4 GHz channel","Increase the DHCP lease time","Enable jumbo frames","Replace the patch cables"],c:0,e:"Microwaves radiate in the 2.4 GHz band. Moving to 5 GHz or away from the affected channel avoids the interference."},
{id:"u9l4-6",t:"u9l4",q:"Wireless coverage is fine in the office but a newly occupied storage room has no signal. What is the problem called, and what is the fix?",a:["Co-channel interference; change channels","Insufficient coverage; add an access point or mesh node","Jitter; add QoS","Attenuation; use Cat 6A"],c:1,e:"A dead spot is a coverage problem solved by adding or repositioning APs."},
{id:"u9l4-7",t:"u9l4",q:"A WAN link's round-trip time rose from 40 ms to 400 ms during business hours with no loss. Interface utilization is near 100 percent. What is causing the added delay?",a:["A rogue DHCP server","Duplex mismatch","Congestion causing queuing delay","MAC flooding"],c:2,e:"When a link is saturated, packets wait in queues, adding latency. This is congestion."},
{id:"u9l4-8",t:"u9l4",q:"Which action MOST directly addresses jitter for voice traffic on a congested link?",a:["Increase the DHCP lease","Change the subnet mask","Enable port mirroring","Configure QoS to prioritize voice"],c:3,e:"QoS gives voice packets priority in queues so their delay stays consistent even under load."},

// u9l5
{id:"u9l5-1",t:"u9l5",q:"A technician needs to find at which hop along the path to a remote server packets are being lost. Which tool is BEST?",a:["ping","traceroute or tracert","nslookup","arp"],c:1,e:"Traceroute shows every hop and its response time, so you can see where loss begins. Ping only tests end to end."},
{id:"u9l5-2",t:"u9l5",q:"Which command displays the cached IP-address-to-MAC-address mappings on a Windows host?",a:["netstat -r","ipconfig /all","arp -a","nslookup"],c:2,e:"arp -a shows the ARP cache. netstat -r shows routes, ipconfig /all shows adapter configuration, nslookup queries DNS."},
{id:"u9l5-3",t:"u9l5",q:"A technician wants to see which switch port a specific server's MAC address was learned on. Which command is appropriate?",a:["show ip route","show power","show vlan","show mac-address-table"],c:3,e:"The MAC address table lists learned addresses with their ports and VLANs."},
{id:"u9l5-4",t:"u9l5",q:"Which tool queries a specific DNS server for a particular record type to verify that a record is correct?",a:["nslookup or dig","ping","tcpdump","arp"],c:0,e:"nslookup and dig send DNS queries directly and let you choose the server and record type."},
{id:"u9l5-5",t:"u9l5",q:"A Linux administrator needs to capture packets on a server from the command line for later analysis. Which tool is appropriate?",a:["netstat","tcpdump","nmap","traceroute"],c:1,e:"tcpdump captures traffic at the command line and can write it to a file for a protocol analyzer."},
{id:"u9l5-6",t:"u9l5",q:"Which command shows the active connections and listening ports on a host?",a:["ipconfig","arp","netstat","tracert"],c:2,e:"netstat displays connections, listening sockets, and with -r the routing table."},
{id:"u9l5-7",t:"u9l5",q:"A technician needs to identify which device and port is on the other end of a switch uplink without tracing the cable. Which protocol provides this information?",a:["STP","SNMP traps","DHCP","LLDP or CDP"],c:3,e:"Link Layer Discovery Protocol and Cisco Discovery Protocol advertise device identity and port information to directly connected neighbors."},
{id:"u9l5-8",t:"u9l5",q:"Which command-line tool scans a subnet for live hosts and reports which TCP ports are open on each?",a:["nmap","ping","arp","dig"],c:0,e:"nmap performs host discovery and port scanning. It must be used only with authorization."},
{id:"u9l5-9",t:"u9l5",q:"A user's PC has stale DNS information after a server move. Which command clears the local resolver cache on Windows?",a:["ipconfig /release","ipconfig /flushdns","arp -d","netstat -an"],c:1,e:"ipconfig /flushdns clears cached DNS entries so new lookups are performed."},
{id:"u9l5-10",t:"u9l5",q:"Which switch command shows a port's speed, duplex, error counters, and CRC count?",a:["show mac-address-table","show vlan","show interface","show config"],c:2,e:"show interface reports link status, negotiated speed and duplex, and error statistics."},

// u9l6
{id:"u9l6-1",t:"u9l6",q:"A technician must identify which wall jack in an office corresponds to a specific port on the patch panel. Which tool should be used?",a:["Cable tester","Wi-Fi analyzer","Toner and probe","Visual fault locator"],c:2,e:"A toner sends a signal down the cable and the probe finds it at the other end."},
{id:"u9l6-2",t:"u9l6",q:"After terminating a new run, a technician wants to confirm the pinout is correct and there are no opens or shorts. Which tool is appropriate?",a:["Toner and probe","Loopback plug","Spectrum analyzer","Cable tester"],c:3,e:"A cable tester verifies wiring, continuity, opens, shorts, and split pairs."},
{id:"u9l6-3",t:"u9l6",q:"A fiber link is down and a technician wants to see whether the strand is broken or tightly bent somewhere in the closet. Which tool helps?",a:["Visual fault locator","Toner and probe","Multimeter","Cable certifier"],c:0,e:"A visual fault locator sends visible red light through the fiber so breaks and bends glow."},
{id:"u9l6-4",t:"u9l6",q:"A security team needs to capture all traffic on a link without depending on the switch's mirror port. Which device provides this?",a:["Load balancer","Network tap","Media converter","PoE injector"],c:1,e:"A passive tap sits inline and copies traffic to an analyzer independent of switch configuration."},
{id:"u9l6-5",t:"u9l6",q:"A technician needs to see which channels nearby access points use and how strong their signals are before choosing channels for new APs. Which tool is appropriate?",a:["Cable certifier","OTDR","Wi-Fi analyzer","Toner"],c:2,e:"A Wi-Fi analyzer shows SSIDs, channels, and signal strength of surrounding networks."},
{id:"u9l6-6",t:"u9l6",q:"A customer wants documented proof that a new Cat 6A installation meets the category's performance standard. Which tool produces this?",a:["Basic cable tester","Multimeter","Toner and probe","Cable certifier"],c:3,e:"A certifier measures performance parameters against the standard and prints a certification report."},
{id:"u9l6-7",t:"u9l6",q:"Which tool locates a break in a long fiber run and reports the distance to the fault?",a:["OTDR","Visual fault locator","Light meter","Toner"],c:0,e:"An optical time-domain reflectometer measures reflections to locate faults and losses by distance."},
{id:"u9l6-8",t:"u9l6",q:"Wireless clients experience interference that does not appear as another Wi-Fi network. Which tool reveals non-Wi-Fi sources of radio energy?",a:["Wi-Fi analyzer","Spectrum analyzer","Cable tester","Protocol analyzer"],c:1,e:"A spectrum analyzer shows all RF energy in a band, including microwaves and other non-802.11 sources that a Wi-Fi analyzer cannot decode."}
);
