// NetPlus Academy question bank: unit 8 lessons 7-9 (security concepts, attacks, defense).
window.FRA = window.FRA || {};
FRA.questions = FRA.questions || [];
FRA.questions.push(
// u8l7
{id:"u8l7-1",t:"u8l7",q:"A user signs in with a password and then enters a six-digit code from an authenticator app on their phone. Which factor types are in use?",a:["Something you know and something you are","Something you know and something you have","Something you have and somewhere you are","Two instances of something you know"],c:1,e:"The password is knowledge; the TOTP app on a possessed device is possession. A fingerprint would be inherence."},
{id:"u8l7-2",t:"u8l7",q:"Which AAA protocol encrypts the entire packet payload, separates authentication from authorization, and is commonly used for administering network devices?",a:["RADIUS","LDAP","TACACS+","SAML"],c:2,e:"TACACS+ uses TCP 49, encrypts the whole payload, and supports per-command authorization. RADIUS encrypts only the password."},
{id:"u8l7-3",t:"u8l7",q:"Which principle states that users should be granted only the access required to perform their job?",a:["Defense in depth","Implicit deny","Separation of duties","Least privilege"],c:3,e:"Least privilege limits each account to the minimum permissions needed."},
{id:"u8l7-4",t:"u8l7",q:"An unpatched service on a server allows remote code execution. In risk terminology, what is the unpatched service?",a:["A vulnerability","A threat","An exploit","A risk"],c:0,e:"A vulnerability is a weakness. A threat could act on it, an exploit is the method used, and risk is the likelihood and impact."},
{id:"u8l7-5",t:"u8l7",q:"Which component of the CIA triad is addressed by hashing files to detect unauthorized modification?",a:["Confidentiality","Integrity","Availability","Authentication"],c:1,e:"Integrity ensures data has not been altered. Hashes and signatures detect changes."},
{id:"u8l7-6",t:"u8l7",q:"Users see a browser warning when connecting to an internal management interface because its certificate is not signed by a trusted authority. What kind of certificate is in use?",a:["Wildcard certificate","Expired root certificate","Self-signed certificate","Extended validation certificate"],c:2,e:"A self-signed certificate is not issued by a trusted CA, so browsers warn unless it is manually trusted."},
{id:"u8l7-7",t:"u8l7",q:"Which protocol lets a user authenticate once to an identity provider and then access multiple web applications without logging in again?",a:["RADIUS","SNMP","TACACS+","SAML"],c:3,e:"SAML is a common standard for web single sign-on between an identity provider and service providers."},
{id:"u8l7-8",t:"u8l7",q:"A security team deploys a deliberately vulnerable server that holds no real data to observe attacker techniques. What is this system called?",a:["Honeypot","Jump box","Screened subnet","Proxy"],c:0,e:"A honeypot attracts attackers so their methods can be studied. A honeynet is a network of them."},
{id:"u8l7-9",t:"u8l7",q:"A company that processes credit card transactions must follow which compliance standard?",a:["GDPR","PCI DSS","HIPAA","SOX"],c:1,e:"The Payment Card Industry Data Security Standard governs card payment data."},
{id:"u8l7-10",t:"u8l7",q:"A regulation requires that customer records for a certain country be stored on servers physically located within that country. Which concept is this?",a:["Multitenancy","Least privilege","Data locality","Geofencing"],c:2,e:"Data locality or data sovereignty rules dictate where data may physically reside."},
{id:"u8l7-11",t:"u8l7",q:"Which authentication protocol is typically used by wireless access points and VPN gateways to verify network users against a central server on UDP ports 1812 and 1813?",a:["TACACS+","LDAPS","Kerberos","RADIUS"],c:3,e:"RADIUS is the standard network access authentication protocol, using UDP 1812 for authentication and 1813 for accounting."},
{id:"u8l7-12",t:"u8l7",q:"Which access control approach assigns permissions to job functions such as help desk or network admin and then places users in those groups?",a:["Role-based access control","Discretionary access control","Mandatory access control","Rule-based access control"],c:0,e:"RBAC ties permissions to roles rather than to individual users."},

// u8l8
{id:"u8l8-1",t:"u8l8",q:"An attacker sets up a wireless access point broadcasting the same SSID as the corporate network so that users connect to it instead. What is this attack called?",a:["Rogue DHCP server","Deauthentication attack","Evil twin","Phishing"],c:2,e:"An evil twin impersonates a legitimate SSID to capture traffic and credentials."},
{id:"u8l8-2",t:"u8l8",q:"An attacker sends forged ARP replies so that traffic between a user and the default gateway passes through the attacker's machine. What is this attack called?",a:["DNS poisoning","VLAN hopping","MAC flooding","ARP poisoning enabling an on-path attack"],c:3,e:"ARP spoofing maps the gateway's IP to the attacker's MAC, inserting the attacker into the path."},
{id:"u8l8-3",t:"u8l8",q:"A switch suddenly begins forwarding all frames out every port, allowing an attacker to sniff traffic. Which attack overflowed the switch's address table?",a:["MAC flooding","VLAN hopping","ARP poisoning","Deauthentication"],c:0,e:"MAC flooding fills the MAC table with fake entries so the switch falls back to flooding like a hub."},
{id:"u8l8-4",t:"u8l8",q:"An attacker crafts frames with two 802.1Q tags so that the second switch forwards them into a VLAN the attacker is not a member of. What is this technique?",a:["Switch spoofing","Double tagging VLAN hopping","MAC spoofing","Rogue DHCP"],c:1,e:"Double tagging exploits the native VLAN so the inner tag reaches a different VLAN. Switch spoofing is the other VLAN hopping method."},
{id:"u8l8-5",t:"u8l8",q:"Thousands of compromised devices send traffic to a company's web server until it cannot respond to legitimate users. What is this attack?",a:["On-path attack","DNS poisoning","DDoS","Evil twin"],c:2,e:"A distributed denial of service uses many sources, typically a botnet, to overwhelm a target."},
{id:"u8l8-6",t:"u8l8",q:"Users typing a bank's web address are sent to a look-alike site because the resolver's cache holds a false record. What is this attack?",a:["ARP spoofing","Tailgating","MAC flooding","DNS poisoning"],c:3,e:"DNS cache poisoning inserts forged records so names resolve to attacker-controlled addresses."},
{id:"u8l8-7",t:"u8l8",q:"An employee plugs a personal wireless router into a conference room jack for convenience. What security issue does this create?",a:["A rogue access point","An evil twin","A honeypot","A screened subnet"],c:0,e:"Any unauthorized AP is a rogue access point and provides an unmanaged path into the network."},
{id:"u8l8-8",t:"u8l8",q:"A caller claiming to be from IT convinces a receptionist to reveal her password. Which category of attack is this?",a:["Malware","Social engineering","On-path","DoS"],c:1,e:"Social engineering manipulates people rather than technology. Over the phone it is called vishing."},
{id:"u8l8-9",t:"u8l8",q:"Files across a department become encrypted and a message demands payment for the key. What type of malware is this?",a:["Spyware","Worm","Ransomware","Rootkit"],c:2,e:"Ransomware encrypts data and extorts payment for decryption."},
{id:"u8l8-10",t:"u8l8",q:"A stranger carrying boxes follows an employee through a badge-controlled door without swiping. What is this called?",a:["Shoulder surfing","Phishing","Dumpster diving","Tailgating"],c:3,e:"Tailgating or piggybacking is gaining physical entry by following an authorized person."},
{id:"u8l8-11",t:"u8l8",q:"Wireless clients are repeatedly disconnected by forged management frames while an attacker captures their reconnection handshakes. Which attack is this?",a:["Deauthentication attack","Evil twin","MAC flooding","Rogue DHCP"],c:0,e:"Deauthentication attacks spoof 802.11 management frames to kick clients off, often to capture handshakes for cracking."},
{id:"u8l8-12",t:"u8l8",q:"An attacker uses a list of leaked username and password pairs from another website to try logging in to a company's VPN. What is this attack?",a:["Brute force","Credential stuffing","Dictionary attack","Rainbow table"],c:1,e:"Credential stuffing reuses credentials stolen from other breaches, relying on password reuse."},

// u8l9
{id:"u8l9-1",t:"u8l9",q:"A company wants only laptops with current antivirus and patches to join the LAN, and wants noncompliant devices moved to a remediation VLAN automatically. Which technology provides this?",a:["A honeypot","Port mirroring","Content filtering","Network access control with posture assessment"],c:3,e:"NAC checks device health at connection time and quarantines devices that fail."},
{id:"u8l9-2",t:"u8l9",q:"Where should a company place a public-facing web server so internet users can reach it without gaining direct access to the internal LAN?",a:["In a screened subnet, also called a DMZ","On the internal trusted network","On the management VLAN","On the guest wireless network"],c:0,e:"The screened subnet sits between the untrusted internet and the trusted LAN, isolating public servers."},
{id:"u8l9-3",t:"u8l9",q:"What is the FIRST hardening step when deploying a new network switch?",a:["Enable jumbo frames","Change the default administrator password","Configure SNMPv1","Enable all ports"],c:1,e:"Default credentials are publicly known. Changing them is the first step, followed by disabling unused ports and services."},
{id:"u8l9-4",t:"u8l9",q:"An ACL on a router lists several permit statements but no explicit deny. Traffic that matches none of the statements is blocked. Why?",a:["The router is misconfigured","The permit statements are in the wrong order","ACLs end with an implicit deny","The traffic is using UDP"],c:2,e:"Access control lists are processed top down with first match, and anything unmatched hits the implicit deny at the end."},
{id:"u8l9-5",t:"u8l9",q:"Which control blocks access to websites based on category, such as gambling or social media?",a:["802.1X","Port security","DHCP snooping","URL filtering"],c:3,e:"URL filtering permits or denies sites by address or category. Content filtering inspects what is inside the traffic."},
{id:"u8l9-6",t:"u8l9",q:"Which switch feature prevents an unauthorized DHCP server from handing out addresses on user ports?",a:["DHCP snooping","Port mirroring","Jumbo frames","LACP"],c:0,e:"DHCP snooping allows DHCP server responses only on trusted ports."},
{id:"u8l9-7",t:"u8l9",q:"Unused switch ports in a conference room are live and connected to the user VLAN. What is the BEST hardening action?",a:["Enable PortFast on them","Administratively disable them or place them in an unused VLAN","Set them to trunk mode","Assign static IP addresses to them"],c:1,e:"Disabling unused ports, or parking them in a dead VLAN, prevents unauthorized devices from joining the network."},
{id:"u8l9-8",t:"u8l9",q:"Which framework requires devices to authenticate at the switch port before being allowed onto the network?",a:["802.1Q","802.3af","802.1X","802.11ax"],c:2,e:"802.1X is port-based network access control, authenticating the device or user through a RADIUS server before the port passes traffic."},
{id:"u8l9-9",t:"u8l9",q:"Industrial control systems that cannot be patched must remain in operation. What is the BEST way to protect them?",a:["Connect them to the guest Wi-Fi","Disable logging","Install antivirus on each controller","Segment them onto an isolated network with strict firewall rules"],c:3,e:"Segmentation limits exposure of unpatchable OT and SCADA systems by controlling exactly what can reach them."},
{id:"u8l9-10",t:"u8l9",q:"Which practice involves rotating encryption keys, protecting private keys, and revoking compromised certificates?",a:["Key management","Port security","Content filtering","Geofencing"],c:0,e:"Key management covers the generation, storage, rotation, and revocation of cryptographic keys and certificates."}
);
