// NetPlus Academy question bank, units 1 to 3. All questions are original.
// Fields: id, t (lesson id), q (stem), a (four options), c (index of correct option), e (explanation).
window.FRA = window.FRA || {};
FRA.questions = FRA.questions || [];
FRA.questions.push(
// u1l1
{id:"u1l1-1",t:"u1l1",q:"A company connects its offices in Denver, Atlanta, and Seattle using circuits leased from a telecommunications provider. Which term BEST describes this network?",a:["LAN","WAN","PAN","SAN"],c:1,e:"A WAN connects LANs across geographic distance, typically over provider links. A LAN is a single site, a PAN is personal-range such as Bluetooth, and a SAN is dedicated storage networking."},
{id:"u1l1-2",t:"u1l1",q:"Which network design lets an administrator manage user accounts, file permissions, and backups from a central location?",a:["Peer-to-peer","Ad hoc","Client-server","Point-to-point"],c:2,e:"Client-server designs centralize resources and control on dedicated servers. Peer-to-peer spreads them across every host, which does not scale for management or security."},
{id:"u1l1-3",t:"u1l1",q:"A small business with six PCs has each user share folders directly from their own machine with no dedicated server. Which drawback is MOST likely as the company grows?",a:["Broadcast storms from the switch","Excessive fiber cabling costs","Lack of IP addresses","Each device must manage its own security and shares"],c:3,e:"This is peer-to-peer networking. Every host handles its own accounts and permissions, so administration becomes unmanageable as the number of devices grows."},
{id:"u1l1-4",t:"u1l1",q:"Servers in a data center access disk arrays over a dedicated network that presents storage as if it were locally attached block devices. What is this network called?",a:["SAN","MAN","WLAN","CAN"],c:0,e:"A storage area network provides block-level storage access over a dedicated network, commonly using iSCSI or Fibre Channel."},
{id:"u1l1-5",t:"u1l1",q:"A fitness tracker syncs with a phone over Bluetooth. Which network type is this?",a:["LAN","PAN","MAN","WAN"],c:1,e:"A personal area network covers a person's immediate space, such as Bluetooth between a wearable and a phone."},
{id:"u1l1-6",t:"u1l1",q:"Which statement about a MAN is accurate?",a:["It is smaller than a LAN and larger than a PAN","It is another name for a wireless LAN","It spans a city-sized area, larger than a LAN but smaller than a WAN","It only uses satellite links"],c:2,e:"A metropolitan area network covers a city or campus region: bigger than one building's LAN, smaller than a multi-region WAN."},

// u1l2
{id:"u1l2-1",t:"u1l2",q:"A network requires that a failure of any single link never isolates a site. Which topology provides the MOST redundancy?",a:["Star","Bus","Full mesh","Ring"],c:2,e:"Full mesh connects every node to every other node, so any single link can fail without cutting a path. It is the most redundant and the most expensive."},
{id:"u1l2-2",t:"u1l2",q:"How many links are required to connect eight routers in a full mesh?",a:["8","16","64","28"],c:3,e:"Full mesh needs n(n-1)/2 links. For eight nodes that is 8 times 7 divided by 2, which equals 28."},
{id:"u1l2-3",t:"u1l2",q:"Every workstation on a floor connects with its own cable to a single switch in the wiring closet. Which topology is this?",a:["Star","Ring","Bus","Mesh"],c:0,e:"Each device having its own connection to one central device is a star, also called hub and spoke. A single cable fault affects one host, but the center is a single point of failure."},
{id:"u1l2-4",t:"u1l2",q:"A wireless bridge links the headquarters roof to a warehouse roof across the street, and nothing else uses that link. Which topology describes the link?",a:["Point-to-multipoint","Point-to-point","Hub and spoke","Hybrid"],c:1,e:"A single dedicated connection between exactly two endpoints is point-to-point."},
{id:"u1l2-5",t:"u1l2",q:"A legacy network uses one shared coaxial cable with terminators at each end. A technician removes a terminator to add a device and the whole segment stops working. Which topology is in use?",a:["Star","Full mesh","Bus","Spine and leaf"],c:2,e:"A bus topology runs every device off one shared cable. A break or missing terminator reflects signals and takes down the entire segment."},
{id:"u1l2-6",t:"u1l2",q:"What is the difference between a physical and a logical topology?",a:["Physical describes wireless links and logical describes wired links","There is no difference; the terms are interchangeable","Physical applies to WANs and logical applies to LANs","Physical is how cables are actually run; logical is how data actually flows"],c:3,e:"Physical topology is the cabling layout; logical topology is the path data takes. They can differ, as in an old Token Ring network that was a physical star but a logical ring."},
{id:"u1l2-7",t:"u1l2",q:"One access point serves twenty laptops in a lobby. Which topology BEST describes this arrangement?",a:["Point-to-multipoint","Point-to-point","Full mesh","Bus"],c:0,e:"One central endpoint communicating with many endpoints is point-to-multipoint, the shape of an access point serving clients."},

// u1l3
{id:"u1l3-1",t:"u1l3",q:"In a data center fabric, every leaf switch connects to every spine switch and no leaf connects to another leaf. What is the maximum number of switch hops between any two servers?",a:["One","It depends on the number of leaves","Three","Two"],c:3,e:"In spine and leaf, traffic goes leaf to spine to leaf, so any two servers are at most two hops apart with predictable latency."},
{id:"u1l3-2",t:"u1l3",q:"A medium-sized office merges the core and distribution layers into one pair of switches to reduce cost. What is this design called?",a:["Collapsed core","Spine and leaf","Three-tier hierarchy","Hub and spoke"],c:0,e:"A collapsed core combines the core and distribution roles into a single layer, appropriate for small and medium networks."},
{id:"u1l3-3",t:"u1l3",q:"Which layer of the three-tier model is where end-user devices physically connect and receive PoE and VLAN assignments?",a:["Core","Access","Distribution","Edge"],c:1,e:"The access layer provides ports for end devices. Distribution aggregates access switches and applies policy; core provides the fast backbone."},
{id:"u1l3-4",t:"u1l3",q:"A web server in the data center queries a database server in the same data center. How is this traffic flow classified?",a:["North-south","Inbound","East-west","Upstream"],c:2,e:"Traffic between servers inside the data center is east-west. Traffic entering or leaving the data center, such as from a user on the internet, is north-south."},
{id:"u1l3-5",t:"u1l3",q:"Which layer of a three-tier design should be kept free of access lists and complex policy so it can forward as fast as possible?",a:["Access","Distribution","Perimeter","Core"],c:3,e:"The core's only job is high-speed transport between distribution blocks. Policy belongs at the distribution layer."},
{id:"u1l3-6",t:"u1l3",q:"An organization's applications generate far more server-to-server traffic than user-to-server traffic. Which architecture is designed for this pattern?",a:["Spine and leaf","Three-tier hierarchical","Collapsed core","Ring"],c:0,e:"Spine and leaf provides equal, predictable bandwidth between any two servers, which suits heavy east-west traffic."},

// u2l1
{id:"u2l1-1",t:"u2l1",q:"A technician replaces a damaged patch cable to restore a link. At which OSI layer was the problem?",a:["Layer 1","Layer 2","Layer 3","Layer 4"],c:0,e:"Cables, connectors, and signaling are Physical layer, Layer 1."},
{id:"u2l1-2",t:"u2l1",q:"Which OSI layer uses MAC addresses to deliver frames between devices on the same segment?",a:["Physical","Data Link","Network","Transport"],c:1,e:"The Data Link layer frames data and addresses it with MAC addresses. Switches operate here."},
{id:"u2l1-3",t:"u2l1",q:"A router forwards a packet from one subnet to another based on its destination IP address. At which layer is the router making this decision?",a:["Layer 2","Layer 4","Layer 3","Layer 7"],c:2,e:"Logical addressing and routing between networks is the Network layer, Layer 3."},
{id:"u2l1-4",t:"u2l1",q:"Which two sublayers make up the Data Link layer?",a:["TCP and UDP","Session and Presentation","IP and ICMP","LLC and MAC"],c:3,e:"The Data Link layer is divided into Logical Link Control, which identifies the upper-layer protocol, and Media Access Control, which handles addressing and media access."},
{id:"u2l1-5",t:"u2l1",q:"As a packet crosses three routers to reach a server, which address changes at every hop?",a:["The destination MAC address","The source IP address","The destination IP address","The port number"],c:0,e:"Each router rewraps the packet in a new frame addressed to the next hop's MAC. IP addresses and ports stay the same end to end unless NAT is in use."},
{id:"u2l1-6",t:"u2l1",q:"A technician using ping receives ICMP echo replies. At which OSI layer does ICMP operate?",a:["Layer 1","Layer 3","Layer 2","Layer 5"],c:1,e:"ICMP is carried inside IP and provides Network layer diagnostics and error messages."},

// u2l2
{id:"u2l2-1",t:"u2l2",q:"A firewall rule blocks all traffic to TCP port 23. At which OSI layer is the firewall filtering when it inspects port numbers?",a:["Layer 2","Layer 4","Layer 3","Layer 7"],c:1,e:"Port numbers belong to the Transport layer, Layer 4, where TCP and UDP identify the application process."},
{id:"u2l2-2",t:"u2l2",q:"Which OSI layer is responsible for encrypting data with TLS and for formatting such as JPEG or ASCII?",a:["Application","Session","Presentation","Transport"],c:2,e:"The Presentation layer, Layer 6, handles data formatting, compression, and encryption."},
{id:"u2l2-3",t:"u2l2",q:"During a TCP connection setup, a client sends a segment with the SYN flag set and receives a SYN-ACK. Which layer is performing this exchange?",a:["Network","Data Link","Session","Transport"],c:3,e:"The three-way handshake is a TCP function at the Transport layer."},
{id:"u2l2-4",t:"u2l2",q:"A proxy server inspects HTTP requests to block specific URLs. At which layer is it operating?",a:["Layer 7","Layer 4","Layer 5","Layer 3"],c:0,e:"HTTP is an Application layer protocol. Inspecting URLs requires reading application content at Layer 7."},
{id:"u2l2-5",t:"u2l2",q:"Which OSI layer establishes, maintains, and terminates the dialog between two applications?",a:["Presentation","Session","Transport","Network"],c:1,e:"The Session layer, Layer 5, manages the conversation between endpoints."},
{id:"u2l2-6",t:"u2l2",q:"Which protocol provides connectionless delivery with no acknowledgments at the Transport layer?",a:["TCP","IP","UDP","ARP"],c:2,e:"UDP is the connectionless Transport layer protocol. TCP is connection-oriented; IP and ARP are lower layers."},
{id:"u2l2-7",t:"u2l2",q:"Which mnemonic correctly lists the OSI layers from Layer 1 to Layer 7?",a:["All People Seem To Need Data Processing","Application Presentation Session Transport Network Data Link Physical","Physical Data Network Session Transport Presentation Application","Please Do Not Throw Sausage Pizza Away"],c:3,e:"Please Do Not Throw Sausage Pizza Away runs bottom up: Physical, Data Link, Network, Transport, Session, Presentation, Application."},

// u2l3
{id:"u2l3-1",t:"u2l3",q:"What is the protocol data unit at the Data Link layer?",a:["Bit","Packet","Frame","Segment"],c:2,e:"Layer 2 carries frames. Layer 1 is bits, Layer 3 is packets, Layer 4 is segments or datagrams."},
{id:"u2l3-2",t:"u2l3",q:"In a packet capture, which header appears outermost, before the IP header?",a:["TCP header","UDP header","Application payload","Ethernet frame header"],c:3,e:"Encapsulation wraps the Layer 3 packet inside the Layer 2 frame, so the frame header with MAC addresses is read first."},
{id:"u2l3-3",t:"u2l3",q:"What is the default maximum transmission unit on a standard Ethernet network?",a:["1500 bytes","576 bytes","4096 bytes","9000 bytes"],c:0,e:"Standard Ethernet carries a 1500-byte payload. Jumbo frames raise this to about 9000 bytes."},
{id:"u2l3-4",t:"u2l3",q:"Which field in the IP header is decremented by each router and causes the packet to be discarded when it reaches zero?",a:["Checksum","Time to live","Sequence number","Fragment offset"],c:1,e:"TTL prevents packets from looping forever. Traceroute exploits it by sending packets with increasing TTL values."},
{id:"u2l3-5",t:"u2l3",q:"Which OSI layers correspond to the Application layer of the four-layer TCP/IP model?",a:["Layers 1 and 2","Layer 3 only","Layers 5, 6, and 7","Layer 4 only"],c:2,e:"The TCP/IP Application layer combines OSI Session, Presentation, and Application."},
{id:"u2l3-6",t:"u2l3",q:"A technician enables jumbo frames on two servers but not on the switch between them. Large transfers fail while small pings succeed. What is the cause?",a:["The servers have the wrong MAC addresses","The switch is not routing between VLANs","A duplex mismatch","An MTU mismatch along the path"],c:3,e:"Every device in the path must support the same MTU. Frames larger than the switch's MTU are dropped while small packets pass normally."},

// u3l1
{id:"u3l1-1",t:"u3l1",q:"A new office needs 10 Gbps to every desk over runs up to 90 meters. Which cable category is the MINIMUM that meets the requirement?",a:["Cat 5e","Cat 6","Cat 8","Cat 6A"],c:3,e:"Cat 6 supports 10 Gbps only to 55 meters. Cat 6A is rated for 10 Gbps at the full 100 meters."},
{id:"u3l1-2",t:"u3l1",q:"A technician crimps a cable with T568A on one end and T568B on the other. What type of cable has been made?",a:["Crossover","Straight-through","Rollover","Loopback"],c:0,e:"Different wiring standards on each end swap the transmit and receive pairs, creating a crossover cable."},
{id:"u3l1-3",t:"u3l1",q:"Network cable must be run through the space above a suspended ceiling that is used for building air return. Which cable rating is required?",a:["Riser","Plenum","Outdoor","Direct burial"],c:1,e:"Air-handling spaces require plenum-rated cable with a low-smoke, fire-resistant jacket."},
{id:"u3l1-4",t:"u3l1",q:"A 130-meter Cat 6 run between a switch and a workstation links intermittently and shows errors. What is the MOST likely cause?",a:["Crosstalk","An incorrect wiring standard","Attenuation from exceeding the 100-meter limit","A duplex mismatch"],c:2,e:"Twisted-pair Ethernet is limited to 100 meters. Beyond that the signal attenuates too much to be reliable."},
{id:"u3l1-5",t:"u3l1",q:"Which connector is used to attach a cable modem to a coaxial wall outlet?",a:["BNC","RJ45","LC","F-type"],c:3,e:"F-type screw-on connectors terminate coax for cable TV and cable modems. BNC is the older coax connector used on legacy LANs."},
{id:"u3l1-6",t:"u3l1",q:"A data center needs an inexpensive 25 Gbps link between a switch and a server three meters away. Which cabling option fits BEST?",a:["Direct attach twinaxial cable","Single-mode fiber with LR optics","Cat 5e UTP","RG-6 coaxial"],c:0,e:"Direct attach twinaxial cables have transceivers built into both ends and are the low-cost choice for very short high-speed links."},
{id:"u3l1-7",t:"u3l1",q:"Cabling must be installed near large motors on a factory floor. Which cable type BEST resists the electrical noise?",a:["UTP","STP","Cat 5e","RG-59 coax"],c:1,e:"Shielded twisted pair adds foil or braid around the pairs to block electromagnetic interference."},

// u3l2
{id:"u3l2-1",t:"u3l2",q:"Two buildings on a campus are 3 kilometers apart and must be connected at 10 Gbps. Which fiber type should be used?",a:["Single-mode","Multimode OM4","Multimode OM3","Twinaxial"],c:0,e:"Multimode fiber reaches a few hundred meters at 10 Gbps. Kilometer distances require single-mode fiber."},
{id:"u3l2-2",t:"u3l2",q:"Which fiber connector is small, square, and snaps into most modern SFP transceivers?",a:["ST","LC","SC","MPO"],c:1,e:"LC is the compact connector standard on SFP and SFP+ modules. SC is larger and ST is a round bayonet."},
{id:"u3l2-3",t:"u3l2",q:"A technician needs to extend a copper Ethernet link across a 400-meter parking lot using existing fiber. Which device is required?",a:["Repeater hub","Load balancer","Media converter","Patch panel"],c:2,e:"A media converter changes the copper signal to fiber and back without altering the data."},
{id:"u3l2-4",t:"u3l2",q:"A fiber patch cord has green connectors. What does the green color indicate?",a:["Multimode fiber","Single-mode UPC polish","A damaged cable","APC angled polish"],c:3,e:"Green connectors indicate an angled physical contact (APC) polish. Blue indicates UPC. The two should not be mated together."},
{id:"u3l2-5",t:"u3l2",q:"Which connector carries 12 or 24 fibers in a single plug for 40 and 100 gigabit links?",a:["MPO","SC","LC","ST"],c:0,e:"MPO (also MTP) is the multi-fiber ribbon connector used with parallel optics at 40G and 100G."},
{id:"u3l2-6",t:"u3l2",q:"Which fiber type has the smaller core, uses a laser light source, and reaches the longest distances?",a:["Multimode","Single-mode","Plenum","Twinaxial"],c:1,e:"Single-mode fiber has a roughly 9-micron core, carries one light path from a laser, and reaches 10 kilometers or more."},

// u3l3
{id:"u3l3-1",t:"u3l3",q:"A switch link runs at 10 Gbps over a fiber module. Which form factor is the module MOST likely to be?",a:["SFP","SFP+","QSFP","GBIC"],c:1,e:"SFP+ is the 10 Gbps version of the small form-factor pluggable. SFP is 1 Gbps and QSFP is 40 Gbps."},
{id:"u3l3-2",t:"u3l3",q:"A technician installs a 10GBASE-SR module in one switch and a 10GBASE-LR module in the other and connects them with single-mode fiber. The link does not come up. Why?",a:["The modules require Cat 6A instead","Single-mode fiber cannot carry 10 Gbps","SR and LR use different wavelengths and fiber types and must match on both ends","SR modules only work at 1 Gbps"],c:2,e:"Both ends need the same standard. SR is short reach over multimode; LR is long reach over single-mode. Mismatched optics will not link."},
{id:"u3l3-3",t:"u3l3",q:"Which Ethernet standard runs 10 Gbps over single-mode fiber to about 10 kilometers?",a:["10GBASE-T","10GBASE-SR","1000BASE-LX","10GBASE-LR"],c:3,e:"10GBASE-LR is long reach single-mode to 10 km. SR is multimode to about 300 meters; ER reaches 40 km."},
{id:"u3l3-4",t:"u3l3",q:"One end of a link is hard-coded to 100 Mbps full duplex and the other is set to auto-negotiate. The link shows late collisions and CRC errors. What is the cause?",a:["Duplex mismatch","Attenuation","Wrong fiber polish","VLAN mismatch"],c:0,e:"When one side is forced and the other auto-negotiates, the auto side falls back to half duplex. The resulting mismatch produces late collisions and CRC errors."},
{id:"u3l3-5",t:"u3l3",q:"What does the first half of a MAC address such as 3C:52:82:1A:9F:07 identify?",a:["The host's IP subnet","The manufacturer (OUI)","The VLAN ID","The switch port"],c:1,e:"The first 24 bits of a MAC address are the Organizationally Unique Identifier assigned to the manufacturer."},
{id:"u3l3-6",t:"u3l3",q:"Which transceiver form factor supports 100 Gbps?",a:["SFP","SFP+","QSFP28","QSFP+"],c:2,e:"QSFP28 carries four 25 Gbps lanes for 100 Gbps. QSFP+ is 40 Gbps."},
{id:"u3l3-7",t:"u3l3",q:"In the standard name 1000BASE-T, what does the T indicate?",a:["Ten kilometers","Twinaxial","Terabit","Twisted pair copper"],c:3,e:"T means twisted-pair copper. S and L denote short and long reach fiber."},

// u3l4
{id:"u3l4-1",t:"u3l4",q:"Which traffic type delivers a packet to the nearest one of several servers that all share the same IP address?",a:["Unicast","Broadcast","Anycast","Multicast"],c:2,e:"Anycast assigns one address to many servers and routes each request to the closest instance. DNS root servers and CDNs use it."},
{id:"u3l4-2",t:"u3l4",q:"A DHCP client sends a Discover message to 255.255.255.255. Which traffic type is this?",a:["Unicast","Anycast","Multicast","Broadcast"],c:3,e:"255.255.255.255 is the limited broadcast address, delivered to every host on the local segment."},
{id:"u3l4-3",t:"u3l4",q:"A video training stream is sent once and received only by the workstations that joined the group address 239.1.1.10. Which traffic type is in use?",a:["Multicast","Broadcast","Unicast","Anycast"],c:0,e:"Multicast delivers one stream to a group of subscribers using a Class D address in the 224 to 239 range."},
{id:"u3l4-4",t:"u3l4",q:"Why does a router not forward an ARP request from one subnet to another?",a:["ARP uses TCP","ARP requests are broadcasts, and routers do not forward broadcasts","ARP is encrypted","Routers operate only at Layer 1"],c:1,e:"ARP requests are Layer 2 broadcasts. Routers separate broadcast domains and never forward broadcast traffic."},
{id:"u3l4-5",t:"u3l4",q:"A remote research station uses a geostationary satellite link. Which characteristic MOST affects interactive applications?",a:["Limited to 2.4 GHz","Lack of encryption","High latency of roughly half a second","Requires Cat 6A cabling"],c:2,e:"Geostationary satellites orbit about 36,000 km up, adding roughly 500 to 600 ms of round-trip latency that hurts voice and interactive traffic."},
{id:"u3l4-6",t:"u3l4",q:"Which statement about broadcast traffic in IPv6 is correct?",a:["IPv6 uses broadcast for neighbor discovery","IPv6 broadcasts are routed across the internet","IPv6 broadcasts are limited to 64 hosts","IPv6 has no broadcast and uses multicast instead"],c:3,e:"IPv6 eliminated broadcast. Functions that used broadcast in IPv4, such as address resolution, use multicast groups like ff02::1."},
{id:"u3l4-7",t:"u3l4",q:"A branch office in a rural area has no wired provider. Which WAN option can provide primary connectivity using carrier networks?",a:["Cellular 4G or 5G","Twinaxial","Multimode fiber","Cat 8"],c:0,e:"Cellular service from a carrier provides WAN connectivity where wired service is unavailable and is also common as a backup link."}
);
