// NetPlus Academy question bank: unit 6 (switching and wireless).
window.FRA = window.FRA || {};
FRA.questions = FRA.questions || [];
FRA.questions.push(
// u6l1 How switches work
{id:"u6l1-1",t:"u6l1",q:"A switch receives a frame whose destination MAC address is not in its MAC address table. What does it do?",a:["Drops the frame","Sends the frame to the default gateway","Floods the frame out all ports in the VLAN except the one it arrived on","Sends an ARP request"],c:2,e:"Unknown unicast frames are flooded within the VLAN so the destination can respond and the switch can learn its port."},
{id:"u6l1-2",t:"u6l1",q:"How does a switch populate its MAC address table?",a:["By reading the destination MAC of incoming frames","By reading the source MAC of incoming frames and noting the arrival port","From the DHCP server","From the routing table"],c:1,e:"Switches learn by recording the source MAC address of each frame along with the port it arrived on."},
{id:"u6l1-3",t:"u6l1",q:"A 24-port switch has all ports in VLAN 10. How many collision domains and broadcast domains does it create?",a:["1 collision domain, 24 broadcast domains","24 collision domains, 1 broadcast domain","1 of each","24 of each"],c:1,e:"Each switch port is its own collision domain. All ports in one VLAN share a single broadcast domain."},
{id:"u6l1-4",t:"u6l1",q:"A technician needs to configure a switch that has no IP address yet and is not reachable over the network. Which method should be used?",a:["SSH to the management VLAN","Telnet to the default gateway","Console cable connection","SNMP set commands"],c:2,e:"The console port provides out-of-band access that does not depend on any network configuration."},
{id:"u6l1-5",t:"u6l1",q:"Which device is required to allow hosts in two different VLANs to communicate?",a:["A hub","An additional Layer 2 switch","A router or Layer 3 switch","A repeater"],c:2,e:"Each VLAN is a separate broadcast domain and subnet. Traffic between them must be routed."},
{id:"u6l1-6",t:"u6l1",q:"Which of the following is one of the three primary functions of a Layer 2 switch?",a:["Assigning IP addresses","Loop avoidance","Name resolution","Encrypting frames"],c:1,e:"Switches perform address learning, forward/filter decisions, and loop avoidance. IP assignment and name resolution are DHCP and DNS."},

// u6l2 VLANs and trunking
{id:"u6l2-1",t:"u6l2",q:"Two switches must be connected by one link that carries traffic for VLANs 10, 20, and 30. How should the ports on each end be configured?",a:["As access ports in VLAN 1","As an 802.1Q trunk","With port mirroring","As a voice VLAN"],c:1,e:"An 802.1Q trunk tags each frame with its VLAN ID so multiple VLANs can share one physical link."},
{id:"u6l2-2",t:"u6l2",q:"A user moves to a new desk. The link light is on and the PC gets an IP address, but in a different range than before, and it cannot reach its file server. What is the MOST likely cause?",a:["The new port is assigned to the wrong VLAN","A bad patch cable","A duplicate IP address","The DNS server is down"],c:0,e:"A different address range means a different DHCP scope, which means the access port belongs to a different VLAN than the user needs."},
{id:"u6l2-3",t:"u6l2",q:"On an 802.1Q trunk, which VLAN's frames are sent without a tag?",a:["VLAN 4094","The management VLAN","The native VLAN","The voice VLAN"],c:2,e:"The native VLAN crosses the trunk untagged. It is VLAN 1 by default and must match on both ends of the trunk."},
{id:"u6l2-4",t:"u6l2",q:"An IP phone with a PC plugged into its pass-through port connects to one switch port. Which feature lets the phone's traffic use a separate VLAN from the PC's?",a:["Port mirroring","Voice VLAN","Spanning tree","Link aggregation"],c:1,e:"A voice VLAN on the access port lets the phone tag its frames into the voice VLAN while the PC's untagged traffic stays in the data VLAN."},
{id:"u6l2-5",t:"u6l2",q:"A Layer 3 switch needs a gateway address for VLAN 20 so hosts in that VLAN can be routed. What is configured?",a:["A subinterface","A switch virtual interface (SVI)","A trunk port","A static MAC entry"],c:1,e:"An SVI, such as interface vlan 20, gives the switch a routed IP interface in that VLAN."},
{id:"u6l2-6",t:"u6l2",q:"Switches log native VLAN mismatch errors on a trunk link. What is the risk if this is not corrected?",a:["The trunk speed drops to 10 Mbps","Untagged traffic leaks between the two mismatched VLANs","The switches lose their MAC tables","DHCP stops working on all VLANs"],c:1,e:"Each side treats untagged frames as belonging to its own native VLAN, so traffic crosses between two different VLANs without any routing or filtering."},
{id:"u6l2-7",t:"u6l2",q:"A router with a single physical interface must route between four VLANs on a trunk. What does the administrator configure on the router?",a:["Four SVIs","Four subinterfaces, each tagged with a VLAN and addressed in that subnet","Four static routes","Four access ports"],c:1,e:"Router on a stick uses one trunk with a subinterface per VLAN. SVIs are the Layer 3 switch equivalent."},

// u6l3 STP
{id:"u6l3-1",t:"u6l3",q:"After a technician adds a second cable between two switches for redundancy, the network floods with broadcast traffic and becomes unusable. Which protocol, if enabled, would have prevented this?",a:["LACP","STP","LLDP","VRRP"],c:1,e:"Spanning Tree Protocol blocks redundant Layer 2 paths to prevent loops and broadcast storms. LACP would bundle the links but must be deliberately configured."},
{id:"u6l3-2",t:"u6l3",q:"How is the root bridge selected in a spanning tree topology?",a:["The switch with the most ports","The switch with the lowest bridge ID","The switch with the highest IP address","The first switch powered on"],c:1,e:"The lowest bridge ID, which is priority followed by MAC address, wins. Administrators lower the priority on the core switch to make it root."},
{id:"u6l3-3",t:"u6l3",q:"Which STP port state receives BPDUs but does not forward frames or learn MAC addresses?",a:["Forwarding","Learning","Blocking","Listening"],c:2,e:"A blocking port stays quiet to prevent a loop, listening only for BPDUs so it can transition if the topology changes."},
{id:"u6l3-4",t:"u6l3",q:"Which feature should be enabled on access ports so a user cannot plug in an unauthorized switch and affect the spanning tree?",a:["PortFast only","BPDU guard","Root guard on the core","Loop guard"],c:1,e:"BPDU guard shuts down an access port if it receives a BPDU, which only a switch would send."},
{id:"u6l3-5",t:"u6l3",q:"A network needs redundant switch links but cannot tolerate 30 to 50 seconds of outage when a link fails. Which protocol should be used?",a:["802.1D STP","802.1w Rapid Spanning Tree","802.1Q","802.3ad"],c:1,e:"RSTP converges in a few seconds compared with the 30 to 50 seconds of classic STP."},
{id:"u6l3-6",t:"u6l3",q:"An access switch with default settings became the root bridge because it had the lowest MAC address, causing traffic to take inefficient paths. What is the fix?",a:["Disable STP on the access switch","Set a lower bridge priority on the intended core switch","Add more links to the access switch","Change the access switch's IP address"],c:1,e:"Root selection is by lowest bridge ID. Lowering the core switch's priority makes it win regardless of MAC address."},
{id:"u6l3-7",t:"u6l3",q:"Which symptom MOST strongly indicates a Layer 2 loop?",a:["Users receive APIPA addresses","MAC addresses flapping between ports and switch CPU near 100 percent","Ping works by IP but not by name","A single port shows administratively down"],c:1,e:"In a loop, the same MAC appears on multiple ports as frames circle, and the flood of broadcasts saturates the switch CPU."},

// u6l4 Switch features
{id:"u6l4-1",t:"u6l4",q:"A new access point requires about 25 watts over its Ethernet cable. Which PoE standard must the switch port support at minimum?",a:["802.3af","802.3at","802.3bt Type 4","802.1X"],c:1,e:"802.3af delivers about 13 watts to the device. 802.3at, PoE+, delivers about 25.5 watts. 802.3bt goes to 60 and 90 watts."},
{id:"u6l4-2",t:"u6l4",q:"Several PoE cameras on a switch work, but the last two added never power on. The switch ports are fine. What is the MOST likely cause?",a:["Wrong VLAN assignment","The switch's PoE power budget is exceeded","Spanning tree blocking","Duplex mismatch"],c:1,e:"Each switch has a total PoE budget. Once it is consumed, additional powered devices cannot be powered even though the ports work."},
{id:"u6l4-3",t:"u6l4",q:"A security analyst needs to capture all traffic passing through a specific switch port using a laptop running a protocol analyzer. Which switch feature is required?",a:["Port security","Port mirroring","Link aggregation","Jumbo frames"],c:1,e:"Port mirroring, also called SPAN, copies traffic from one or more ports to the port where the analyzer is connected."},
{id:"u6l4-4",t:"u6l4",q:"Which protocol negotiates the bundling of several physical links between two switches into one logical link?",a:["STP","LACP","VTP","CDP"],c:1,e:"Link Aggregation Control Protocol negotiates and maintains the bundle. Both ends need matching speed, duplex, and VLAN configuration."},
{id:"u6l4-5",t:"u6l4",q:"A storage network needs to move large amounts of data efficiently. Which switch setting reduces per-frame overhead?",a:["Enable jumbo frames end to end","Set all ports to half duplex","Reduce the MTU to 576","Enable PortFast"],c:0,e:"Jumbo frames raise the MTU to about 9000 bytes so fewer, larger frames carry the same data. Every device in the path must support it."},
{id:"u6l4-6",t:"u6l4",q:"A port shows err-disabled after a user plugged in a small unmanaged switch. Which feature MOST likely triggered this?",a:["Port security limiting learned MAC addresses","Jumbo frames","Auto-negotiation","Voice VLAN"],c:0,e:"Port security restricts the number or identity of MAC addresses on a port. Multiple devices behind an unmanaged switch violate it and the port is error-disabled."},
{id:"u6l4-7",t:"u6l4",q:"A pan-tilt-zoom camera requires 60 watts of PoE. Which standard is required?",a:["802.3af","802.3at","802.3bt","802.11ax"],c:2,e:"Only 802.3bt, PoE++, delivers 60 watts (Type 3) or 90 watts (Type 4)."},

// u6l5 Wireless fundamentals
{id:"u6l5-1",t:"u6l5",q:"Which three channels should adjacent access points use in the 2.4 GHz band to avoid overlapping frequencies?",a:["1, 6, and 11","1, 5, and 9","36, 40, and 44","2, 7, and 12"],c:0,e:"2.4 GHz channels are 5 MHz apart but 20 MHz wide, so only 1, 6, and 11 do not overlap. Channels 36, 40, and 44 are 5 GHz."},
{id:"u6l5-2",t:"u6l5",q:"Which wireless standard introduced operation in the 6 GHz band?",a:["802.11n","802.11ac","802.11ax (Wi-Fi 6E)","802.11g"],c:2,e:"Wi-Fi 6E extends 802.11ax into the 6 GHz band. Wi-Fi 5 (802.11ac) is 5 GHz only."},
{id:"u6l5-3",t:"u6l5",q:"What does a BSSID identify?",a:["The network name shown to users","The MAC address of a specific access point radio","A group of access points sharing one SSID","The wireless channel in use"],c:1,e:"The BSSID is the MAC address of one radio on one access point. The SSID is the human-readable name, and an ESSID spans multiple APs."},
{id:"u6l5-4",t:"u6l5",q:"Two office buildings 800 meters apart need a wireless link. Which antenna type should be used on each end?",a:["Omnidirectional","Directional","Dipole","Isotropic"],c:1,e:"Directional antennas focus energy along one path, providing the gain and range needed for building-to-building links."},
{id:"u6l5-5",t:"u6l5",q:"A campus deploys 60 access points that must be configured and monitored from one place, with automatic channel and power coordination. Which design is appropriate?",a:["Autonomous APs configured individually","Lightweight APs managed by a wireless LAN controller","Ad hoc mode on all devices","A single high-power AP"],c:1,e:"Lightweight APs receive configuration from a wireless LAN controller, which also coordinates channels, power, and roaming."},
{id:"u6l5-6",t:"u6l5",q:"Which wireless network type connects devices directly to each other without an access point?",a:["Infrastructure","Ad hoc","Mesh","Point-to-multipoint"],c:1,e:"Ad hoc, or IBSS, mode lets devices communicate peer to peer with no access point."},
{id:"u6l5-7",t:"u6l5",q:"In a dense apartment environment, a technician sets the 2.4 GHz radios to 20 MHz channel width instead of 40 MHz. Why?",a:["Wider channels do not work in 2.4 GHz","Narrower channels reduce overlap and interference with neighbors","20 MHz is required by WPA3","The switch only supports 20 MHz"],c:1,e:"Wider channels consume more of the limited 2.4 GHz spectrum and overlap more neighbors. 20 MHz keeps the three non-overlapping channels usable."},
{id:"u6l5-8",t:"u6l5",q:"Which technology lets multiple access points share one network name so clients can move between them without reconnecting?",a:["BSSID","ESSID","Ad hoc","Band steering"],c:1,e:"An extended service set uses the same SSID across many APs, allowing clients to roam."},

// u6l6 Wireless security and design
{id:"u6l6-1",t:"u6l6",q:"A company wants each employee to authenticate to Wi-Fi with individual credentials verified by a RADIUS server, using the strongest available protection. What should be configured?",a:["WPA2-Personal","WPA3-Enterprise","WEP with MAC filtering","An open network with a captive portal"],c:1,e:"Enterprise mode uses 802.1X with RADIUS for per-user authentication. WPA3 is the current strongest standard."},
{id:"u6l6-2",t:"u6l6",q:"Which WPA3 feature protects a personal-mode network against offline dictionary attacks on the passphrase?",a:["TKIP","SAE","WEP keys","MAC filtering"],c:1,e:"Simultaneous Authentication of Equals replaces the pre-shared key handshake so captured traffic cannot be used to crack the passphrase offline."},
{id:"u6l6-3",t:"u6l6",q:"Visitors must accept terms of use in a web page before browsing on the guest Wi-Fi. Which feature provides this?",a:["802.1X","Captive portal","Band steering","Pre-shared key"],c:1,e:"A captive portal intercepts the first web request and presents a page for acceptance or login before granting access."},
{id:"u6l6-4",t:"u6l6",q:"What is the purpose of a wireless site survey?",a:["To register the SSID with the FCC","To measure coverage, signal strength, and interference and produce a heat map","To assign IP addresses to access points","To configure WPA3 keys"],c:1,e:"A site survey measures the RF environment so APs can be placed and channels planned. Its output is a heat map."},
{id:"u6l6-5",t:"u6l6",q:"Many dual-band clients stay on the crowded 2.4 GHz band even though 5 GHz is available. Which feature encourages them to move?",a:["Captive portal","Band steering","PortFast","Channel bonding"],c:1,e:"Band steering nudges capable clients from 2.4 GHz to 5 GHz to relieve congestion."},
{id:"u6l6-6",t:"u6l6",q:"A small business relies on a hidden SSID and MAC filtering for wireless security. Which statement is accurate?",a:["This is equivalent to WPA2","These are weak controls that are easily bypassed and must be paired with WPA2 or WPA3 encryption","Hidden SSIDs prevent all unauthorized access","MAC filtering encrypts traffic"],c:1,e:"SSIDs are revealed in client traffic and MAC addresses are trivially spoofed. Neither provides encryption or real authentication."},
{id:"u6l6-7",t:"u6l6",q:"Users report that laptops drop connections when walking between two parts of the office. A survey shows the two AP cells barely touch. What is the MOST likely issue?",a:["Insufficient cell overlap for roaming","Too many non-overlapping channels","The APs use WPA3","The wrong antenna polish"],c:0,e:"Roaming requires adjacent cells to overlap by roughly 15 to 20 percent so the client can associate with the next AP before losing the current one."},
{id:"u6l6-8",t:"u6l6",q:"Which wireless encryption standard should NEVER be used because it can be cracked in minutes?",a:["WPA2-AES","WPA3-SAE","WEP","WPA2-Enterprise"],c:2,e:"WEP has fundamental flaws in its use of RC4 and initialization vectors and is trivially broken."}
);
