// APlus Academy Core 1 question bank, units 4 to 6. All questions are original.
// Fields: id, t (lesson id), q (stem), a (four options), c (index of correct option), e (explanation).
window.FRA = window.FRA || {};
FRA.questions = FRA.questions || [];
FRA.questions.push(
// u4l1
{id:"u4l1-1",t:"u4l1",q:"A new office needs 10 Gb/s Ethernet to workstations on cable runs of up to 90 meters. Which is the lowest category that meets the requirement?",a:["Cat 5e","Cat 6a","Cat 6","Cat 8"],c:1,e:"Cat 6a supports 10 Gb/s over the full 100 m. Cat 6 manages 10 Gb/s only to about 55 m, Cat 5e tops out at 1 Gb/s, and Cat 8 is limited to 30 m runs."},
{id:"u4l1-2",t:"u4l1",q:"Cable is being installed in the air-handling space above a suspended ceiling. Which cable rating is required by fire code?",a:["Direct burial","Shielded twisted pair","Plenum-rated","Riser-rated only"],c:2,e:"Plenum spaces carry return air, so cable there must have a low-smoke, fire-resistant jacket. Ordinary PVC jackets release toxic smoke when burned."},
{id:"u4l1-3",t:"u4l1",q:"A patch cable is wired T568A on one end and T568B on the other. What kind of cable has been made?",a:["A straight-through cable","A shielded cable","A rollover console cable","A crossover cable"],c:3,e:"Using different standards at each end swaps the orange and green pairs, crossing transmit and receive. That is a crossover cable, once used between like devices before auto-MDIX ports became standard."},
{id:"u4l1-4",t:"u4l1",q:"A campus needs a fiber link between two buildings 2 kilometers apart. Which fiber type and light source should be used?",a:["Single-mode with a laser source","Multimode with an LED source","Multimode with a laser source","Coaxial with an F-type connector"],c:0,e:"Single-mode fiber has a tiny core of about 9 microns, uses a laser, and spans kilometers. Multimode with LED or VCSEL sources is limited to hundreds of meters."},
{id:"u4l1-5",t:"u4l1",q:"Which connector is found on the RG-6 coaxial cable that feeds a cable modem?",a:["BNC","F-type","RJ11","SC"],c:1,e:"RG-6 cable television and cable modem connections use the threaded F-type connector. BNC is the bayonet connector on RG-59 CCTV runs, RJ11 is telephone, and SC is a fiber connector."},

// u4l2
{id:"u4l2-1",t:"u4l2",q:"A technician plugs an external drive into a blue USB port on a desktop. What maximum transfer rate does that port support?",a:["480 Mb/s","10 Gb/s","5 Gb/s","40 Gb/s"],c:2,e:"Blue ports indicate USB 3.0 (also called 3.2 Gen 1) at 5 Gb/s. Black ports are USB 2.0 at 480 Mb/s, teal or red ports are 10 Gb/s, and 40 Gb/s is USB4 or Thunderbolt."},
{id:"u4l2-2",t:"u4l2",q:"Which video connector carries an analog signal and typically uses a 15-pin blue plug with thumbscrews?",a:["DVI-D","HDMI","DisplayPort","VGA"],c:3,e:"VGA is the only common analog video interface, using a 15-pin DE-15 connector. DVI-D, HDMI, and DisplayPort are digital."},
{id:"u4l2-3",t:"u4l2",q:"A user wants to run two monitors from a single video output by connecting the second monitor to the first. Which interface supports this daisy chaining?",a:["DisplayPort","DVI","VGA","HDMI 1.4"],c:0,e:"DisplayPort multi-stream transport allows monitors to be daisy chained from one output. VGA, DVI, and HDMI do not support daisy chaining."},
{id:"u4l2-4",t:"u4l2",q:"A technician needs to connect a computer's DVI-D output to a monitor that has only a VGA input. What is required?",a:["A passive DVI to VGA adapter","An active DVI-D to VGA converter","A DisplayPort cable","A USB-C to HDMI adapter"],c:1,e:"DVI-D carries only a digital signal, so converting to analog VGA requires an active converter. A passive adapter works only from DVI-I or DVI-A, which include analog pins."},
{id:"u4l2-5",t:"u4l2",q:"Which cable connects an internal SATA drive's data port to the motherboard?",a:["A 15-pin cable","A 4-pin Molex cable","A 7-pin cable","A 24-pin cable"],c:2,e:"SATA data cables have 7 pins in an L-shaped connector and run up to 1 m. The 15-pin connector is SATA power, Molex is legacy power, and the 24-pin connector powers the motherboard."},

// u4l3
{id:"u4l3-1",t:"u4l3",q:"A photo editor needs a monitor with the most accurate color and the widest viewing angles. Which LCD panel type should be recommended?",a:["TN","VA","Mini-LED backlit TN","IPS"],c:3,e:"IPS (in-plane switching) panels offer the best color accuracy and viewing angles. TN is fastest but poor in color and angles, and VA emphasizes contrast."},
{id:"u4l3-2",t:"u4l3",q:"A laptop screen is extremely dim, but when a flashlight is shined on it the desktop is faintly visible. What has MOST likely failed?",a:["The backlight or inverter","The digitizer","The LCD panel","The video cable"],c:0,e:"The panel is still forming an image, so the missing element is the light behind it. On older CCFL screens the inverter fails; on LED screens the backlight or its driver fails."},
{id:"u4l3-3",t:"u4l3",q:"Which display technology lights each pixel individually, producing perfect blacks but risking burn-in from static images?",a:["IPS LCD","OLED","VA LCD","Mini-LED"],c:1,e:"OLED pixels emit their own light, so a black pixel is simply off. Because the organic material wears, static content can leave permanent ghost images."},
{id:"u4l3-4",t:"u4l3",q:"A tablet displays a clear image but no longer responds to touch anywhere on the screen. Which component is MOST likely at fault?",a:["The backlight","The display panel","The digitizer or its cable","The inverter"],c:2,e:"The digitizer is the layer that senses touch or pen input. A working image with no touch response points to the digitizer or its connection rather than the panel."},
{id:"u4l3-5",t:"u4l3",q:"A user connected a new 144 Hz monitor, but it runs at only 60 Hz. What should the technician check?",a:["The monitor's pixel density","Whether the monitor is IPS or VA","The color gamut setting","The cable and port version, and the refresh rate setting in the operating system"],c:3,e:"High refresh rates need enough cable and port bandwidth for the resolution, and the refresh rate must be selected in the display settings. Density and gamut do not affect refresh."},

// u5l1
{id:"u5l1-1",t:"u5l1",q:"Which memory module has 288 pins, runs at 1.2 V, and is the most common desktop memory in service?",a:["DDR4 DIMM","DDR3 DIMM","DDR5 SODIMM","DDR3 SODIMM"],c:0,e:"DDR4 DIMMs have 288 pins at 1.2 V. DDR3 DIMMs have 240 pins at 1.5 V, and DDR5 DIMMs also have 288 pins but a different notch and 1.1 V."},
{id:"u5l1-2",t:"u5l1",q:"A technician installs a second identical memory module in a desktop to enable dual-channel operation. Where should it be placed?",a:["In the slot immediately next to the first module","In the paired slot indicated by the motherboard manual, usually matching in color","In any empty slot","In the slot farthest from the CPU"],c:1,e:"Dual channel requires matched modules in the slots the board pairs together, typically color-coded. Placing modules side by side in unpaired slots can leave the system in single-channel mode."},
{id:"u5l1-3",t:"u5l1",q:"A database server must detect and correct single-bit memory errors to avoid silent data corruption. Which memory type is required?",a:["Non-ECC unbuffered","Low-voltage DDR3","ECC","SODIMM"],c:2,e:"ECC (error-correcting code) memory detects and corrects single-bit errors. It requires support from both the CPU and the motherboard and is used in servers and workstations."},
{id:"u5l1-4",t:"u5l1",q:"A PC with 4 GB of RAM runs very slowly with several applications open, and the drive activity light stays on constantly. What is the BEST fix?",a:["Increase the size of the paging file","Defragment the drive","Replace the CPU","Add more RAM"],c:3,e:"Constant drive activity under memory pressure means the OS is paging to disk because RAM is full. Adding RAM removes the bottleneck; a larger paging file only enlarges the slow overflow."},
{id:"u5l1-5",t:"u5l1",q:"After installing a DDR4-3200 module in a board rated for DDR4-2666, at what speed will the memory operate?",a:["2666 MT/s","3200 MT/s","It will not boot","1600 MT/s"],c:0,e:"Memory runs at the speed the board and the slowest module support. A faster module simply operates at the board's supported speed of 2666 MT/s."},

// u5l2
{id:"u5l2-1",t:"u5l2",q:"A user wants the fastest possible boot drive for a desktop that has an M-keyed M.2 slot connected to PCIe lanes. Which drive should be chosen?",a:["A 2.5-inch SATA SSD","An M.2 NVMe SSD","An M.2 SATA SSD","A 7,200 rpm hard drive"],c:1,e:"NVMe drives use PCIe lanes and reach thousands of megabytes per second, far beyond the roughly 550 MB/s limit of any SATA drive, including M.2 SATA."},
{id:"u5l2-2",t:"u5l2",q:"A laptop hard drive has started making a repeated clicking sound and files open slowly. What should the technician do FIRST?",a:["Run a defragmentation","Update the SATA driver","Back up the data immediately","Reformat the drive"],c:2,e:"Clicking indicates a mechanical failure in progress. The priority is to back up the data before the drive dies completely, then replace it."},
{id:"u5l2-3",t:"u5l2",q:"Which storage controller type can accept both SAS and SATA drives?",a:["A SATA controller","A USB controller","An IDE controller","A SAS controller"],c:3,e:"SAS controllers and backplanes are compatible with SATA drives, but a SATA controller cannot operate SAS drives. This one-way compatibility is a common exam point."},
{id:"u5l2-4",t:"u5l2",q:"What does the designation 2280 on an M.2 SSD indicate?",a:["A width of 22 mm and a length of 80 mm","A capacity of 2,280 GB","A PCIe generation and lane count","A SATA revision"],c:0,e:"M.2 sizes encode width and length in millimeters: 2280 is 22 mm wide and 80 mm long, the most common size. The key (B, M, or B+M) is separate from the size."},
{id:"u5l2-5",t:"u5l2",q:"What is the capacity of a standard single-layer DVD?",a:["700 MB","4.7 GB","8.5 GB","25 GB"],c:1,e:"A single-layer DVD holds 4.7 GB; dual-layer holds 8.5 GB. A CD holds 700 MB and a single-layer Blu-ray disc holds 25 GB."},

// u5l3
{id:"u5l3-1",t:"u5l3",q:"A server has four 4 TB drives configured as RAID 10. How much usable capacity does the array provide?",a:["16 TB","12 TB","8 TB","4 TB"],c:2,e:"RAID 10 mirrors pairs and stripes across them, so usable capacity is half the total: 4 x 4 TB = 16 TB, halved to 8 TB. RAID 5 would give 12 TB and RAID 0 would give 16 TB."},
{id:"u5l3-2",t:"u5l3",q:"Which RAID level requires a minimum of four drives and can survive the failure of any two drives?",a:["RAID 1","RAID 5","RAID 0","RAID 6"],c:3,e:"RAID 6 uses two independent parity sets across at least four drives and tolerates two simultaneous failures. RAID 5 tolerates one, RAID 1 mirrors two drives, and RAID 0 tolerates none."},
{id:"u5l3-3",t:"u5l3",q:"A video editor wants maximum read and write speed from two drives and keeps all source files backed up elsewhere. Which RAID level fits?",a:["RAID 0","RAID 1","RAID 5","RAID 10"],c:0,e:"RAID 0 stripes data across drives for the best speed and full capacity, with no fault tolerance. Because the data is backed up elsewhere, the lack of protection is acceptable."},
{id:"u5l3-4",t:"u5l3",q:"Five 2 TB drives are configured in RAID 5. What is the usable capacity and how many drives can fail without data loss?",a:["10 TB; no failures","8 TB; one failure","6 TB; two failures","5 TB; one failure"],c:1,e:"RAID 5 loses one drive's worth of space to parity: (5 minus 1) x 2 TB = 8 TB, and it survives one drive failure. RAID 6 would give 6 TB and survive two."},
{id:"u5l3-5",t:"u5l3",q:"A RAID 5 array shows an amber light on one drive bay and an audible alarm, but the server is still running. What should the technician do?",a:["Nothing; the array is still functional","Convert the array to RAID 0 to restore performance","Replace the failed drive promptly so the array can rebuild before a second failure occurs","Power off the server until a new controller arrives"],c:2,e:"A degraded RAID 5 array runs without protection and slower. Replacing the failed drive starts the rebuild; a second failure before it completes would lose the array."},

// u5l4
{id:"u5l4-1",t:"u5l4",q:"Which motherboard form factor measures 6.7 x 6.7 inches and is used for compact builds with a single expansion slot?",a:["ATX","microATX","E-ATX","Mini-ITX"],c:3,e:"Mini-ITX boards are 170 mm (6.7 inches) square with one expansion slot. ATX is 12 x 9.6 inches and microATX is 9.6 x 9.6 inches."},
{id:"u5l4-2",t:"u5l4",q:"A newly assembled PC shows no signs of POST, and the technician discovers an extra brass standoff under the motherboard that does not align with a mounting hole. What is the MOST likely problem?",a:["The standoff is shorting the board to the case","The CPU is not compatible with the chipset","The memory is not seated","The power supply selector is on the wrong voltage"],c:0,e:"A standoff touching the underside of the board where there is no mounting hole creates a short circuit that prevents the board from starting. Remove it and retest."},
{id:"u5l4-3",t:"u5l4",q:"Which connector supplies power specifically to the CPU's voltage regulators on a motherboard?",a:["The 24-pin main connector","The 4- or 8-pin EPS connector","The 6-pin PCIe connector","The 15-pin SATA connector"],c:1,e:"The EPS 4-pin or 8-pin connector near the socket powers the CPU voltage regulators. The 24-pin connector feeds the board generally, PCIe connectors feed graphics cards, and SATA power feeds drives."},
{id:"u5l4-4",t:"u5l4",q:"Which CPU socket design places the pins in the socket rather than on the processor?",a:["PGA","AM4","LGA","ZIF"],c:2,e:"LGA (land grid array) sockets contain the pins, and the CPU has flat contacts. Intel uses LGA, as does AMD's AM5; AM4 is a PGA socket with pins on the chip."},
{id:"u5l4-5",t:"u5l4",q:"A technician wants to install a PCIe x1 sound card, but the only open slot on the board is a PCIe x16 slot. What is the result?",a:["The card will not fit","The slot must be converted in firmware","The card will run at x16 speed","The card will fit and operate using one lane"],c:3,e:"A shorter PCIe card fits in any longer slot and uses only its own lanes. An x1 card in an x16 slot works normally at x1 bandwidth."},

// u5l5
{id:"u5l5-1",t:"u5l5",q:"A desktop prompts the user to set the date and time at every startup, and websites report certificate errors until it is corrected. What should be replaced?",a:["The CMOS battery","The power supply","The TPM module","The hard drive"],c:0,e:"The CR2032 CMOS battery keeps the clock and firmware settings when the PC is off. When it dies, the clock resets, which also breaks certificate validation and authentication."},
{id:"u5l5-2",t:"u5l5",q:"A developer installs a hypervisor and receives an error stating that hardware virtualization is not available, although the CPU supports it. What should be done?",a:["Install more RAM","Enable VT-x or AMD-V in the firmware settings","Disable Secure Boot","Convert the disk to GPT"],c:1,e:"Hardware virtualization support is a firmware setting that is sometimes disabled by default. Enabling Intel VT-x or AMD-V allows hypervisors and virtualization-based features to run."},
{id:"u5l5-3",t:"u5l5",q:"Which firmware feature allows only digitally signed boot loaders to run, protecting against boot-sector malware?",a:["A supervisor password","USB permissions","Secure Boot","Fast boot"],c:2,e:"Secure Boot, part of UEFI, verifies the signature of the boot loader before running it. It requires UEFI mode with a GPT disk and may need to be disabled for some older media."},
{id:"u5l5-4",t:"u5l5",q:"Which component on a motherboard stores encryption keys for BitLocker and is required by Windows 11?",a:["A hardware security module","The chipset","The CMOS chip","The Trusted Platform Module"],c:3,e:"The TPM (version 2.0 for Windows 11) stores keys and measures the boot process. An HSM is a separate enterprise appliance, not a component on a PC motherboard."},
{id:"u5l5-5",t:"u5l5",q:"A company wants to prevent lab users from booting the PCs from USB drives and from changing that setting. Which two actions accomplish this?",a:["Set the boot order to the internal drive only and set a supervisor password","Remove the USB ports and disable the network","Enable fast boot and disable Secure Boot","Clear the CMOS and enable virtualization"],c:0,e:"Removing USB from the boot order (or disabling USB boot) stops the behavior, and a supervisor password prevents users from re-enabling it in firmware setup."},

// u5l6
{id:"u5l6-1",t:"u5l6",q:"A user with an ARM-based laptop cannot install a device driver written for x64 Windows. Why?",a:["ARM laptops cannot run any drivers","Software and drivers must be compiled for the ARM architecture","The laptop needs more RAM","The driver requires a 32-bit operating system"],c:1,e:"ARM is a different instruction set from x86 and x64. Drivers and native software must be built for ARM; x64 drivers cannot be loaded even if some x64 applications run through emulation."},
{id:"u5l6-2",t:"u5l6",q:"A technician removes a CPU cooler to replace the motherboard and later reinstalls the same cooler. What must be done during reinstallation?",a:["Update the CPU microcode","Reverse the fan direction","Clean both surfaces and apply fresh thermal paste","Replace the CPU"],c:2,e:"Thermal paste must be renewed whenever the cooler is removed, because the old layer no longer fills the gap evenly. Clean with isopropyl alcohol and apply a thin new layer."},
{id:"u5l6-3",t:"u5l6",q:"A newly installed graphics card is not detected and the monitor shows no image, though the system powers on. What should be checked FIRST?",a:["The monitor's color gamut","The DNS settings","Whether the CPU supports virtualization","Whether the card is fully seated and its PCIe power connectors are attached"],c:3,e:"An undetected card is usually not fully seated in the slot or is missing its supplemental power connector. Both must be checked before suspecting a defective card."},
{id:"u5l6-4",t:"u5l6",q:"A streamer wants to record the video output of a game console on a PC. Which expansion card is needed?",a:["A capture card","A sound card","A network interface card","A RAID controller"],c:0,e:"A capture card accepts an HDMI or similar video input and records or streams it. Sound cards handle audio, NICs handle networking."},
{id:"u5l6-5",t:"u5l6",q:"A desktop that used to run quietly now has loud fans and shuts down during demanding tasks. Firmware shows high CPU temperatures at idle. What is the MOST likely cause?",a:["The power supply is too large","Dust buildup and dried thermal paste are preventing effective cooling","The RAM is running in single channel","The boot order is wrong"],c:1,e:"Dust in the heat sink and filters, together with dried thermal paste, raises temperatures until the system throttles and shuts down. Cleaning and repasting restores normal operation."},

// u5l7
{id:"u5l7-1",t:"u5l7",q:"A PC shipped from Europe fails with a loud pop and a burning smell the moment it is plugged into a North American outlet. What MOST likely happened?",a:["The outlet delivered too little voltage","The CMOS battery shorted","The power supply's voltage selector was set incorrectly for the outlet","The graphics card drew too much current"],c:2,e:"A supply set to 115 V and connected to 230 V (or a mismatch in the other direction on some units) overloads the input stage. Auto-switching supplies avoid this, but a manual selector must match the mains."},
{id:"u5l7-2",t:"u5l7",q:"Which power supply rail carries most of the load for the CPU, graphics card, and drive motors?",a:["3.3 V","5 V","Negative 12 V","12 V"],c:3,e:"The 12 V rail (yellow wires) feeds the CPU voltage regulators through the EPS connector, the graphics card through PCIe connectors, and drive motors. The 3.3 V and 5 V rails feed logic and USB."},
{id:"u5l7-3",t:"u5l7",q:"After installing a high-end graphics card that requires two 8-pin power connectors, a PC restarts whenever a game starts. The original 450 W supply is still installed. What is the MOST likely cause?",a:["The power supply cannot deliver enough wattage under load","The card is in the wrong PCIe slot","The monitor refresh rate is too high","The RAM needs to be upgraded"],c:0,e:"High-end graphics cards can draw 300 W or more. A supply without enough capacity sags under load and the system resets, so it must be replaced with one sized for the total draw plus headroom."},
{id:"u5l7-4",t:"u5l7",q:"What does an 80 Plus Gold rating on a power supply indicate?",a:["It delivers 80 W of continuous power","It converts about 90 percent of input power into usable output at typical load","It has gold-plated connectors","It supports 220 V input only"],c:1,e:"80 Plus tiers certify efficiency: Bronze about 85 percent, Gold about 90 percent, Titanium about 94 percent. Higher efficiency means less heat and lower electricity use."},
{id:"u5l7-5",t:"u5l7",q:"Which power supply feature allows a server to keep running when one of its supply modules fails?",a:["A modular cable design","An 80 Plus Titanium rating","Redundant hot-swappable power supplies","A 20+4 pin connector"],c:2,e:"Redundant supplies share the load, and if one fails the remaining unit carries the server while an alert is raised. The failed module can be swapped without shutting down."},

// u6l1
{id:"u6l1-1",t:"u6l1",q:"A graphic design firm needs printed output that is identical regardless of which printer model renders the job. Which page description language should the driver use?",a:["PCL","ESC/P","Host-based printing","PostScript"],c:3,e:"PostScript is a device-independent page description language that renders identically on any PostScript printer, which is why publishing and design workflows rely on it. PCL is faster but printer-dependent."},
{id:"u6l1-2",t:"u6l1",q:"Every Monday morning, an office printer that was working on Friday shows as offline until a technician updates its IP address on each computer. What is the BEST permanent fix?",a:["Assign the printer a static IP address or a DHCP reservation","Restart the print spooler every Monday","Switch the printer to USB","Reinstall the driver weekly"],c:0,e:"The printer is receiving a different DHCP address after its lease expires. A static address or a reservation keeps the address constant so clients always find it."},
{id:"u6l1-3",t:"u6l1",q:"Human resources reports that confidential documents are being picked up from the printer's output tray by other employees. Which feature solves this?",a:["Duplex printing","Secured print released with a PIN or badge at the device","Draft quality mode","Scan to email"],c:1,e:"Secured (held) print keeps the job on the printer until the owner authenticates at the panel, so pages never sit unattended in the tray."},
{id:"u6l1-4",t:"u6l1",q:"A multifunction printer's scan-to-folder function stopped working right after the company forced a password change on all accounts. What should be updated?",a:["The printer's firmware","The SMTP server address","The credentials for the service account stored on the printer","The paper tray settings"],c:2,e:"Scan to folder writes to an SMB share using an account whose password is saved on the printer. When that password changes, the saved credentials must be updated."},
{id:"u6l1-5",t:"u6l1",q:"A company with sixty users and eight printers wants drivers deployed automatically and printing usage logged centrally. Which approach should be used?",a:["Share each printer from the nearest user's PC","Connect each printer by USB to a workstation","Have each user add printers by IP address","Configure a print server that hosts the queues and drivers"],c:3,e:"A print server centralizes queues, pushes the correct drivers to clients, applies default settings, and keeps logs. PC sharing depends on that PC being on, and direct IP offers no central control."},

// u6l2
{id:"u6l2-1",t:"u6l2",q:"In the laser printing process, which step applies a uniform negative charge of about minus 600 V to the imaging drum?",a:["Charging","Exposing","Developing","Transferring"],c:0,e:"Charging comes second, after processing, and uses the primary charge roller or corona wire to place a uniform negative charge on the drum before the laser writes the image."},
{id:"u6l2-2",t:"u6l2",q:"Which laser printing step immediately follows exposing?",a:["Fusing","Developing","Cleaning","Charging"],c:1,e:"The order is processing, charging, exposing, developing, transferring, fusing, cleaning. After the laser exposes the image, toner is applied to the drum in the developing step."},
{id:"u6l2-3",t:"u6l2",q:"Pages from a laser printer look correct but the toner smears off when touched. Which component has MOST likely failed?",a:["The imaging drum","The transfer roller","The fuser assembly","The pickup roller"],c:2,e:"Toner that reaches the paper but does not bond has not been fused. The fuser's heated roller and pressure roller melt toner into the paper; a failed or cold fuser leaves it loose."},
{id:"u6l2-4",t:"u6l2",q:"A laser printer frequently pulls two or three sheets at a time from the tray. Which parts should be replaced?",a:["The fuser and the laser scanner","The toner cartridge","The formatter board","The pickup rollers and separation pad, typically as part of a maintenance kit"],c:3,e:"The separation pad allows only one sheet through, and worn rollers and pads cause multi-sheet feeds. Both are included in the printer's maintenance kit."},
{id:"u6l2-5",t:"u6l2",q:"Toner has spilled inside a laser printer. What is the correct way to clean it?",a:["Use a toner-rated vacuum with a HEPA filter and lint-free cloths","Use a household vacuum cleaner","Blow it out with compressed air","Wipe it with a wet paper towel"],c:0,e:"Compressed air spreads fine toner into the air and mechanism, and household vacuums let the particles pass through and can ignite them. A toner-rated vacuum is the safe method."},

// u6l3
{id:"u6l3-1",t:"u6l3",q:"A warehouse must print three-part carbonless invoices in a single pass. Which printer type is the only one suited to this?",a:["Laser","Impact (dot matrix)","Thermal","Inkjet"],c:1,e:"Impact printers strike the paper through a ribbon with enough force to print through multipart carbonless forms. No other type transfers an image to the copies underneath."},
{id:"u6l3-2",t:"u6l3",q:"An inkjet printer produces text with horizontal gaps and missing lines. What should the technician try FIRST?",a:["Replace the carriage belt","Replace the feed rollers","Run the print head cleaning routine","Switch to PostScript"],c:2,e:"Missing lines mean some nozzles are clogged. The cleaning cycle purges dried ink from the print head; alignment is for misregistration, and the belt affects head movement, not output gaps."},
{id:"u6l3-3",t:"u6l3",q:"A receipt printer at a checkout suddenly produces blank receipts after a new roll of paper was loaded. What is the MOST likely cause?",a:["The ribbon is worn out","The printer needs toner","The print head pins are broken","The thermal paper was loaded with the coated side facing away from the heating element"],c:3,e:"Thermal printers darken a heat-sensitive coating on one side of the paper. Loaded backward, the element heats the uncoated side and nothing appears. Thermal printers use no ribbon, ink, or toner."},
{id:"u6l3-4",t:"u6l3",q:"A dot matrix printer prints every character with the same horizontal row of dots missing. Which part should be replaced?",a:["The print head","The ribbon","The tractor feed","The platen"],c:0,e:"A dot missing in the same position on every character means one pin in the print head is broken. A worn ribbon causes even fading, not a consistent missing row."},
{id:"u6l3-5",t:"u6l3",q:"Which maintenance step is appropriate for a thermal label printer that produces faint, streaky output?",a:["Replace the ink cartridge","Clean the heating element with isopropyl alcohol on a lint-free swab","Run a head alignment","Replace the toner cartridge"],c:1,e:"Thermal printers have no ink or toner. Residue on the heating element causes faint or streaked print; cleaning it with isopropyl alcohol is the standard maintenance."}
);
