// APlus Academy Core 1 question bank, units 1 to 3. All questions are original.
// Fields: id, t (lesson id), q (stem), a (four options), c (index of correct option), e (explanation).
window.FRA = window.FRA || {};
FRA.questions = FRA.questions || [];
FRA.questions.push(
// u1l1
{id:"u1l1-1",t:"u1l1",q:"A technician is about to replace the keyboard in a laptop that has an internal battery. Which step should be taken FIRST?",a:["Remove the keyboard ribbon cable from its ZIF connector","Disconnect the AC adapter and the internal battery connector","Update the keyboard firmware","Remove the display assembly"],c:1,e:"Every internal laptop repair begins by shutting down, unplugging the adapter, and disconnecting or removing the battery so no power reaches the board while cables are moved. The ribbon cable comes out only after that."},
{id:"u1l1-2",t:"u1l1",q:"After a laptop's wireless card was replaced, the user reports one bar of Wi-Fi signal next to a phone showing full signal. What is the MOST likely cause?",a:["The new card is DDR4 instead of DDR5","The laptop is in airplane mode","An antenna lead was left disconnected from the card","The SSID was changed during the repair"],c:2,e:"The wireless card has two tiny antenna leads that must be snapped onto their terminals. A lead left off or on the wrong terminal gives a weak signal. Airplane mode would give no signal at all, and the SSID would not affect strength."},
{id:"u1l1-3",t:"u1l1",q:"The trackpad on a two-year-old laptop has started to bulge upward and the bottom cover no longer sits flat. What should the technician do?",a:["Reseat the trackpad ribbon cable","Recalibrate the trackpad in the operating system","Tighten the bottom cover screws","Replace the swollen battery and stop using the laptop until it is replaced"],c:3,e:"A bulging trackpad or keyboard on a laptop is a swollen lithium-ion battery pushing up from underneath. The battery must be replaced and handled without puncturing; continuing to use it is a fire hazard."},
{id:"u1l1-4",t:"u1l1",q:"Which memory module type is installed in the angled slots found under a laptop's bottom cover?",a:["SODIMM","DIMM","ECC registered DIMM","M.2 2280"],c:0,e:"Laptops use small outline DIMMs (SODIMMs), inserted at an angle and pressed down until the side clips catch. Full-size DIMMs are desktop modules, and M.2 2280 is a storage form factor."},
{id:"u1l1-5",t:"u1l1",q:"Where are the Wi-Fi antennas of a typical laptop physically routed?",a:["Along the bottom cover next to the RAM slots","Inside the lid around the display, with leads running through the hinge","Inside the optical drive bay","Along the front edge below the trackpad"],c:1,e:"Laptop wireless antennas are placed around the display in the lid, where they sit high and clear of the metal in the base. Their leads pass through the hinge to the wireless card on the board."},

// u1l2
{id:"u1l2-1",t:"u1l2",q:"A user wants to sit at a desk, plug one cable into a thin laptop, and have it charge, drive two external monitors, and connect to wired Ethernet. Which accessory meets this need?",a:["A USB port replicator","A powered USB hub","A Thunderbolt or USB-C docking station","An HDMI splitter"],c:2,e:"A docking station over Thunderbolt or USB-C carries power delivery to charge the laptop, video for multiple monitors, Ethernet, and USB through a single connection. A port replicator adds ports but typically does not charge or drive multiple high-resolution displays."},
{id:"u1l2-2",t:"u1l2",q:"Which connector is reversible and can carry USB data, DisplayPort video, and up to 240 W of power depending on the device?",a:["USB Type A","microUSB","miniUSB","USB-C"],c:3,e:"USB-C is a reversible 24-pin connector that can carry USB data, DisplayPort alternate mode video, Thunderbolt, and power delivery. microUSB, miniUSB, and Type A are one-way connectors without those capabilities."},
{id:"u1l2-3",t:"u1l2",q:"A salesperson needs a laptop online through a phone's cellular data while the phone also charges. Which method fits BEST?",a:["USB tethering","Bluetooth tethering","NFC tethering","Wi-Fi hotspot"],c:0,e:"USB tethering shares the phone's cellular data over a cable that also charges the phone, and it is the most reliable method. Bluetooth tethering is slowest, a hotspot drains the phone's battery, and NFC has a range of a few centimeters."},
{id:"u1l2-4",t:"u1l2",q:"A customer taps a phone against a payment terminal to pay for coffee. Which technology performs the exchange?",a:["Bluetooth","Near field communication","Wi-Fi Direct","Infrared"],c:1,e:"NFC operates at 13.56 MHz over about 4 cm, which is why the phone must nearly touch the terminal. That short range is a security feature for payments and badge readers."},
{id:"u1l2-5",t:"u1l2",q:"A newly purchased active stylus does nothing when touched to a tablet screen, although fingers work normally. What should be checked FIRST?",a:["Whether the screen protector is too thick","Whether the tablet's screen resolution is set too high","Whether the stylus is charged or has a battery and is paired to the tablet","Whether the tablet is in airplane mode"],c:2,e:"An active stylus contains electronics that need a battery or a charge and often need pairing, and it must be a model supported by the device. A passive stylus would work anywhere a finger works."},

// u1l3
{id:"u1l3-1",t:"u1l3",q:"A user's phone shows no cellular signal, no Wi-Fi networks, and no Bluetooth devices. What should the technician check FIRST?",a:["Whether the SIM card is seated","Whether the phone's storage is full","Whether the carrier settings need an update","Whether airplane mode is enabled"],c:3,e:"Airplane mode switches off every radio at once, which matches all three symptoms together. A SIM problem would affect cellular only, and carrier settings would not disable Wi-Fi or Bluetooth."},
{id:"u1l3-2",t:"u1l3",q:"Which component stores the subscriber identity that lets a phone onto a carrier's network and moves the phone number when transferred to another handset?",a:["The SIM card","The baseband processor","The NFC chip","The eSIM QR code"],c:0,e:"The SIM card holds the subscriber identity and keys; moving the card moves the number and plan. An eSIM performs the same role as a soldered chip provisioned with a downloaded profile rather than a removable card."},
{id:"u1l3-3",t:"u1l3",q:"A technician is pairing a Bluetooth headset with a phone. After turning Bluetooth on in the phone, what is the NEXT step?",a:["Enter the PIN on the phone","Put the headset into pairing mode so it is discoverable","Test audio playback","Select the headset from the list of found devices"],c:1,e:"The order is: enable Bluetooth, make the accessory discoverable, select it from the list, enter or confirm the PIN, then test. A headset that is not in pairing mode never appears in the list."},
{id:"u1l3-4",t:"u1l3",q:"A delivery app locates a driver accurately on the road but cannot fix a position inside a warehouse. Which location method is the app depending on?",a:["Cellular tower triangulation","Wi-Fi positioning","GPS satellite positioning","Bluetooth beacons"],c:2,e:"GPS needs a view of the sky and is accurate outdoors but fails indoors. Cellular and Wi-Fi positioning work inside buildings with less precision, which is why phones blend the methods."},
{id:"u1l3-5",t:"u1l3",q:"A company wants to add a work phone line to an employee's existing phone without inserting a second physical card. Which feature makes this possible?",a:["Dual-band Wi-Fi","A PRL update","A hotspot","An eSIM profile"],c:3,e:"An eSIM is a chip built into the phone that can hold one or more carrier profiles downloaded by QR code or app, so a second line can be added without a physical SIM card."},

// u1l4
{id:"u1l4-1",t:"u1l4",q:"An employee who used a personal phone for corporate email under a BYOD policy is leaving the company. Which MDM action removes the company data while leaving personal photos untouched?",a:["A selective wipe of the work profile","A full factory reset","Disabling the phone's camera","Revoking the SIM card"],c:0,e:"On a BYOD device, company data lives in a managed work profile or container. A selective wipe removes that container only; a full wipe would erase the employee's personal data, which is inappropriate on a device they own."},
{id:"u1l4-2",t:"u1l4",q:"A user's phone was blocked from corporate email after they postponed an operating system update for several weeks. What is the MOST likely reason?",a:["The mail server's MX record expired","The device fell out of MDM compliance with the minimum OS version policy","The phone's storage is full","The SIM card needs reprovisioning"],c:1,e:"MDM policies commonly require a minimum OS version, encryption, and a passcode. A device that no longer meets policy is marked non-compliant and blocked from corporate resources until it is brought back into compliance."},
{id:"u1l4-3",t:"u1l4",q:"Which policy set is typical of a fully managed corporate-owned phone rather than a BYOD device?",a:["A work profile with a selective wipe option only","No passcode requirement","Restrictions on the camera and app stores plus full device wipe","Personal apps blocked from the personal side of the device"],c:2,e:"Corporate-owned devices are fully enrolled, so IT can restrict hardware features such as the camera, control app stores, and wipe the entire device. BYOD management is limited to a work container."},
{id:"u1l4-4",t:"u1l4",q:"A user exceeds the cellular data plan every month even though they rarely browse on the phone. What is the MOST likely cause?",a:["Bluetooth is left enabled","Location services are enabled","The phone is set to prefer 5G","Photo and cloud file synchronization is running over cellular"],c:3,e:"Large photo libraries and cloud storage sync silently in the background and can consume gigabytes over cellular. Setting sync to Wi-Fi only, and disabling background data for the app, solves it."},
{id:"u1l4-5",t:"u1l4",q:"A contact edited on a phone and separately on a laptop before either device synchronized now appears twice in the address book. What is this situation called?",a:["A sync conflict","A data cap overrun","A selective wipe","Containerization"],c:0,e:"A synchronization conflict happens when the same item is changed in two places before they sync. Systems resolve it by keeping the latest edit or by creating a duplicate that the user must merge."},

// u2l1
{id:"u2l1-1",t:"u2l1",q:"A PC can ping every other device on its own subnet but cannot reach any address on the internet. Which configuration item is the MOST likely fault?",a:["The MAC address","The default gateway","The DNS suffix","The link speed"],c:1,e:"Traffic for other networks is sent to the default gateway. If the gateway is missing, mistyped, or outside the subnet, local communication works while everything beyond the router fails."},
{id:"u2l1-2",t:"u2l1",q:"Which address does a switch examine to decide which port should receive a frame?",a:["The destination IP address","The destination port number","The destination MAC address","The default gateway address"],c:2,e:"Switches forward frames by MAC address, learning which MAC is on which port from the traffic they see. Routers, not switches, look at IP addresses."},
{id:"u2l1-3",t:"u2l1",q:"What information can be read from the first three pairs of hex digits in a network adapter's MAC address?",a:["The subnet it belongs to","The VLAN it is on","The IP address assigned by DHCP","The manufacturer of the adapter"],c:3,e:"A MAC address is 48 bits shown as six hex pairs; the first three pairs form the organizationally unique identifier that identifies the manufacturer, and the last three are the device's serial portion."},
{id:"u2l1-4",t:"u2l1",q:"Which protocol lets a computer discover the MAC address that belongs to a known IPv4 address on its local network?",a:["ARP","DHCP","DNS","SNMP"],c:0,e:"Address resolution protocol broadcasts a request for the owner of an IP address, and that device replies with its MAC address. The result is cached briefly for later frames."},
{id:"u2l1-5",t:"u2l1",q:"When troubleshooting a workstation that cannot reach a website, which order of checks follows the layers from the bottom up?",a:["DNS resolution, IP configuration, link light, application","Link light, IP configuration, gateway reachability, DNS resolution, application","Application, gateway, link light, DNS","Gateway, DNS, link light, IP configuration"],c:1,e:"Working from the physical layer upward (link, IP address, gateway, name resolution, application) finds the simplest fault first and avoids guessing about DNS when a cable is unplugged."},

// u2l2
{id:"u2l2-1",t:"u2l2",q:"A technician needs to open a firewall port so remote users can connect with Remote Desktop. Which port must be allowed?",a:["TCP 22","TCP 445","TCP 3389","UDP 161"],c:2,e:"Remote Desktop Protocol uses TCP port 3389. Port 445 is SMB file sharing, 22 is SSH, and UDP 161 is SNMP."},
{id:"u2l2-2",t:"u2l2",q:"A security audit finds that network switches are managed with a protocol that sends passwords in clear text on port 23. Which protocol and port should replace it?",a:["RDP on 3389","Telnet on 25","HTTPS on 443","SSH on 22"],c:3,e:"Telnet on port 23 transmits credentials in clear text. SSH on port 22 provides an encrypted remote shell and is its direct replacement on network devices."},
{id:"u2l2-3",t:"u2l2",q:"Which pair of UDP ports is used when a client obtains an IP address automatically from a server?",a:["67 and 68","137 and 139","20 and 21","161 and 162"],c:0,e:"DHCP uses UDP port 67 on the server and 68 on the client. Ports 20 and 21 are FTP, 137 to 139 are NetBIOS, and 161 and 162 are SNMP."},
{id:"u2l2-4",t:"u2l2",q:"A user's mail client keeps a synchronized copy of the mailbox on the phone, laptop, and webmail. Which protocol and default port is the client using to receive mail?",a:["POP3 on 110","IMAP on 143","SMTP on 25","LDAP on 389"],c:1,e:"IMAP (port 143, or 993 with TLS) leaves mail on the server and synchronizes state across devices. POP3 downloads mail to one device, SMTP sends mail, and LDAP is a directory protocol."},
{id:"u2l2-5",t:"u2l2",q:"Why do voice and video streaming applications typically use UDP rather than TCP?",a:["UDP encrypts the stream automatically","UDP retransmits lost packets faster than TCP","UDP avoids the handshake and retransmission delays, and a late packet is worthless for real-time media","UDP uses well-known ports below 1024"],c:2,e:"UDP is connectionless with no acknowledgments or retransmissions, so it adds minimal delay. For real-time media a late retransmitted packet has no value, so speed is preferred over reliability."},

// u2l3
{id:"u2l3-1",t:"u2l3",q:"Three access points on the 2.4 GHz band in one office are set to channels 2, 4, and 7, and users report slow wireless. Which channel plan would fix the interference?",a:["A single channel on all three access points","Channels 1, 2, and 3","Channels 36, 40, and 44","Channels 1, 6, and 11"],c:3,e:"In the 2.4 GHz band only channels 1, 6, and 11 do not overlap at 20 MHz width. Adjacent channels such as 2, 4, and 7 overlap and interfere. Channels 36 and above belong to the 5 GHz band."},
{id:"u2l3-2",t:"u2l3",q:"Which wireless standard operates ONLY in the 5 GHz band?",a:["802.11ac","802.11n","802.11ax","802.11g"],c:0,e:"802.11ac (Wi-Fi 5) is a 5 GHz only standard. 802.11n and 802.11ax use both 2.4 and 5 GHz, and 802.11g is 2.4 GHz only."},
{id:"u2l3-3",t:"u2l3",q:"A warehouse needs wireless coverage across a large open floor with thick walls between sections, and speed is not critical. Which band gives the best range and penetration?",a:["6 GHz","2.4 GHz","5 GHz","60 GHz"],c:1,e:"Lower frequencies travel farther and pass through walls better. The 2.4 GHz band has the longest range and best penetration, at the cost of fewer channels and more interference."},
{id:"u2l3-4",t:"u2l3",q:"Which Wi-Fi generation first added the 6 GHz band?",a:["Wi-Fi 4 (802.11n)","Wi-Fi 5 (802.11ac)","Wi-Fi 6E (802.11ax extended)","Wi-Fi 3 (802.11g)"],c:2,e:"Wi-Fi 6E extended 802.11ax into the 6 GHz band, and Wi-Fi 7 (802.11be) uses it as well. Wi-Fi 5 is 5 GHz only and Wi-Fi 4 uses 2.4 and 5 GHz."},
{id:"u2l3-5",t:"u2l3",q:"A retailer attaches tags to inventory that contain no battery and are read by a handheld scanner from a meter away. Which technology is this?",a:["Bluetooth Low Energy","Active RFID","NFC","Passive RFID"],c:3,e:"Passive RFID tags are powered by the reader's radio field and need no battery, which makes them cheap enough for inventory labels. Active tags carry a battery for longer range, and NFC works only within a few centimeters."},

// u2l4
{id:"u2l4-1",t:"u2l4",q:"A small clinic needs its IP phones on a separate voice network from its computers, using a single switch. Which device is required?",a:["A managed switch","An unmanaged switch","A hub","A PoE injector"],c:0,e:"Separating voice and data on one switch means VLANs, which are configured only on a managed switch. Unmanaged switches have no configuration interface."},
{id:"u2l4-2",t:"u2l4",q:"A fiber internet installation ends at a small box on the wall that converts the optical signal to an Ethernet port for the customer's router. What is this box?",a:["A cable modem","An optical network terminal","A DSL modem","A patch panel"],c:1,e:"The ONT (optical network terminal) terminates the fiber at the premises and presents an Ethernet port. Cable and DSL modems serve coax and phone lines respectively."},
{id:"u2l4-3",t:"u2l4",q:"An access point at the far end of a long cable run needs power, but the switch in the closet does not support PoE. Which is the simplest solution?",a:["Replace the access point with a wireless router","Run a second Ethernet cable to the access point","Install a PoE injector on that run","Add a hub near the access point"],c:2,e:"A PoE injector adds power to a single Ethernet run between a non-PoE switch and a powered device. Replacing the whole switch is unnecessary for one device."},
{id:"u2l4-4",t:"u2l4",q:"Which Power over Ethernet standard supplies up to 30 W per port?",a:["802.3af","802.11ac","802.3bt Type 4","802.3at"],c:3,e:"802.3at (PoE+) delivers 30 W per port. 802.3af provides 15.4 W, 802.3bt provides 60 W (Type 3) or 100 W (Type 4), and 802.11ac is a wireless standard."},
{id:"u2l4-5",t:"u2l4",q:"In a wiring closet, the cable runs from wall jacks throughout a building are terminated on which device before being connected to the switch with short cables?",a:["A patch panel","A firewall","A network tap","A load balancer"],c:0,e:"Building cable runs are punched down on the back of a patch panel; short patch cables then link each panel port to a switch port. This protects the permanent cabling and simplifies moves."},

// u2l5
{id:"u2l5-1",t:"u2l5",q:"Users report that no websites load by name, but a technician can ping a public IP address successfully from a workstation. Which server is MOST likely down?",a:["The DHCP server","The DNS server","The proxy server","The syslog server"],c:1,e:"Name resolution failing while IP connectivity works points to DNS. A DHCP failure would show APIPA addresses, and a syslog failure is invisible to users."},
{id:"u2l5-2",t:"u2l5",q:"A company's public website slows badly during promotions and goes offline whenever its single web server reboots. Which appliance addresses both problems?",a:["A spam gateway","A proxy server","A load balancer with additional web servers","A UTM appliance"],c:2,e:"A load balancer distributes requests across several identical servers, adding capacity and letting one server fail or reboot without taking the site down."},
{id:"u2l5-3",t:"u2l5",q:"Which appliance combines a firewall, intrusion prevention, antivirus, and content filtering in a single box suited to a small business?",a:["A DHCP relay","A network tap","A print server","A unified threat management appliance"],c:3,e:"A UTM (unified threat management) appliance bundles several security functions so a small business can manage them in one place."},
{id:"u2l5-4",t:"u2l5",q:"A factory's SCADA system runs an operating system that no longer receives updates and controls production equipment. What is the BEST way to connect it?",a:["Keep it on an isolated network segment with only the required connections allowed","Connect it directly to the internet for vendor support","Place it on the guest wireless network","Install antivirus on it and join it to the office LAN"],c:0,e:"Legacy and embedded control systems cannot be patched and can halt production if disturbed. They belong on an isolated segment with strictly limited access and no internet exposure."},
{id:"u2l5-5",t:"u2l5",q:"Wireless users cannot sign in with their corporate credentials, while wired users continue working. Which server role should be investigated FIRST?",a:["The NTP server only","The AAA (RADIUS) server","The file server","The print server"],c:1,e:"Enterprise Wi-Fi authenticates users through an AAA server using RADIUS or TACACS+. Wired users often continue with cached credentials, so a RADIUS failure appears first on wireless."},

// u3l1
{id:"u3l1-1",t:"u3l1",q:"A workstation reports the address 169.254.71.9 and cannot reach the internet. What does this address indicate?",a:["The workstation has a static address on the wrong subnet","The workstation is using the loopback address","The workstation did not receive a response from a DHCP server","The workstation was assigned a public address"],c:2,e:"169.254.x.x is an APIPA address that a client assigns itself when its DHCP request goes unanswered. The fix is to check the link, the switch port or VLAN, and the DHCP server."},
{id:"u3l1-2",t:"u3l1",q:"Which of the following IPv4 addresses is in a private range and will not be routed on the internet?",a:["172.32.4.10","192.169.1.5","11.0.0.1","172.20.15.200"],c:3,e:"The private ranges are 10.0.0.0/8, 172.16.0.0 to 172.31.255.255, and 192.168.0.0/16. 172.20.15.200 falls inside the 172.16 to 172.31 block; 172.32, 192.169, and 11.x are public."},
{id:"u3l1-3",t:"u3l1",q:"A host is configured with address 192.168.10.57, mask 255.255.255.0, and gateway 192.168.1.1. It can reach local devices but not the internet. What is wrong?",a:["The gateway is outside the host's subnet","The subnet mask is too large","The address is an APIPA address","The DNS server is not set"],c:0,e:"With a /24 mask the host is on 192.168.10.0, but the gateway 192.168.1.1 is on 192.168.1.0. The host cannot reach a gateway outside its own subnet, so traffic to other networks fails."},
{id:"u3l1-4",t:"u3l1",q:"A network printer's IP address changes periodically and users lose their connection to it. Which solution keeps the address fixed with the least ongoing effort?",a:["Shorten the DHCP lease time","Configure a DHCP reservation for the printer's MAC address","Enable APIPA on the printer","Move the printer to the guest VLAN"],c:1,e:"A DHCP reservation ties a fixed address to the printer's MAC address so the server always assigns the same one. A static address on the printer also works but must be maintained on the device itself."},
{id:"u3l1-5",t:"u3l1",q:"Pinging which address verifies that the TCP/IP stack on the local machine is working, without involving the network card's link or any other device?",a:["192.168.1.1","169.254.0.1","127.0.0.1","255.255.255.255"],c:2,e:"127.0.0.1 is the IPv4 loopback address, which always refers to the local host. A successful ping shows the protocol stack is installed and functioning."},

// u3l2
{id:"u3l2-1",t:"u3l2",q:"Which of the following is an IPv6 link-local address that a device assigns to itself automatically?",a:["2001:db8::1","fd12:3456::1","::1","fe80::1c3a:9f2e:44b1:7d0c"],c:3,e:"Link-local addresses begin with fe80:: and exist on every IPv6 interface without any server. 2001:db8 is global unicast, ::1 is loopback, and fd12 is a unique local address."},
{id:"u3l2-2",t:"u3l2",q:"How many bits long is an IPv6 address?",a:["128","48","64","32"],c:0,e:"IPv6 addresses are 128 bits, written as eight groups of four hexadecimal digits. IPv4 addresses are 32 bits and MAC addresses are 48 bits."},
{id:"u3l2-3",t:"u3l2",q:"What does the double colon (::) represent in the address 2001:db8::ff00:42:8329?",a:["A wildcard for any interface","One or more consecutive groups of zeros, which may be compressed once per address","The subnet prefix length","A separator between the network and host portions"],c:1,e:"The :: notation replaces a single run of consecutive all-zero groups. It may appear only once in an address so the number of missing groups is unambiguous."},
{id:"u3l2-4",t:"u3l2",q:"A workstation shows an IPv4 address and a global IPv6 address on the same adapter and uses whichever the destination supports. What is this configuration called?",a:["Tunneling","NAT64","Dual stack","Link-local only"],c:2,e:"Dual stack runs IPv4 and IPv6 side by side on the same interface, with the operating system preferring IPv6 when the destination has an IPv6 address."},
{id:"u3l2-5",t:"u3l2",q:"Which IPv6 address serves the same purpose as 127.0.0.1 in IPv4?",a:["fe80::1","2000::1","ff02::1","::1"],c:3,e:"::1 is the IPv6 loopback address and always refers to the local host, just as 127.0.0.1 does in IPv4. fe80::1 is link-local and ff02::1 is a multicast address."},

// u3l3
{id:"u3l3-1",t:"u3l3",q:"A technician must make www.example.com resolve to the IPv6 address of a web server. Which DNS record type should be created?",a:["AAAA","A","CNAME","PTR"],c:0,e:"AAAA records map a hostname to an IPv6 address. A records map to IPv4, CNAME creates an alias, and PTR performs reverse lookups."},
{id:"u3l3-2",t:"u3l3",q:"After moving email to a cloud provider, a company's messages start landing in customers' spam folders. Which DNS record MOST likely still lists only the old mail server as an authorized sender?",a:["The MX record","The SPF TXT record","The A record","The CNAME record"],c:1,e:"SPF is a TXT record listing which servers may send mail for the domain. If the new provider's servers are not included, receivers see mail from an unauthorized source and mark it as spam."},
{id:"u3l3-3",t:"u3l3",q:"Which DNS record tells other mail servers where to deliver email addressed to users at a domain?",a:["TXT","NS","MX","AAAA"],c:2,e:"MX (mail exchanger) records identify the mail servers for a domain, with a priority number where the lowest is tried first. Without an MX record, mail to the domain cannot be delivered."},
{id:"u3l3-4",t:"u3l3",q:"Which email authentication mechanism attaches a cryptographic signature so receivers can verify a message came from the domain and was not altered in transit?",a:["SPF","PTR","DMARC","DKIM"],c:3,e:"DKIM signs outgoing messages with a private key; the public key is published in a DNS TXT record so receivers can verify the signature. SPF lists allowed senders and DMARC sets the policy."},
{id:"u3l3-5",t:"u3l3",q:"A domain owner wants receiving servers to reject messages that fail both SPF and DKIM checks and to send reports about them. Which record accomplishes this?",a:["A DMARC TXT record with a reject policy","An MX record with a low priority","A CNAME record pointing to the mail provider","An AAAA record for the mail server"],c:0,e:"DMARC is published as a TXT record and specifies the policy (none, quarantine, or reject) for messages failing authentication, along with addresses for aggregate and failure reports."},

// u3l4
{id:"u3l4-1",t:"u3l4",q:"Place the DHCP address assignment exchange in the correct order.",a:["Offer, Discover, Acknowledge, Request","Discover, Offer, Request, Acknowledge","Request, Offer, Discover, Acknowledge","Discover, Request, Offer, Acknowledge"],c:1,e:"The client broadcasts a Discover, a server responds with an Offer, the client broadcasts a Request for that offer, and the server sends an Acknowledge to start the lease. Remember it as DORA."},
{id:"u3l4-2",t:"u3l4",q:"A DHCP scope covers 192.168.5.50 through 192.168.5.200, but the file server uses static address 192.168.5.100. Which setting prevents the server from handing 192.168.5.100 to a laptop?",a:["A shorter lease time","A reservation for the laptop","An exclusion for 192.168.5.100","A DHCP relay"],c:2,e:"An exclusion removes addresses inside the scope from the pool so the server never assigns them. Without it, a client could receive the file server's address and both would suffer a duplicate address conflict."},
{id:"u3l4-3",t:"u3l4",q:"A company wants phones, staff computers, and guest wireless to be separated from each other while sharing the same physical switches. Which technology provides this?",a:["A VPN","A PoE injector","DHCP reservations","VLANs on managed switches"],c:3,e:"VLANs create separate logical networks on the same managed switch hardware. Traffic between VLANs must pass through a router or layer 3 switch where it can be controlled."},
{id:"u3l4-4",t:"u3l4",q:"A remote employee working from a hotel can browse the internet but cannot open the company's internal file shares. What is the MOST likely missing piece?",a:["A client-to-site VPN connection","A DHCP reservation","A DNS AAAA record","A VLAN trunk"],c:0,e:"Internal resources are reachable only from inside the company network. A client VPN makes the laptop appear to be on the office network through an encrypted tunnel across the internet."},
{id:"u3l4-5",t:"u3l4",q:"Two branch offices need a permanent, encrypted connection between their networks over the internet so users at either site can reach servers at the other. Which solution fits?",a:["A split-tunnel client VPN on each PC","A site-to-site VPN between the office routers","A guest VLAN at each site","A DHCP relay agent"],c:1,e:"A site-to-site VPN links two routers or firewalls with a persistent encrypted tunnel, joining the two networks without every user running a client."},

// u3l5
{id:"u3l5-1",t:"u3l5",q:"A technician has just connected a new SOHO router to the modem and logged into its web interface. What should be done FIRST?",a:["Enable port forwarding for the security cameras","Hide the SSID","Change the default administrator password","Turn on remote management"],c:2,e:"Default router credentials are publicly known, so changing the administrator password is the first step. Remote management and port forwarding should stay off unless specifically needed."},
{id:"u3l5-2",t:"u3l5",q:"A remote cabin has no phone or cable lines and no clear line of sight to a wireless tower. Which internet connection type is the only option?",a:["DSL","Cable","Fiber","Satellite"],c:3,e:"Satellite works anywhere with a view of the sky but has the highest latency and often data caps. DSL and cable need lines, fiber needs a fiber build-out, and WISP needs line of sight."},
{id:"u3l5-3",t:"u3l5",q:"A homeowner far from town has an internet connection that is much slower than the neighbors closer to the telephone exchange. Which connection type has this distance limitation?",a:["DSL","Cable","Fiber","Cellular"],c:0,e:"DSL runs over copper phone lines and its speed falls sharply with distance from the provider's equipment. Cable speed depends on neighborhood sharing rather than line length."},
{id:"u3l5-4",t:"u3l5",q:"Which network type describes a Bluetooth connection between a phone and a wireless headset?",a:["LAN","PAN","WAN","MAN"],c:1,e:"A personal area network covers a few meters around one person, which is exactly what Bluetooth provides. A LAN covers a site, a MAN a city, and a WAN spans regions."},
{id:"u3l5-5",t:"u3l5",q:"A data center gives its servers block-level access to shared disk arrays over a dedicated Fibre Channel or iSCSI network. What is this network called?",a:["A WLAN","A MAN","A SAN","A PAN"],c:2,e:"A storage area network is a dedicated high-speed network that presents shared storage to servers as if it were local disk. It is separate from the user LAN."},

// u3l6
{id:"u3l6-1",t:"u3l6",q:"A wiring closet contains dozens of unlabeled cables, and a technician must find the one that runs to a specific office jack. Which tool is designed for this?",a:["A loopback plug","A crimper","A cable certifier","A toner probe"],c:3,e:"A tone generator is clipped to the cable at the jack and the probe is swept across the closet cables; it sounds loudest on the matching cable."},
{id:"u3l6-2",t:"u3l6",q:"A technician suspects a switch port is dead but has no spare computer or known-good cable available. Which tool tests the port by itself?",a:["A loopback plug","A Wi-Fi analyzer","A punchdown tool","A cable stripper"],c:0,e:"A loopback plug wires the transmit pins back to the receive pins so the port sees its own signal. A working port shows link and passes diagnostics with nothing else attached."},
{id:"u3l6-3",t:"u3l6",q:"Which tool seats individual wires into the 110 block on the back of a patch panel and trims the excess in one motion?",a:["A crimper","A punchdown tool","A cable tester","A network tap"],c:1,e:"A punchdown tool pushes each conductor into its slot on a 110 block or keystone jack and cuts the tail. A crimper attaches RJ45 plugs to cable ends instead."},
{id:"u3l6-4",t:"u3l6",q:"Users in one wing report slow and unreliable Wi-Fi. Which tool shows the technician the nearby networks, their channels, and signal strength to identify overlap?",a:["A cable certifier","A toner probe","A Wi-Fi analyzer","A loopback plug"],c:2,e:"A Wi-Fi analyzer displays every SSID in range with its channel and signal level, revealing channel overlap, weak coverage, and rogue access points."},
{id:"u3l6-5",t:"u3l6",q:"A newly made patch cable lights only seven of eight indicators on a cable tester, with one light never appearing. What does this result indicate?",a:["The cable is a crossover cable","The tester battery is low","The cable exceeds its category rating","One conductor is open, most likely not seated in the plug"],c:3,e:"A missing light on a wire-map test means that conductor has no continuity, an open, usually because the wire did not reach the contact in the RJ45 plug. Re-terminate the end."}
);
