// APlus Academy Core 1 question bank, units 7 to 9. All questions are original.
// Fields: id, t (lesson id), q (stem), a (four options), c (index of correct option), e (explanation).
window.FRA = window.FRA || {};
FRA.questions = FRA.questions || [];
FRA.questions.push(
// u7l1
{id:"u7l1-1",t:"u7l1",q:"A data center wants the best performance and isolation for dozens of server VMs on each physical host. Which hypervisor type should be deployed?",a:["A type 2 hypervisor installed on a desktop OS","A type 1 hypervisor installed directly on the hardware","A container runtime on a workstation","A VDI client"],c:1,e:"Type 1 (bare-metal) hypervisors run directly on the hardware with no host OS beneath them, giving the best performance and isolation for server virtualization."},
{id:"u7l1-2",t:"u7l1",q:"A technician needs to open an email attachment that may be malicious without risking the workstation. Which virtualization use fits?",a:["VDI on a production server","A container sharing the workstation's kernel","A sandbox VM that can be reverted or deleted afterward","Cross-platform virtualization"],c:2,e:"A sandbox is an isolated VM used to open suspicious files or test risky changes. Anything that goes wrong stays inside the VM, which is then reverted to a snapshot or deleted."},
{id:"u7l1-3",t:"u7l1",q:"Which technology packages an application with its libraries while sharing the host operating system's kernel, allowing many instances to start in seconds?",a:["A type 1 hypervisor","A snapshot","Virtual desktop infrastructure","Containers"],c:3,e:"Containers isolate applications rather than whole operating systems, sharing the host kernel. They are far lighter than VMs but require the same OS family as the host."},
{id:"u7l1-4",t:"u7l1",q:"A hospital wants clinicians to access a full desktop from thin clients and tablets, with all data staying in the data center. Which solution provides this?",a:["Virtual desktop infrastructure","Containers on the thin clients","Type 2 hypervisors on each tablet","A host-only network"],c:0,e:"VDI runs user desktops as VMs on servers; endpoints only display the screen and send input. Data never leaves the data center and any device can be used."},
{id:"u7l1-5",t:"u7l1",q:"An accounting application only runs on an operating system that is no longer supported on modern hardware. What allows the company to keep using it safely?",a:["Installing the old OS directly on new hardware","Running the old OS in a virtual machine as a legacy application environment","Converting the application to a container","Using a cloud SaaS version of the OS"],c:1,e:"Application (legacy) virtualization runs the old operating system inside a VM on modern hardware, isolating it from the host and allowing the legacy application to continue working."},

// u7l2
{id:"u7l2-1",t:"u7l2",q:"A VM will host a file share that other computers on the office LAN must connect to directly. Which virtual network mode should be used?",a:["NAT","Host-only","Bridged","Internal only"],c:2,e:"Bridged networking connects the VM to the physical network as if it were another computer, giving it its own address that other devices can reach. NAT and host-only hide the VM."},
{id:"u7l2-2",t:"u7l2",q:"A malware analysis VM must be completely isolated from the company network and the internet but still communicate with the host. Which network mode is correct?",a:["Bridged","NAT","Bridged with a static IP","Host-only"],c:3,e:"Host-only networking creates a private virtual network between the VM and the host with no route to the LAN or internet, which is the safe configuration for malware analysis."},
{id:"u7l2-3",t:"u7l2",q:"Three VMs assigned 8 GB, 4 GB, and 4 GB of memory run on a laptop with 16 GB of RAM, and everything has become extremely slow. What is the cause?",a:["The host has no memory left for itself, so it is swapping","The virtual disks are dynamically expanding","The VMs are using bridged networking","Snapshots have been disabled"],c:0,e:"Guest memory cannot be oversubscribed safely. Allocating all 16 GB to guests leaves nothing for the host OS and hypervisor, which then swap to disk and stall every VM."},
{id:"u7l2-4",t:"u7l2",q:"Before applying an untested patch to a virtual server, what should the technician do so the change can be undone quickly?",a:["Convert the VM to a container","Take a snapshot of the VM","Switch the VM to NAT networking","Increase the VM's memory allocation"],c:1,e:"A snapshot records the VM's state so it can be reverted in seconds if the patch causes problems. Snapshots are not backups and should be merged after the test."},
{id:"u7l2-5",t:"u7l2",q:"Code running inside a guest VM exploits a hypervisor flaw to access the host and other guests. What is this attack called?",a:["VM sprawl","Multitenancy","VM escape","A snapshot collision"],c:2,e:"VM escape is a guest breaking out of its isolation to reach the host or other VMs. Keeping the hypervisor patched and avoiding untrusted VM images are the defenses."},

// u7l3
{id:"u7l3-1",t:"u7l3",q:"A company keeps its patient database in its own data center but uses a provider's cloud for public web servers, with the two connected. Which deployment model is this?",a:["Public cloud","Private cloud","Community cloud","Hybrid cloud"],c:3,e:"A hybrid cloud combines private infrastructure with public cloud resources, connected so workloads can be placed according to sensitivity and demand."},
{id:"u7l3-2",t:"u7l3",q:"Six regional hospitals jointly fund cloud infrastructure built to meet the healthcare regulations they all share. Which deployment model describes this?",a:["Community","Private","Hybrid","Public"],c:0,e:"A community cloud is shared by organizations with common requirements, such as regulatory compliance, giving them more control than a public cloud at lower cost than separate private clouds."},
{id:"u7l3-3",t:"u7l3",q:"A company rents virtual machines and storage from a provider and remains responsible for installing and patching the operating systems. Which service model is this?",a:["SaaS","IaaS","PaaS","DaaS"],c:1,e:"Infrastructure as a service provides virtual machines, storage, and networks; the customer manages everything from the operating system upward."},
{id:"u7l3-4",t:"u7l3",q:"Developers deploy their web application code to a provider-managed runtime and database without administering any servers. Which service model are they using?",a:["IaaS","SaaS","PaaS","Private cloud"],c:2,e:"Platform as a service supplies the operating system, runtime, and supporting services; developers manage only their code and data."},
{id:"u7l3-5",t:"u7l3",q:"Employees access the company's email and office applications entirely through a web browser, with the provider handling all servers and software updates. Which service model is this?",a:["IaaS","PaaS","VDI","SaaS"],c:3,e:"Software as a service delivers a finished application over the network. The customer manages only user accounts and data, and the provider manages everything else."},

// u7l4
{id:"u7l4-1",t:"u7l4",q:"An online retailer's cloud environment automatically adds web servers during a sale and removes them afterward, billing only for the hours used. Which cloud characteristic is demonstrated?",a:["Rapid elasticity","Multitenancy","File synchronization","Dedicated resources"],c:0,e:"Rapid elasticity is the automatic growth and shrinkage of capacity to match demand, which is what allows a business to handle a spike without owning hardware for its busiest day."},
{id:"u7l4-2",t:"u7l4",q:"A company's monthly cloud bill rose sharply after it restored a very large backup from cloud storage to its own data center. Which billing element caused this?",a:["Ingress charges","Egress charges","Elasticity fees","Multitenancy charges"],c:1,e:"Metered utilization bills data transfer out of the cloud (egress) per gigabyte, while data coming in (ingress) is usually free. Large restores or migrations out of a cloud incur egress costs."},
{id:"u7l4-3",t:"u7l4",q:"A financial firm requires that no other customer's workloads run on the same physical servers as its own. Which cloud option meets this requirement?",a:["Shared resources","Multitenant SaaS","Dedicated resources","Community cloud"],c:2,e:"Dedicated resources reserve physical hosts for one customer, providing isolation and predictable performance at a higher cost than shared, multitenant infrastructure."},
{id:"u7l4-4",t:"u7l4",q:"A single instance of a cloud application serves thousands of companies, each seeing only its own data. Which characteristic does this describe?",a:["Elasticity","High availability","File synchronization","Multitenancy"],c:3,e:"Multitenancy is the design that lets one system serve many customers (tenants) with their data logically separated, which is how SaaS providers achieve efficiency."},
{id:"u7l4-5",t:"u7l4",q:"A user deleted a document from a synced folder on a laptop, and it also disappeared from their phone and the company's shared cloud folder. What is the BEST way to get it back?",a:["Restore it from the cloud service's trash or version history","Re-create the document from memory","Turn off synchronization on the phone","Reinstall the sync client"],c:0,e:"File synchronization propagates deletions to every device. Cloud file services keep deleted files in a trash folder or version history for a period, which is the recovery path."},

// u8l1
{id:"u8l1-1",t:"u8l1",q:"A technician has questioned the user and identified recent changes on a PC that is behaving erratically. Before making any changes, what should the technician do?",a:["Reinstall the operating system","Back up the user's data","Replace the hard drive","Document the outcome"],c:1,e:"Step one of the troubleshooting method includes backing up before changes, because a fix can make things worse and the data must be protected first."},
{id:"u8l1-2",t:"u8l1",q:"A technician's theory that a faulty cable was causing a problem has been tested and proven wrong. According to the troubleshooting method, what is the NEXT step?",a:["Document the findings and close the ticket","Implement the original plan anyway","Establish a new theory of probable cause, or escalate","Verify full system functionality"],c:2,e:"When a theory fails testing, the method returns to establishing a new theory. If no theory can be confirmed, the technician escalates to someone with more expertise."},
{id:"u8l1-3",t:"u8l1",q:"After replacing a failed power supply, the technician confirms the PC boots. What should be done before closing the ticket?",a:["Reset the firmware to defaults","Reinstall the drivers","Take a snapshot","Verify full system functionality, implement preventive measures, and document"],c:3,e:"Steps five and six require confirming the whole system works (not just that it boots), adding prevention such as a surge protector or cleaning, and documenting the cause, fix, and outcome."},
{id:"u8l1-4",t:"u8l1",q:"A motherboard powers on but shows nothing on any display and gives no beeps. Which tool displays diagnostic codes that show where the firmware stopped?",a:["A POST card","A loopback plug","A multimeter","A cable tester"],c:0,e:"A POST card plugs into a slot or USB port and displays the firmware's progress codes, identifying the stage (memory, video, keyboard) where startup halted."},
{id:"u8l1-5",t:"u8l1",q:"Which tool quickly checks each output voltage of a desktop power supply and its power-good signal without a running system?",a:["A POST card","A power supply tester","A toner probe","An ESD strap"],c:1,e:"A PSU tester connects to the 24-pin and other connectors and shows each rail (3.3, 5, 12 V) and the power-good signal, making it the fastest check of a suspect supply."},

// u8l2
{id:"u8l2-1",t:"u8l2",q:"A desktop shows no lights and no fan movement when the power button is pressed. What should the technician check FIRST?",a:["The RAM seating","The CMOS battery","The wall outlet, power cord, and PSU switch","The CPU thermal paste"],c:2,e:"No power at all means starting at the source: the outlet, the cord at both ends, the power strip, and the supply's own switch and voltage selector, before suspecting internal parts."},
{id:"u8l2-2",t:"u8l2",q:"After a technician adds a second RAM module, the PC emits repeating short beeps at power-on and displays nothing. What is the MOST likely cause?",a:["The CPU has overheated","The CMOS battery is dead","The hard drive has failed","The new module is not seated correctly or is incompatible"],c:3,e:"Repeating beeps with no display point to memory. A newly installed module that is not fully seated or not supported by the board is the obvious cause given the recent change."},
{id:"u8l2-3",t:"u8l2",q:"A PC runs normally at idle but restarts a few minutes into any demanding task. Which two causes are MOST likely?",a:["Overheating or a failing power supply that sags under load","A bad keyboard or mouse","A wrong boot order or a missing driver","A full hard drive or fragmented files"],c:0,e:"Shutdowns tied to load point to thermal protection tripping or a power supply whose rails drop under demand. Check temperatures and test the supply under load."},
{id:"u8l2-4",t:"u8l2",q:"A workstation displays blue screen errors with different stop codes at random times, and no software or drivers have changed. What should the technician do FIRST?",a:["Reinstall the operating system","Run a memory test","Replace the motherboard","Update the firmware"],c:1,e:"Random crashes with varying codes and no recent changes point to hardware, most often faulty RAM. A memory test is a cheap, non-destructive first step."},
{id:"u8l2-5",t:"u8l2",q:"During an inspection, a technician notices several capacitors on a motherboard with domed tops and brown residue. What should be done?",a:["Clean the residue and continue using the board","Replace the CMOS battery","Replace the motherboard","Reapply thermal paste"],c:2,e:"Swollen or leaking capacitors indicate a failing board (or power supply). They cannot be reliably repaired in the field, so the board is replaced."},

// u8l3
{id:"u8l3-1",t:"u8l3",q:"During startup, a PC displays a S.M.A.R.T. failure warning for the system drive. What should the technician do?",a:["Disable S.M.A.R.T. in firmware to stop the message","Run a memory test","Defragment the drive","Back up the data and replace the drive"],c:3,e:"A S.M.A.R.T. failure prediction means the drive has crossed its own reliability thresholds. Treat it as a countdown: back up immediately and replace the drive."},
{id:"u8l3-2",t:"u8l3",q:"A PC reports 'bootable device not found' after a technician used a USB stick to run diagnostics. What should be checked FIRST?",a:["Whether the USB stick is still inserted and the boot order","Whether the RAM is seated","Whether the CMOS battery is dead","Whether the drive cable supports 6 Gb/s"],c:0,e:"A non-bootable USB device left inserted while it is first in the boot order produces exactly this message. Remove it and confirm the boot order before suspecting the drive."},
{id:"u8l3-3",t:"u8l3",q:"After a power outage, a server's RAID volume is missing and the operating system shows the member disks as separate, uninitialized drives. What should the technician do?",a:["Initialize the disks and restore from backup","Check the RAID controller and restore or import its configuration without initializing the disks","Replace all the drives","Convert the disks to dynamic disks"],c:1,e:"All drives do not fail simultaneously; a vanished array points to the controller, its configuration, driver, or cache battery. Initializing the disks would destroy the data that is still on them."},
{id:"u8l3-4",t:"u8l3",q:"A RAID 5 array on a small server is running but shows a degraded status with one amber bay light. Users report slow file access. What is the correct action?",a:["Wait until the weekend to avoid disruption","Reboot the server to clear the warning","Replace the failed drive promptly so the array can rebuild, after confirming a recent backup","Remove the failed drive and run the array as RAID 0"],c:2,e:"A degraded RAID 5 has no fault tolerance and slower performance. Replacing the failed member starts the rebuild; a second failure before then would lose the array, so confirm backups and act quickly."},
{id:"u8l3-5",t:"u8l3",q:"An SSD that is 97 percent full has become noticeably slow at writing files. What should the technician recommend?",a:["Defragment the SSD weekly","Switch the drive to IDE mode","Replace the SATA cable","Free up space and ensure TRIM is enabled"],c:3,e:"SSDs slow down when few free blocks remain and when TRIM is not maintaining them. Keeping 10 to 20 percent free restores performance; defragmentation is unnecessary and adds wear."},

// u8l4
{id:"u8l4-1",t:"u8l4",q:"A monitor displays 'No signal' while the connected PC is clearly running. What should the technician check FIRST?",a:["The monitor's selected input source and the cable connections","The graphics card's driver version","The monitor's color gamut","The PC's boot order"],c:0,e:"The cheapest and most common causes of no image are a monitor on the wrong input and a loose or damaged cable. Both are checked before any hardware is suspected."},
{id:"u8l4-2",t:"u8l4",q:"A laptop's screen is very dark, but a faint image of the desktop can be seen when a flashlight is aimed at it. Which component has failed?",a:["The LCD panel","The backlight or inverter","The graphics processor","The digitizer"],c:1,e:"An image that is present but unlit means the panel and graphics path work and only the light source behind the panel has failed. On CCFL screens that is often the inverter; on LED screens, the backlight or its driver."},
{id:"u8l4-3",t:"u8l4",q:"A conference room projector shuts itself off about fifteen minutes into every meeting. What is the MOST likely cause?",a:["The input source is wrong","The keystone setting is incorrect","Overheating due to a clogged filter or poor ventilation","The HDMI cable does not carry audio"],c:2,e:"Projectors that run for a while and then shut down are tripping thermal protection. A dust-clogged filter or blocked vents are the usual reasons; a lamp near end of life can also cause it."},
{id:"u8l4-4",t:"u8l4",q:"A television connected to a PC over HDMI shows video but produces no sound, while the PC's speakers still play audio. What should be done?",a:["Replace the HDMI cable with a DVI cable","Change the monitor's refresh rate","Enable Secure Boot","Select the television as the playback device in the operating system's sound settings"],c:3,e:"HDMI carries audio, but the OS sends sound to whichever output is selected. Choosing the TV as the playback device routes audio over HDMI; DVI would carry no audio at all."},
{id:"u8l4-5",t:"u8l4",q:"An OLED display used for digital signage shows a permanent faint outline of a logo that was displayed for months. What is this condition?",a:["Burn-in","Dead pixels","A refresh rate mismatch","Incorrect chroma display"],c:0,e:"Burn-in is permanent image retention on OLED or plasma screens caused by static content. Pixel shifting and screen savers prevent it; there is no repair."},

// u8l5
{id:"u8l5-1",t:"u8l5",q:"A user reports that the back cover of their phone is lifting away from the case and the screen no longer sits flat. What should the technician advise?",a:["Press the cover back into place and apply adhesive","Stop using the phone, do not charge it, and have the swollen battery replaced","Perform a factory reset","Update the operating system"],c:1,e:"A lifting cover or screen is the classic sign of a swollen battery. The device should not be used, charged, or pressed on, and the battery must be replaced and recycled properly."},
{id:"u8l5-2",t:"u8l5",q:"A phone was dropped into a sink full of water and retrieved immediately. What should the user do FIRST?",a:["Plug it in to see whether it still charges","Place it in the freezer","Power it off and avoid charging it while it dries","Run a diagnostic app"],c:2,e:"Water conducts and corrodes, and applying power accelerates the damage. Power off, remove the SIM and case, and dry the device thoroughly with airflow for days before attempting to use it."},
{id:"u8l5-3",t:"u8l5",q:"A tablet registers touches the user did not make, but only while it is charging from a car adapter. What is the MOST likely cause?",a:["The digitizer is cracked","The battery health is poor","The operating system needs a factory reset","The charger is producing electrical noise that confuses the digitizer"],c:3,e:"Phantom touches that appear only while charging point to a noisy, low-quality charger. Testing with a known-good adapter confirms it; a cracked digitizer would misbehave all the time."},
{id:"u8l5-4",t:"u8l5",q:"A user's phone shows no cellular service, no Wi-Fi networks, and no Bluetooth devices after a flight. What should be checked FIRST?",a:["Whether airplane mode is still enabled","Whether the SIM card has expired","Whether the phone has malware","Whether location services are on"],c:0,e:"Airplane mode disables every radio at once, which matches all three symptoms and is commonly left on after a flight. It is the quickest check before any deeper diagnosis."},
{id:"u8l5-5",t:"u8l5",q:"A three-year-old phone shuts down when the battery indicator still shows around 30 percent and has become sluggish. What is the MOST likely cause?",a:["Too many saved Wi-Fi networks","Poor battery health that also triggers performance throttling","A damaged charging port","An outdated carrier settings file"],c:1,e:"An aged battery cannot supply peak current, causing shutdowns at a displayed charge level and OS-imposed throttling. Checking the battery health percentage confirms it; replacement is the fix."},

// u8l6
{id:"u8l6-1",t:"u8l6",q:"Three PCs in one office began freezing briefly every hour right after new fluorescent lighting was installed in that office, while other offices are unaffected. What is the MOST likely cause?",a:["A malware infection on all three PCs","Failing RAM in all three PCs","Electrical interference or power quality problems from the new lighting circuit","An expired domain certificate"],c:2,e:"Several machines in the same location failing together after an electrical change points to the environment, not to software or individual hardware. Power conditioning or a separate circuit resolves it."},
{id:"u8l6-2",t:"u8l6",q:"A laptop runs on AC power but reports 'plugged in, not charging' since the user bought an inexpensive replacement adapter. What should be checked FIRST?",a:["Whether the operating system needs reinstalling","Whether the hard drive is failing","Whether the display cable is loose","Whether the adapter supplies the correct wattage and is compatible"],c:3,e:"An underpowered or non-genuine adapter can run the laptop but not charge the battery. Trying the correct original-wattage adapter is the cheapest test and usually the fix."},
{id:"u8l6-3",t:"u8l6",q:"A desktop shows the manufacturer's logo, then a black screen with only a mouse cursor, immediately after a graphics driver update. What should the technician do?",a:["Boot into safe mode and roll back the graphics driver","Replace the monitor","Replace the graphics card","Clear the CMOS"],c:0,e:"The firmware and boot process work and the failure appears only when the OS loads the new driver. Safe mode uses a basic display driver, allowing the faulty driver to be rolled back."},
{id:"u8l6-4",t:"u8l6",q:"A small office NAS flashes an amber light and reports its mirrored volume as degraded, though users can still open files. What is the correct course of action?",a:["Ignore it because the files are still accessible","Confirm backups, replace the failed drive, and let the mirror rebuild","Power off the NAS and reinitialize the volume","Convert the volume to RAID 0 for performance"],c:1,e:"The volume is running on one drive with no redundancy. Verifying the backup and replacing the failed drive so the mirror rebuilds is the fix; reinitializing would destroy the data."},
{id:"u8l6-5",t:"u8l6",q:"A tablet that was dropped last week has a perfect display image but ignores touch along one edge. What is the MOST likely fault and fix?",a:["A software bug; factory reset the tablet","A dead backlight; replace the backlight","A cracked digitizer; replace the screen assembly","A calibration error; recalibrate the capacitive screen"],c:2,e:"A clear image with a localized touch dead zone after a drop indicates a cracked digitizer. Capacitive screens cannot be recalibrated to fix physical damage, and software cannot repair a sensor."},

// u9l1
{id:"u9l1-1",t:"u9l1",q:"A wired desktop transfers files far more slowly than the identical PC beside it, and its NIC reports 100 Mb/s half duplex. What is the MOST likely cause?",a:["A DNS misconfiguration","Wireless interference","An APIPA address","A speed or duplex mismatch with the switch port"],c:3,e:"When one end of a link is hard-set and the other auto-negotiates, the auto side falls to half duplex, causing collisions and very slow transfers. Setting both ends to auto resolves it."},
{id:"u9l1-2",t:"u9l1",q:"A switch log shows a port repeatedly going up and down every few seconds. What should the technician do FIRST?",a:["Replace the patch cable on that port","Replace the switch","Reinstall the NIC driver on every PC","Change the VLAN assignment"],c:0,e:"Port flapping is most often caused by a damaged cable or connector. Replacing the cable is the cheapest first step, followed by trying another port and then the NIC."},
{id:"u9l1-3",t:"u9l1",q:"Voice over IP calls in an office are choppy and robotic, while web browsing and file downloads work normally. What is the BEST solution?",a:["Increase the DHCP lease time","Implement QoS and place phones on a wired voice VLAN","Move the phones to the 2.4 GHz wireless network","Replace the phones' handsets"],c:1,e:"Choppy voice with otherwise working data indicates jitter and latency affecting time-sensitive packets. QoS prioritizes voice, and a wired voice VLAN removes wireless variability."},
{id:"u9l1-4",t:"u9l1",q:"Wireless clients in a break room lose their connection whenever the microwave oven is used. What is the BEST fix?",a:["Replace the access point with a hub","Shorten the DHCP scope","Move the affected clients and access point to the 5 GHz band","Disable Secure Boot on the clients"],c:2,e:"Microwave ovens emit interference in the 2.4 GHz band. Moving to 5 GHz avoids it entirely; changing 2.4 GHz channels or relocating the access point helps less."},
{id:"u9l1-5",t:"u9l1",q:"No user can authenticate to the company's enterprise wireless network this morning, although all could yesterday. Which cause should be investigated FIRST?",a:["Each user's password has been mistyped","The wireless channel width","One laptop's MAC address filter entry","The RADIUS server, its certificate, or time synchronization"],c:3,e:"A failure affecting every user points to the shared authentication infrastructure: the RADIUS server being down, an expired server certificate, or clock skew, rather than individual credentials."},

// u9l2
{id:"u9l2-1",t:"u9l2",q:"Every page from a laser printer shows a faint duplicate of the previous page's image lower on the sheet. Which component is MOST likely at fault?",a:["The imaging drum or its cleaning blade and erase lamp","The pickup rollers","The paper tray sensor","The network interface"],c:0,e:"Ghosting means the drum was not fully cleaned or discharged between pages. A worn cleaning blade, dead erase lamp, or worn drum is the cause; replacing the drum unit resolves it."},
{id:"u9l2-2",t:"u9l2",q:"A laser printer's output looks correct but the toner rubs off the page when touched. What is the MOST likely cause?",a:["The transfer roller is worn","The fuser is not reaching temperature or the paper type setting is wrong","The toner cartridge is nearly empty","The laser scanner window is dirty"],c:1,e:"Toner that reaches the paper but does not bond has not been fused. Check the paper type setting for heavy stock first, then replace the fuser or maintenance kit."},
{id:"u9l2-3",t:"u9l2",q:"A print job produces dozens of pages containing random characters and symbols. What should the technician check FIRST?",a:["The fuser temperature","The paper tray size setting","Whether the correct driver and printer language are installed and cancel the job","The toner level"],c:2,e:"Garbled output means the printer received data in a language it does not understand, usually a wrong or corrupted driver or a corrupted job. Cancel the job, clear the queue, and install the correct driver."},
{id:"u9l2-4",t:"u9l2",q:"A laser printer's output has gradually become uniformly light across the whole page, and the toner cartridge reports 15 percent remaining. What should be tried FIRST?",a:["Replace the fuser","Reinstall the printer driver","Replace the imaging drum","Check the driver quality setting and replace the toner cartridge"],c:3,e:"Uniformly faded output most often comes from low toner or an economy or draft mode. These are checked before suspecting the transfer roller or other parts."},
{id:"u9l2-5",t:"u9l2",q:"An inkjet printer prints text with horizontal white gaps through the letters. What should the technician do FIRST?",a:["Run the print head cleaning routine","Replace the carriage belt","Replace the feed rollers","Switch the driver to PostScript"],c:0,e:"Gaps in inkjet text mean clogged nozzles. The head cleaning cycle purges dried ink and is the first, non-invasive step; alignment addresses misregistration, not gaps."},

// u9l3
{id:"u9l3-1",t:"u9l3",q:"A laser printer pulls two or three sheets at a time from its tray on most jobs. Which parts should be replaced?",a:["The fuser and transfer belt","The separation pad and pickup rollers, typically via the maintenance kit","The toner cartridge","The formatter board"],c:1,e:"The separation pad holds back all but the top sheet; when it and the rollers wear, multiple sheets feed at once. Both are included in the maintenance kit."},
{id:"u9l3-2",t:"u9l3",q:"A print server's queue shows many jobs pending with the first job stuck at 'printing' for hours, and the printer itself displays 'Ready.' What should the technician do?",a:["Replace the printer's network cable","Reinstall the operating system on the server","Cancel the stuck job and, if it will not clear, restart the print spooler service and clear the spool folder","Power cycle every client PC"],c:2,e:"A corrupted job can hang the spooler so nothing behind it moves. Cancelling it, then restarting the spooler and clearing spooled files, releases the queue."},
{id:"u9l3-3",t:"u9l3",q:"A wireless printer becomes unreachable every few days and works again only after users re-add it with a new address. What is the permanent fix?",a:["Restart the printer daily","Reduce the DHCP lease time","Move the printer to the guest network","Configure a DHCP reservation or static IP address for the printer"],c:3,e:"The printer is receiving a new DHCP address when its lease expires or the router restarts. A reservation or static address keeps it constant so clients always find it."},
{id:"u9l3-4",t:"u9l3",q:"After an optional second paper tray is installed, the printer does not list it and jobs sent to it fail. What should be checked?",a:["That the tray is fully seated, its paper size is set, and the tray is enabled in the firmware or driver options","The toner level","The fuser temperature","The SMTP settings"],c:0,e:"A tray must be physically seated with its size set, and the printer's firmware or the driver's installable options must know it exists. Any of these being wrong makes the tray unrecognized."},
{id:"u9l3-5",t:"u9l3",q:"A multifunction printer's stapler jams on every finished set. What should the technician do FIRST?",a:["Replace the fuser","Clear the stapler head of bent staples and replace the staple cartridge","Reinstall the printer driver","Change the DHCP reservation"],c:1,e:"Finisher problems are mechanical: bent staples in the head or a depleted cartridge cause repeated jams. Clearing and reloading the stapler is the first step before checking finisher sensors or settings."}
);
