// SecPlus Academy question bank, units 6 to 10. All questions are original.
window.FRA = window.FRA || {};
FRA.questions = FRA.questions || [];
FRA.questions.push(
// u6l1
{id:"u6l1-1",t:"u6l1",q:"A company runs virtual machines in an infrastructure-as-a-service cloud. Under the shared responsibility model, who is responsible for applying operating system patches to those virtual machines?",a:["The cloud provider","The customer","The internet service provider","The hypervisor vendor"],c:1,e:"In IaaS the provider secures the physical infrastructure and hypervisor, while the customer manages and patches the operating systems and everything above them. Data, identities, and configuration are always the customer's responsibility."},
{id:"u6l1-2",t:"u6l1",q:"A single typo in a deployment template caused every newly built server to expose a management port to the internet. Which architecture concept explains both the speed of the mistake and the way to fix it?",a:["Serverless computing","Microservices","Infrastructure as code","Physical isolation"],c:2,e:"Infrastructure as code builds environments from files, so one error is deployed everywhere consistently. The fix is the same mechanism: correct the template, scan it, and redeploy."},
{id:"u6l1-3",t:"u6l1",q:"A development team wants to run event-triggered code without managing or patching any servers. Which architecture meets this need?",a:["Air-gapped systems","Containerization on self-managed hosts","On-premises virtualization","Serverless"],c:3,e:"Serverless computing runs functions in response to events while the provider manages the underlying servers and operating systems. The customer remains responsible for the code, its permissions, and input validation."},
{id:"u6l1-4",t:"u6l1",q:"Which security consideration is MOST specific to a microservices architecture?",a:["Many service-to-service API connections must each be authenticated and encrypted","A single compromised component gives access to the whole application","Operating system patching is eliminated","Physical hardware must be isolated"],c:0,e:"Microservices communicate through many APIs, so each internal connection becomes an attack surface that needs authentication, encryption, and usually an API gateway. Compromise is contained to one service, which is a benefit rather than a risk."},
{id:"u6l1-5",t:"u6l1",q:"A company uses a software-as-a-service email platform. Which responsibility remains with the company rather than the provider?",a:["Patching the email server operating system","Managing user identities and access to mailboxes","Maintaining the data center's physical security","Replacing failed storage hardware"],c:1,e:"In every cloud model the customer keeps responsibility for its data, identities, and access configuration. In SaaS the provider handles the application, operating system, hardware, and facility."},

// u6l2
{id:"u6l2-1",t:"u6l2",q:"A defense contractor requires that a classified research network have no possible network path to the internet. Which architecture provides this?",a:["Logical segmentation with VLANs","Software-defined networking","Physical isolation (air gap)","A screened subnet"],c:2,e:"An air gap physically separates the network from all others, so no network path exists. VLANs and SDN provide logical separation on shared infrastructure, and a screened subnet is still connected."},
{id:"u6l2-2",t:"u6l2",q:"Which statement correctly contrasts containers with virtual machines?",a:["Containers each include a full operating system, while virtual machines share the host kernel","Containers require a hypervisor, while virtual machines do not","Containers provide stronger isolation than virtual machines","Containers share the host operating system kernel, while virtual machines each run their own operating system"],c:3,e:"Containers package an application and its dependencies and share the host's kernel, which makes them light but less isolated. Virtual machines run full operating systems on a hypervisor with stronger isolation between them."},
{id:"u6l2-3",t:"u6l2",q:"A water treatment plant's control system cannot be patched without a scheduled multi-day shutdown, and a vulnerability has been published. Which approach BEST protects it in the meantime?",a:["Isolate the control network from business networks and monitor its traffic passively","Install endpoint protection agents on the controllers","Apply the patch immediately during production","Move the control system to a public cloud provider"],c:0,e:"ICS/SCADA systems prioritize safety and availability, so patching waits for a planned window. Segmentation from business networks plus passive monitoring is the compensating control. Agents cannot run on controllers, and cloud migration is not appropriate."},
{id:"u6l2-4",t:"u6l2",q:"A medical infusion pump must respond to sensor input within strict microsecond limits. Which system type is this, and what does it imply for security controls?",a:["A container; the kernel must be shared","An RTOS; controls that add latency may be unacceptable","A hot site; failover must be immediate","A jump server; all access must be audited"],c:1,e:"A real-time operating system guarantees response within strict timing constraints, so security agents that introduce delay cannot be used. Security is designed around the device through isolation and physical controls."},
{id:"u6l2-5",t:"u6l2",q:"Which describes a risk that is specific to a centralized security management model?",a:["Policies are inconsistent across sites","Local administrators cannot be audited","The central system is a single point of failure and a high-value target","Segmentation cannot be implemented"],c:2,e:"Centralized control gives consistency and easy auditing, but the central system becomes both a single point of failure and the attacker's primary target. Inconsistency is the risk of decentralized models."},

// u6l3
{id:"u6l3-1",t:"u6l3",q:"A retailer's website must handle triple its normal traffic during holiday sales without redesign. Which architecture consideration is MOST important?",a:["Responsiveness","Power","Patch availability","Scalability"],c:3,e:"Scalability is the ability to grow capacity with demand. Responsiveness concerns speed for each user, not volume, and the other options are unrelated to traffic growth."},
{id:"u6l3-2",t:"u6l3",q:"A company moves its email to a cloud provider to reduce the burden of running mail servers. Which consideration does this represent, and what remains with the company?",a:["Risk transference; accountability for the data remains with the company","Ease of deployment; the company keeps no responsibility","Compute; the company keeps the hardware","Inability to patch; the company keeps the patching"],c:0,e:"Moving a function to a provider transfers operational risk, but accountability for outcomes such as data loss stays with the organization. Risk transference never transfers responsibility to customers and regulators."},
{id:"u6l3-3",t:"u6l3",q:"A hospital uses an imaging device whose certification prohibits any changes to its software configuration, even though the vendor releases updates. Which consideration applies?",a:["Patch availability","Inability to patch","Ease of recovery","Resilience"],c:1,e:"Patches exist but cannot be applied because of certification restrictions, which is inability to patch. Patch availability would apply if the vendor released no updates at all. Compensating controls are required either way."},
{id:"u6l3-4",t:"u6l3",q:"A financial trading platform requires that transactions be processed within milliseconds. Which architecture consideration drives the decision to host it on dedicated hardware close to the exchange?",a:["Cost","Ease of deployment","Responsiveness","Risk transference"],c:2,e:"Responsiveness is how quickly a system reacts; latency-sensitive workloads favor dedicated, nearby infrastructure. Scalability would concern handling more volume rather than faster individual transactions."},
{id:"u6l3-5",t:"u6l3",q:"Which pair of considerations describes a design where any single server can fail and users are not affected?",a:["Cost and compute","Scalability and ease of deployment","Power and patch availability","Availability and resilience"],c:3,e:"Resilience is the ability to keep operating through a failure, and availability is the resulting outcome that the service stays reachable. The other pairs do not describe tolerance of component failure."},

// u7l1
{id:"u7l1-1",t:"u7l1",q:"A company must place its public web servers so that they are reachable from the internet but separated from the internal network by firewalls on both sides. Which zone is this?",a:["Screened subnet","Internal trusted zone","Management network","Air gap"],c:0,e:"A screened subnet, historically called a DMZ, sits between the internet and the internal network with firewalls at each boundary, so a compromised public server does not give access to internal systems."},
{id:"u7l1-2",t:"u7l1",q:"A firewall protecting a payment processing environment must never allow unfiltered traffic through, even if the firewall itself fails. Which failure mode should be configured?",a:["Fail-open","Fail-closed","Active-active","Passive"],c:1,e:"Fail-closed stops all traffic when the control fails, preserving security at the cost of availability, which is correct for sensitive systems. Fail-open would allow traffic to flow unfiltered."},
{id:"u7l1-3",t:"u7l1",q:"A security team wants to detect attacks on the network but must guarantee that the monitoring device can never slow down or interrupt production traffic, even if it crashes. Which deployment should be used?",a:["Inline intrusion prevention system","Inline web application firewall","Intrusion detection system fed by a network tap","Load balancer in active-passive mode"],c:2,e:"A passive device connected to a tap or mirror port receives a copy of traffic and can only alert; it cannot block, bottleneck, or interrupt the flow. Inline devices can do all three."},
{id:"u7l1-4",t:"u7l1",q:"Administrators currently connect directly from their workstations to database servers. Which appliance should be introduced so that all administrative access passes through a single hardened, audited host?",a:["Reverse proxy","Forward proxy","Load balancer","Jump server"],c:3,e:"A jump server is a hardened host in a protected zone that administrators connect to first and from which they reach internal systems, creating one monitored chokepoint for administration."},
{id:"u7l1-5",t:"u7l1",q:"Which statement BEST describes the difference between an intrusion detection system and an intrusion prevention system?",a:["An IDS is passive and alerts; an IPS is inline and blocks","An IDS is inline and blocks; an IPS is passive and alerts","An IDS protects web applications; an IPS protects email","An IDS encrypts traffic; an IPS decrypts it"],c:0,e:"An intrusion detection system watches a copy of traffic and raises alerts. An intrusion prevention system sits inline in the traffic path and can drop malicious packets in real time, at the risk of becoming a bottleneck."},

// u7l2
{id:"u7l2-1",t:"u7l2",q:"In an 802.1X deployment, which role does the network switch perform?",a:["Supplicant","Authenticator","Authentication server","Certificate authority"],c:1,e:"The switch or access point is the authenticator: it relays the device's credentials to the RADIUS authentication server and opens the port only after approval. The device is the supplicant."},
{id:"u7l2-2",t:"u7l2",q:"A company wants the strongest available authentication for its corporate wireless network and already operates a PKI that issues certificates to devices. Which EAP method should be used?",a:["EAP-FAST","PEAP","EAP-TLS","EAP-TTLS with passwords"],c:2,e:"EAP-TLS uses certificates on both the client and the server, making it the strongest EAP method. PEAP and EAP-TTLS protect password-based inner methods inside a TLS tunnel, and EAP-FAST is lighter weight."},
{id:"u7l2-3",t:"u7l2",q:"An online store's customer portal is being attacked with SQL injection and cross-site scripting. Which firewall type is designed to inspect HTTP traffic and block these attacks?",a:["Layer 4 stateful firewall","Unified threat management appliance","Host-based firewall","Web application firewall"],c:3,e:"A web application firewall inspects HTTP traffic for application-layer attacks such as injection and cross-site scripting. A Layer 4 firewall sees only ports and addresses, and UTM appliances are general-purpose bundles."},
{id:"u7l2-4",t:"u7l2",q:"A small business with no dedicated security staff wants a single appliance that provides firewall, antivirus, content filtering, spam filtering, and VPN. Which device fits?",a:["Unified threat management appliance","Web application firewall","Layer 4 firewall","Jump server"],c:0,e:"Unified threat management bundles multiple security functions into one appliance, which suits small organizations, at the risk of becoming a performance bottleneck."},
{id:"u7l2-5",t:"u7l2",q:"Which firewall capability distinguishes a next-generation firewall from a traditional Layer 4 firewall?",a:["Filtering by source and destination port","Identifying applications and users within traffic and applying intrusion prevention","Tracking connection state","Physically isolating network segments"],c:1,e:"Next-generation firewalls add application awareness, user identity, intrusion prevention, and threat intelligence. Port filtering and stateful tracking are Layer 4 capabilities that traditional firewalls already have."},

// u7l3
{id:"u7l3-1",t:"u7l3",q:"Two branch offices must be permanently connected so that their networks behave as one, without users taking any action. Which solution is appropriate?",a:["Clientless TLS portal","Remote access VPN with split tunneling","Site-to-site IPsec VPN","SD-WAN without encryption"],c:2,e:"A site-to-site VPN uses gateways at each office to maintain a permanent encrypted tunnel, joining the networks transparently. Remote access and clientless options serve individual users."},
{id:"u7l3-2",t:"u7l3",q:"Remote employees complain that video calls are slow because all of their traffic is routed through the corporate VPN gateway. Which change improves performance while still protecting corporate traffic, and what is its trade-off?",a:["Full tunnel; all traffic is inspected","IPsec transport mode; the whole packet is wrapped","Site-to-site VPN; users need no client","Split tunnel; internet traffic bypasses corporate inspection"],c:3,e:"Split tunneling sends only corporate-bound traffic through the VPN and lets internet traffic go direct, improving performance. The trade-off is that the direct traffic is not inspected by corporate security controls."},
{id:"u7l3-3",t:"u7l3",q:"Which IPsec component provides encryption of the packet payload?",a:["Encapsulating security payload (ESP)","Authentication header (AH)","Internet key exchange (IKE)","Transport Layer Security (TLS)"],c:0,e:"ESP provides confidentiality through encryption along with integrity. AH provides integrity and authentication only, with no encryption, and IKE negotiates the keys. TLS is a separate protocol."},
{id:"u7l3-4",t:"u7l3",q:"A company with many branch offices wants to use inexpensive broadband and cellular links while automatically routing each application over the best-performing path. Which technology provides this?",a:["SASE","SD-WAN","Site-to-site IPsec","A screened subnet"],c:1,e:"Software-defined WAN uses multiple links and an application-aware controller to steer traffic over the best path. SASE adds cloud-delivered security on top of SD-WAN but is not the networking function itself."},
{id:"u7l3-5",t:"u7l3",q:"A company with a fully remote workforce wants every user to receive the same firewall, web filtering, and zero trust access policies from the cloud without routing traffic back to headquarters. Which solution meets this?",a:["SD-WAN","Site-to-site VPN","SASE","Port security with 802.1X"],c:2,e:"Secure access service edge delivers networking and security services, including firewall as a service, secure web gateway, and zero trust network access, from cloud points of presence close to each user."},

// u8l1
{id:"u8l1-1",t:"u8l1",q:"A European customer's personal data is stored in a data center located in another country, raising concerns that it is subject to that country's laws. Which concept describes this issue?",a:["Data masking","Trade secret protection","Data in use","Data sovereignty"],c:3,e:"Data sovereignty means data is subject to the laws of the country in which it is physically stored. Geographic restrictions and regional cloud storage are the controls that address it."},
{id:"u8l1-2",t:"u8l1",q:"Point-of-sale terminals were infected with malware that read card numbers from memory while transactions were being processed. Which data state was attacked?",a:["Data in use","Data in transit","Data at rest","Data in archive"],c:0,e:"Data being processed in memory is data in use, the state that disk and transport encryption do not protect. Secure enclaves and strict control of processing systems address it."},
{id:"u8l1-3",t:"u8l1",q:"A beverage company's product formula is valuable only as long as it remains secret. Which data type BEST describes it?",a:["Regulated data","Trade secret","Financial information","Public data"],c:1,e:"A trade secret derives its value from secrecy; disclosure destroys the asset itself. Regulated data is defined by law, and financial information concerns accounts and filings."},
{id:"u8l1-4",t:"u8l1",q:"Which classification level typically requires the strongest controls such as encryption, access logging, and approval for each access, and usually applies to regulated data?",a:["Public","Private","Restricted","Sensitive"],c:2,e:"Restricted is a high classification for tightly controlled, often regulated data, with encryption, logging, and access approval. Public requires no controls, and private and sensitive sit lower on the ladder."},
{id:"u8l1-5",t:"u8l1",q:"Why is a data loss prevention system less effective at detecting sensitive information inside encrypted archives than inside spreadsheets?",a:["Spreadsheets are always larger","Encrypted archives are classified as public","DLP only works on email","Encrypted archives are non-human-readable data that pattern matching cannot inspect"],c:3,e:"DLP relies on recognizing patterns such as card numbers in human-readable data. Encrypted or binary data is non-human-readable, so different controls, such as blocking unknown archives or requiring decryption, are needed."},

// u8l2
{id:"u8l2-1",t:"u8l2",q:"An organization must store user passwords so that even its own administrators cannot recover the original values. Which method should be used?",a:["Hashing with salt","Tokenization","AES encryption","Data masking"],c:0,e:"Hashing is one-way; nothing recovers the input. Salting makes each hash unique. Encryption and tokenization are reversible by design, and masking only hides part of a displayed value."},
{id:"u8l2-2",t:"u8l2",q:"Customer service agents must be able to confirm a caller's card by its last four digits but must never see the full number on screen. Which method meets this?",a:["Tokenization","Data masking","Hashing","Segmentation"],c:1,e:"Data masking displays only part of a value, such as the last four digits, while the full value remains stored. Tokenization replaces the whole value with a substitute and hashing is irreversible."},
{id:"u8l2-3",t:"u8l2",q:"A merchant wants to ensure that if its database is stolen, the attackers obtain no usable card numbers, while the merchant can still process refunds. Which method fits BEST?",a:["Hashing the card numbers","Masking the card numbers","Tokenization with a separate secured vault","Geographic restrictions"],c:2,e:"Tokenization stores random tokens in the merchant's database and keeps the real numbers in a separate vault, so a database breach yields nothing usable while refunds can still be mapped back through the vault. Hashing would prevent refunds."},
{id:"u8l2-4",t:"u8l2",q:"A regulation requires that citizens' records never be stored or accessed outside the country. Which data protection method directly enforces this?",a:["Encryption","Hashing","Obfuscation","Geographic restrictions"],c:3,e:"Geographic restrictions keep data within permitted locations and block access from prohibited ones, using regional storage and geofencing. They are the enforcement mechanism for data sovereignty requirements."},
{id:"u8l2-5",t:"u8l2",q:"A compromised marketing workstation was able to read the research database because both were on the same network with broad file permissions. Which two methods would MOST directly have prevented this?",a:["Segmentation and permission restrictions","Encryption and hashing","Tokenization and masking","Obfuscation and geographic restrictions"],c:0,e:"Segmentation would keep the workstation network from reaching the database, and permission restrictions would deny the marketing account access. Encryption would not help because permitted access would decrypt the data."},

// u8l3
{id:"u8l3-1",t:"u8l3",q:"A company requires that if its primary data center is lost, operations resume within minutes with current data. Which recovery site type is required?",a:["Cold site","Hot site","Warm site","Tabletop site"],c:1,e:"A hot site is a running duplicate with current data that can take over in minutes. A warm site needs data restored and takes hours, and a cold site is empty space that takes days or weeks."},
{id:"u8l3-2",t:"u8l3",q:"A database must remain available with no loss of session state when one of its servers fails. Which high availability technique is appropriate?",a:["Load balancing","Geographic dispersion","Clustering","Platform diversity"],c:2,e:"Clustering makes servers act as one system with shared state and automatic failover, protecting stateful services such as databases. Load balancing spreads requests and suits stateless services."},
{id:"u8l3-3",t:"u8l3",q:"Why should an organization's recovery site be located in a different region from its primary site?",a:["To reduce network latency","To lower staffing costs","To satisfy load balancing requirements","So that a single regional disaster cannot affect both sites"],c:3,e:"Geographic dispersion ensures that one hurricane, earthquake, or grid failure cannot take out both the primary and recovery sites. Two sites on the same campus are not dispersed."},
{id:"u8l3-4",t:"u8l3",q:"Only one engineer knows how to restore the organization's backup system, and that engineer is on extended leave. Which capacity planning area does this gap represent?",a:["People","Infrastructure","Technology","Compute"],c:0,e:"Capacity planning covers people, technology, and infrastructure. Dependence on a single individual is a people capacity gap addressed by cross-training and documented procedures."},
{id:"u8l3-5",t:"u8l3",q:"An organization deliberately runs its critical workloads across two different cloud providers. Which resilience strategy is this?",a:["Clustering","Multi-cloud","Cold site","Continuity of operations"],c:1,e:"Multi-cloud spreads workloads across providers so one provider's outage or breach is survivable, a form of diversity. It costs additional complexity to manage."},

// u8l4
{id:"u8l4-1",t:"u8l4",q:"A company performs a full backup every Sunday and wants weekday backups that can be restored using only the full backup plus the most recent weekday backup. Which backup type should be used on weekdays?",a:["Incremental","Snapshot","Differential","Replication"],c:2,e:"A differential backup captures everything changed since the last full backup, so a restore needs only the full plus the latest differential. Incremental restores need every incremental since the full."},
{id:"u8l4-2",t:"u8l4",q:"After a ransomware attack, the organization discovers that its backups were also encrypted because the backup server was reachable from the infected network. Which backup practice was missing?",a:["Encrypting the backups","Taking more frequent snapshots","Using RAID 6 on the backup server","Keeping an offline or immutable copy"],c:3,e:"Ransomware encrypts any backup it can write to. An offline (disconnected) or immutable copy cannot be altered by the compromised systems, which is what makes recovery possible without paying."},
{id:"u8l4-3",t:"u8l4",q:"Why is RAID not considered a substitute for backups?",a:["RAID protects against disk failure but mirrors deletions, corruption, and ransomware across all disks","RAID is too slow to restore","RAID cannot be used on servers","RAID only works with tape"],c:0,e:"RAID keeps a system running when a disk fails, but a deleted or encrypted file is deleted or encrypted on every disk in the array. Backups protect against everything RAID does not."},
{id:"u8l4-4",t:"u8l4",q:"An organization wants to verify that its disaster recovery plan is complete by having the team walk through a scenario step by step in a meeting, without touching any systems. Which test is this?",a:["Failover test","Tabletop exercise","Parallel processing","Simulation"],c:1,e:"A tabletop exercise is a discussion-based walkthrough that finds gaps in the plan without affecting production. A failover test actually switches systems, and parallel processing runs the recovery environment alongside production."},
{id:"u8l4-5",t:"u8l4",q:"During a power outage, which component keeps servers running for the seconds to minutes before the generator reaches full output?",a:["Generator","Power distribution unit","Uninterruptible power supply","Surge protector"],c:2,e:"A UPS uses batteries to carry the load through short outages and the generator's start-up delay, and it conditions power. The generator provides long-term power once running."},

// u9l1
{id:"u9l1-1",t:"u9l1",q:"Servers were configured according to the approved baseline when built, but an audit months later finds that many now differ from the baseline and from each other. Which step of secure baseline management failed?",a:["Establish","Deploy","Classify","Maintain"],c:3,e:"Maintaining a baseline means monitoring for drift and re-applying the approved configuration. The systems were established and deployed correctly but not maintained."},
{id:"u9l1-2",t:"u9l1",q:"A technician is installing a new network switch. Which hardening actions should be performed FIRST?",a:["Change the default credentials and disable unused ports and services","Enable jumbo frames and LACP","Install an endpoint protection agent","Configure the switch as a jump server"],c:0,e:"Default credentials are publicly known and unused services are pure attack surface, so changing defaults and disabling unneeded ports and services are the first hardening steps for any device. Agents cannot run on switches."},
{id:"u9l1-3",t:"u9l1",q:"Which hardening approach is MOST appropriate for embedded systems and IoT devices that cannot run security software and rarely receive firmware updates?",a:["Install host-based intrusion prevention on each device","Place them on a separate network segment and monitor their traffic","Require multifactor authentication on the devices","Encrypt their internal storage with a TPM"],c:1,e:"Constrained devices cannot host agents or be patched reliably, so protection comes from the environment: isolation on their own segment, firewall rules allowing only needed traffic, and monitoring."},
{id:"u9l1-4",t:"u9l1",q:"An organization's cloud storage buckets keep being created with public read access. Which measure addresses this at the baseline level?",a:["Manual review of each bucket monthly","Full-disk encryption on administrator laptops","A cloud baseline with automated configuration scanning and enforcement","Disabling the cloud provider's logging"],c:2,e:"A cloud baseline defines that storage must not be public, and configuration scanning with enforcement detects and corrects violations automatically. Manual monthly review is too slow and inconsistent."},
{id:"u9l1-5",t:"u9l1",q:"Which hardening measure applies specifically to workstations rather than to network devices?",a:["Changing the SNMP community string","Updating router firmware","Disabling Telnet in favor of SSH","Ensuring users do not run as local administrators"],c:3,e:"Least privilege for interactive users, so they are not local administrators, is a workstation control that limits what malware can do. The other options are network device hardening steps."},

// u9l2
{id:"u9l2-1",t:"u9l2",q:"Every time an employee leaves, the company must change the Wi-Fi passphrase on all devices. Which change eliminates this problem?",a:["Implement WPA Enterprise with 802.1X and RADIUS","Hide the SSID","Switch to WPA3-Personal","Enable MAC address filtering"],c:0,e:"Enterprise mode authenticates each user or device individually against a RADIUS server, so one account can be revoked without affecting anyone else. Personal mode shares one passphrase regardless of WPA version."},
{id:"u9l2-2",t:"u9l2",q:"Which WPA3 feature prevents attackers from capturing the wireless handshake and cracking the passphrase offline?",a:["TKIP","Simultaneous authentication of equals (SAE)","Hidden SSID","WEP key rotation"],c:1,e:"SAE replaces the pre-shared key handshake with an exchange that requires live interaction for every guess, defeating offline dictionary attacks. TKIP and WEP are deprecated; hidden SSIDs provide no security."},
{id:"u9l2-3",t:"u9l2",q:"A wireless engineer measures signal strength throughout a building before and after installing access points and produces a color-coded floor plan. What is this activity and its output?",a:["Penetration test; a risk register","Vulnerability scan; a CVSS report","Site survey; a heat map","Enumeration; an inventory"],c:2,e:"A site survey measures coverage, signal, and interference, and its output is a heat map showing signal strength across the floor plan, used to place access points and limit signal leaking outside."},
{id:"u9l2-4",t:"u9l2",q:"A company purchases phones and lets employees select one from a list of three approved models; the company owns and manages the devices. Which deployment model is this?",a:["BYOD","COPE","Shadow IT","CYOD"],c:3,e:"Choose your own device means the company owns and manages the device but the employee selects it from an approved list. COPE is company-owned with personal use allowed but company-chosen; BYOD is employee-owned."},
{id:"u9l2-5",t:"u9l2",q:"An executive's phone containing customer data was lost. Which control would allow the organization to remotely erase the corporate data?",a:["Mobile device management enrollment","A site survey","A captive portal","Bluetooth pairing restrictions"],c:0,e:"Mobile device management enforces policy on enrolled devices, including remote lock and wipe. A device that was never enrolled cannot be wiped, which would itself be the finding."},

// u9l3
{id:"u9l3-1",t:"u9l3",q:"A single development practice defeats SQL injection, cross-site scripting, buffer overflows, and directory traversal. Which practice is it?",a:["Code signing","Server-side input validation","Sandboxing","Secure cookies"],c:1,e:"Validating every input on the server for type, length, format, and range stops malicious input before it reaches a query, a page, a buffer, or a file path. Client-side validation alone is bypassed by attackers."},
{id:"u9l3-2",t:"u9l3",q:"Which cookie attribute prevents a cross-site scripting payload from reading a user's session cookie?",a:["Secure","SameSite","HttpOnly","Expires"],c:2,e:"The HttpOnly flag makes the cookie unavailable to JavaScript, so a script injected through XSS cannot steal it. Secure restricts the cookie to HTTPS, and SameSite limits cross-site requests."},
{id:"u9l3-3",t:"u9l3",q:"A security team wants developers to discover hard-coded credentials and unvalidated database queries before the application is ever built or run. Which technique fits?",a:["Dynamic analysis","Penetration testing","Fuzzing the running application","Static code analysis"],c:3,e:"Static code analysis examines source code without executing it and flags dangerous patterns early in the pipeline. Dynamic analysis and penetration testing require a running application."},
{id:"u9l3-4",t:"u9l3",q:"Systems must verify that a software update genuinely came from the vendor and was not modified in transit before installing it. Which control provides this?",a:["Code signing","Input validation","Data masking","Load balancing"],c:0,e:"Code signing uses the vendor's private key to sign releases; the installing system verifies the signature with the public key, proving origin and integrity. It is the defense against tampered downloads and malicious updates."},
{id:"u9l3-5",t:"u9l3",q:"An analyst receives a suspicious email attachment and wants to observe its behavior without any risk to the network. Which approach should be used?",a:["Open it on a production workstation with antivirus enabled","Execute it in a sandbox","Upload it to the file server for review","Forward it to all analysts"],c:1,e:"A sandbox runs code in an isolated environment with no access to real systems or networks, so suspected malware can be detonated and observed safely."},

// u9l4
{id:"u9l4-1",t:"u9l4",q:"A network scan identifies six active devices that do not appear in the organization's asset records. Which asset management activity produced this finding?",a:["Classification","Sanitization","Enumeration","Procurement"],c:2,e:"Enumeration actively discovers what is really on the network and compares it to the inventory; the difference is the set of unknown assets. Inventory alone is only what the organization believes it has."},
{id:"u9l4-2",t:"u9l4",q:"An organization plans to donate laptops that previously held internal documents. Which disposal method allows the laptops to be reused while ensuring the data cannot be recovered?",a:["Physical destruction of the drives","Formatting with the default quick format","Simply deleting the user profiles","Sanitization of the drives"],c:3,e:"Sanitization removes data irrecoverably while leaving the media usable, through cryptographic erase or secure overwriting. Deleting or quick formatting leaves data recoverable, and destruction prevents reuse."},
{id:"u9l4-3",t:"u9l4",q:"Before destroying old financial records, what must an organization verify FIRST?",a:["That data retention requirements and legal holds do not require the records to be kept","That the shredder is certified","That the records have been classified as public","That a hot site has a copy"],c:0,e:"Retention laws, regulations, and legal holds may require records to be kept for a period; destroying them prematurely can be a serious violation. Retention is checked before any disposal."},
{id:"u9l4-4",t:"u9l4",q:"Auditors require proof that the drives from a retired cardholder database were destroyed. Which item satisfies this requirement?",a:["The original purchase order","A certificate of destruction from the disposal vendor","The asset's classification label","A heat map"],c:1,e:"Certification is documented proof, typically from a third party, that sanitization or destruction was completed. It is required for regulated data and is what auditors accept."},
{id:"u9l4-5",t:"u9l4",q:"A critical file server has gone unpatched for two years because no one is responsible for it. Which asset management element was missing?",a:["Sanitization","Enumeration","Assignment and ownership","Certification"],c:2,e:"Every asset needs a named owner accountable for patching, access decisions, and disposal. Ownerless assets are the ones that decay into long-term vulnerabilities."},

// u10l1
{id:"u10l1-1",t:"u10l1",q:"A security team wants the most accurate report of missing patches and installed software on its servers. Which scanning approach should be used?",a:["Non-credentialed scan from outside the network","Dynamic application analysis","Passive threat feed subscription","Credentialed scan using an account on each server"],c:3,e:"A credentialed scan logs into the system and sees installed software, patch levels, and configuration directly, producing fewer false positives than a non-credentialed scan that sees only exposed services."},
{id:"u10l1-2",t:"u10l1",q:"An application is built from dozens of open-source libraries. Which practice alerts the team when one of those libraries receives a new vulnerability identifier?",a:["Package monitoring","Static code analysis of the team's own code","Penetration testing","Responsible disclosure"],c:0,e:"Package monitoring tracks third-party dependencies and their known vulnerabilities, alerting when a new CVE is published for a library in use. Static analysis covers the team's own code."},
{id:"u10l1-3",t:"u10l1",q:"Management asks whether a vulnerability reported by the scanner on the customer portal can actually be exploited to reach customer data. Which activity answers this?",a:["A vulnerability rescan","A penetration test","Package monitoring","Log archiving"],c:1,e:"A penetration test attempts exploitation under authorization and demonstrates the actual path and consequences, proving whether a scanner finding is exploitable in practice."},
{id:"u10l1-4",t:"u10l1",q:"A hospital wants to learn about threats currently targeting other healthcare organizations from its peers. Which threat intelligence source fits?",a:["Dark web monitoring","A proprietary vendor feed","An industry information sharing and analysis center (ISAC)","Static code analysis"],c:2,e:"ISACs are sector-specific organizations whose members share threat information affecting their industry. Vendor feeds are commercial, and dark web monitoring watches criminal markets."},
{id:"u10l1-5",t:"u10l1",q:"A researcher finds a serious flaw in a company's product but sees no way to report it safely. Which program gives researchers a defined, safe process for reporting flaws and may reward them?",a:["Change management","A system audit","Package monitoring","A bug bounty program with responsible disclosure"],c:3,e:"Responsible disclosure policies define how to report and what the researcher can expect, and bug bounty programs pay for valid reports. Both turn outside researchers into allies rather than adversaries."},

// u10l2
{id:"u10l2-1",t:"u10l2",q:"A vulnerability scanner reports a critical flaw in a web server version, but the administrator confirms the server runs a different, patched version. What is this finding called?",a:["False positive","False negative","Zero-day","Exception"],c:0,e:"A false positive is a reported vulnerability that does not actually exist. A false negative is a real vulnerability the scanner missed, which is the more dangerous error."},
{id:"u10l2-2",t:"u10l2",q:"Two findings have the same CVSS score of 9.1: one on an isolated lab server with no sensitive data, and one on the internet-facing payment gateway. Which factors justify remediating the gateway first?",a:["CVSS score alone","Environmental variables and organizational impact","The age of the servers","Alphabetical order of hostnames"],c:1,e:"Prioritization combines CVSS with environmental factors such as exposure to the internet and the sensitivity of data, plus the impact to the organization. Equal CVSS scores do not mean equal risk."},
{id:"u10l2-3",t:"u10l2",q:"Which CVSS score range is classified as Critical?",a:["4.0 to 6.9","7.0 to 8.9","9.0 to 10.0","0.1 to 3.9"],c:2,e:"CVSS severity ratings are None 0, Low 0.1 to 3.9, Medium 4.0 to 6.9, High 7.0 to 8.9, and Critical 9.0 to 10.0."},
{id:"u10l2-4",t:"u10l2",q:"A patch was deployed to fifty servers last week to fix a reported vulnerability. What should the team do NEXT to confirm the remediation?",a:["Close the tickets","Document an exception","Purchase cyber insurance","Rescan the servers"],c:3,e:"Validation requires evidence that the flaw is gone; rescanning the systems confirms the patch took effect on every server. A closed ticket is a claim, not proof."},
{id:"u10l2-5",t:"u10l2",q:"An essential legacy application has a vulnerability with no available patch. Management decides to leave it in place with added monitoring and a review in six months. Which response is being documented?",a:["A risk exception with compensating controls","Patching","Insurance","A false negative"],c:0,e:"An exception is a documented, approved decision to leave a vulnerability unremediated for a stated reason and period, usually with compensating controls and an owner, and it is reviewed when it expires."},

// u10l3
{id:"u10l3-1",t:"u10l3",q:"A security team wants to detect that the same credentials were used on the VPN, then on an internal server from a different country, then to transfer large files externally, all within an hour. Which tool correlates these events across sources?",a:["Vulnerability scanner","SIEM","SNMP trap receiver","Antivirus console"],c:1,e:"A security information and event management system aggregates logs from many sources and correlates events to reveal patterns no single log shows. The other tools each see only their own domain."},
{id:"u10l3-2",t:"u10l3",q:"Analysts receive thousands of alerts each day and have started ignoring them, missing a real intrusion. Which activity addresses this problem?",a:["Log archiving","Increasing scan frequency","Alert tuning","Adding more SNMP traps"],c:2,e:"Alert tuning suppresses benign patterns, adjusts thresholds, and enriches alerts so false positives drop and real alerts are seen. Alert fatigue is a tuning failure, not a staffing one."},
{id:"u10l3-3",t:"u10l3",q:"An organization wants to automatically verify that every server matches a published hardening benchmark. Which standard enables tools to perform these checks?",a:["NetFlow","IPsec","DLP","SCAP"],c:3,e:"The Security Content Automation Protocol expresses configuration checks in a standard format so tools can compare systems against benchmarks automatically and report compliance."},
{id:"u10l3-4",t:"u10l3",q:"A network operations team wants to be notified the instant a core switch interface goes down, without waiting for the next polling cycle. Which mechanism provides this?",a:["SNMP traps","NetFlow export","A credentialed scan","Log archiving"],c:0,e:"SNMP traps are pushed by the device the moment an event occurs, unlike polling, which checks on a schedule. NetFlow summarizes traffic and scans check for vulnerabilities."},
{id:"u10l3-5",t:"u10l3",q:"Which tool detects and blocks an employee from emailing a spreadsheet containing customer card numbers to a personal address?",a:["Vulnerability scanner","Data loss prevention","SNMP","NetFlow"],c:1,e:"Data loss prevention inspects content leaving by email, upload, or removable media, recognizes sensitive patterns such as card numbers, and blocks or alerts. NetFlow sees only conversation summaries."}
);
