// SecPlus Academy question bank, units 11 to 15. All questions are original.
window.FRA = window.FRA || {};
FRA.questions = FRA.questions || [];
FRA.questions.push(
// u11l1
{id:"u11l1-1",t:"u11l1",q:"A firewall administrator adds a rule denying SSH to a server, but SSH connections from the internet are still succeeding. Which explanation is MOST likely?",a:["The implicit deny is disabled","A broader allow rule higher in the list matches the traffic first","SSH cannot be blocked by firewalls","The rule needs a reboot to apply"],c:1,e:"Firewall rules are evaluated top-down and the first match wins, so an allow rule above the new deny still permits the traffic. Rule order must be corrected."},
{id:"u11l1-2",t:"u11l1",q:"An organization must block gambling and social media sites for employees using laptops at home as well as in the office. Which web filtering approach meets the requirement?",a:["A centralized proxy on the corporate network","DNS filtering on the office resolver only","Agent-based web filtering with content categorization","A screened subnet"],c:2,e:"Agent-based filtering runs on the device and enforces policy wherever it goes. A centralized proxy only covers traffic that passes through the corporate network, and an office-only resolver does not affect home use."},
{id:"u11l1-3",t:"u11l1",q:"A security team wants to prevent infected hosts from reaching their command-and-control servers, regardless of which application initiates the connection, with minimal deployment effort. Which control fits BEST?",a:["Group Policy","A web application firewall","Signature-based IPS on the web proxy","DNS filtering"],c:3,e:"DNS filtering refuses to resolve known-malicious domains, so any application on any device fails to reach them. It is inexpensive and covers everything that uses DNS."},
{id:"u11l1-4",t:"u11l1",q:"Which intrusion detection approach can identify an attack for which no signature has been published?",a:["Trend or behavior-based detection","Signature-based detection","URL scanning","Block rules"],c:0,e:"Behavior or trend-based detection alerts on deviations from normal activity, so it can catch new attacks at the cost of more false positives. Signatures only match known patterns."},
{id:"u11l1-5",t:"u11l1",q:"A packet that matches none of the configured firewall rules arrives at the firewall. What happens to it?",a:["It is allowed by default","It is dropped by the implicit deny","It is forwarded to the IDS for a decision","It is held until an administrator approves it"],c:1,e:"Every firewall rule set ends with an implicit deny that drops traffic not explicitly permitted. This is why unlisted services are blocked without a specific deny rule."},

// u11l2
{id:"u11l2-1",t:"u11l2",q:"Which email security mechanism publishes a policy telling receiving servers whether to quarantine or reject messages that fail sender authentication checks?",a:["SPF","DKIM","DMARC","An email gateway"],c:2,e:"DMARC is the DNS policy record that instructs receivers what to do when SPF or DKIM checks fail and where to send reports. SPF lists allowed senders and DKIM signs messages."},
{id:"u11l2-2",t:"u11l2",q:"A security team wants to be alerted if any system binary or configuration file on a critical server is modified. Which control provides this?",a:["Data loss prevention","User behavior analytics","Network access control","File integrity monitoring"],c:3,e:"File integrity monitoring stores hashes of critical files and alerts when they change, detecting replaced binaries, edited configurations, and dropped web shells."},
{id:"u11l2-3",t:"u11l2",q:"Only laptops with current antivirus, applied patches, and disk encryption should be allowed onto the corporate network; others should be placed in a remediation network. Which control implements this?",a:["Network access control with posture assessment","EDR","DLP","SELinux"],c:0,e:"Network access control authenticates devices and checks their posture before granting access, sending noncompliant devices to a quarantine or remediation network with limited access."},
{id:"u11l2-4",t:"u11l2",q:"A finance clerk's valid account began downloading the entire engineering repository at 3 a.m. Which tool is designed to detect this kind of deviation from an account's normal pattern?",a:["File integrity monitoring","User behavior analytics","Group Policy","SPF"],c:1,e:"User behavior analytics baselines each account's normal activity and alerts on deviations in hours, systems, and volumes, catching compromised credentials and malicious insiders whose credentials are valid."},
{id:"u11l2-5",t:"u11l2",q:"Which endpoint capability detects ransomware by its behavior rather than by a known file signature and allows analysts to isolate the host remotely?",a:["Traditional antivirus","Data loss prevention","Endpoint detection and response","Group Policy"],c:2,e:"EDR agents record process, file, and network activity, detect malicious behavior, and provide response actions such as remote isolation. Signature antivirus misses fileless and novel malware."},

// u12l1
{id:"u12l1-1",t:"u12l1",q:"An audit finds that several employees who left the company months ago still have active VPN accounts. Which identity management process failed?",a:["Identity proofing","Attestation","Federation","Deprovisioning"],c:3,e:"Deprovisioning removes access when someone leaves. Automating it from the HR system's termination record closes the gap that leaves accounts active after departure."},
{id:"u12l1-2",t:"u12l1",q:"Employees of a partner company access an organization's web portal using their own company credentials, and the organization never stores their passwords. Which concept is this?",a:["Federation","Password vaulting","Kerberos","Rule-based access control"],c:0,e:"Federation lets one organization trust identities managed by another: the partner's identity provider authenticates, and the organization's application trusts the signed assertion."},
{id:"u12l1-3",t:"u12l1",q:"A scheduling application asks for permission to add events to a user's calendar on another service without ever receiving the user's password. Which protocol enables this delegated access?",a:["SAML","OAuth","LDAP","Kerberos"],c:1,e:"OAuth provides delegated authorization: an application receives limited, scoped access to a user's resources on another service. It is not itself an authentication protocol."},
{id:"u12l1-4",t:"u12l1",q:"Managers are required each quarter to review and confirm that each of their direct reports still needs the access they hold. What is this process called?",a:["Provisioning","Identity proofing","Attestation","Interoperability"],c:2,e:"Attestation is the periodic confirmation by an accountable person that access remains appropriate, catching permissions that accumulate as people change roles."},
{id:"u12l1-5",t:"u12l1",q:"Which protocol is XML-based and commonly used for enterprise single sign-on to software-as-a-service applications?",a:["OAuth","OpenID Connect","RADIUS","SAML"],c:3,e:"SAML uses XML assertions issued by an identity provider and trusted by the service provider, and it is the common standard for enterprise web single sign-on."},

// u12l2
{id:"u12l2-1",t:"u12l2",q:"In a government system, documents carry classification labels and users hold clearances; a user cannot share a secret document with a colleague who lacks clearance, even if the user created it. Which access control model is this?",a:["Mandatory access control","Discretionary access control","Role-based access control","Rule-based access control"],c:0,e:"Mandatory access control enforces system-assigned labels and clearances that users cannot override. Discretionary control would let the document's owner decide who may access it."},
{id:"u12l2-2",t:"u12l2",q:"Access to a financial application is granted only if the user is in the finance department, is using a managed device, is located in an approved country, and is connecting during business hours. Which access control model evaluates these conditions together?",a:["Discretionary access control","Attribute-based access control","Role-based access control","Mandatory access control"],c:1,e:"Attribute-based access control makes decisions from combinations of user, device, resource, and context attributes. Role-based control considers only the role."},
{id:"u12l2-3",t:"u12l2",q:"A user authenticates with a password and then answers a security question about their first pet. How many authentication factors are in use?",a:["Three","Two","One","Four"],c:2,e:"Both a password and a security question are something you know, so this is one factor used twice. Multifactor authentication requires two different categories such as know and have."},
{id:"u12l2-4",t:"u12l2",q:"New employees in the accounting department automatically receive the same set of permissions as every other accountant when their accounts are created. Which access control model is being used?",a:["Discretionary access control","Time-of-day restrictions","Mandatory access control","Role-based access control"],c:3,e:"Role-based access control attaches permissions to roles and assigns users to roles, so everyone in a job function receives consistent access. It scales and audits well."},
{id:"u12l2-5",t:"u12l2",q:"An organization wants an MFA method that cannot be phished because it responds only to the genuine website. Which implementation should it choose?",a:["Hardware security keys using public key cryptography","Software token app","SMS one-time codes","Security questions"],c:0,e:"Security keys use public key cryptography bound to the legitimate site's origin, so a fake site receives no valid response. Codes sent by SMS or generated by apps can be entered into a phishing page."},

// u12l3
{id:"u12l3-1",t:"u12l3",q:"Which password attribute MOST increases resistance to brute force attacks?",a:["Requiring at least one special character","Length","Changing it every 30 days","Using a security question as backup"],c:1,e:"Guessing cost grows exponentially with length, so long passphrases beat short complex passwords. Forced expiration and complexity rules add little and can push users toward predictable patterns."},
{id:"u12l3-2",t:"u12l3",q:"Employees have started writing passwords on sticky notes since the company began forcing password changes every month. Which policy change addresses the root of the problem?",a:["Shorten expiration to two weeks","Require two special characters","Remove routine expiration, require longer passwords, and check against breached password lists","Disable password managers"],c:2,e:"Modern guidance discourages routine expiration because it produces predictable, written-down passwords. Length requirements and breached-password checks provide real strength."},
{id:"u12l3-3",t:"u12l3",q:"A dozen administrators share knowledge of the root password for a critical database. Which privileged access management practice fixes this?",a:["Just-in-time permissions","Time-of-day restrictions","Passwordless authentication for end users","Password vaulting with automatic rotation"],c:3,e:"Password vaulting stores privileged credentials in a vault that administrators check out per session, after which the vault rotates the password. Nobody needs to know the shared credential."},
{id:"u12l3-4",t:"u12l3",q:"Administrators currently hold permanent domain administrator rights on their daily accounts. Which practice reduces the impact of one of those accounts being compromised?",a:["Just-in-time permissions","Longer passwords","Security questions","Federation"],c:0,e:"Just-in-time permissions grant administrative rights only when requested, for a limited window, then remove them automatically, so no standing privilege exists to be stolen."},
{id:"u12l3-5",t:"u12l3",q:"An organization wants to eliminate the possibility of its executives' passwords being phished. Which authentication approach BEST achieves this?",a:["Complex 12-character passwords","Passwordless authentication with security keys","Monthly password expiration","Shared password vault"],c:1,e:"Passwordless authentication removes the password entirely, leaving nothing to phish, spray, or reuse, and security keys respond only to the genuine site."},

// u12l4
{id:"u12l4-1",t:"u12l4",q:"Security analysts spend hours each day copying alert details into the ticketing system by hand. Which automation use case directly addresses this?",a:["Guard rails","User provisioning","Ticket creation through orchestration","Continuous integration"],c:2,e:"Orchestration can create tickets automatically from alerts with the evidence attached, eliminating manual copying and speeding response. This is a classic use case for automation."},
{id:"u12l4-2",t:"u12l4",q:"A developer's deployment accidentally created a publicly readable storage bucket, but the automation platform blocked the change before it took effect. Which automation concept prevented the exposure?",a:["Workforce multiplier","Escalation","Technical debt","Guard rails"],c:3,e:"Guard rails are automated checks that stop deployments or configurations that violate policy, such as public storage or open ports, before they are applied."},
{id:"u12l4-3",t:"u12l4",q:"When an organization's orchestration platform crashed, no security alerts were processed and no accounts could be disabled automatically for several hours. Which consideration of automation does this illustrate?",a:["Single point of failure","Employee retention","Reaction time","Enforcing baselines"],c:0,e:"Centralizing response in one platform makes that platform a single point of failure; when it fails, every dependent process stops. It must be made resilient."},
{id:"u12l4-4",t:"u12l4",q:"Which of the following is a benefit of security automation that the exam objectives specifically identify?",a:["Increased complexity","Workforce multiplier","Technical debt","Ongoing supportability costs"],c:1,e:"Automation acts as a workforce multiplier, letting a small team accomplish the work of a larger one. Complexity, technical debt, and supportability are listed as considerations or drawbacks."},
{id:"u12l4-5",t:"u12l4",q:"A script that rotates encryption keys was written years ago by an employee who has since left; nobody understands it and it fails intermittently. Which two automation considerations does this describe?",a:["Reaction time and efficiency","Guard rails and escalation","Technical debt and ongoing supportability","Baselines and scaling"],c:2,e:"Undocumented, unmaintained automation is technical debt, and the lack of anyone able to maintain it is an ongoing supportability problem. Both are recognized drawbacks of automation."},

// u13l1
{id:"u13l1-1",t:"u13l1",q:"Analysis has confirmed that malware is actively spreading from an infected workstation to file shares. What is the NEXT step in the incident response process?",a:["Eradication","Lessons learned","Recovery","Containment"],c:3,e:"Once an incident is confirmed and scoped, containment stops the spread before any cleanup. Eradication and recovery follow containment."},
{id:"u13l1-2",t:"u13l1",q:"All affected systems have been rebuilt from clean images, the vulnerability has been patched, and normal operations have resumed under close monitoring. Which phase is the team in, and what comes next?",a:["Recovery; lessons learned is next","Containment; eradication is next","Eradication; recovery is next","Preparation; detection is next"],c:0,e:"Restoring systems and resuming operations is recovery. The final phase is lessons learned, which reviews the incident and feeds improvements back into preparation."},
{id:"u13l1-3",t:"u13l1",q:"An incident response team meets in a conference room to discuss how they would handle a hypothetical ransomware outbreak, without touching any systems. Which activity is this?",a:["A simulation","A tabletop exercise","Threat hunting","Root cause analysis"],c:1,e:"A tabletop exercise is a discussion-based walkthrough of a scenario that finds gaps in the plan without affecting systems. A simulation is a hands-on drill."},
{id:"u13l1-4",t:"u13l1",q:"After a phishing incident, the team determines that the real reason the attacker gained broad access was the absence of multifactor authentication and excessive account permissions. Which activity produced this conclusion?",a:["Detection","Containment","Root cause analysis","Attestation"],c:2,e:"Root cause analysis looks past the immediate event to the underlying condition that made the incident possible, so the fix prevents recurrence rather than only addressing the symptom."},
{id:"u13l1-5",t:"u13l1",q:"Without any alert having fired, analysts search logs and endpoint data for traces of an attack technique described in a recent threat report. What is this activity called?",a:["Incident detection","Alert tuning","Lessons learned","Threat hunting"],c:3,e:"Threat hunting proactively searches for signs of compromise based on hypotheses and threat intelligence, assuming attackers may already be present and undetected."},

// u13l2
{id:"u13l2-1",t:"u13l2",q:"Legal counsel informs IT that a lawsuit involving a former employee is expected. What must IT do with that employee's mailbox and files?",a:["Preserve them under a legal hold and suspend routine deletion","Delete them according to the normal retention schedule","Reimage the laptop for reuse","Move them to a public share for counsel"],c:0,e:"A legal hold requires preservation of relevant data the moment litigation is reasonably anticipated. Routine retention purges and reimaging must be suspended for that data."},
{id:"u13l2-2",t:"u13l2",q:"A server suspected of compromise is still powered on. Which evidence should be collected FIRST, and why?",a:["The disk image, because it is the largest","Memory contents, because they are lost at power off","Backup tapes, because they are stable","Remote logs, because they are easy to reach"],c:1,e:"Order of volatility dictates capturing the most transient evidence first. Memory holds running processes, keys, and connections and disappears when the system is powered down."},
{id:"u13l2-3",t:"u13l2",q:"An investigator computes a hash of a seized drive before imaging and a hash of the resulting image, and the two match. What does this demonstrate?",a:["The drive contains no malware","The chain of custody is complete","The image is an exact, unaltered copy of the original","The evidence is encrypted"],c:2,e:"Matching hashes prove the image is bit-for-bit identical to the original, supporting the integrity of the evidence. Chain of custody is documented separately."},
{id:"u13l2-4",t:"u13l2",q:"Seized evidence was left on an analyst's desk unattended for an afternoon with no record of who had access. Which forensic principle was violated?",a:["Order of volatility","Legal hold","E-discovery","Chain of custody"],c:3,e:"Chain of custody requires a continuous record of everyone who handled the evidence and when. An undocumented gap allows an opposing party to argue the evidence was altered."},
{id:"u13l2-5",t:"u13l2",q:"Which term describes the overall legal process of identifying, preserving, collecting, and producing electronically stored information for litigation?",a:["E-discovery","Threat hunting","Acquisition","Attestation"],c:0,e:"E-discovery is the legal process for producing electronic evidence in proceedings. Legal hold, chain of custody, and proper acquisition are what make the produced evidence admissible."},

// u13l3
{id:"u13l3-1",t:"u13l3",q:"An investigator needs to determine which internal device was using a specific IP address at 2:15 p.m. yesterday. Which data source answers this?",a:["Application logs","DHCP and network logs","IPS logs","Vulnerability scan results"],c:1,e:"DHCP lease records and network logs map IP addresses to devices over time. Application and IPS logs record activity, not address assignments."},
{id:"u13l3-2",t:"u13l3",q:"An email appears to come from the CEO, but the investigator suspects impersonation. Which data source reveals the servers the message actually passed through?",a:["Firewall logs","Endpoint logs","Email header metadata","Dashboards"],c:2,e:"Email headers are metadata recording every server that handled the message and its true origin, which exposes forged sender addresses."},
{id:"u13l3-3",t:"u13l3",q:"To determine exactly what data was transmitted to an external address during a suspected exfiltration, which source provides the most complete detail?",a:["NetFlow records","Automated reports","Firewall logs","Packet captures"],c:3,e:"Packet captures contain the full contents of network traffic and allow exact reconstruction of what was sent. NetFlow and firewall logs record only summaries and connection details."},
{id:"u13l3-4",t:"u13l3",q:"An analyst needs to know which processes executed on a laptop immediately after a user opened a suspicious attachment. Which log source is appropriate?",a:["Endpoint logs","Firewall logs","OS security logs on the domain controller","Network logs"],c:0,e:"Endpoint logs from the endpoint agent record process starts, file changes, and detections on the device itself. Firewall and network logs show connections, not local execution."},
{id:"u13l3-5",t:"u13l3",q:"Investigators cannot order events across the firewall, server, and endpoint logs because each system reports different times for the same event. Which control was missing?",a:["Log archiving","Time synchronization across systems","Packet capture","Vulnerability scanning"],c:1,e:"Correlating events across sources requires all systems to agree on the time, typically through NTP. Without synchronization the sequence of events cannot be reconstructed."},

// u14l1
{id:"u14l1-1",t:"u14l1",q:"A document states: \"All company laptops must use AES-256 full-disk encryption and TLS 1.2 or higher for all connections.\" Which type of governance document is this?",a:["Policy","Procedure","Standard","Guideline"],c:2,e:"A standard specifies exact, mandatory requirements that implement a policy, such as named algorithms and versions. A policy states what must be done at a high level without the specific settings."},
{id:"u14l1-2",t:"u14l1",q:"A document lists numbered steps for disabling accounts, forwarding email, and collecting equipment when an employee leaves. Which document type is this?",a:["Acceptable use policy","Guideline","Encryption standard","Offboarding procedure"],c:3,e:"Procedures provide step-by-step instructions for performing a task. Offboarding procedures ensure access and equipment are consistently recovered when someone departs."},
{id:"u14l1-3",t:"u14l1",q:"A document says employees are encouraged to use a password manager and to consider enabling automatic updates on home devices. Which document type is this?",a:["Guideline","Standard","Procedure","Policy"],c:0,e:"Guidelines are recommended practices that are not mandatory, signaled by words like encouraged, consider, and should. Policies and standards use must."},
{id:"u14l1-4",t:"u14l1",q:"Which policy defines what users may and may not do with company computers, email, and internet access?",a:["Change management policy","Acceptable use policy","Disaster recovery policy","Software development lifecycle policy"],c:1,e:"The acceptable use policy sets the rules for how employees may use organizational systems and data. The other policies govern changes, recovery, and development."},
{id:"u14l1-5",t:"u14l1",q:"Security analysts follow a predefined step-by-step checklist whenever a user reports a phishing email. What is this document called?",a:["An information security policy","A guideline","A playbook","A standard"],c:2,e:"A playbook is a procedure written for a specific incident type, giving responders defined steps so they do not have to improvise under pressure."},

// u14l2
{id:"u14l2-1",t:"u14l2",q:"A company uses a cloud payroll service that processes employee data strictly according to the company's instructions. In privacy terms, which roles do the company and the service hold?",a:["Company is the processor; service is the controller","Company is the custodian; service is the owner","Both are data subjects","Company is the controller; service is the processor"],c:3,e:"The controller decides why and how personal data is processed, and the processor acts on the controller's instructions. The employees are the data subjects."},
{id:"u14l2-2",t:"u14l2",q:"The finance director decides who may access the general ledger and how it must be protected, while the database team performs backups and grants the approved access. Which roles do they hold?",a:["Director is the owner; team is the custodian","Director is the custodian; team is the owner","Director is the processor; team is the controller","Both are data subjects"],c:0,e:"The data owner is accountable for classification and access decisions, and the custodian or steward handles the data day to day on the owner's behalf."},
{id:"u14l2-3",t:"u14l2",q:"Merchants that accept credit cards must follow security requirements set by the card brands rather than by a government. Which type of external consideration is this?",a:["Regulatory","Industry","Legal","Local"],c:1,e:"Industry requirements are standards imposed by the industry itself, such as payment card security rules from the card brands, as opposed to laws or government regulations."},
{id:"u14l2-4",t:"u14l2",q:"Which governance body holds ultimate accountability for an organization's cyber risk and receives regular risk reports?",a:["The help desk","The change advisory board","The board of directors","The data custodians"],c:2,e:"The board of directors carries ultimate accountability for organizational risk, including cyber risk, and depends on regular reporting to exercise oversight."},
{id:"u14l2-5",t:"u14l2",q:"An organization lets each business division run its own security program while a small central team provides coordination and guidelines. Which governance structure is this, and what is its main trade-off?",a:["Centralized; consistency at the cost of responsiveness","Committee-based; oversight at the cost of ownership","Regulatory; compliance at the cost of speed","Decentralized; responsiveness at the cost of consistency"],c:3,e:"Decentralized governance lets units respond to local needs but makes consistent policy and monitoring harder. Centralized governance is the opposite trade-off."},

// u14l3
{id:"u14l3-1",t:"u14l3",q:"A server is valued at 80,000 and a fire would destroy 50 percent of its value. Fires are expected once every 10 years. What is the annualized loss expectancy?",a:["4,000","40,000","8,000","400"],c:0,e:"SLE = AV x EF = 80,000 x 0.5 = 40,000. ARO = 1/10 = 0.1. ALE = SLE x ARO = 40,000 x 0.1 = 4,000 per year."},
{id:"u14l3-2",t:"u14l3",q:"A risk assessment rates each risk as low, medium, or high for likelihood and impact and plots them on a matrix without dollar values. Which type of analysis is this?",a:["Quantitative","Qualitative","Continuous","Ad hoc"],c:1,e:"Qualitative analysis uses descriptive ratings and judgment rather than monetary values. Quantitative analysis computes figures such as SLE and ALE."},
{id:"u14l3-3",t:"u14l3",q:"A company performs a risk assessment specifically because it is about to acquire another firm, and does not plan to repeat it. Which assessment type is this?",a:["Recurring","Continuous","One-time","Ad hoc"],c:2,e:"A one-time assessment is performed once for a specific event such as an acquisition. Ad hoc assessments arise from a need but may recur; recurring and continuous are scheduled or ongoing."},
{id:"u14l3-4",t:"u14l3",q:"An asset worth 50,000 has a single loss expectancy of 10,000 for a particular threat. What is the exposure factor?",a:["0.5","2","5","0.2"],c:3,e:"SLE = AV x EF, so EF = SLE / AV = 10,000 / 50,000 = 0.2, meaning 20 percent of the asset's value is lost in one incident."},
{id:"u14l3-5",t:"u14l3",q:"A control costs 6,000 per year and reduces the annualized loss expectancy of a risk from 15,000 to 2,000. Which statement is correct?",a:["The control is justified because it reduces ALE by 13,000 at a cost of 6,000","The control is not justified because it costs more than the remaining ALE","The control should be replaced by insurance","The ALE cannot be compared to control cost"],c:0,e:"The control removes 13,000 of expected annual loss for 6,000 per year, a net benefit of 7,000. Comparing ALE reduction to control cost is how quantitative analysis justifies spending."},

// u14l4
{id:"u14l4-1",t:"u14l4",q:"An organization purchases cyber insurance to cover breach response costs. Which risk management strategy is this, and what does it NOT do?",a:["Mitigate; it does not reduce likelihood","Transfer; it does not transfer accountability","Avoid; it does not eliminate the activity","Accept; it does not document the risk"],c:1,e:"Insurance transfers the financial impact of a risk to another party. Accountability to customers and regulators for the outcome remains with the organization."},
{id:"u14l4-2",t:"u14l4",q:"A business impact analysis determines that order processing must be restored within four hours and that no more than 15 minutes of transaction data may be lost. Which two metrics have been defined?",a:["MTTR of 4 hours and MTBF of 15 minutes","RPO of 4 hours and RTO of 15 minutes","RTO of 4 hours and RPO of 15 minutes","MTBF of 4 hours and MTTR of 15 minutes"],c:2,e:"The recovery time objective is the maximum acceptable restoration time, and the recovery point objective is the maximum acceptable data loss measured in time."},
{id:"u14l4-3",t:"u14l4",q:"A company decides to stop offering a feature that collected customers' biometric data because the risk outweighed the benefit. Which risk strategy is this?",a:["Mitigate","Accept","Transfer","Avoid"],c:3,e:"Avoidance eliminates a risk by discontinuing the activity that creates it. Mitigation would add controls while keeping the feature."},
{id:"u14l4-4",t:"u14l4",q:"A fast-growing startup deliberately accepts higher security risk to ship products quickly, while a hospital accepts very little. Which term describes these differing attitudes?",a:["Risk appetite","Risk threshold","Key risk indicator","Risk register"],c:0,e:"Risk appetite is the amount of risk an organization is willing to pursue: expansionary for the startup, conservative for the hospital. Tolerance is the practical limit for a specific risk."},
{id:"u14l4-5",t:"u14l4",q:"Which element of a risk register provides an early, measurable warning that a risk is increasing, such as the count of unpatched critical systems?",a:["Risk owner","Key risk indicator","Risk appetite","Exposure factor"],c:1,e:"Key risk indicators are measurable signals tracked in the risk register; when one crosses its threshold the risk owner must act."},

// u15l1
{id:"u15l1-1",t:"u15l1",q:"A company wants the contractual ability to inspect a vendor's security controls on site. Which contract element provides this?",a:["Service level agreement","Non-disclosure agreement","Right-to-audit clause","Statement of work"],c:2,e:"A right-to-audit clause gives the customer the ability to examine the vendor's controls directly, which is the strongest form of vendor assurance."},
{id:"u15l1-2",t:"u15l1",q:"Which agreement specifies measurable performance commitments such as 99.9 percent uptime and defines remedies if they are not met?",a:["Memorandum of understanding","Master service agreement","Business partnership agreement","Service level agreement"],c:3,e:"A service level agreement defines measurable service targets and the consequences of missing them. An MOU is non-binding intent and an MSA is the umbrella contract."},
{id:"u15l1-3",t:"u15l1",q:"A company signs an umbrella contract with a consulting firm and then issues separate documents defining the deliverables, timeline, and price of each individual project. What are these two document types?",a:["MSA and SOW","SLA and NDA","MOU and BPA","NDA and MOA"],c:0,e:"The master service agreement covers the overall relationship, and each statement of work defines one specific piece of work under it."},
{id:"u15l1-4",t:"u15l1",q:"The employee leading vendor selection owns shares in one of the bidding vendors. Which vendor selection concern does this represent?",a:["Supply chain analysis","Conflict of interest","Rules of engagement","Due diligence"],c:1,e:"A conflict of interest exists when a decision maker has a personal stake in the outcome, undermining objective selection regardless of the vendor's quality."},
{id:"u15l1-5",t:"u15l1",q:"Which vendor assessment source provides the MOST objective evidence of a vendor's security controls?",a:["The vendor's completed security questionnaire","The vendor's marketing materials","An independent third-party assessment report","The vendor's verbal assurances"],c:2,e:"Independent assessments by outside auditors have no stake in the outcome and follow recognized standards. Questionnaires and assurances are the vendor's own claims."},

// u15l2
{id:"u15l2-1",t:"u15l2",q:"A customer requests that a company erase all personal data it holds about them, and the applicable law obliges the company to comply. Which privacy right is being exercised?",a:["Data sovereignty","Due care","Attestation","Right to be forgotten"],c:3,e:"The right to be forgotten allows a data subject to have their personal data erased on request under applicable privacy law. Fulfilling it requires a complete data inventory."},
{id:"u15l2-2",t:"u15l2",q:"An organization thoroughly researches a new regulation and then implements the required controls. Which two concepts together describe acting responsibly in this way?",a:["Due diligence and due care","Attestation and acknowledgement","Controller and processor","Internal and external reporting"],c:0,e:"Due diligence is understanding the requirements and risks; due care is taking the reasonable actions that follow. Together they demonstrate responsible conduct."},
{id:"u15l2-3",t:"u15l2",q:"Employees must sign each year to confirm they have read and understood the information security policy. Which compliance monitoring element is this?",a:["Attestation by an auditor","Acknowledgement","Automation","External reporting"],c:1,e:"Acknowledgement is an individual's recorded confirmation of having read a policy or completed training. Attestation is a formal statement that controls are in place."},
{id:"u15l2-4",t:"u15l2",q:"A regulator revokes a financial firm's authorization to operate after repeated compliance failures. Which consequence of non-compliance is this?",a:["Reputational damage","Contractual impact","Loss of license","Fine"],c:2,e:"Loss of license means the organization loses its permission to operate in a regulated business, one of the most severe consequences of non-compliance."},
{id:"u15l2-5",t:"u15l2",q:"Why is a complete data inventory a prerequisite for honoring a data subject's deletion request?",a:["Because deletion requests must be reported externally","Because the processor owns the data","Because the inventory serves as the legal hold","Because the organization cannot erase data it does not know it holds"],c:3,e:"To erase all of a person's data, the organization must know every place that data exists. Without an inventory, complete deletion cannot be assured or demonstrated."},

// u15l3
{id:"u15l3-1",t:"u15l3",q:"Penetration testers are provided with network diagrams, source code, and administrator credentials before the engagement. Which type of test environment is this?",a:["Known environment","Partially known environment","Unknown environment","Integrated environment"],c:0,e:"A known environment test gives testers full information, providing the deepest coverage in the least time. Unknown environment tests provide no information and simulate an outside attacker."},
{id:"u15l3-2",t:"u15l3",q:"Before touching the target, testers gather information from DNS records, public job postings, and employees' social media profiles. Which activity is this?",a:["Active reconnaissance","Passive reconnaissance","Self-assessment","Attestation"],c:1,e:"Passive reconnaissance collects information from public sources without interacting with the target and cannot be detected. Active reconnaissance involves scanning or probing the target."},
{id:"u15l3-3",t:"u15l3",q:"During an exercise, the attacking team and the defending team work together in real time, sharing what the attackers are doing so detection can be improved immediately. Which testing approach is this?",a:["Offensive","Defensive","Integrated","Physical"],c:2,e:"Integrated, or purple team, testing combines the red (offensive) and blue (defensive) teams collaboratively. Separate red and blue exercises do not share findings in real time."},
{id:"u15l3-4",t:"u15l3",q:"A prospective customer will only sign if the company provides evidence of its security controls from an auditor with no stake in the outcome. Which type of audit satisfies this?",a:["Self-assessment","Internal compliance audit","Audit committee review","Independent third-party audit"],c:3,e:"An independent third-party audit is performed by an outside auditor with no interest in the result, producing a report that customers and regulators can rely on. Self-assessments are not independent."},
{id:"u15l3-5",t:"u15l3",q:"Which internal governance body oversees the audit function and ensures that audit findings are addressed?",a:["The audit committee","The change advisory board","The help desk","The data custodians"],c:0,e:"The audit committee is a board-level body that oversees internal and external audits, receives their results, and ensures remediation of findings."},

// u15l4
{id:"u15l4-1",t:"u15l4",q:"An organization sends simulated phishing emails to employees and measures how many click and how many report the message. What is this activity, and what is its primary purpose?",a:["A penetration test; to find vulnerabilities","A phishing campaign; to educate users and improve reporting","Disciplinary monitoring; to identify employees to terminate","A tabletop exercise; to test the incident plan"],c:1,e:"Phishing campaigns are awareness tools whose purpose is education and improved recognition and reporting. Punishing clickers undermines the program."},
{id:"u15l4-2",t:"u15l4",q:"An employee notices a coworker photographing customer records on screen and reports it to security. Which awareness program element enabled this?",a:["Password management training","Removable media guidance","Anomalous behavior recognition","Hybrid work guidance"],c:2,e:"Training users to recognize and report risky, unexpected, or unintentional behavior turns employees into sensors for insider threats and policy violations."},
{id:"u15l4-3",t:"u15l4",q:"Which metric BEST indicates that a security awareness program is working, according to the way phishing simulations should be evaluated?",a:["Number of employees disciplined","Decrease in training completion","Number of emails sent","Increase in the rate at which suspicious emails are reported"],c:3,e:"Reporting is the most valuable behavior because a single early report lets the security team protect everyone. Rising report rates show the program is changing behavior."},
{id:"u15l4-4",t:"u15l4",q:"Which security awareness topic specifically addresses securing home routers, locking screens away from family members, and using a VPN on public Wi-Fi?",a:["Hybrid and remote work","Operational security","Insider threat","Situational awareness"],c:0,e:"Hybrid and remote work guidance covers the risks of working outside the office: home network security, device protection at home, and public network use."},
{id:"u15l4-5",t:"u15l4",q:"Before launching an awareness program, an organization records its current phishing click rate and training completion percentage. Which reporting element is this?",a:["Recurring reporting","Initial reporting","External reporting","Attestation"],c:1,e:"Initial reporting establishes the baseline against which recurring measurements show improvement and reveal groups that need additional attention."}
);
