// SecPlus Academy question bank, units 1 to 5. All questions are original.
// Fields: id, t (lesson id), q (stem), a (four options), c (index of correct option), e (explanation).
window.FRA = window.FRA || {};
FRA.questions = FRA.questions || [];
FRA.questions.push(
// u1l1
{id:"u1l1-1",t:"u1l1",q:"A hospital cannot patch an infusion pump because the vendor has not released an update. The security team places the pump on an isolated network segment and adds traffic monitoring. Which control type BEST describes these additions?",a:["Deterrent","Compensating","Directive","Corrective"],c:1,e:"A compensating control substitutes for the ideal control when it cannot be applied. Patching is impossible, so segmentation and monitoring compensate. Corrective controls repair damage after an event; deterrent controls discourage; directive controls instruct."},
{id:"u1l1-2",t:"u1l1",q:"A company adopts a written policy requiring quarterly reviews of user access rights. Which control category does this policy belong to?",a:["Physical","Technical","Managerial","Operational"],c:2,e:"Policies, risk assessments, and oversight are managerial controls. Technical controls are enforced by systems, physical controls protect facilities, and operational controls are performed by people as procedures."},
{id:"u1l1-3",t:"u1l1",q:"A login screen displays a banner stating that all activity is monitored and unauthorized use will be prosecuted. Which control type is this banner?",a:["Preventive","Compensating","Detective","Deterrent"],c:3,e:"A warning banner discourages misuse without physically stopping it, which is a deterrent. It does not prevent access, detect activity, or compensate for a missing control."},
{id:"u1l1-4",t:"u1l1",q:"After a file server was breached, administrators restored the data from the previous night's backup. Which control type does the restoration represent?",a:["Corrective","Preventive","Directive","Detective"],c:0,e:"Restoring from backup repairs the damage after an incident, which is the definition of a corrective control. Detective controls only notice the event, and preventive controls try to stop it beforehand."},
{id:"u1l1-5",t:"u1l1",q:"Security guards at the lobby check every visitor's identification against a list before allowing entry. Which category and type BEST describe this control?",a:["Physical, detective","Operational, preventive","Technical, preventive","Managerial, directive"],c:1,e:"A guard carrying out a checking procedure is an operational control (performed by people), and checking identities before entry prevents unauthorized access. The guard is not a system (technical) or a building feature (physical)."},

// u1l2
{id:"u1l2-1",t:"u1l2",q:"An organization wants to guarantee that a contract signed electronically cannot later be denied by the person who signed it. Which security concept and mechanism address this?",a:["Confidentiality, using symmetric encryption","Availability, using a redundant server","Non-repudiation, using a digital signature","Authorization, using role-based access"],c:2,e:"Non-repudiation means the signer cannot deny the action. A digital signature is created with the signer's private key, which only they hold, so it ties the document to them. Encryption provides confidentiality, not proof of origin."},
{id:"u1l2-2",t:"u1l2",q:"A database administrator discovers that several customer records were modified without any record of who changed them or when. Which pillar of the CIA triad was MOST directly violated?",a:["Confidentiality","Availability","Non-repudiation","Integrity"],c:3,e:"Unauthorized or undetected modification of data is an integrity failure. Confidentiality concerns disclosure, availability concerns access, and non-repudiation is a separate concept about denying actions."},
{id:"u1l2-3",t:"u1l2",q:"Before an upcoming compliance audit, a security manager compares the organization's current controls against every requirement in the applicable regulation and lists what is missing. What is this activity called?",a:["Gap analysis","Risk transference","Penetration test","Tabletop exercise"],c:0,e:"A gap analysis compares the current state to a required or target state and produces a list of gaps to close. A penetration test attacks systems, a tabletop exercise walks through a response plan, and risk transference shifts risk to another party."},
{id:"u1l2-4",t:"u1l2",q:"A laptop presents a certificate to a switch before it is allowed onto the corporate network. Which element of AAA does this represent?",a:["Accounting of a system","Authentication of a system","Authorization of a user","Auditing of a user"],c:1,e:"Presenting a certificate proves the device's identity, which is authentication. It is a system, not a person, being authenticated. Authorization decides what the device may access afterward, and accounting records what it did."},
{id:"u1l2-5",t:"u1l2",q:"A web application logs every action each user takes so that changes can be traced back to an individual. Which AAA component is being implemented?",a:["Authentication","Authorization","Accounting","Attestation"],c:2,e:"Accounting records what an authenticated identity did. Authentication proves identity, authorization decides permitted actions, and attestation is a separate concept of confirming a claimed state."},

// u1l3
{id:"u1l3-1",t:"u1l3",q:"In a zero trust architecture, which component is responsible for making the decision to allow or deny an access request?",a:["Policy enforcement point","Policy administrator","Implicit trust zone","Policy engine"],c:3,e:"The policy engine evaluates each request against policy and decides. The policy administrator communicates that decision, and the policy enforcement point applies it to the traffic in the data plane."},
{id:"u1l3-2",t:"u1l3",q:"A user who normally signs in from a managed office laptop attempts to sign in from a personal tablet in another country and is prompted for an additional verification factor. Which zero trust concept is being applied?",a:["Adaptive identity","Threat scope reduction","Implicit trust zone","Policy-driven access control"],c:0,e:"Adaptive identity adjusts authentication requirements to context such as device, location, and behavior. Threat scope reduction limits what an identity can reach; policy-driven access control is the general principle of rules over location."},
{id:"u1l3-3",t:"u1l3",q:"Which zero trust component sits in the data plane and physically allows or blocks a connection after a decision is made?",a:["Policy engine","Policy enforcement point","Policy administrator","Adaptive identity service"],c:1,e:"The policy enforcement point is the data plane gate that applies the control plane's decision to actual traffic. The engine and administrator are control plane components that decide and communicate."},
{id:"u1l3-4",t:"u1l3",q:"A security architect redesigns access so that a compromised account can reach only the two applications that role requires, instead of the entire internal network. Which zero trust principle does this implement?",a:["Implicit trust zones","Policy administrator","Threat scope reduction","Subject and system separation"],c:2,e:"Threat scope reduction limits what any single identity can reach, so a compromised account causes minimal damage. Implicit trust zones are the small areas where traffic is allowed after verification, not the principle of limiting reach."},
{id:"u1l3-5",t:"u1l3",q:"Which statement BEST contrasts zero trust with a traditional perimeter security model?",a:["Zero trust removes the need for authentication inside the network","Zero trust trusts all managed devices without further checks","Zero trust relies on a stronger firewall at the network edge","Zero trust grants access based on verification of each request rather than network location"],c:3,e:"Zero trust treats network location as meaningless and verifies every request against policy using identity, device, and context. A perimeter model trusts anything inside the boundary. Zero trust adds verification; it does not remove it."},

// u1l4
{id:"u1l4-1",t:"u1l4",q:"Employees have been observed holding the secure door open for people walking in behind them. Which physical control BEST prevents this behavior from granting unauthorized entry?",a:["An access control vestibule","Bollards at the entrance","Additional lighting in the lobby","A pressure sensor in the hallway"],c:0,e:"An access control vestibule uses two interlocking doors so only one authenticated person passes at a time, defeating tailgating. Bollards stop vehicles, lighting deters, and a pressure sensor only detects."},
{id:"u1l4-2",t:"u1l4",q:"A security team places a spreadsheet named executive_bonuses.xlsx on a file share. Nobody is told about it, and any attempt to open it generates an alert. What is this file?",a:["A honeynet","A honeyfile","A honeytoken","A honeypot"],c:1,e:"A honeyfile is a bait document that alerts when accessed. A honeytoken is a fake credential or data record, a honeypot is a decoy system, and a honeynet is a decoy network."},
{id:"u1l4-3",t:"u1l4",q:"A data center wants to detect an intruder walking through a dark corridor by sensing body heat. Which sensor type is MOST appropriate?",a:["Pressure","Ultrasonic","Infrared","Microwave"],c:2,e:"Infrared sensors detect heat, such as a person's body heat moving across the field of view. Pressure sensors detect weight, while microwave and ultrasonic sensors detect motion through reflected waves."},
{id:"u1l4-4",t:"u1l4",q:"A retail store wants to stop vehicles from being driven through its glass storefront during a robbery. Which control should be installed?",a:["Video surveillance","Fencing","An access badge system","Bollards"],c:3,e:"Bollards are posts designed specifically to stop vehicles. Fencing defines a perimeter for people, badges control door access, and cameras deter and detect but do not stop a vehicle."},
{id:"u1l4-5",t:"u1l4",q:"An organization plants a fake administrator account in its directory that is never used for any legitimate purpose. Weeks later a login with that account is detected. What has the organization learned?",a:["An attacker has obtained credentials from the directory","The directory needs a larger password length requirement","The account's password has expired","A legitimate administrator made a typo"],c:0,e:"The fake account is a honeytoken. Because nothing legitimate ever uses it, any use proves that someone obtained credentials they should not have, indicating a breach. Honeytokens produce true positives by design."},

// u2l1
{id:"u2l1-1",t:"u2l1",q:"A change advisory board reviews a request to upgrade the email server. Which document MUST accompany the request so the change can be reversed if it fails?",a:["Maintenance window schedule","Backout plan","Stakeholder list","Standard operating procedure"],c:1,e:"The backout plan documents the exact steps to return to the previous state if the change fails. The maintenance window schedules the change, the stakeholder list identifies affected parties, and a standard operating procedure covers routine pre-approved changes."},
{id:"u2l1-2",t:"u2l1",q:"After a database upgrade succeeded, the reporting application that connects to the database stopped working the next morning. Which part of the change process was MOST likely inadequate?",a:["Version control","Ownership assignment","Impact analysis of dependencies","Approval by the change board"],c:2,e:"The reporting application depended on the database, and a proper impact analysis would have identified and tested that dependency before the change. Ownership, approval, and version control do not identify dependent systems."},
{id:"u2l1-3",t:"u2l1",q:"A network team needs to revert a firewall to last week's configuration after a bad change. Which practice makes this fast and reliable?",a:["Maintaining a deny list","Documenting the stakeholders","Restricting activities during the window","Using version control for configurations"],c:3,e:"Version control keeps every previous version of a configuration with a record of who changed what, so rolling back is retrieving the prior version. The other options do not preserve prior configurations."},
{id:"u2l1-4",t:"u2l1",q:"A security administrator adds a new application to the organization's application allow list as part of a scheduled change. Which category of change management consideration does this represent?",a:["Technical implication: allow lists and deny lists","Business process: ownership","Business process: approval","Documentation: version control"],c:0,e:"Modifying allow or deny lists is a technical implication of a change: it directly alters what software or traffic is permitted. The business process items concern approval, ownership, and scheduling."},
{id:"u2l1-5",t:"u2l1",q:"An engineer applied an emergency patch at 2 a.m. to stop an active attack, without prior approval. What is required after the fact according to change management practice?",a:["Nothing, because emergency changes are exempt from the process","The change must be documented and reviewed through the change process","The patch must be removed until it is approved","The engineer must be removed from the change board"],c:1,e:"Emergency changes may skip prior approval to address an urgent risk, but they must still be documented, reviewed, and recorded afterward so the change is understood and the configuration record stays accurate."},

// u2l2
{id:"u2l2-1",t:"u2l2",q:"Alice wants to send a confidential file to Bob so that only Bob can read it. Which key should Alice use to encrypt the file?",a:["Alice's private key","Alice's public key","Bob's public key","Bob's private key"],c:2,e:"Encrypting with the recipient's public key means only the matching private key, which only Bob holds, can decrypt. Alice's private key would be used for signing, not for confidentiality."},
{id:"u2l2-2",t:"u2l2",q:"A company must encrypt a 400 GB backup set every night as quickly as possible. Which approach is MOST appropriate?",a:["RSA with a 4096-bit key","Diffie-Hellman key exchange alone","ECDSA signatures on each file","AES-256 symmetric encryption"],c:3,e:"Symmetric encryption such as AES is fast and designed for bulk data. Asymmetric algorithms like RSA are far slower and used for key exchange and signatures. ECDSA signs; Diffie-Hellman only agrees on a key."},
{id:"u2l2-3",t:"u2l2",q:"An auditor requires that if a web server's private key is stolen next year, previously recorded TLS sessions must still be undecryptable. Which feature satisfies this?",a:["Perfect forward secrecy using ephemeral Diffie-Hellman","Longer RSA key length","A wildcard certificate","Key escrow"],c:0,e:"Perfect forward secrecy comes from ephemeral key exchange: each session uses a fresh key not derived from the server's long-term key, so compromising that key later does not expose past sessions. Longer RSA keys do not change this property."},
{id:"u2l2-4",t:"u2l2",q:"A manufacturer needs strong public key cryptography on battery-powered sensors with minimal processing power. Which algorithm family is BEST suited?",a:["RSA","Elliptic curve cryptography","3DES","MD5"],c:1,e:"Elliptic curve cryptography provides equivalent strength to RSA with much shorter keys and less computation, which suits constrained devices. 3DES is a legacy symmetric cipher and MD5 is a broken hash."},
{id:"u2l2-5",t:"u2l2",q:"Which of the following BEST describes the role of asymmetric cryptography in a TLS connection?",a:["It encrypts all of the web page content for the whole session","It compresses the data before transmission","It authenticates the server and protects the exchange of the session key","It replaces the need for a session key"],c:2,e:"TLS uses asymmetric cryptography to prove the server's identity through its certificate and to establish a shared session key. The bulk of the session data is then encrypted with fast symmetric encryption using that session key."},

// u2l3
{id:"u2l3-1",t:"u2l3",q:"A security analyst notices that two users who chose the same password have different values stored in the password database. Which technique explains this?",a:["Key stretching","Digital signing","Tokenization","Salting"],c:3,e:"Salting adds a unique random value to each password before hashing, so identical passwords produce different hashes and precomputed tables become useless. Key stretching slows hashing but does not by itself differentiate identical inputs."},
{id:"u2l3-2",t:"u2l3",q:"A developer wants to make offline cracking of stolen password hashes as slow as possible for attackers. Which approach accomplishes this?",a:["Using a key-stretching function such as bcrypt or PBKDF2","Storing passwords with reversible encryption","Using MD5 for speed","Shortening the minimum password length"],c:0,e:"Key-stretching functions are deliberately slow and iterate the hash many times, so each attacker guess costs real time. MD5 is fast and broken, reversible encryption exposes passwords if the key leaks, and shorter passwords are easier to crack."},
{id:"u2l3-3",t:"u2l3",q:"A software vendor publishes a SHA-256 value next to each download. What does a customer verify by computing the hash of the downloaded file and comparing it?",a:["That the file is encrypted","That the file has not been altered since the vendor published it","That the vendor's private key is valid","That the file contains no malware"],c:1,e:"Matching hashes prove the file is bit-for-bit identical to what the vendor hashed, which is integrity. A hash does not encrypt, does not validate keys, and cannot detect malware that was present when the vendor hashed the file."},
{id:"u2l3-4",t:"u2l3",q:"Which sequence correctly describes creating a digital signature?",a:["Encrypt the message with the recipient's public key, then hash it","Hash the message, then encrypt the hash with the sender's public key","Hash the message, then encrypt the hash with the sender's private key","Encrypt the message with a shared symmetric key, then sign the key"],c:2,e:"A digital signature is the hash of the message encrypted with the sender's private key. The receiver decrypts it with the sender's public key and compares it to their own hash of the message to confirm integrity and origin."},
{id:"u2l3-5",t:"u2l3",q:"An organization still uses SHA-1 for code-signing hashes. A researcher demonstrates two different files that produce the same SHA-1 value. Which attack has been demonstrated, and what is the remedy?",a:["A downgrade attack; disable TLS 1.0","A birthday attack; increase the salt length","A replay attack; add timestamps","A collision; migrate to SHA-256 or stronger"],c:3,e:"Two different inputs with the same hash is a collision, which lets a forged file carry a valid signature. The remedy is a modern hash algorithm such as SHA-256. Salting applies to password storage, not code signing."},

// u2l4
{id:"u2l4-1",t:"u2l4",q:"An administrator needs a certificate for a new web server from a public certificate authority. What is sent to the CA to request it?",a:["A certificate signing request containing the public key","The server's private key","A self-signed certificate","The root CA's certificate"],c:0,e:"A certificate signing request contains the server's public key and identity information. The private key is generated on the server and never leaves it. The CA validates the request and returns the signed certificate."},
{id:"u2l4-2",t:"u2l4",q:"Users report that browsers display a warning when visiting the company's internal help desk site, even though the site works. What is the MOST likely cause?",a:["The certificate is a wildcard certificate","The site uses a self-signed certificate not trusted by the browsers","The certificate was issued by a public CA","OCSP stapling is enabled on the server"],c:1,e:"A self-signed certificate has no trusted CA behind it, so browsers warn. Wildcard and publicly issued certificates are trusted, and OCSP stapling improves revocation checking rather than causing warnings."},
{id:"u2l4-3",t:"u2l4",q:"A security architect wants clients to check whether a certificate has been revoked in real time without downloading a large periodically updated list. Which mechanism should be used?",a:["CRL","CSR","OCSP","Key escrow"],c:2,e:"OCSP lets a client query the status of a single certificate in real time. A CRL is a downloaded list that can be stale. A CSR requests a certificate, and key escrow stores copies of keys."},
{id:"u2l4-4",t:"u2l4",q:"A company hosts mail.example.com, www.example.com, and portal.example.com and wants one certificate that covers all current and future hosts at that level. Which certificate type fits?",a:["Self-signed","Code-signing","Root","Wildcard"],c:3,e:"A wildcard certificate for *.example.com covers every single-label subdomain, including ones created later. A subject alternative name certificate lists specific names only; code-signing and root certificates serve other purposes."},
{id:"u2l4-5",t:"u2l4",q:"An employee who encrypted important project files with a personal certificate leaves the company, and the files must be recovered. Which practice would have made recovery possible?",a:["Key escrow","OCSP stapling","Using a DER-formatted certificate","Certificate pinning"],c:0,e:"Key escrow keeps a copy of private keys with a trusted party so encrypted data can be recovered if the key holder is unavailable. Formats, stapling, and pinning do not provide key recovery."},

// u2l5
{id:"u2l5-1",t:"u2l5",q:"Several company laptops have been stolen from vehicles. Which control BEST ensures that data on future stolen laptops remains unreadable?",a:["File-level encryption of the Documents folder","Full-disk encryption tied to the TPM","Transport encryption using TLS","Record-level database encryption"],c:1,e:"Full-disk encryption protects everything on the drive, including the operating system and temporary files, and binding it to the TPM means the disk unlocks only in its own machine. File-level encryption leaves other data exposed."},
{id:"u2l5-2",t:"u2l5",q:"Database administrators must be able to run queries but must never see customers' credit card numbers stored in the database. Which encryption level meets this requirement?",a:["Full-disk encryption on the database server","Volume encryption","Record-level encryption of the card number field","Transport encryption between the application and the database"],c:2,e:"Record-level encryption protects individual fields with a key the administrators do not hold, so the rest of the data stays queryable while the card numbers stay unreadable. Full-disk and volume encryption are transparent to anyone logged in."},
{id:"u2l5-3",t:"u2l5",q:"A certificate authority needs to store its signing keys so they cannot be extracted even by system administrators, and perform signing operations without exposing the keys. Which device is designed for this?",a:["Trusted Platform Module","Key management service","Secure enclave","Hardware security module"],c:3,e:"A hardware security module is a dedicated tamper-resistant device that stores keys and performs cryptographic operations internally at scale. A TPM is a per-machine chip, a secure enclave is inside a processor, and a KMS is a management service."},
{id:"u2l5-4",t:"u2l5",q:"A retailer replaces stored credit card numbers with random substitute values and keeps the real numbers in a separate secured vault. What is this technique called?",a:["Tokenization","Steganography","Data masking","Hashing"],c:0,e:"Tokenization substitutes a token for sensitive data and maps it back only through a protected vault. Masking hides part of a value for display, steganography hides data inside other files, and hashing is one-way."},
{id:"u2l5-5",t:"u2l5",q:"An investigator suspects that confidential documents were leaked by embedding them inside ordinary image files posted publicly. Which technique is being described?",a:["Tokenization","Steganography","Data masking","Key stretching"],c:1,e:"Steganography conceals the existence of data by hiding it within another file such as an image or audio file. Tokenization and masking substitute or partially hide values, and key stretching relates to password hashing."},

// u3l1
{id:"u3l1-1",t:"u3l1",q:"Forensic analysis of a defense contractor's network reveals custom malware that has been present for nine months, communicating with infrastructure linked to a foreign government. Which threat actor is MOST likely responsible?",a:["Hacktivist","Unskilled attacker","Nation-state","Shadow IT"],c:2,e:"Long-term stealthy access with custom tooling against a defense target is characteristic of a nation-state actor conducting espionage. Hacktivists seek publicity, unskilled attackers use borrowed tools, and shadow IT is not an attacker."},
{id:"u3l1-2",t:"u3l1",q:"A company's public website is defaced with a message condemning its environmental practices. Which threat actor is MOST likely responsible, and what is the motivation?",a:["Organized crime, financial gain","Nation-state, espionage","Insider threat, revenge","Hacktivist, philosophical or political beliefs"],c:3,e:"Defacement with a political or ethical message is the signature of a hacktivist motivated by beliefs. Organized crime seeks money, insiders act from inside, and nation-states pursue espionage or disruption quietly."},
{id:"u3l1-3",t:"u3l1",q:"A vulnerability scan discovers an unregistered file server running an unpatched operating system that the marketing department set up on its own to share large files. Which term describes the source of this risk?",a:["Shadow IT","Insider threat","Organized crime","Hacktivist"],c:0,e:"Shadow IT is technology deployed by employees without approval or oversight. It is not malicious, but it is unmanaged and unpatched. An insider threat involves intent or negligence causing harm, not simply unapproved tooling."},
{id:"u3l1-4",t:"u3l1",q:"Which attribute BEST distinguishes an insider threat from all external threat actors?",a:["Level of sophistication","Existing legitimate access to systems","Amount of funding","Use of ransomware"],c:1,e:"An insider already has authorized access, so they do not need to breach the perimeter. Sophistication and funding vary among all actor types, and ransomware is a tool used mainly by organized crime."},
{id:"u3l1-5",t:"u3l1",q:"A well-funded, highly sophisticated group encrypts a hospital's systems and demands payment through a professional-looking portal that offers a discount for quick payment. Which threat actor is this?",a:["Nation-state","Unskilled attacker","Organized crime","Hacktivist"],c:2,e:"High resources and sophistication combined with a financial motive point to organized crime, which runs ransomware as a business. A nation-state would pursue espionage or disruption rather than a payment portal."},

// u3l2
{id:"u3l2-1",t:"u3l2",q:"An employee finds a USB drive in the parking lot, plugs it into a workstation to identify the owner, and malware executes. Which threat vector was exploited?",a:["Message-based","Unsecure wireless network","Supply chain","Removable device"],c:3,e:"A removable device such as a USB drive is a physical threat vector; malware runs when it is connected. The defense combines device control policies with user training."},
{id:"u3l2-2",t:"u3l2",q:"A breach investigation finds that attackers entered through the remote access credentials of the managed service provider that maintains the company's backups. Which threat vector does this represent?",a:["Supply chain","Open service ports","Default credentials","Image-based"],c:0,e:"A managed service provider is part of the supply chain; compromising its access provides a path into every customer. The company's own credentials and ports were not the entry point."},
{id:"u3l2-3",t:"u3l2",q:"A visitor plugs a laptop into a live network jack in an unattended conference room and gains access to internal servers. Which control MOST directly closes this vector?",a:["Email filtering","Port security with 802.1X on switch ports","Full-disk encryption","A web application firewall"],c:1,e:"An unsecured wired network is the vector. Port security and 802.1X require authentication before a switch port carries traffic, so an unknown laptop gets nothing. The other controls address different vectors."},
{id:"u3l2-4",t:"u3l2",q:"A company runs an application on an operating system version that reached end of support two years ago. Which statement BEST describes the risk?",a:["The system is safe as long as antivirus is installed","The vendor will provide patches only for critical flaws","Every vulnerability discovered from now on will remain unpatched","The system can only be attacked from inside the network"],c:2,e:"An unsupported system receives no patches at all, so each newly discovered flaw stays open permanently. Antivirus does not fix vulnerabilities, and the system is attackable from any vector that reaches it."},
{id:"u3l2-5",t:"u3l2",q:"Which vulnerability scanning approach requires software to be installed on each endpoint that is assessed?",a:["Agentless scanning","External penetration testing","Passive network monitoring","Client-based scanning"],c:3,e:"Client-based scanning uses an agent installed on the endpoint to report its software and configuration. Agentless scanning assesses systems over the network without installing anything."},

// u3l3
{id:"u3l3-1",t:"u3l3",q:"The accounts payable clerk receives an email that appears to come from the CFO, instructing an urgent wire transfer to a new supplier account before the end of the day. Which attack is this, and what is the BEST control?",a:["Business email compromise; verify the request through a known phone number","Whaling; install antivirus on the CFO's laptop","Smishing; block SMS messages","Watering hole; filter the supplier's website"],c:0,e:"An email impersonating an executive to redirect a payment is business email compromise. The effective control is procedural: out-of-band verification of any payment change through a known contact, never by replying to the email."},
{id:"u3l3-2",t:"u3l3",q:"A caller claiming to be from the help desk tells a user that mailboxes are being migrated tonight and asks for the user's password to complete the move. Which technique is the caller using?",a:["Typosquatting","Pretexting","Watering hole","Dumpster diving"],c:1,e:"Pretexting is inventing a believable story that justifies the request. Legitimate help desks never need a user's password. Typosquatting involves look-alike domains, and a watering hole is a compromised website."},
{id:"u3l3-3",t:"u3l3",q:"Several employees of an engineering firm were infected after visiting an industry news website that the attackers had compromised specifically because the firm's staff read it daily. What is this attack called?",a:["Spear phishing","Brand impersonation","Watering hole","Vishing"],c:2,e:"A watering hole attack compromises a site the targets already visit and waits for them. Spear phishing uses targeted messages, brand impersonation fakes a company, and vishing uses phone calls."},
{id:"u3l3-4",t:"u3l3",q:"Users receive text messages containing a link to 'confirm' their payroll direct deposit details. Which attack is this?",a:["Vishing","Shoulder surfing","Whaling","Smishing"],c:3,e:"Phishing delivered by SMS text message is smishing. Vishing uses voice calls, whaling targets executives by email, and shoulder surfing is observing a screen in person."},
{id:"u3l3-5",t:"u3l3",q:"An attacker registers the domain rnicrosoft-support.com to host a fake login page that captures credentials from users who misread the address. Which technique is this?",a:["Typosquatting","Misinformation","Watering hole","Tailgating"],c:0,e:"Typosquatting registers domains that resemble legitimate ones to catch typos and misreadings. Misinformation is false content spread unknowingly, and tailgating is a physical entry technique."},

// u4l1
{id:"u4l1-1",t:"u4l1",q:"A tester sends a 3,000-character string to a field that expects a 50-character name. The service crashes and, with a crafted input, executes code supplied by the tester. Which vulnerability is this?",a:["Race condition","Buffer overflow","SQL injection","Directory traversal"],c:1,e:"Copying more data into a memory buffer than it can hold overwrites adjacent memory, including the return address, allowing attacker code to run. That is a buffer overflow."},
{id:"u4l1-2",t:"u4l1",q:"A program verifies that a temporary file is safe to read and then opens it a moment later. An attacker replaces the file with a link to a sensitive system file between those two steps. Which vulnerability is exploited?",a:["Memory injection","Malicious update","Time-of-check to time-of-use race condition","Buffer overflow"],c:2,e:"The check was valid when performed, but the resource changed before it was used. This is a time-of-check to time-of-use race condition, fixed only by making the check and use atomic in the code."},
{id:"u4l1-3",t:"u4l1",q:"Endpoint analysts find malicious code executing inside a legitimate system process with no corresponding file on disk. Which vulnerability class does this exploit?",a:["Side loading","Firmware vulnerability","Misconfiguration","Memory injection"],c:3,e:"Memory injection writes attacker code into the memory of a running process and executes it there, leaving nothing on disk for file-based antivirus to find. Behavior-based endpoint detection is needed."},
{id:"u4l1-4",t:"u4l1",q:"Thousands of organizations were compromised when a software vendor's official update mechanism distributed a backdoored version of its product. Which vulnerability and vector combination does this represent?",a:["Malicious update delivered through the supply chain","Zero-day exploited through unsecure wireless","Buffer overflow delivered through email","Race condition delivered through removable media"],c:0,e:"A malicious update abuses the trusted update channel, and because the vendor is a trusted supplier, this is a supply chain vector. Verifying update signatures and staging rollouts reduce the impact."},
{id:"u4l1-5",t:"u4l1",q:"Which control MOST directly reduces the likelihood that a buffer overflow in a network service can be exploited?",a:["Adding a stronger password policy","Applying vendor patches and enabling memory protection features","Installing a physical firewall in front of the server","Encrypting the server's disk"],c:1,e:"Buffer overflows are code flaws; patches remove them and operating system memory protections such as address space layout randomization make exploitation unreliable. Passwords, network firewalls, and disk encryption do not address the flaw."},

// u4l2
{id:"u4l2-1",t:"u4l2",q:"Entering a single quotation mark into a website's search box returns a database error message. Which vulnerability does this indicate?",a:["Cross-site scripting","VM escape","SQL injection","Firmware vulnerability"],c:2,e:"A database error triggered by a quote character shows that user input is being inserted directly into a database query, the hallmark of SQL injection. The fix is parameterized queries and input validation."},
{id:"u4l2-2",t:"u4l2",q:"Visitors to a forum see a pop-up that silently sends their session cookies to an external server. The script was posted in a comment by an attacker. Which vulnerability is this?",a:["SQL injection","Server-side request forgery","Resource reuse","Cross-site scripting"],c:3,e:"Script placed in page content that executes in other users' browsers is cross-site scripting. Unlike SQL injection, which runs against the server's database, XSS runs in the victims' browsers. Output encoding prevents it."},
{id:"u4l2-3",t:"u4l2",q:"A cloud provider reports that a flaw allowed code in one customer's virtual machine to execute on the hypervisor and access other customers' virtual machines. What is this vulnerability called?",a:["VM escape","Resource reuse","Side loading","Cache poisoning"],c:0,e:"VM escape is breaking out of a guest virtual machine to the hypervisor or host, from which every other guest is reachable. It is the most serious virtualization vulnerability and requires prompt hypervisor patching."},
{id:"u4l2-4",t:"u4l2",q:"After a company's cloud backups were found readable by anyone on the internet, investigation showed the storage bucket permissions had been set to public. Which statement BEST describes responsibility for this exposure?",a:["The cloud provider is responsible because it owns the storage hardware","The customer is responsible because configuration of its data and permissions is on its side of the shared responsibility model","Neither party is responsible because no attack occurred","The internet service provider is responsible for filtering access"],c:1,e:"Under the shared responsibility model, the provider secures the infrastructure while the customer secures its data, identities, and configuration. A public bucket permission is a customer misconfiguration."},
{id:"u4l2-5",t:"u4l2",q:"A newly provisioned virtual disk in a multi-tenant cloud contained fragments of another organization's files. Which vulnerability does this demonstrate?",a:["End-of-life hardware","Cross-site scripting","Resource reuse","Malicious update"],c:2,e:"Resource reuse occurs when memory or storage released by one tenant is allocated to another without being wiped, leaking data between tenants. Providers must zero resources before reallocation."},

// u4l3
{id:"u4l3-1",t:"u4l3",q:"Attackers are actively exploiting a flaw in a widely used file transfer product, and the vendor has announced that a patch is still several days away. What should the security team do FIRST?",a:["Wait for the patch and apply it when released","Change all user passwords","Reinstall the operating system on the server","Apply compensating controls such as isolating the system and adding monitoring"],c:3,e:"This is a zero-day: exploitation is active and no patch exists. The correct response is compensating controls that reduce exposure now, such as segmentation, disabling the vulnerable feature, and increased monitoring, until the patch is available."},
{id:"u4l3-2",t:"u4l3",q:"A developer's build pulls an open-source library that was later found to contain a backdoor inserted by attackers who took over the maintainer's account. Which vulnerability class is this?",a:["Software supply chain","Hardware supply chain","Cryptographic","Misconfiguration"],c:0,e:"A compromised software component from a provider is a software supply chain vulnerability. Defenses include verifying signatures, maintaining an inventory of components, and monitoring dependencies."},
{id:"u4l3-3",t:"u4l3",q:"A mobile device management report flags several phones that have had their operating system restrictions removed by users. Which vulnerability do these devices represent?",a:["Side loading","Jailbreaking or rooting","Resource reuse","Downgrade"],c:1,e:"Jailbreaking (iOS) and rooting (Android) remove the operating system's built-in protections, giving both the user and any malware full control. MDM should detect and block these devices from corporate resources."},
{id:"u4l3-4",t:"u4l3",q:"An assessment finds that a web application still supports the RC4 cipher and 1024-bit RSA keys. Which vulnerability class do these findings belong to?",a:["Mobile device","Zero-day","Cryptographic","Virtualization"],c:2,e:"Weak or deprecated algorithms and short key lengths are cryptographic vulnerabilities. The remedy is to disable legacy ciphers and use current algorithms with adequate key lengths."},
{id:"u4l3-5",t:"u4l3",q:"A network camera is found with the manufacturer's default administrator password and directory listing enabled on its web interface. Which vulnerability class is this?",a:["Zero-day","Malicious update","Race condition","Misconfiguration"],c:3,e:"Default credentials and unnecessary features left enabled are misconfigurations, the most common vulnerability class. Secure baselines applied at deployment and configuration scanning prevent them."},

// u5l1
{id:"u5l1-1",t:"u5l1",q:"Within an hour, dozens of workstations across several offices become infected although no user opened an attachment or clicked a link. Which type of malware is MOST likely responsible?",a:["Worm","Trojan","Virus","Logic bomb"],c:0,e:"A worm spreads on its own by exploiting vulnerabilities across the network with no user action. A virus needs a user to run or share a file, and a trojan requires the user to install it."},
{id:"u5l1-2",t:"u5l1",q:"Antivirus scans report a system is clean, yet outbound connections to a suspicious address continue and the malware returns after each removal attempt. Which malware type BEST explains this?",a:["Spyware","Rootkit","Bloatware","Keylogger"],c:1,e:"A rootkit hides at the kernel or firmware level, below where antivirus looks, concealing itself and persisting through removal. The reliable fix is to wipe and reinstall from trusted media."},
{id:"u5l1-3",t:"u5l1",q:"Two weeks after a system administrator was terminated, scripts on a server deleted all backups on the anniversary date of the administrator's hiring. Which malware type is this?",a:["Ransomware","Worm","Logic bomb","Trojan"],c:2,e:"A logic bomb is code that waits for a trigger such as a date or event before acting. It is frequently planted by an insider with the access and the motive."},
{id:"u5l1-4",t:"u5l1",q:"Ransomware has been detected on a workstation in the finance department. What should be done FIRST?",a:["Pay the ransom to recover the files quickly","Run a full antivirus scan on every server","Reboot the workstation to clear memory","Isolate the workstation from the network"],c:3,e:"The first priority is containment: disconnect the infected system so the ransomware cannot spread to shares and other hosts. Recovery from tested offline backups follows; paying is unreliable and funds further attacks."},
{id:"u5l1-5",t:"u5l1",q:"Several users' passwords were stolen although none of them received phishing messages or visited suspicious websites. Which malware type is the MOST likely cause?",a:["Keylogger","Bloatware","Worm","Logic bomb"],c:0,e:"A keylogger records keystrokes, capturing passwords as they are typed, with no phishing required. Bloatware is unwanted preinstalled software, and worms and logic bombs do not specifically capture credentials."},

// u5l2
{id:"u5l2-1",t:"u5l2",q:"A company's web server is overwhelmed by enormous DNS responses arriving from thousands of DNS servers that the company never queried. Which attack is occurring?",a:["DNS cache poisoning","Reflected and amplified DDoS","On-path attack","Credential replay"],c:1,e:"The attacker sent small queries with the victim's spoofed address to open DNS servers, which reply with large responses to the victim. That combination of reflection and amplification is a DDoS technique."},
{id:"u5l2-2",t:"u5l2",q:"Employees report that a wireless network with the company's SSID appears in the parking lot and that after connecting, their sessions behave oddly. Which attack is this?",a:["Rogue DHCP","DNS hijacking","Evil twin","Password spraying"],c:2,e:"An evil twin is an attacker's access point broadcasting the legitimate SSID so clients connect to it and route traffic through the attacker. Enterprise authentication with 802.1X prevents the fake AP from impersonating the network."},
{id:"u5l2-3",t:"u5l2",q:"An attacker who captured a user's session token from an unencrypted connection uses that token to access the application without knowing the password. Which attack is this, and which control BEST prevents it?",a:["Amplified DDoS; rate limiting","Brute force; account lockout","Evil twin; WPA3","Credential replay; MFA and short-lived tokens"],c:3,e:"Reusing a captured authentication artifact is credential replay. Multifactor authentication makes the replayed token insufficient, and short token lifetimes plus encrypted channels limit the window and prevent capture."},
{id:"u5l2-4",t:"u5l2",q:"Users typing the correct address for their bank are being sent to a fraudulent site, and the resolver's records show incorrect addresses. Which control would have prevented the forged records from being accepted?",a:["DNSSEC","WPA3","Application allow list","Full-disk encryption"],c:0,e:"DNSSEC signs DNS records so resolvers reject forged answers, defeating cache poisoning. The other controls address wireless, endpoints, and storage rather than name resolution."},
{id:"u5l2-5",t:"u5l2",q:"Wireless clients are repeatedly disconnected by forged management frames and then reconnect to an attacker-controlled access point. Which wireless feature stops the forged disconnections?",a:["Hidden SSID","Protected management frames","MAC address filtering","A captive portal"],c:1,e:"Deauthentication attacks forge unauthenticated management frames. Protected management frames, required by WPA3, authenticate those frames so forged ones are ignored. Hidden SSIDs and MAC filtering are easily bypassed."},

// u5l3
{id:"u5l3-1",t:"u5l3",q:"A logged-in bank customer visits a malicious website in another tab, and their email address on file at the bank is silently changed to the attacker's. Which attack occurred?",a:["Server-side request forgery","Directory traversal","Cross-site request forgery","Privilege escalation"],c:2,e:"Cross-site request forgery tricks the victim's browser into sending a request to a site where they are authenticated, using their session cookie. Anti-forgery tokens and SameSite cookies prevent it."},
{id:"u5l3-2",t:"u5l3",q:"A web application's link preview feature fetches any URL a user supplies. An attacker supplies an internal address and retrieves data from the cloud metadata service. Which attack is this?",a:["Cross-site scripting","Replay","Downgrade","Server-side request forgery"],c:3,e:"Server-side request forgery abuses a server feature that fetches URLs, making the server request internal resources on the attacker's behalf. Allow-listing permitted destinations prevents it."},
{id:"u5l3-3",t:"u5l3",q:"A request for /files?name=../../../../etc/shadow returns the system's password hashes. Which attack is this?",a:["Directory traversal","SQL injection","Buffer overflow","Collision"],c:0,e:"Directory traversal uses ../ sequences to escape the intended folder and reach other files. Path validation and minimal file permissions for the web server prevent it."},
{id:"u5l3-4",t:"u5l3",q:"A regular user changes the account number in a URL and views another customer's order history. Which attack has occurred?",a:["Vertical privilege escalation","Horizontal privilege escalation","Replay attack","Injection"],c:1,e:"Accessing another user's data at the same privilege level is horizontal privilege escalation. Vertical escalation would mean gaining administrative rights. Authorization checks on every request prevent it."},
{id:"u5l3-5",t:"u5l3",q:"A packet capture shows that two systems capable of TLS 1.3 negotiated TLS 1.0 during a session that an attacker was interfering with. Which attack is this, and how is it prevented?",a:["Birthday attack; use longer hashes","Replay attack; add timestamps","Downgrade attack; disable legacy protocol versions","Collision attack; use SHA-256"],c:2,e:"Forcing a connection to a weaker protocol version is a downgrade attack. Disabling legacy versions and ciphers removes the weak option, and TLS 1.3 has no weak ciphers to fall back to."},

// u5l4
{id:"u5l4-1",t:"u5l4",q:"Logs show that 400 different user accounts each recorded exactly one failed login attempt from the same external address within ten minutes, and no accounts were locked out. Which attack is this?",a:["Brute force","Dictionary attack on one account","Credential replay","Password spraying"],c:3,e:"One attempt against many accounts is password spraying, designed to stay under per-account lockout thresholds. Detection requires alerting on failures across accounts, and MFA makes a guessed password insufficient."},
{id:"u5l4-2",t:"u5l4",q:"A user's account shows a successful login from Chicago at 09:05 and another from Singapore at 09:30 the same day. Which indicator of compromise is this?",a:["Impossible travel","Out-of-cycle logging","Resource consumption","Blocked content"],c:0,e:"Two logins from locations too far apart to travel between in the elapsed time is impossible travel, a strong sign that credentials are being used by someone other than the user."},
{id:"u5l4-3",t:"u5l4",q:"Which control is MOST effective against password spraying while having the least effect on legitimate users?",a:["Locking accounts after three failed attempts","Requiring multifactor authentication","Shortening password expiration to 30 days","Disabling accounts that are unused for a day"],c:1,e:"Spraying stays under lockout thresholds, so lockout does little; MFA makes a correctly guessed password insufficient. Frequent expiration and aggressive disabling burden users without stopping the attack."},
{id:"u5l4-4",t:"u5l4",q:"An analyst reviewing a domain controller notices that its security log has no entries for a two-hour period during which the server was online. What is the BEST interpretation?",a:["The system was idle and nothing occurred","The log service was upgraded","The logs may have been cleared by an attacker and the system should be treated as compromised","Logging is not needed on domain controllers"],c:2,e:"Missing logs are an indicator of malicious activity: attackers clear logs to hide their actions. A gap during normal operation is evidence of tampering, not absence of events."},
{id:"u5l4-5",t:"u5l4",q:"A web server's CPU has been at 100 percent for days with no increase in legitimate traffic. Which indicator of malicious activity does this represent, and what is a likely cause?",a:["Resource inaccessibility; a ransomware infection","Account lockout; a brute force attack","Concurrent session usage; shared credentials","Resource consumption; unauthorized cryptocurrency mining"],c:3,e:"Unexplained sustained resource consumption is an indicator often caused by cryptomining malware or by participation in a botnet. Resource inaccessibility would mean the service became unavailable."},

// u5l5
{id:"u5l5-1",t:"u5l5",q:"Employees continue to install unapproved utilities, some of which contain malware. Which control is MOST effective at preventing unknown software from executing?",a:["An application allow list","A deny list of known malicious programs","Antivirus signature updates","A stronger password policy"],c:0,e:"An allow list permits only approved software and blocks everything else by default, so unknown malware cannot run. A deny list only blocks what is already known, which is always behind new threats."},
{id:"u5l5-2",t:"u5l5",q:"During an active malware outbreak, a workstation is confirmed infected. Which action contains the immediate threat?",a:["Segmenting the network into new VLANs","Isolating the workstation from the network","Enforcing the configuration baseline","Decommissioning the workstation"],c:1,e:"Isolation removes the infected system from all network contact immediately, stopping the spread while it is investigated. Segmentation is a structural design for limiting future spread, not an immediate containment step."},
{id:"u5l5-3",t:"u5l5",q:"An attacker who compromised a receptionist's workstation was able to reach and read the payroll database. Which two controls would MOST have limited this outcome?",a:["Encryption and monitoring","Patching and decommissioning","Least privilege and network segmentation","Application allow list and antivirus"],c:2,e:"Least privilege would prevent the receptionist's account from having rights to the payroll data, and segmentation would keep the workstation network from reaching the database network. Together they limit lateral movement and access."},
{id:"u5l5-4",t:"u5l5",q:"A newly deployed switch still uses the manufacturer's administrator password and has several unused services enabled. Which hardening steps should be taken FIRST?",a:["Add the switch to a honeynet","Install a host-based firewall on every connected workstation","Enable jumbo frames","Change default credentials and disable unnecessary services"],c:3,e:"Changing default passwords and removing unused services and ports are the first hardening steps for any new device; defaults are publicly known and unused services are pure attack surface."},
{id:"u5l5-5",t:"u5l5",q:"An audit repeatedly finds that servers drift away from the approved security settings weeks after deployment. Which mitigation addresses this directly?",a:["Configuration enforcement","Isolation","Decommissioning","Encryption"],c:0,e:"Configuration enforcement continuously applies the secure baseline and automatically corrects drift, so settings do not quietly change over time. The other options do not maintain configuration state."}
);
